### ISSUE TITLE
Issue with Rundeck on Ubuntu 14.04

### ISSUE THREAD

**Issue by linbynd** [rundeck/rundeck#1063]
I have installed rundeck on Ubuntu 14.04. When ever I make a change to a ACL policy the changes do not pickup. Upon looking the rundeck pid does not exist the init process shows its not running. 

```
root@linbynd-xfce:~# ps -ef | grep rundeck
rundeck   1035     1  1 18:31 ?        00:01:27 /usr/bin/java -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf -Dloginmodule.name=RDpropertyfilelogin -Drdeck.config=/etc/rundeck -Drdeck.base=/var/lib/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/lib/rundeck/data -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Djava.io.tmpdir=/tmp/rundeck -Xmx1024m -Xms256m -XX:MaxPermSize=256m -server -cp /var/lib/rundeck/bootstrap/libpam4j-1.5.jar:/var/lib/rundeck/bootstrap/rundeck-jetty-server-2.4.0.jar:/var/lib/rundeck/bootstrap/servlet-api-2.5.jar:/var/lib/rundeck/bootstrap/log4j-1.2.16.jar:/var/lib/rundeck/bootstrap/not-yet-commons-ssl-0.3.11.jar:/var/lib/rundeck/bootstrap/jetty-all-7.6.0.v20120127.jar:/var/lib/rundeck/bootstrap/jna-3.2.2.jar: com.dtolabs.rundeck.RunServer /var/lib/rundeck 4440
root@linbynd-xfce:~# /etc/init.d/rundeckd status
* rundeckd is not running
```

In the service log it shows that the address is in use, there is nothing that is listening on 4440 apart from rundeck.

```
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
2015-01-06 20:31:11.696:INFO:oejs.Server:jetty-7.6.0.v20120127
2015-01-06 20:31:13.892:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2015-01-06 20:31:14.767:INFO:/:Initializing Spring root WebApplicationContext
INFO  BootStrap: Starting Rundeck 2.4.0-1...
INFO  BootStrap: using rdeck.base config property: /var/lib/rundeck
INFO  BootStrap: loaded configuration: /etc/rundeck/framework.properties
INFO  BootStrap: RSS feeds disabled
2015-01-06 20:31:32.995:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
2015-01-06 20:31:33.057:INFO:/:Initializing Spring FrameworkServlet 'grails'
2015-01-06 20:31:33.090:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:4440: java.net.BindException: Address already in use
java.net.BindException: Address already in use
  at sun.nio.ch.Net.bind0(Native Method)
  at sun.nio.ch.Net.bind(Unknown Source)
  at sun.nio.ch.Net.bind(Unknown Source)
  at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
  at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
  at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:173)
  at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311)
  at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:251)
  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
  at org.eclipse.jetty.server.Server.doStart(Server.java:272)
  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
  at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
  at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
2015-01-06 20:31:33.091:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@13e411b: java.net.BindException: Address already in use
java.net.BindException: Address already in use
```

**Comment by xiaods** [comment]
@linbynd which acl changed, please give more information. it will help us reproduce your steps.
