### ISSUE TITLE
ERROR FrameworkProject - Cannot get nodes from [DirectoryResourceModelSource

### ISSUE THREAD

**Issue by smithtimamy** [rundeck/rundeck#1064]
We are running Rundeck 2.4.0-1 on Joyent SmartOS via the launcher. With this setup, we are using the "Directory Resource Model Source" method of defining nodes. On occasion, we get the below stack and job failure on some executions. This issue is intermittent and I have not been able to recreate it on my own.

```
2015-01-07 11:20:01,468 ERROR FrameworkProject - Cannot get nodes from [DirectoryResourceModelSource{directory=/path/to/resource/files/}]: null
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at com.dtolabs.rundeck.core.resources.DirectoryResourceModelSource.loadNodeSets(DirectoryResourceModelSource.java:136)
        at com.dtolabs.rundeck.core.resources.DirectoryResourceModelSource.getNodes(DirectoryResourceModelSource.java:131)
        at com.dtolabs.rundeck.core.common.FrameworkProject.getNodeSet(FrameworkProject.java:525)
        at com.dtolabs.rundeck.core.common.Framework.filterNodeSet(Framework.java:523)
        at com.dtolabs.rundeck.core.common.Framework$filterNodeSet.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at com.dtolabs.rundeck.core.common.Framework$filterNodeSet.call(Unknown Source)
        at rundeck.services.FrameworkService$_filterNodeSet_closure4.doCall(FrameworkService.groovy:275)
        at rundeck.services.FrameworkService$_filterNodeSet_closure4.doCall(FrameworkService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:174)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
        at groovy.lang.Closure.call(Closure.java:412)
        at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:59)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:313)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
        at rundeck.services.FrameworkService.filterNodeSet(FrameworkService.groovy:274)
        at rundeck.services.FrameworkService$filterNodeSet.call(Unknown Source)
        at rundeck.services.ExecutionService.createContext(ExecutionService.groovy:1010)
        at rundeck.services.ExecutionService$createContext$3.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy:743)
        at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy)
        at rundeck.services.ExecutionService$$FastClassByCGLIB$$ffb73873.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
        at rundeck.services.ExecutionService$$EnhancerByCGLIB$$3e62918d.executeAsyncBegin(<generated>)
        at rundeck.services.ExecutionService$executeAsyncBegin.call(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:252)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:113)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:69)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:68)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:199)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:546)
2015-01-07 11:20:02,200 ERROR ExecutionUtilService - Execution failed: 41978: No matched nodes: NodeSet{includes={name=cmh-shortngxpd-001, dominant=false, }}
```

Things we have tried thus far to eliminate this issue that have not worked:
* Move the directory from an NFS mount to the local filesystem - has not helped
* Upgrade to version 2.4.0-1 from 2.3.2 - has not helped

I have tried looking for similar issues on here but have not found any. Please let me know what additional information you might need

**Comment by katanafleet** [comment]
Hello,

We've the same issue with the last rundeck version 2.4.0 on a local file system. 
Job are executed from a jenkins plugin for our nightly build deployment.
```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=PAOPERF1WASPAOCOM-BLACKICE|PAOPERF1WASPAOCOM-GREYHOUND|PAOPERF1WASPAOCAT-,BLACKICE|PAOPERF1WASPAOCAT-GREYHOUND|PAOPERF1WASPAOSOG-FLATLINER|PAOPERF1WASPAOSOG-SEABREEZE|PAOPERF1WASPAOGST-FLATLINER|PAOPERF1WASPAOGST-SEABREEZE|PAOPERF1HTTPPAO-GREENGER, dominant=false, }}
08:00:01			at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.validateNodeSet(NodeFirstWorkflowStrategy.java:333)
08:00:01			at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:85)
08:00:01			at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:124)
08:00:01			at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
08:00:01			Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=PAOPERF1WASPAOCOM-BLACKICE|PAOPERF1WASPAOCOM-GREYHOUND|PAOPERF1WASPAOCAT-,BLACKICE|PAOPERF1WASPAOCAT-GREYHOUND|PAOPERF1WASPAOSOG-FLATLINER|PAOPERF1WASPAOSOG-SEABREEZE|PAOPERF1WASPAOGST-FLATLINER|PAOPERF1WASPAOGST-SEABREEZE|PAOPERF1HTTPPAO-GREENGER, dominant=false, }}
08:00:01			No matched nodes: NodeSet{includes={name=PAOPERF1WASPAOCOM-BLACKICE|PAOPERF1WASPAOCOM-GREYHOUND|PAOPERF1WASPAOCAT-,BLACKICE|PAOPERF1WASPAOCAT-GREYHOUND|PAOPERF1WASPAOSOG-FLATLINER|PAOPERF1WASPAOSOG-SEABREEZE|PAOPERF1WASPAOGST-FLATLINER|PAOPERF1WASPAOGST-SEABREEZE|PAOPERF1HTTPPAO-GREENGER, dominant=false, }}
```
