### ISSUE TITLE
Windows launcher not working

### ISSUE THREAD

**Issue by bygiro** [rundeck/rundeck#1116]
windows 8.1
I installed JRE 7.
rundeck launcher, placed in c:\rundeck\rundeck-launcher-2.4.2.jar
jetty seem to start, but I get the following:

HTTP ERROR: 503

Problem accessing /. Reason:

    Service Unavailable

here the log in the command window, any help is really appreciated.

C:\rundeck>java -jar rundeck-launcher-2.4.2.jar
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=C:/rundeck/server/config/ssl.properties to enable.
2015-02-22 18:01:40.367:INFO:oejs.Server:jetty-7.6.0.v20120127
2015-02-22 18:01:42.250:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2015-02-22 18:01:42.962:INFO:/:Initializing Spring root WebApplicationContext
2015-02-22 18:01:44,736 [main] ERROR context.ContextLoader  - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke method getAt() on null object
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
        at org.eclipse.jetty.server.Server.doStart(Server.java:261)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
        at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
        at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)

        at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
        at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
        ... 15 more
2015-02-22 18:01:44,739 [main] ERROR context.GrailsContextLoader  - Error initializing the application: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke method getAt() on null object
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke method getAt() on null object
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
        at org.eclipse.jetty.server.Server.doStart(Server.java:261)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
        at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
        at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)

        at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
        at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
        ... 15 more
2015-02-22 18:01:44,742 [main] ERROR context.GrailsContextLoader  - Error initializing Grails: Error creating bean with name 'pluginManager' defined in ServletC
ontext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke method getAt() on null object
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke method getAt() on null object
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
        at org.eclipse.jetty.server.Server.doStart(Server.java:261)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
        at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
        at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)

        at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
        at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
        ... 15 more
2015-02-22 18:01:44.750:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/,file:/C:/rundeck/server/exp/webapp/},C:\rundeck\server\exp\webapp
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationC
ontext.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke method getAt() on null object
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
        at org.eclipse.jetty.server.Server.doStart(Server.java:261)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
        at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
        at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)

        at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
        at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by:
java.lang.NullPointerException: Cannot invoke method getAt() on null object
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
        at org.eclipse.jetty.server.Server.doStart(Server.java:261)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
        at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
        at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)

        at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
        at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
2015-02-22 18:01:44.820:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

**Comment by bygiro** [comment]
can someone confirm the rundeck is working on windows 8?

**Comment by gschueler** [comment]
can you make sure you are not using JDK 8?  That error occurs if you are using Java 8

**Comment by bygiro** [comment]
I tried both.
first installation with JRE 8, then I downgrade to JRE7 with a clean installation.

**Comment by gschueler** [comment]
what is `java -version` ?

**Comment by bygiro** [comment]
the java -version didn't return anything, but the java was installed. I tried again to do a clean installation, and now it is working with version 1.7.0_75
I was going to abandon the idea to use it, now it is working and I'll try it.
thanks for the support.....I'm closing the issue.

**Comment by skonsoft** [comment]
I still get the same problem with rundeck 2.2.4 under Ubuntu Server 14.04 + Java 9.
So i Changed to Java 8 but the problem was not resolved...

Any Help ?

**Comment by gschueler** [comment]
rundeck 2.4 and earlier requires java 6 or 7

**Comment by skonsoft** [comment]
Thank you. I fixed the problem by installing JAVA 7.
