### ISSUE TITLE
Schedules don't launch

### ISSUE THREAD

**Issue by hjdr4** [rundeck/rundeck#1150]
Using 2.5 snapshot from yesterday, schedules don't launch. Is there anything more to do than setting the schedules in the jobs ?

**Comment by hjdr4** [comment]
Went a bit further :

2015-03-25 14:35:00,003 [quartzScheduler_Worker-1] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Unable to start Job execution: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at rundeck.quartzjobs.ExecutionJob.fetchScheduledExecution(ExecutionJob.groovy:413)
	at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:170)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:90)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:69)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:68)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	... 8 more

**Comment by gschueler** [comment]
not seeing this behavior in the latest code. what 2.5 snapshot do you mean?

**Comment by hjdr4** [comment]
Hello,

I used development branch from 2015-03-24.
I will triple check by compiling today's version.

For now, it looks like schedules work for the time my session exists(I'm the creator/owner). When it expires, schedules produce the attached error and don't launch. There is no trace in activity, just the general log.

**Comment by hjdr4** [comment]
Hello,

With latest snapshot, it looks ok for now with hourly jobs. I have some daily jobs pending, I'll take a look on Monday.

**Comment by gschueler** [comment]
thanks

**Comment by gschueler** [comment]
any more issues like this?

**Comment by hjdr4** [comment]
Looks like this is ok with latest code :)

**Comment by gschueler** [comment]
thanks

**Comment by schast** [comment]
Hi,

get the same error with rundeck-launcher-2.5.0.jar when job is started on a remote node.

var/log/service.log
2015-04-28 07:36:26,924 ERROR ExecutionUtilService - Execution failed: 13: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [myNode_myUser: Unknown: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread]}, Node failures: {myNode_myUser=[Unknown: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread]}, flow control: Continue, status: failed]
