### ISSUE TITLE
rundeck 2.5.0 error after installation

### ISSUE THREAD

**Issue by reigner-yrastorza** [rundeck/rundeck#1173]
OS: CentOS release 6.6  (x86_64)
Version:
rundeck-2.5.0-1.6.GA.noarch
rundeck-repo-3-0.noarch
rundeck-config-2.5.0-1.6.GA.noarch

Error when starting rundeck -

/etc/init.d/rundeckd start

$ cat service.log
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dtolabs/rundeck/RunServer : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.dtolabs.rundeck.RunServer. Program will exit.

Note:
- This is a clean installation

**Comment by gschueler** [comment]
2.5.0 requires java 7

**Comment by reigner-yrastorza** [comment]
Ah right, confirmed working.


Thanks,
Reigner
