### ISSUE TITLE
Bulk Delete Execution Failing

### ISSUE THREAD

**Issue by ctgaff** [rundeck/rundeck#1184]
Java 7
Rundeck: 2.5.0-1
Reproducible across multiple installations and Jobs.

Steps: Bulk Delete, Select All, Delete Selected Executions

Bulk Delete Executions: Results
Request did not succeed: Server Error

**Comment by ctgaff** [comment]
ERROR GrailsExceptionResolver - ClassNotFoundException occurred when processing request: [POST] /execution/deleteBulkApi
org.springframework.mock.web.MockHttpServletRequest. Stacktrace follows:
java.lang.ClassNotFoundException: org.springframework.mock.web.MockHttpServletRequest
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at rundeck.services.ApiService.renderSuccessJson(ApiService.groovy:176)
        at rundeck.services.ExecutionService.renderBulkExecutionDeleteResult(ExecutionService.groovy:123)
        at rundeck.controllers.ExecutionController.executionDeleteBulk(ExecutionController.groovy:1351)
        at rundeck.controllers.ExecutionController$_deleteBulkApi_closure25.doCall(ExecutionController.groovy:1006)
        at rundeck.controllers.ExecutionController.deleteBulkApi(ExecutionController.groovy:1004)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)

**Comment by gschueler** [comment]
I'm not able to reproduce this. Is this happening with a clean install, or was it an upgrade install? OS/version?

**Comment by ctgaff** [comment]
I just determined what I did to reproduce this error.  It was not an
upgrade, but I did an import of an archive to recreate the projects.   It's
caused by importing all from an archive while choosing to strip the UUID's.

OS: Red Hat Enterprise Linux Server release 6.6 (Santiago)

**Comment by gschueler** [comment]
thanks, I will try that

**Comment by gschueler** [comment]
still no luck.  Is it possible for you to send me some job definitions or an archive file?

is this Oracle JVM, or OpenJDK?

**Comment by gschueler** [comment]
I have still not seen this bug occur yet.

what browser/OS are you using on the client side?

**Comment by ctgaff** [comment]
I am using Firefox 34.0.5 with Windows Server 2008.  However, I exported
the archive this evening and imported it into my Linux box running Fedora
and the same exception occurred immediately while trying to bulk delete.

I am trying to truncate the logs so that I can send you an archive but I
cannot seem to find the default username and password for the rundeck H2
database.

**Comment by gschueler** [comment]
well i'm wondering if it has something to do with the client side (e.g. firefox), and the way the ajax request is made... just a stab in the dark really without more info.  Firefox on Windows?

**Comment by ctgaff** [comment]
The same exception occurs with the archive if it's imported on Fedora Linux
using Chrome.  I have attached the archive.

**Comment by gschueler** [comment]
sorry, I don't think it made it through to github. do you want to email it to me directly?

**Comment by gschueler** [comment]
ok, so i finally reproduced it!  I was trying bulk delete from the Activity page, without hitting the error. When I tried via the Activity tab in the Jobs page, I saw the error.

thanks, should be able to fix it now
