### ISSUE TITLE
Unable to Start Rundeck under tomcat

### ISSUE THREAD

**Issue by linbynd** [rundeck/rundeck#1187]
I have deployed the rundeck war(2.5) under tomcat7 running on ubuntu in its default directory. When I start tomcat, I get the following error on logs when rundeck is trying to be deployed.

====INFO: Deploying web application directory /var/lib/tomcat7/webapps/rundeck 
Apr 23, 2015 4:31:52 PM org.apache.catalina.startup.TaglibUriRule body 
INFO: TLD skipped. URI: http://www.springframework.org/tags is already defined 
2015-04-23 16:32:14,250 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
	at java.lang.Thread.run(Thread.java:745) 
Caused by: java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist 
	... 5 more 
2015-04-23 16:32:14,257 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
	at java.lang.Thread.run(Thread.java:745) 
Caused by: java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist 
	... 5 more 
Apr 23, 2015 4:32:14 PM org.apache.catalina.core.StandardContext startInternal 
SEVERE: Error listenerStart 
Apr 23, 2015 4:32:14 PM org.apache.catalina.core.StandardContext startInternal 
SEVERE: Context [/rundeck] startup failed due to previous errors 
Apr 23, 2015 4:32:14 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc 
SEVERE: The web application [/rundeck] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered. 
Apr 23, 2015 4:32:14 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks 
SEVERE: The web application [/rundeck] created a ThreadLocal with key of type [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2] (value [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2@525f9eba]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak. 
Apr 23, 2015 4:32:14 PM org.apache.catalina.startup.HostConfig deployDirectory 
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT 
Apr 23, 2015 4:32:14 PM org.apache.coyote.AbstractProtocol start 
INFO: Starting ProtocolHandler ["http-bio-8080"] 
Apr 23, 2015 4:32:14 PM org.apache.catalina.startup.Catalina start 
INFO: Server startup in 37939 ms 

Need some Help on it.

**Comment by gschueler** [comment]
the normal jetty/launcher installer creates a "log4j.properties" file for you.  You would need to create one within the classpath for the webapp, e.g. at `$CATALINA_HOME/webapps/rundeck/WEB-INF/classes/log4j.properties`. it could be just an empty file

**Comment by linbynd** [comment]
Awesome!!! Thanks Greg!! Worked like a charm, I was mucking around in other places. Thanks for it.
I did not have this problem in 2.4 so it did not strike me.
Issue solved.

**Comment by linbynd** [comment]
Closing the issue

**Comment by Youans** [comment]
I think you should mention this in Doc

**Comment by gaetanquentin** [comment]
@gschueler 
you can do that only if rundeck is already deployed (exploded)

in the case of rundeck.war  integration on wildfly 10->13 (jboss) , deployment will fail because log4j.properties is missing. So you can't access exploded WEB-INF directory.

**Comment by jheusser** [comment]
What's the status of this? Happens when starting rundeckd on Ubuntu after installing rundeck_3.0.5.20180828-1.201808282140_all.deb.
