### ISSUE TITLE
2.5 debian package should require java 7

### ISSUE THREAD

**Issue by arthurlogilab** [rundeck/rundeck#1192]
Install from http://dl.bintray.com/rundeck/rundeck-deb/rundeck-2.5.0-1-GA.deb

```
root@vagrant-debian-wheezy:~# /etc/init.d/rundeckd 
Usage: /etc/init.d/rundeckd {start|stop|restart|condrestart|status}
root@vagrant-debian-wheezy:~# /etc/init.d/rundeckd start
[ ok ing rundeckd: .

root@vagrant-debian-wheezy:~# /etc/init.d/rundeckd stop
Stopping rundeckd: /sbin/start-stop-daemon: warning: failed to kill 7473: No such process

root@vagrant-debian-wheezy:~# /etc/init.d/rundeckd status
[FAIL] rundeckd is not running ... failed!

```

**Comment by gschueler** [comment]
is there any info in the `/var/log/rundeck/service.log` file?

**Comment by arthurlogilab** [comment]
```
# cat /var/log/rundeck/service.log 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dtolabs/rundeck/RunServer : Unsupported mjor.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.dtolabs.rundeck.RunServer. Program will exit.
```

**Comment by gschueler** [comment]
Rundeck 2.5.0 requires Java 7

**Comment by arthurlogilab** [comment]
could this be displayed as a error message in start ? 

could this be enforced in the debian package's dependencies ?

**Comment by gschueler** [comment]
yes, there should be a change to the dependencies, marking this as a bug

**Comment by sreekanthsnair** [comment]
I'm facing the same issue, my JAVA_HOME is set correct and shows /usr/lib/jvm/java-7-openjdk-amd64 any other possibility ?

**Comment by gschueler** [comment]
@sreekanthsnair if you are seeing the "UnsupportedClassVersionError" message, you are still using java 6 somehow.  double check your rundeck install settings, e.g. in /etc/rundeck/profile

**Comment by egov-systems** [comment]
echo $JAVA_HOME pointing to java 8 only, let e check the profile setting, thanks

**Comment by sreekanthsnair** [comment]
echo $JAVA_HOME pointing to java 8 only, let e check the profile setting, thanks
