### ISSUE TITLE
Unable to save changes to jobs using Local Command node step

### ISSUE THREAD

**Issue by michlaustn** [rundeck/rundeck#1193]
I am able to create new jobs using the Local Command node step plugin.  However if I wish to edit the step for example the commands that are executed I am presented with the following error when saving the job;

    object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow

I am using Rundeck 2.5.0-1 configured to use MySQL.

**Comment by michlaustn** [comment]
Error Messages;

<pre>
Request: /project/Ansible-Automation/job/update/7713cb65-a8ef-4417-ad6f-1646971b3935?loglevel=INFO&notifyFailureRecipients=&notifyPlugin.onfailure.enabled.HipChatNotification=true&notifyPlugin=%5Bonfailure.enabled.HipChatNotification%3Atrue%2C+onfailure%3A%5Benabled.HipChatNotification%3Atrue%2C+enabled%3A%5BHipChatNotification%3Atrue%2C+_HipChatNotification%3A%5D%2C+type%3AHipChatNotification%2C+HipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%2C+enabled._HipChatNotification%3A%5D%2C+onsuccess.enabled._HipChatNotification%3A%2C+onsuccess%3A%5Benabled._HipChatNotification%3A%2C+enabled%3A%5B_HipChatNotification%3A%5D%2C+HipChatNotification.config.room%3A%2C+HipChatNotification%3A%5Bconfig.room%3A%2C+config%3A%5Broom%3A%5D%5D%2C+type%3AHipChatNotification%5D%2C+onsuccess.HipChatNotification.config.room%3A%2C+onstart.enabled.HipChatNotification%3Atrue%2C+onstart%3A%5Benabled.HipChatNotification%3Atrue%2C+enabled%3A%5BHipChatNotification%3Atrue%2C+_HipChatNotification%3A%5D%2C+type%3AHipChatNotification%2C+enabled._HipChatNotification%3A%2C+HipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%5D%2C+onstart.type%3AHipChatNotification%2C+onfailure.type%3AHipChatNotification%2C+onstart.enabled._HipChatNotification%3A%2C+onfailure.HipChatNotification.config.room%3AHosting%2C+onfailure.enabled._HipChatNotification%3A%2C+onstart.HipChatNotification.config.room%3AHosting%2C+onsuccess.type%3AHipChatNotification%5D&_notifySuccessAttach=&crontab.month._MAY=&crontab=%5Bmonth._MAY%3A%2C+month%3A%5B_MAY%3A%2C+_MAR%3A%2C+_APR%3A%2C+_DEC%3A%2C+_SEP%3A%2C+_FEB%3A%2C+_AUG%3A%2C+_OCT%3A%2C+_JAN%3A%2C+_JUN%3A%2C+_NOV%3A%2C+_JUL%3A%5D%2C+dayOfWeek._SAT%3A%2C+dayOfWeek%3A%5B_SAT%3A%2C+_FRI%3A%2C+_TUE%3A%2C+_SUN%3A%2C+_WED%3A%2C+_THU%3A%2C+_MON%3A%5D%2C+month._MAR%3A%2C+month._APR%3A%2C+dayOfWeek._FRI%3A%2C+month._DEC%3A%2C+dayOfWeek._TUE%3A%2C+dayOfWeek._SUN%3A%2C+month._SEP%3A%2C+month._FEB%3A%2C+month._AUG%3A%2C+month._OCT%3A%2C+dayOfWeek._WED%3A%2C+dayOfWeek._THU%3A%2C+dayOfWeek._MON%3A%2C+month._JAN%3A%2C+month._JUN%3A%2C+month._NOV%3A%2C+month._JUL%3A%5D&_notifyOnstartUrl=&crontab.dayOfWeek._SAT=&notifyPlugin.onsuccess.enabled._HipChatNotification=&crontab.month._MAR=&nodeRankAttribute=&_everyDayOfWeek=&orig.notifyPlugin.onstart.HipChatNotification.config.room=Hosting&orig=%5BnotifyPlugin.onstart.HipChatNotification.config.room%3AHosting%2C+notifyPlugin%3A%5Bonstart.HipChatNotification.config.room%3AHosting%2C+onstart%3A%5BHipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%5D%2C+onsuccess.HipChatNotification.config.room%3A%2C+onsuccess%3A%5BHipChatNotification.config.room%3A%2C+HipChatNotification%3A%5Bconfig.room%3A%2C+config%3A%5Broom%3A%5D%5D%5D%2C+onfailure.HipChatNotification.config.room%3AHosting%2C+onfailure%3A%5BHipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%5D%5D%2C+notifyPlugin.onsuccess.HipChatNotification.config.room%3A%2C+notifyPlugin.onfailure.HipChatNotification.config.room%3AHosting%5D&notifyPlugin.onsuccess.HipChatNotification.config.room=&notifyStartRecipients=&crontab.month._APR=&prefix=&dayOfMonth=%3F&formInput=true&_notifyOnfailureEmail=&_sessionwf=true&doNodedispatch=false&notifyPlugin.onstart.enabled.HipChatNotification=true&workflow.keepgoing=false&workflow=%5Bkeepgoing%3Afalse%2C+strategy%3Anode-first%5D&crontab.dayOfWeek._FRI=&crontab.month._DEC=&crontabString=0+19+15+%3F+*+*+*&crontab.dayOfWeek._TUE=&crontab.dayOfWeek._SUN=&workflow.strategy=node-first&crontab.month._SEP=&SYNCHRONIZER_TOKEN=6ebb686729db459f3c777187646990c592dd0740d01adcd232b73b1116365ffb&notifyPlugin.onstart.type=HipChatNotification&notifyPlugin.onfailure.type=HipChatNotification&crontab.month._FEB=&_sessionopts=true&nodeExcludePrecedence=true&hour=15&SYNCHRONIZER_URI=%2Fproject%2FAnsible-Automation%2Fjob%2Fedit%2F7713cb65-a8ef-4417-ad6f-1646971b3935&orig.notifyPlugin.onsuccess.HipChatNotification.config.room=&_everyMonth=&crontab.month._AUG=&crontab.month._OCT=&nodeThreadcount=1&retry=&nodeRankOrderAscending=true&notifySuccessUrl=&type=localexec&jobName=UKGeneral+Ansible+2&description=Execute+Ansible+against+UKGeneral&_notifyOnfailureUrl=&notified=true&crontab.dayOfWeek._WED=&nodeKeepgoing=false&notifyPlugin.onstart.enabled._HipChatNotification=&config.command=ansible-playbook+-i+%2Fopt%2Frundeck%2Fansible-playbooks%2Fhosts%2Fstage%2Fukgeneral+%2Fopt%2Frundeck%2Fansible-playbooks%2Fsite.yml+-l+ukgeneralstage.ixishosting.co.uk+-t+db%2Cweb+--check+--diff&config=%5Bcommand%3Aansible-playbook+-i+%2Fopt%2Frundeck%2Fansible-playbooks%2Fhosts%2Fstage%2Fukgeneral+%2Fopt%2Frundeck%2Fansible-playbooks%2Fsite.yml+-l+ukgeneralstage.ixishosting.co.uk+-t+db%2Cweb+--check+--diff%5D&notifyPlugin.onfailure.HipChatNotification.config.room=Hosting&notifyFailureUrl=&everyDayOfWeek=true&scheduled=false&notifyStartSubject=&crontab.dayOfWeek._THU=&notifyPlugin.onfailure.enabled._HipChatNotification=&notifyStartUrl=&filter=&everyMonth=true&notifySuccessRecipients=&useCrontabString=false&multipleExecutions=false&notifyPlugin.onstart.HipChatNotification.config.room=Hosting&minute=19&crontab.dayOfWeek._MON=&notifyFailureSubject=&notifyPlugin.onsuccess.type=HipChatNotification&_notifyOnstartEmail=&crontab.month._JAN=&groupPath=stage&_action_Update=Save&_notifyOnsuccessEmail=&crontab.month._JUN=&crontab.month._NOV=&_notifyOnsuccessUrl=&_notifyFailureAttach=&notifySuccessSubject=&orig.notifyPlugin.onfailure.HipChatNotification.config.room=Hosting&crontab.month._JUL=&timeout=&_sessionEditWFObject=Workflow%3A%28threadcount%3A1%29%7B+%5BPluginStep%7BnodeStep%3Dtrue%2C+type%3D%27localexec%27%2C+jsonData%3D%27%7B%22command%22%3A%22ansible-playbook+-i+%2Fopt%2Frundeck%2Fansible-playbooks%2Fhosts%2Fstage%2Fukgeneral+%2Fopt%2Frundeck%2Fansible-playbooks%2Fsite.yml+-l+ukgeneralstage.ixishosting.co.uk+-t+db%2Cweb+--check+--diff%22%7D%27%7D%5D+%7D&notifications=%7BeventTrigger%3Donfailure%2C+type%3DHipChatNotification%2C+configuration%3D%5Broom%3AHosting%5D%7D&notifications=%7BeventTrigger%3Donstart%2C+type%3DHipChatNotification%2C+configuration%3D%5Broom%3AHosting%5D%7D
Message: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow 
Caused by: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow 
Class: ScheduledExecutionController 
At Line: [1164] 
Code Snippet:
</pre>

<pre>
org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at rundeck.services.ProjectManagerService.$tt__existsFrameworkProject(ProjectManagerService.groovy:80)
	at rundeck.services.ProjectManagerService.$tt__getFrameworkProject(ProjectManagerService.groovy:68)
	at rundeck.services.FrameworkService.getFrameworkProject(FrameworkService.groovy:156)
	at rundeck.services.FrameworkService.getFrameworkPropertyResolver(FrameworkService.groovy:260)
	at rundeck.services.NotificationService.validatePluginConfig(NotificationService.groovy:66)
	at rundeck.services.ScheduledExecutionService.validatePluginNotification(ScheduledExecutionService.groovy:1545)
	at rundeck.services.ScheduledExecutionService$__updateNotificationsData_closure44.doCall(ScheduledExecutionService.groovy:1691)
	at rundeck.services.ScheduledExecutionService._updateNotificationsData(ScheduledExecutionService.groovy:1665)
	at rundeck.services.ScheduledExecutionService._doupdate(ScheduledExecutionService.groovy:1463)
	at rundeck.controllers.ScheduledExecutionController$_update_closure44.doCall(ScheduledExecutionController.groovy:1172)
	at rundeck.controllers.ScheduledExecutionController.update(ScheduledExecutionController.groovy:1164)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:744)
</pre>

**Comment by michlaustn** [comment]
Further testing shows the same issue occurs with other forms of executor.  For example when using the Command executor.

<pre>
Request: /project/Ansible-Automation/job/update/628015c2-8713-4e57-b6aa-cf41da7f40dc?loglevel=INFO&nodeRankOrderAscending=true&notifyFailureRecipients=&notifyPlugin.onfailure.enabled.HipChatNotification=true&notifyPlugin=%5Bonfailure.enabled.HipChatNotification%3Atrue%2C+onfailure%3A%5Benabled.HipChatNotification%3Atrue%2C+enabled%3A%5BHipChatNotification%3Atrue%2C+_HipChatNotification%3A%5D%2C+HipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%2C+enabled._HipChatNotification%3A%2C+type%3AHipChatNotification%5D%2C+onsuccess.enabled._HipChatNotification%3A%2C+onsuccess%3A%5Benabled._HipChatNotification%3A%2C+enabled%3A%5B_HipChatNotification%3A%5D%2C+HipChatNotification.config.room%3A%2C+HipChatNotification%3A%5Bconfig.room%3A%2C+config%3A%5Broom%3A%5D%5D%2C+type%3AHipChatNotification%5D%2C+onsuccess.HipChatNotification.config.room%3A%2C+onstart.enabled._HipChatNotification%3A%2C+onstart%3A%5Benabled._HipChatNotification%3A%2C+enabled%3A%5B_HipChatNotification%3A%2C+HipChatNotification%3Atrue%5D%2C+enabled.HipChatNotification%3Atrue%2C+HipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%2C+type%3AHipChatNotification%5D%2C+onfailure.HipChatNotification.config.room%3AHosting%2C+onfailure.enabled._HipChatNotification%3A%2C+onstart.enabled.HipChatNotification%3Atrue%2C+onstart.HipChatNotification.config.room%3AHosting%2C+onsuccess.type%3AHipChatNotification%2C+onstart.type%3AHipChatNotification%2C+onfailure.type%3AHipChatNotification%5D&notifySuccessUrl=&_notifySuccessAttach=&jobName=UKGeneral+Ansible+2&crontab.month._MAY=&crontab=%5Bmonth._MAY%3A%2C+month%3A%5B_MAY%3A%2C+_MAR%3A%2C+_APR%3A%2C+_DEC%3A%2C+_SEP%3A%2C+_FEB%3A%2C+_JAN%3A%2C+_JUN%3A%2C+_NOV%3A%2C+_AUG%3A%2C+_OCT%3A%2C+_JUL%3A%5D%2C+dayOfWeek._SAT%3A%2C+dayOfWeek%3A%5B_SAT%3A%2C+_WED%3A%2C+_THU%3A%2C+_FRI%3A%2C+_MON%3A%2C+_TUE%3A%2C+_SUN%3A%5D%2C+month._MAR%3A%2C+dayOfWeek._WED%3A%2C+dayOfWeek._THU%3A%2C+month._APR%3A%2C+dayOfWeek._FRI%3A%2C+month._DEC%3A%2C+dayOfWeek._MON%3A%2C+dayOfWeek._TUE%3A%2C+dayOfWeek._SUN%3A%2C+month._SEP%3A%2C+month._FEB%3A%2C+month._JAN%3A%2C+month._JUN%3A%2C+month._NOV%3A%2C+month._AUG%3A%2C+month._OCT%3A%2C+month._JUL%3A%5D&description=Execute+Ansible+against+UKGeneral&_notifyOnstartUrl=&_notifyOnfailureUrl=&crontab.dayOfWeek._SAT=&notifyPlugin.onsuccess.enabled._HipChatNotification=&notified=true&crontab.month._MAR=&nodeRankAttribute=&crontab.dayOfWeek._WED=&_everyDayOfWeek=&orig.notifyPlugin.onstart.HipChatNotification.config.room=Hosting&orig=%5BnotifyPlugin.onstart.HipChatNotification.config.room%3AHosting%2C+notifyPlugin%3A%5Bonstart.HipChatNotification.config.room%3AHosting%2C+onstart%3A%5BHipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%5D%2C+onsuccess.HipChatNotification.config.room%3A%2C+onsuccess%3A%5BHipChatNotification.config.room%3A%2C+HipChatNotification%3A%5Bconfig.room%3A%2C+config%3A%5Broom%3A%5D%5D%5D%2C+onfailure.HipChatNotification.config.room%3AHosting%2C+onfailure%3A%5BHipChatNotification.config.room%3AHosting%2C+HipChatNotification%3A%5Bconfig.room%3AHosting%2C+config%3A%5Broom%3AHosting%5D%5D%5D%5D%2C+notifyPlugin.onsuccess.HipChatNotification.config.room%3A%2C+notifyPlugin.onfailure.HipChatNotification.config.room%3AHosting%5D&notifyPlugin.onsuccess.HipChatNotification.config.room=&nodeKeepgoing=false&notifyPlugin.onstart.enabled._HipChatNotification=&notifyPlugin.onfailure.HipChatNotification.config.room=Hosting&notifyFailureUrl=&notifyStartRecipients=&everyDayOfWeek=true&scheduled=false&notifyStartSubject=&crontab.dayOfWeek._THU=&notifyPlugin.onfailure.enabled._HipChatNotification=&crontab.month._APR=&dayOfMonth=%3F&notifyStartUrl=&_notifyOnfailureEmail=&formInput=true&_sessionwf=true&filter=&everyMonth=true&doNodedispatch=false&notifySuccessRecipients=&notifyPlugin.onstart.enabled.HipChatNotification=true&workflow.keepgoing=false&workflow=%5Bkeepgoing%3Afalse%2C+strategy%3Anode-first%5D&useCrontabString=false&crontab.dayOfWeek._FRI=&multipleExecutions=false&crontab.month._DEC=&notifyPlugin.onstart.HipChatNotification.config.room=Hosting&crontabString=0+19+15+%3F+*+*+*&minute=19&crontab.dayOfWeek._MON=&crontab.dayOfWeek._TUE=&crontab.dayOfWeek._SUN=&notifyFailureSubject=&workflow.strategy=node-first&crontab.month._SEP=&notifyPlugin.onsuccess.type=HipChatNotification&notifyPlugin.onstart.type=HipChatNotification&SYNCHRONIZER_TOKEN=6f68f5a89e92e77514e25047813c6300f9ef507a10b243259b5751d84cd4a71c&notifyPlugin.onfailure.type=HipChatNotification&crontab.month._FEB=&_sessionopts=true&_notifyOnstartEmail=&crontab.month._JAN=&nodeExcludePrecedence=true&groupPath=stage&_action_Update=Save&_notifyOnsuccessEmail=&hour=15&SYNCHRONIZER_URI=%2Fproject%2FAnsible-Automation%2Fjob%2Fedit%2F628015c2-8713-4e57-b6aa-cf41da7f40dc&crontab.month._JUN=&crontab.month._NOV=&orig.notifyPlugin.onsuccess.HipChatNotification.config.room=&_notifyOnsuccessUrl=&_notifyFailureAttach=&_everyMonth=&crontab.month._AUG=&crontab.month._OCT=&notifySuccessSubject=&nodeThreadcount=1&orig.notifyPlugin.onfailure.HipChatNotification.config.room=Hosting&crontab.month._JUL=&retry=&timeout=&_sessionEditWFObject=Workflow%3A%28threadcount%3A1%29%7B+%5Bcommand%28+exec%3A+ansible-playbook+-i+%2Fopt%2Frundeck%2Fansible-playbooks%2Fhosts%2Fstage%2Fukgeneral+%2Fopt%2Frundeck%2Fansible-playbooks%2Fsite.yml+-l+ukgeneralstage.ixishosting.co.uk+--check+--diff%29%2C+command%28+exec%3A+pwd%29%5D+%7D&notifications=%7BeventTrigger%3Donfailure%2C+type%3DHipChatNotification%2C+configuration%3D%5Broom%3AHosting%5D%7D&notifications=%7BeventTrigger%3Donstart%2C+type%3DHipChatNotification%2C+configuration%3D%5Broom%3AHosting%5D%7D
Message: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow 
Caused by: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow 
Class: ScheduledExecutionController 
At Line: [1164] 
Code Snippet:
</pre>

<pre>
org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at rundeck.services.ProjectManagerService.$tt__existsFrameworkProject(ProjectManagerService.groovy:80)
	at rundeck.services.ProjectManagerService.$tt__getFrameworkProject(ProjectManagerService.groovy:68)
	at rundeck.services.FrameworkService.getFrameworkProject(FrameworkService.groovy:156)
	at rundeck.services.FrameworkService.getFrameworkPropertyResolver(FrameworkService.groovy:260)
	at rundeck.services.NotificationService.validatePluginConfig(NotificationService.groovy:66)
	at rundeck.services.ScheduledExecutionService.validatePluginNotification(ScheduledExecutionService.groovy:1545)
	at rundeck.services.ScheduledExecutionService$__updateNotificationsData_closure44.doCall(ScheduledExecutionService.groovy:1691)
	at rundeck.services.ScheduledExecutionService._updateNotificationsData(ScheduledExecutionService.groovy:1665)
	at rundeck.services.ScheduledExecutionService._doupdate(ScheduledExecutionService.groovy:1463)
	at rundeck.controllers.ScheduledExecutionController$_update_closure44.doCall(ScheduledExecutionController.groovy:1172)
	at rundeck.controllers.ScheduledExecutionController.update(ScheduledExecutionController.groovy:1164)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:744)
</pre>

**Comment by gschueler** [comment]
I was able to reproduce this
