### ISSUE TITLE
Key Storage - DB Backend Exception - Could not obtain current Hibernate Session

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#1197]
Hi,

i would like to use the db backend for key storage.

My configuration looks like described in http://rundeck.org/docs/plugins-user-guide/configuring.html#storage-plugins

My $RDECK_BASE/server/config/rundeck-config.properties:
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=/

Any execution on a remote node failed with the following exception:

```
[workflow] finishExecuteNodeStep(myNode_myUser): NodeDispatch: Unknown: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
Failed dispatching to node myNode_myUser: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
Failed dispatching to node myNode_myUser: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:158)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:177)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:258)
	at com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:79)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy$DispatchedWorkflow.dispatch(NodeFirstWorkflowStrategy.java:374)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:118)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:64)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:196)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWFSectionNodeDispatch(NodeFirstWorkflowStrategy.java:180)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:106)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:210)
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:166)
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:123)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractFindByPersistentMethod.doInvokeInternalWithExpressions(AbstractFindByPersistentMethod.java:62)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractClausedStaticPersistentMethod.doInvokeInternal(AbstractClausedStaticPersistentMethod.java:544)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractClausedStaticPersistentMethod.doInvokeInternal(AbstractClausedStaticPersistentMethod.java:418)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:79)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:72)
	at org.grails.datastore.gorm.finders.FinderMethod$invoke$0.call(Unknown Source)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.call(GormStaticApi.groovy)
	at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:59)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:93)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at rundeck.services.DbStorageService.findResource(DbStorageService.groovy:157)
	at sun.reflect.GeneratedMethodAccessor397.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at rundeck.services.DbStorageService.getResource(DbStorageService.groovy:147)
	at rundeck.services.DbStorageService.getResource(DbStorageService.groovy)
	at com.dtolabs.rundeck.core.storage.ResolvedExtTree.getResource(ResolvedExtTree.java:52)
	at org.rundeck.storage.impl.DelegateTree.getResource(DelegateTree.java:40)
	at org.rundeck.storage.impl.DelegateTree.getResource(DelegateTree.java:40)
	at org.rundeck.storage.conf.ListenerTree.getResource(ListenerTree.java:54)
	at org.rundeck.storage.impl.DelegateTree.getResource(DelegateTree.java:40)
	at org.rundeck.storage.conf.ConverterTree.getResource(ConverterTree.java:53)
	at org.rundeck.storage.impl.DelegateTree.getResource(DelegateTree.java:40)
	at org.rundeck.storage.conf.ConverterTree.getResource(ConverterTree.java:53)
	at org.rundeck.storage.impl.DelegateTree.getResource(DelegateTree.java:40)
	at com.dtolabs.rundeck.core.storage.AuthRundeckStorageTree.getResource(AuthRundeckStorageTree.java:130)
	at com.dtolabs.rundeck.core.storage.AuthRundeckStorageTree.getResource(AuthRundeckStorageTree.java:18)
	at com.dtolabs.rundeck.core.storage.ResolvedExtTree.getResource(ResolvedExtTree.java:52)
	at org.rundeck.storage.impl.StringToPathTree.getResource(StringToPathTree.java:38)
	at com.dtolabs.rundeck.core.execution.impl.jsch.NodeSSHConnectionInfo.getPrivateKeyStorageData(NodeSSHConnectionInfo.java:65)
	at com.dtolabs.rundeck.core.tasks.net.SSHTaskBuilder.configureSSHBase(SSHTaskBuilder.java:554)
	at com.dtolabs.rundeck.core.tasks.net.SSHTaskBuilder.buildScp(SSHTaskBuilder.java:684)
	at com.dtolabs.rundeck.core.tasks.net.SSHTaskBuilder.buildScp(SSHTaskBuilder.java:664)
	at com.dtolabs.rundeck.core.execution.impl.jsch.JschScpFileCopier.copyFile(JschScpFileCopier.java:158)
	at com.dtolabs.rundeck.core.execution.impl.jsch.JschScpFileCopier.copyFile(JschScpFileCopier.java:217)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.fileCopyFile(ExecutionServiceImpl.java:261)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeScriptFile(ScriptFileNodeStepExecutor.java:140)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:69)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:149)
	... 18 more
Caused by: org.hibernate.HibernateException: No Session found for current thread
	at org.codehaus.groovy.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:1014)
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:208)
	... 69 more
```

With the File Backend all works ($RDECK_BASE/server/config/rundeck-config.properties):
rundeck.storage.provider.1.path=/
rundeck.storage.provider.1.type=file
rundeck.storage.provider.1.config.baseDir=${framework.var.dir}/storage

**Comment by gschueler** [comment]
any info on what kind of job was being executed? a few questions:

was it multi threaded? 
was the command within a job reference or anything like that? 
was it a long running job?
was it a scheduled job?

thanks

**Comment by sidewinder12s** [comment]
1. Single step command that was calling a powershell script
2. Nope, just a single command in one step in one job
3. Would have been about a 10-20 minute job to complete but it didn't look like it connected at all to the remote host.
4. It was a scheduled job. I also switched to using the file backend and it works. 

The log output is the same for my job as schast's

**Comment by gschueler** [comment]
thanks, I was able to reproduce it
