### ISSUE TITLE
Service unavailable after Ugprade to 2.5.0-1

### ISSUE THREAD

**Issue by pfweberp** [rundeck/rundeck#1202]
Hey,

I just tried to upgrade my second (standby) Rundeck instance from 2.0.3.1-GA to 2.5.0.1-GA using the Debian package. On the first node it worked very well, except the already known database issue from #1179 .

On the second node I get the attached exception during startup.
While searching for "transactionManagerPostProcessor" I found #337 and #937 - so I tried to check the permissions of /tmp/rundeck/ - but they're correct.

Any idea what the cause could be?
On the first node I've upgraded the same way, I didn't encounter that problem.

___________________________________________________

2015-04-30 13:43:51,890 [main] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:105)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	... 11 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	... 11 more
Caused by: java.lang.ExceptionInInitializerError
	at rundeck.ScheduledExecutionFilter$__clinit__closure4.doCall(ScheduledExecutionFilter.groovy:43)
	... 11 more
Caused by: groovy.lang.MissingPropertyException: No such property: VALID_RESOURCE_NAME_CHARSET_REGEX for class: com.dtolabs.rundeck.core.common.FrameworkResource
	at com.dtolabs.rundeck.app.api.ApiBulkJobDeleteRequest.<clinit>(ApiBulkJobDeleteRequest.groovy:32)
	... 12 more
2015-04-30 13:43:51,899 [main] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:105)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	... 11 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	... 11 more
Caused by: java.lang.ExceptionInInitializerError
	at rundeck.ScheduledExecutionFilter$__clinit__closure4.doCall(ScheduledExecutionFilter.groovy:43)
	... 11 more
Caused by: groovy.lang.MissingPropertyException: No such property: VALID_RESOURCE_NAME_CHARSET_REGEX for class: com.dtolabs.rundeck.core.common.FrameworkResource
	at com.dtolabs.rundeck.app.api.ApiBulkJobDeleteRequest.<clinit>(ApiBulkJobDeleteRequest.groovy:32)
	... 12 more
2015-04-30 13:43:51.901:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/rundeck,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:105)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)
Caused by: 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:105)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)
Caused by: 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:105)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)
Caused by: 
java.lang.ExceptionInInitializerError
	at rundeck.ScheduledExecutionFilter$__clinit__closure4.doCall(ScheduledExecutionFilter.groovy:43)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:105)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)
Caused by: 
groovy.lang.MissingPropertyException: No such property: VALID_RESOURCE_NAME_CHARSET_REGEX for class: com.dtolabs.rundeck.core.common.FrameworkResource
	at com.dtolabs.rundeck.app.api.ApiBulkJobDeleteRequest.<clinit>(ApiBulkJobDeleteRequest.groovy:32)
	at rundeck.ScheduledExecutionFilter$__clinit__closure4.doCall(ScheduledExecutionFilter.groovy:43)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:105)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:66)

**Comment by gschueler** [comment]
This error:

```
Caused by: groovy.lang.MissingPropertyException: No such property: VALID_RESOURCE_NAME_CHARSET_REGEX for class: com.dtolabs.rundeck.core.common.FrameworkResource
```

sounds like there is some issue loading the correct java classes.  Is it possible that some of the previous 2.0.x files are still on disk?

Also, i assume you saw the upgrade guide information about new requirements  (e.g Java 7)?

**Comment by pfweberp** [comment]
Hey,

I'm already using Java 8 (1.8.0_45) - so that shouldn't be a problem. ;-)
Your assumption could be possible. I just downloaded the latest .deb-file and installed it with "dpkg -i".
On the first node, where it works, I did the same. 

Which previous files could be the cause for example?

**Comment by gschueler** [comment]
look for 2.0.2 files in the `/var/lib/rundeck/exp/webapp/WEB-INF/lib` dir. E.g. if there are more than one rundeck-core-*.jar files

**Comment by pfweberp** [comment]
Hey

There was really a rundeck-core-2.0.2.jar in the mentioned dir.
After I deleted it, Rundeck started again without any error. :+1: 

I'm just confused cause the rundeck-core-

**Comment by gschueler** [comment]
@pfweberp probably just chance that the correct jar was loaded in the first node
