### ISSUE TITLE
Hibernate encoding error

### ISSUE THREAD

**Issue by RyanGoldstein** [rundeck/rundeck#1205]
I just upgraded from 1.6.1 to 2.5.0 with a MySQL DB. I am getting this fatal error on the Jobs page for all projects:

```
Error Details
Request: /project/Standalone/jobs
Message: Unable to convert string [¬ísrjava.net.URL%76üärIhashCodeIportL	authoritytLjava/lang/String;Lfileq~Lhostq~Lprotocolq~Lrefq~xpÿÿÿÿÿÿÿÿt	localhostt,/Environments.json?Path=${option.Path.value}q~thttppx] to URL : java.net.MalformedURLException: no protocol: ¬ísrjava.net.URL%76üärIhashCodeIportL	authoritytLjava/lang/String;Lfileq~Lhostq~Lprotocolq~Lrefq~xpÿÿÿÿÿÿÿÿt localhostt,/Environments.json?Path=${option.Path.value}q~thttppx 
Caused by: Unable to convert string [¬ísrjava.net.URL%76üärIhashCodeIportL	authoritytLjava/lang/String;Lfileq~Lhostq~Lprotocolq~Lrefq~xpÿÿÿÿÿÿÿÿt	localhostt,/Environments.json?Path=${option.Path.value}q~thttppx] to URL : java.net.MalformedURLException: no protocol: ¬ísrjava.net.URL%76üärIhashCodeIportL	authoritytLjava/lang/String;Lfileq~Lhostq~Lprotocolq~Lrefq~xpÿÿÿÿÿÿÿÿt localhostt,/Environments.json?Path=${option.Path.value}q~thttppx 
Class: MenuController 
At Line: [208] 
Code Snippet:
```

```
Stack Trace
org.hibernate.HibernateException: Unable to convert string [¬ísrjava.net.URL%76üärIhashCodeIportL	authoritytLjava/lang/String;Lfileq~Lhostq~Lprotocolq~Lrefq~xpÿÿÿÿÿÿÿÿt	localhostt,/Environments.json?Path=${option.Path.value}q~thttppx] to URL : java.net.MalformedURLException: no protocol: ¬ísrjava.net.URL%76üärIhashCodeIportL	authoritytLjava/lang/String;Lfileq~Lhostq~Lprotocolq~Lrefq~xpÿÿÿÿÿÿÿÿt	localhostt,/Environments.json?Path=${option.Path.value}q~thttppx
	at rundeck.services.ScheduledExecutionService.listWorkflows(ScheduledExecutionService.groovy:131)
	at rundeck.controllers.MenuController.listWorkflows(MenuController.groovy:299)
	at rundeck.controllers.MenuController$_closure9.doCall(MenuController.groovy:258)
	at rundeck.controllers.MenuController$_closure8.doCall(MenuController.groovy:208)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:910)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)
```

Any suggestions would be really helpful. Thanks!

**Comment by gschueler** [comment]
did you follow the upgrade guide instructions? specifically there is a section about upgrading h2 from 1.6 to 2.0. 
http://rundeck.org/docs/upgrading/index.html#upgrading-to-rundeck-2.0-from-1.6.x

**Comment by gschueler** [comment]
sorry, I see you said Mysql, disregard note about h2.

The upgrade guide explains how to export your projects to import to a clean database for 2.x http://rundeck.org/docs/upgrading/index.html#upgrading-to-rundeck-2.0-from-1.6.x

**Comment by RyanGoldstein** [comment]
Yeah, I was just trying to do it the indirect/unclean way. The instructions made it sound possible just less desirable. And I would have gotten away with it if it weren't for those meddling kids. Thanks for setting me straight... +1
