### ISSUE TITLE
Rundeck start fails in Tomcat 7 on Win2012

### ISSUE THREAD

**Issue by jasonaughton** [rundeck/rundeck#1216]
I've deployed Rundeck 2.5.0 to run in Tomcat 7 on Windows 2012 server. However, when trying to start the Rundeck app the etc folder and its contents do not get created in the rundeck base (the other folders and files in rundeck base get created fine). The localhost log file has this entry, coinciding with the failure to start:
SEVERE: Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/Apache Software Foundation/Tomcat 7.0/webapps/rundeck-2.5.0/WEB-INF/lib/grails-plugin-log4j-2.4.4.jar!/META-INF/grails-plugin.xml
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:126)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1322)
	at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:694)
	at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/Apache Software Foundation/Tomcat 7.0/webapps/rundeck-2.5.0/WEB-INF/lib/grails-plugin-log4j-2.4.4.jar!/META-INF/grails-plugin.xml
	at AssetPipelineGrailsPlugin$_closure1.doCall(AssetPipelineGrailsPlugin.groovy:54)

Any idea what might be wrong here?

**Comment by gschueler** [comment]
"Illegal character in path at index 16", i think the fact that your install path contains spaces (" ") is causing some URI validation issue.

Can you try relocating the webapps dir, or the tomcat install to a path without spaces?

**Comment by gschueler** [comment]
we may be able to upgrade our use of that AssetPipeline plugin and fix this issue, but please try the workaround

**Comment by jasonaughton** [comment]
Moving the Tomcat installation to a path without spaces has fixed the problem, Rundeck starts up fine. I have another issue now, in that I can login to the Rundeck UI but as soon as I have logged in I get a 404 response from http://localhost:8080/rundeck/menu/home , I guess that's a different issue though.

**Comment by ahonor** [comment]
@jasonaughton Edit the rundeck-config.properties and declare grails.serverURL to the public address you want to use.

**Comment by jasonaughton** [comment]
Thanks @ahonor, that was the missing link. All working now.
