### ISSUE TITLE
CLI in GUI inline script step

### ISSUE THREAD

**Issue by pkr1234** [rundeck/rundeck#1217]
My JSON file is supplying another json in "values" like this (there are more entries in value, I've just shown two tags):

```
[
  { "name" : "ENV1", "value" : {
                                        "EC2Tag1" : "sometag",
                                        "EC2Tag2" : "anothertag"
                                      }
  },
  { "name" : "ENV2", "value" : {
                                        "EC2Tag1" : "sometag",
                                        "EC2Tag2" : "anothertag"
                                      }
  }
]
```

I supply this JSON in remote option provider "ENVIRONMENT". The option ENVIRONMENT contains the "value" which is another JSON. All good so far. 

But there is no way to filter the nodes by EC2Tag1 and EC2Tag2 using the ${option.field} syntax as rundeck does not provide any way to manipulate option. 

I then write an inline script step to parse the json in ENVIRONMENT option and grab that value. This will execute on the local node and I still can't filter.

So I now use the "dispatch" command in inline script step which seemed like the way to go (GUI with CLI!!). But it complains about authentication. It seems the CLI cannot use GUI authentication. 

Is there any other way to achieve what I'm doing? I'm finding rundeck a good tool but rather limiting.  For example:
- I can't set an option from the workflow step
- I can't use another option as JSON provider model. This would've been really cool and served my purpose easily.
- I can't set default of an option to a value to another option
- I can't select all to multivalue option by default 

and so on ..

**Comment by pkr1234** [comment]
After endless hours, I'm still getting nowhere. It appears CLI command does not work in GUI inline script step?? 

```
ERROR BaseFormAuthenticator: Form-based auth failed
com.dtolabs.rundeck.core.CoreException: Error making server request to https://myrundeckserver.com: Unable to authenticate user: rundeck.cli 
	at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:200)
	at com.dtolabs.client.services.RundeckAPICentralDispatcher.submitRunRequest(RundeckAPICentralDispatcher.java:378)
	at com.dtolabs.client.services.RundeckAPICentralDispatcher.queueDispatcherScript(RundeckAPICentralDispatcher.java:295)
	at com.dtolabs.rundeck.core.cli.ExecTool.queueAction(ExecTool.java:431)
	at com.dtolabs.rundeck.core.cli.ExecTool.run(ExecTool.java:368)
	at com.dtolabs.rundeck.core.cli.ExecTool.main(ExecTool.java:545)
Caused by: com.dtolabs.client.utils.AuthorizationFailureException: Unable to authenticate user: rundeck.cli 
	at com.dtolabs.client.utils.BaseHttpClientChannel.doAuthentication(BaseHttpClientChannel.java:129)
	at com.dtolabs.client.utils.HttpClientChannel.makeRequest(HttpClientChannel.java:331)
	at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:196)
	... 5 more
error: Error making server request to https://myrundeckserver.com: Unable to authenticate user: rundeck.cli 
Result: 1
Failed: NonZeroResultCode: Result code was 1
Execution failed: 55167: [Workflow step failures: {1=Dispatch failed on 1 nodes: [rndvmhsvr01: NonZeroResultCode: Result code was 1]}, Node failures: {rndvmhsvr01=[NonZeroResultCode: Result code was 1]}]

```

The user rundeck.cli has been configured in framework.properties. The "dispatch" command works when I ssh to the server where rundeck has been installed. Why does it not work in GUI inline script?
