### ISSUE TITLE
Notification validation: require value for email/webhook

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck#1250]
If selecting email or webhook notification, there is no validation that proper notification configuration is provided (email addres or webhook url). Some simple validation would be good, possibly just that something is specified.

Rundeck 2.5.1

**Comment by andham** [comment]
I'm seeing this error in service.log, which is think is because no url is specified for a webhook notification:

> ERROR NotificationService: Error sending notification: Notification{eventTrigger='onstart', type='url', content='null'}: class java.lang.NullPointerException: Cannot invoke method split() on null object
java.lang.NullPointerException: Cannot invoke method split() on null object
        at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:300)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:142)
        at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:84)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:81)
        at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy:759)
        at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:287)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:122)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by gschueler** [comment]
email/webhook url should have validation, this sounds like a regression

**Comment by gschueler** [comment]
validation of email/url is performed if a value is specified, but it looks like no check that it is not blank
