### ISSUE TITLE
Service Unavailable on startup 2.5.1-1.7GA installed from rpm

### ISSUE THREAD

**Issue by touzoku** [rundeck/rundeck#1252]
Hi!

I installed rundeck from rpm but on startup it gives error 503 with the following stacktrace:
```
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
2015-05-20 11:22:30.397:INFO:oejs.Server:jetty-7.6.0.v20120127
2015-05-20 11:22:32.696:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2015-05-20 11:22:34.266:INFO:/:Initializing Spring root WebApplicationContext
INFO  BootStrap: Starting Rundeck 2.5.1-1...
INFO  BootStrap: using rdeck.base system property: /var/lib/rundeck
INFO  BootStrap: loaded configuration: /etc/rundeck/framework.properties
ERROR BootStrap: NOT importing existing filesystem projects filesystem
INFO  BootStrap: RSS feeds enabled
2015-05-20 11:22:57.396:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
2015-05-20 11:22:57.419:WARN:oejs.Holder:
java.lang.ClassNotFoundException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:92)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:71)
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:84)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
2015-05-20 11:22:57.422:WARN:oejuc.AbstractLifeCycle:FAILED sitemesh: javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:91)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
2015-05-20 11:22:57.423:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:91)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)

�
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)

�
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
2015-05-20 11:22:57.471:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440
```

I tried OpenJDK version 7 and 8. Oracle Java 7 and 8. Nothing fixes the problem.

**Comment by touzoku** [comment]
Actually it looks like the upgrade of Grails is causing this. Same issue as described here, I guess http://stackoverflow.com/questions/28887118/grails-2-4-classnotfoundexception-sitemesh-grailspagefilter

**Comment by saimak** [comment]
Facing the same issue, any resolution ?

**Comment by touzoku** [comment]
Actually downgrading to 2.4.2 solves the problem. 2.5.0 still has it.

**Comment by saimak** [comment]
It worked, thanks !!

**Comment by gschueler** [comment]
if you modified the `web.xml` file, upgrading rundeck may cause this issue.  you need need to use the new web.xml in rundeck 2.5.1, and then apply any changes you made manually back to it.

you can check it by running `rpm --verify rundeck`

**Comment by michaelPf85** [comment]
I have the same issue, and I just downgraded to 2.5.0 to fix it.

The web.xml file is the default one : I only modify it to put my AD group name as a "role" name, and I have to put it back manually after each update because the rpm overwrites it.

**Comment by stack72** [comment]
I just faced the same issue on ubuntu 14.04

```
2015-06-05 11:52:04.694:INFO:/:Initializing Spring root WebApplicationContext
2015-06-05 11:59:01,733 [main] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: java.lang.NullPointerException
	... 11 more
2015-06-05 11:59:01,740 [main] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: java.lang.NullPointerException
	... 11 more
2015-06-05 11:59:01.740:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by:
java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
2015-06-05 11:59:01.790:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440
```

This was on a brand new installation *not an upgrade* 

```
root@ip-10-0-64-34:/# dpkg-query -l | grep rundeck
ii  rundeck                             2.5.0                            all          No ordinary wooden deck. You can build a bon fire on this deck.
```
