### ISSUE TITLE
Execution status not getting updated in 2.5.0 & 2.5.1

### ISSUE THREAD

**Issue by pamri** [rundeck/rundeck#1257]
I had setup a Rundeck 2.4.2 Tomcat cluster using a shared database, shared directory for logs, memcached session manager and the Apache load balancer for handling the failover. To test the setup, I run a job and then disable and stop instance 1. The instance 2 shows the job progress while instance 1 exits after running this job. I see a "job succeeded" message on instance 2.

When I moved this setup to 2.5.0 and 2.5.1., I see the job was getting completed but the 2nd instance was not showing the job as "Succeeded". After some debugging, I see that instance 1 exits immediately after running the job but before saving the "execution status" and causes an exception.

I have pasted a snippet of the logs. Let me know if you want more details and I will put in the full logs :

2.5.1 Job where it fails to update the status :

```
2015-05-26 10:12:22,923 [quartzScheduler_Worker-3] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Execution 102 save result status: caught exception: Method on class [rundeck.Execution] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
java.lang.IllegalStateException: Method on class [rundeck.Execution] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:1809)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure3.doCall(ExecutionJob.groovy:449)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:392)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:458)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:143)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

2.4.2 log where it succesfully updates the status :

```
2015-05-26 10:52:32,669 [quartzScheduler_Worker-1] INFO  org.rundeck.execution.status - finish (admin): id: 104 state: succeeded project: test user: admin job: 66389177-1709-461d-9ff3-480762dbe6b6 /Test Failover
2015-05-26 10:52:32,730 [quartzScheduler_Worker-1] INFO  grails.app.services.rundeck.services.ExecutionService - updated scheduled Execution
```

**Comment by pamri** [comment]
This also happens when there is a single instance of Rundeck (in Tomcat). To reproduce,
1. Start Rundeck and start a job
2. Shutdown Rundeck
3. Start Rundeck 
4. Go to the job stats page. The job is shown as "completed" but "Killed" . 

The logs are here : https://gist.github.com/pamri/ad15296616a5d9995557

**Comment by ahonor** [comment]
This job will now be marked incomplete.
