### ISSUE TITLE
Weird Startup Issue for Rundeck 2.5.x

### ISSUE THREAD

**Issue by stack72** [rundeck/rundeck#1276]
I have just provisioned a new rundeck server and when it starts, I get the following errors:

```
2015-06-05 11:52:04.694:INFO:/:Initializing Spring root WebApplicationContext
2015-06-05 11:59:01,733 [main] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: java.lang.NullPointerException
	... 11 more
2015-06-05 11:59:01,740 [main] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	... 11 more
Caused by: java.lang.NullPointerException
	... 11 more
2015-06-05 11:59:01.740:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
Caused by:
java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:112)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:72)
2015-06-05 11:59:01.790:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440
```

Rundeck Version:

```
root@ip-10-0-64-34:/# dpkg-query -l | grep rundeck
ii  rundeck                             2.5.0                            all          No ordinary wooden deck. You can build a bon fire on this deck.
```

I tried a 2.5.1 server and got the same issue. My setup is

EC2 instance with DB Project storage enabled. DB is Mysql. Looks similar to this error

https://github.com/ondrej-kvasnovsky/grails-vaadin-plugin/issues/48

**Comment by gschueler** [comment]
what java version? 2.5 only supports java 7/8

**Comment by stack72** [comment]
@gschueler 

```
ubuntu@ip-10-0-7-142:~$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by gschueler** [comment]
Can you paste your rundeck-config.properties?

does the same thing occur if you switch back to h2?

**Comment by stack72** [comment]
```
ubuntu@ip-10-0-7-142:~$ sudo cat /etc/rundeck/rundeck-config.properties
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=DEBUG
rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=https://<url>
dataSource.dbCreate = update
dataSource.url=jdbc:mysql://<connection string>:3306/rundeck
rundeck.projectsStorageType=db
rundeck.clusterMode.enabled=true
rundeck.gui.title=Rundeck Host: ip-10-0-7-142
dataSource.driverClassName=com.mysql.jdbc.Driver
dataSource.dialect=org.hibernate.dialect.MySQLDialect
dataSource.username=rundeck
dataSource.password=rundeck
rundeck.execution.logs.fileStoragePlugin=org.rundeck.amazon-s3
```

**Comment by stack72** [comment]
@gschueler Just a FYI, this was a MySQL connection issue. The stacktrace was sending me off in a completely different direction but we are all good now :)

**Comment by gschueler** [comment]
aha ok! good to hear it is resolved :)

**Comment by diekvar** [comment]
Can you please share what the the connection issue and how you resolved it? 
I'm having a similar issue where i'm trying to direct Rundeck to use s3 as storage.
After configuring the s3 setting (following suggestions from similar topics here), my projects are gone and s3 is not backing up.
The only thing i found that's giving an error about s3 is when i look at the activity log in Rundeck, the history of the old projects that disappear provide this error:
Log file availability could not be determined: Unable to execute HTTP request: Connect to `s3.amazonaws.com:443 [s3.amazonaws.com/ipaddress] failed: connect timed out (via plugin "org.rundeck.amazon-s3")`

any thoughts?
