### ISSUE TITLE
2.5.0 resource fail from file

### ISSUE THREAD

**Issue by Mario-12** [rundeck/rundeck#1283]
Hi all,

My rundeck take the resource from a url like `http://rundeck:rrI-74EtL$kleqOA@mypuppetmasterserver/hosts?rundeck=true&format=yaml`, the url returns a yaml file and it works without problem. 

Being now my url very slow I've created a crontab that downloads the file on the disk, same rundeck user, and I've set rundeck to use it. 

Now the scripts are a lot more faster but rundeck sometime returns errors like:
```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={tags=domain=mydomain+class=app_service, dominant=false, }}
				at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.validateNodeSet(NodeFirstWorkflowStrategy.java:341)
				at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:84)
				at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
				at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
			Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={tags=domain=mydomain+class=app_service, dominant=false, }}
			No matched nodes: NodeSet{includes={tags=domain=mydomain+class=app_service, dominant=false, }}
```

The same script, with the same settings, if relunched can carry on until the end without problems or fail in another point: the error are not always in the same points.

the filter of the script is set dynamically with `tags: domain=${option.domain}+class=${option.app_name}` 

Thank you for any help..

**Comment by Mario-12** [comment]
Hi all,

This is the stack trace of another error that appear randomly, in a random position only when I use the file resource, like the first one, maybe it can be useful to understand the problem:

```
12:30:09	localhost	 8. Run puppet with tags	[workflow] finishExecuteNodeStep(mynode01): NodeDispatch: Succeeded
12:30:09			8: Workflow step finished, result: Dispatch successful (1 nodes)
12:30:09			[workflow] Finish step: 8,NodeDispatch
12:30:09		 9. See if there is something to start like jboss or tomcat	[workflow] Begin step: 9,NodeDispatch
12:30:09			9: Workflow step executing: com.dtolabs.rundeck.execution.ExecutionItemFactory$5@44fa30ae
12:30:09			preparing for sequential execution on 1 nodes
12:30:09			Executing command on node: myserver01, NodeEntryImpl{tags=[class=attribute1,  class=attibute2, domain=mydomain, class=attibute3], attributes={..., Environment=stage, username=rundeck, osArch=x86_64, osVersion=6.3, description=, hostname=mynode01, nodename=mynode01, osName=CentOS}, project='null'}
12:30:09	mynode01	 9. See if there is something to start like jboss or tomcat	[workflow] beginExecuteNodeStep(mynode01): NodeDispatch: com.dtolabs.rundeck.execution.ExecutionItemFactory$5@44fa30ae
12:30:09			No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}
12:30:09	localhost	 9. See if there is something to start like jboss or tomcat	[workflow] finishExecuteNodeStep(mynode01): NodeDispatch: Unknown: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}
12:30:09			Failed dispatching to node mynode01: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}
12:30:09			Failed dispatching to node mynode01: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:158)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:177)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:258)
	at com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:79)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy$DispatchedWorkflow.dispatch(NodeFirstWorkflowStrategy.java:374)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:118)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:64)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:196)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWFSectionNodeDispatch(NodeFirstWorkflowStrategy.java:180)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:106)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Caused by: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at rundeck.services.ExecutionService.runJobRefExecutionItem(ExecutionService.groovy:2398)
	at rundeck.services.ExecutionService.this$2$runJobRefExecutionItem(ExecutionService.groovy)
	at rundeck.services.ExecutionService$this$2$runJobRefExecutionItem$30.callCurrent(Unknown Source)
	at rundeck.services.ExecutionService.executeNodeStep(ExecutionService.groovy:2736)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:149)
	... 18 more
12:30:09			[workflow] Finish step: 9,NodeDispatch
12:30:09			[workflow] Finish execution:  rundeck-workflow-node-first: [Workflow result: , step failures: {9=Dispatch failed on 1 nodes: [mynode01: Unknown: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=rmynode01, dominant=false, }}]}, Node failures: {rmynode01=[Unknown: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}]}, flow control: Continue, status: failed]
12:30:09			[Workflow result: , step failures: {9=Dispatch failed on 1 nodes: [mynode01: Unknown: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}]}, Node failures: {mynode01=[Unknown: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}]}, flow control: Continue, status: failed]
12:30:09			Execution failed: 741: [Workflow result: , step failures: {9=Dispatch failed on 1 nodes: [mynode01: Unknown: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}]}, Node failures: {rmynode01=[Unknown: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: NodeSet{includes={name=mynode01, dominant=false, }}]}, flow control: Continue, status: failed]```

**Comment by gschueler** [comment]
make sure your crontab which downloads the file overwrites the existing file atomically.  If your process writes to the file directly, Rundeck may try reading/parsing the file when it is empty or has invalid Yaml or something.  

E.g. instead of this:

    curl $URL > /var/rundeck/projects/myproject/etc/resources.yaml

do something like this:

    curl $URL > /tmp/myoutput
    mv /tmp/myoutput /var/rundeck/projects/myproject/etc/resources.yaml

**Comment by Mario-12** [comment]
Done. I think the issue is fixed. Thank you very much!
