### ISSUE TITLE
Simultaneously triggered jobs sometimes hang

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#1310]
I have setup RunDeck 2.5.1-1 on CentOS 6.6 using MySQL for the DB.

I have a 4 jobs that are triggered simultaneously from Jenkins, most of the time these jobs execute to completion without any problems.  On the odd occasion I have found that jobs hang attempting to execute and continue in this state until I kill them.  I have spotted the following in the server.log when this happens:

```
2015-06-30 14:49:09,691 [quartzScheduler_Worker-9] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Unable to start Job execution: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
        at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:221)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:92)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.HibernateException: No Session found for current thread
        ... 7 more
```

From the frontend, if I try to access logs for the execution I am presented with the message `Execution Summary and Report detail is not available.`, drilling down into this I find `The Execution Log could not be found.`

I have also seen this issue when using the out of the box filesystem DB provided with RunDeck.

**Comment by jherrmann** [comment]
I have the same problem with RunDeck 2.5.1-1 on Red Hat 6.6 using oracle 11g as DB.

I trigger the same job several times simultaneously via `tools/bin/run` script. Very rarely a job execution hangs. I found the following in `var/log/service.log`: 

````
2015-07-31 08:08:45,466 ERROR ExecutionJob - Unable to start Job execution: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:221)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:92)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	... 7 more
````

**Comment by fivesix** [comment]
I have the same problem with RunDeck 2.5.2 when run the same job concurrent. using the h2 db
```
2015-08-25 17:44:42,372 ERROR ExecutionJob - Unable to start Job execution: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
        at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:221)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:92)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.HibernateException: No Session found for current thread
        ... 7 more
```

**Comment by herrygoon** [comment]
Dose anyone has any solution?

**Comment by herrygoon** [comment]
I change the ExecutionJob.groovy to solve the error “No Session found for current thread” throw from Execution.get(initMap.executionId) in method initialize:
1.add new method fetchExecution
```
def Execution fetchExecution(String executionId) {
            def Execution execution = null
            Execution.withNewSession {
                execution = Execution.get(executionId)
            }
            return execution
    }
```
2.change the method initialize code fragment from
```
else if(jobDataMap.get("executionId")){
            //a job execution invoked by a user
            initMap.executionId=jobDataMap.get("executionId")
            initMap.secureOpts=jobDataMap.get("secureOpts")
            initMap.secureOptsExposed=jobDataMap.get("secureOptsExposed")
            initMap.execution = Execution.get(initMap.executionId)
            //NOTE: Oracle/hibernate bug workaround: if session has not flushed we may have to wait until Execution.get
            //can return the right entity
            int retry=30
            if(!initMap.execution){
                log.warn("ExecutionJob: Execution not found with ID [${initMap.executionId}], will retry for up to 60 seconds...")
            }
            while(!initMap.execution && retry>0){
                Thread.sleep(2000)
                initMap.execution = Execution.get(initMap.executionId)
                retry--;
            }
            if (!initMap.execution) {
                throw new RuntimeException("Failed to find Execution with id: ${initMap.executionId}")
            }
            if(retry<30){
                log.info("ExecutionJob: Execution found with ID [${initMap.executionId}] retried (${30-retry})")
            }
            if (! initMap.execution instanceof Execution) {
                throw new RuntimeException("JobDataMap contained invalid Execution type: " + initMap.execution.getClass().getName())
            }
            initMap.execution.refresh()
            FrameworkService frameworkService = initMap.frameworkService
            initMap.framework = frameworkService.rundeckFramework
            initMap.authContext = jobDataMap.get('authContext')
        }
```

to
```
else if(jobDataMap.get("executionId")){
            //a job execution invoked by a user
            initMap.executionId=jobDataMap.get("executionId")
            initMap.secureOpts=jobDataMap.get("secureOpts")
            initMap.secureOptsExposed=jobDataMap.get("secureOptsExposed")
            //NOTE: Oracle/hibernate bug workaround: if session has not flushed we may have to wait until Execution.get
            //can return the right entity
            initMap.execution = fetchExecution(initMap.executionId) //changed
            int retry=30
            if(!initMap.execution){
                log.warn("ExecutionJob: Execution not found with ID [${initMap.executionId}], will retry for up to 60 seconds...")
            }
            while(!initMap.execution && retry>0){
                Thread.sleep(2000)
                initMap.execution = fetchExecution(initMap.executionId) //changed
                retry--;
            }
            if (!initMap.execution) {
                throw new RuntimeException("Failed to find Execution with id: ${initMap.executionId}")
            }
            if(retry<30){
                log.info("ExecutionJob: Execution found with ID [${initMap.executionId}] retried (${30-retry})")
            }
            if (! initMap.execution instanceof Execution) {
                throw new RuntimeException("JobDataMap contained invalid Execution type: " + initMap.execution.getClass().getName())
            }
            initMap.execution = fetchExecution(initMap.executionId) //changed
            FrameworkService frameworkService = initMap.frameworkService
            initMap.framework = frameworkService.rundeckFramework
            initMap.authContext = jobDataMap.get('authContext')
        }
```
But I come across other error in console,but the job state is succeed:
```
2015-09-01 09:14:25,234 ERROR ExecutionService - Caught OptimisticLockingFailure, will retry updateScheduledExecStatistics for 1074
2015-09-01 09:14:25,254 ERROR ExecutionJob - ExecutionJob: Failed to update job statistics for 1074, after retrying 3 times
```

And if I do the save command such as "echo me" on the same node serveral times and I come across this error:
```
2015-09-01 09:14:24,161 ERROR ExecutionUtilService - Execution failed: 1068: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [LeoVideo_Master30: WinRMProtocolError: WinRM Error: Unexpected HTTP response on http://192.168.21.7:5985/wsman:   (500)]}, Node failures: {LeoVideo_Master30=[WinRMProtocolError: WinRM Error: Unexpected HTTP response on http://192.168.21.7:5985/wsman:   (500)]}, flow control: Continue, status: failed]
2015-09-01 09:14:24,161 ERROR ExecutionUtilService - Execution failed: 1080: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [LeoVideo_Master27: WinRMProtocolError: WinRM Error: Unexpected HTTP response on http://192.168.21.7:5985/wsman:   (500)]}, Node failures: {LeoVideo_Master27=[WinRMProtocolError: WinRM Error: Unexpected HTTP response on http://192.168.21.7:5985/wsman:   (500)]}, flow control: Continue, status: failed]
```

**Comment by grafjo** [comment]
I'm having the same issue, 2 jenkins jobs are triggering the same rundeck job with different options. One job execution is hanging ...

```
2015-09-25 17:23:25,837 [qtp1489013561-29] INFO  grails.app.services.rundeck.services.ScheduledExecutionService - scheduling immediate job run: TEMP:jenkins:3:784
2015-09-25 17:23:25,837 [qtp1489013561-28] INFO  grails.app.services.rundeck.services.ScheduledExecutionService - scheduling immediate job run: TEMP:jenkins:3:783
2015-09-25 17:23:25,912 [quartzScheduler_Worker-3] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Unable to start Job execution: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:221)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:92)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	... 7 more
2015-09-25 17:23:34,928 [quartzScheduler_Worker-2] INFO  grails.app.services.rundeck.services.ExecutionUtilService - Execution successful: 783
2015-09-25 17:23:34,990 [quartzScheduler_Worker-2] INFO  grails.app.services.rundeck.services.ExecutionService - updated scheduled Execution
```


Rundeck Version on Centos 7.1 is:
```
rpm -qa| grep rundeck
rundeck-config-2.5.3-1.10.GA.noarch
rundeck-repo-3-0.noarch
rundeck-2.5.3-1.10.GA.noarch
```

**Comment by jp** [comment]
Hi @gschueler ,

Is there any news on this? Is there a workaround?

Thanks,
J

**Comment by dprime** [comment]
Same issue on 2.6.2 on ubuntu.

**Comment by albertmfb** [comment]
same issue on 2.6.2 on Red Hat

**Comment by 3ll3d00d** [comment]
same on 2.6.2 running on suse

i have an app that uses the java rdclient, if I trigger jobs "simultaneously" (i.e. using a threadpool with >1 thread) to trigger jobs then it breaks in this way basically every single time I fire a batch of jobs at it. If I switch so there is a single thread triggering jobs then the problem does not occur.

**Comment by remixtj** [comment]
I can confirm what @3ll3d00d said. Launching the jobs without parallelism solves the issue.

**Comment by gschueler** [comment]
i discovered the cause of this bug: we add a quartz listener for each new execution to bind a hibernate session for the quartz thread, but this was done incorrectly and could cause it to fail for an execution when they are triggered at the same time (race condition).

**Comment by jp** [comment]
+:100:
