### ISSUE TITLE
Job Fails after 0s

### ISSUE THREAD

**Issue by stack72** [rundeck/rundeck#1314]
Using Rundeck 2.5.0, we get a lot of errors in job runs that have the following symptoms

<img width="451" alt="screen shot 2015-07-03 at 11 09 23" src="https://cloud.githubusercontent.com/assets/227823/8497317/086f61a0-2174-11e5-973f-029b23b3c269.png">

On looking at the logs, I can see the following being logged at this time:

```
2015-07-03 10:06:10,356 [quartzScheduler_Worker-6] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Execution 6264 failed to start: Object of class [rundeck.LogFileStorageRequest] with identifier [8437]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [rundeck.LogFileStorageRequest#8437]
org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [rundeck.LogFileStorageRequest] with identifier [8437]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [rundeck.LogFileStorageRequest#8437]
	at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy:720)
	at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:287)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:122)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [rundeck.LogFileStorageRequest#8437]
	... 8 more
2015-07-03 10:06:10,356 [quartzScheduler_Worker-6] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Failed execution 6264 : Object of class [rundeck.LogFileStorageRequest] with identifier [8437]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [rundeck.LogFileStorageRequest#8437]
org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [rundeck.LogFileStorageRequest] with identifier [8437]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [rundeck.LogFileStorageRequest#8437]
	at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy:720)
	at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:287)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:122)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [rundeck.LogFileStorageRequest#8437]
	... 8 more
```

I am using an S3 bucket to store my logs if that helps

**Comment by rgazaryants** [comment]
Row locking error seems similar to https://github.com/rundeck/rundeck/issues/1312
Our jobs actually run though.

**Comment by gschueler** [comment]
initial thought is this should flush the transaction https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy#L278

**Comment by gschueler** [comment]
are these manually triggered job runs, or scheduled job runs?

**Comment by stack72** [comment]
Hi Greg

These are manually run either by the UI or the API. My first thought was to
upgrade to 2.5.1

Thoughts?

Paul

**Comment by gschueler** [comment]
I reproduced a similar error, so I believe I have a fix, but I wasn't able to get the same exact conditions (on job start).  working on a 2.5.2 to come out soon

**Comment by stack72** [comment]
Good news :)

What do you think the issue may be?

**Comment by gschueler** [comment]
The issue I think is that a LogFileStorageRequest domain object is created which refers to the Execution.  It is created when the execution starts, and updated after the execution finishes.  The Storage creation does not get flushed right away, and the Execution is quickly modified. Grails uses an "optimistic locking" method to try to make sure changes are actually persisted as requested. The error may occur if the Execution change is actually persisted before the Storage object changes are flushed, which could be at some later point in the thread's life. 

The issue I reproduced was at the completion of the job, when the Storage object is again updated. It happens on a separate thread, and the Storage object is not "detached" from the original Hibernate session, so it triggers the same error when it attempts to save changes since it refers to the older version of the Execution.

The solution i have is to flush the original Storage object creation, and detach it from the original session, then reattach when the asynchronous storage request thread runs.

**Comment by gschueler** [comment]
included a fix if you are able to try it out here is a snapshot build: https://bintray.com/gschueler/rundeck-maint-maven/rundeck-launcher/view or rpm here https://bintray.com/gschueler/rundeck-maint-staging-rpm

**Comment by stack72** [comment]
@gschueler just wanted to let you know that after upgrading to rundeck 2.5.2, this issue seems to have disappeared :)

**Comment by gschueler** [comment]
:+1:
