### ISSUE TITLE
Launcher jar on windows: stack trace on startup

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#1326]
Using the launcher jar on windows causes a stacktrace in the log at startup, but no other issues.

~~~
2015-07-09 18:40:35,318 ERROR AssetSpecLoader - Error loading asset specification asset.pipeline.HtmlAssetFile
asset.pipeline.JsAssetFile
asset.pipeline.CssAssetFile: asset.pipeline.HtmlAssetFile
asset.pipeline.JsAssetFile
asset.pipeline.CssAssetFile
java.lang.ClassNotFoundException: asset.pipeline.HtmlAssetFile
asset.pipeline.JsAssetFile
asset.pipeline.CssAssetFile
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
        at asset.pipeline.AssetSpecLoader$_loadSpecifications_closure1.doCall(AssetSpecLoader.groovy:51)
        at asset.pipeline.AssetSpecLoader.loadSpecifications(AssetSpecLoader.groovy:46)
        at asset.pipeline.AssetSpecLoader.loadSpecifications(AssetSpecLoader.groovy:40)
        at asset.pipeline.AssetHelper.<clinit>(AssetHelper.groovy:31)
        at asset.pipeline.AssetsTagLib$_closure2.doCall(AssetsTagLib.groovy:61)
~~~

**Comment by gschueler** [comment]
nb: upgrade asset-pipeline plugin to 2.0.10 or later

**Comment by ihvargas** [comment]
hi!  im having the same ERROR, but how can i upgrade asset-pipeline plugin into the rundeck jar?

**Comment by Zebra54** [comment]
@ihvargas  : Hello! ist there any answer to your question? I have the same problem.

**Comment by gschueler** [comment]
this fix is not completed yet, it has to happen in the rundeck build

**Comment by emittman1002** [comment]
I created a temp folder and extracted rundeck-launcher-2.6.4.jar into it, downloaded a newer version of the plugin jar (less-asset-pipeline-2.1.0.jar) from a Maven repository, dropped it into the extracted subfolder pkgs/webapp/WEB-INF/lib, removed less-asset-pipeline-2.0.8.jar from the same folder, deleted rundeck-launcher-2.6.4.jar from the temp folder, and finally JARred everything up again with
  jar cvfm rundeck-launcher-2.6.4-fix.jar META-INF/MANIFEST.MF *

It's at least gotten rid of the exception on startup.  Any reason this won't work as a workaround?

**Comment by chromial** [comment]
seems to still be present as of June 2016...

2016-06-13 20:00:47.294:INFO:/:Initializing Spring FrameworkServlet 'grails'
2016-06-13 20:00:47.508:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440
2016-06-13 20:01:36,448 ERROR AssetSpecLoader - Error loading asset specification asset.pipeline.HtmlAssetFile
asset.pipeline.JsAssetFile
asset.pipeline.CssAssetFile: asset.pipeline.HtmlAssetFile
asset.pipeline.JsAssetFile
asset.pipeline.CssAssetFile
java.lang.ClassNotFoundException: asset.pipeline.HtmlAssetFile
asset.pipeline.JsAssetFile
asset.pipeline.CssAssetFile
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
        at asset.pipeline.AssetSpecLoader$_loadSpecifications_closure1.doCall(AssetSpecLoader.groovy:51)
        at asset.pipeline.AssetSpecLoader.loadSpecifications(AssetSpecLoader.groovy:46)
        at asset.pipeline.AssetSpecLoader.loadSpecifications(AssetSpecLoader.groovy:40)
        at asset.pipeline.AssetHelper.<clinit>(AssetHelper.groovy:31)
        at asset.pipeline.AssetsTagLib$_closure2.doCall(AssetsTagLib.groovy:61)
        at gsp_rundeck_userlogin_gsp$_run_closure1.doCall(gsp_rundeck_userlogin_gsp.groovy:40)
        at gsp_rundeck_userlogin_gsp.run(gsp_rundeck_userlogin_gsp.groovy:55)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)

**Comment by jenulis** [comment]
I'm still seeing this issue.  Is it project to be fix in an upcoming version?

**Comment by jastorgalj** [comment]
fix it manually.  (sorry for my English).

download jar's asset-pipeline-core-2.11.1.jar and less-asset-pipeline-2.11.1.jar from maven (https://mvnrepository.com/artifact/com.bertramlabs.plugins/asset-pipeline-core/2.11.1) (https://mvnrepository.com/artifact/com.bertramlabs.plugins/less-asset-pipeline/2.11.1)
and i put them in to rundeck\server\exp\webapp\WEB-INF\lib. remove older versions, and add --skipinstall in the java excecution line. 

this working fine for me.
