### ISSUE TITLE
ldap auth doesn't work with SSHA password hashing 

### ISSUE THREAD

**Issue by wjimenez5271** [rundeck/rundeck#1333]
Observing this on 2.5.1-1. When a user in ldap has a password hashed with SSHA (salted SHA1) rundeck does not authenticate the user and doesn't give any indication of the hash being the issue in the log:

```
==> /var/log/rundeck/service.log <==
2015-07-14 13:21:36.505:INFO:cdrjj.JettyCachingLdapLoginModule:Login attempts: 60, Hits: 0, Ratio: 0%.
2015-07-14 13:21:36.515:WARN:oejpj.JAASLoginService:
javax.security.auth.login.LoginException: Login Failure: all modules ignored
    at javax.security.auth.login.LoginContext.invoke(LoginContext.java:913)
    at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:690)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:687)
    at javax.security.auth.login.LoginContext.login(LoginContext.java:595)
    at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:217)
    at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:183)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:456)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:349)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by wjimenez5271** [comment]
After talking to @ahonor about this, it turns out the ldap module (which uses JAAS) only supports MD5 or CRYPT hashing. It can also support "binding login" however, which allows the ldap server to compare the hashes which should in turn support other has methods. This mode can be enabled by specifying `forceBindingLogin="true"` in the jaas-ldap.conf file (or whatever you called your rundeck ldap conf). 

So this is somewhat expected behavior, but I think an action item could be to enhance the logging to let the user know the issue is a hash mis-match (and not a simple bad user/pass combo) and/or update the documentation to express this distinction re. password hashing.

**Comment by wjimenez5271** [comment]
Documentation updated in PR: https://github.com/rundeck/rundeck/pull/1336.
