### ISSUE TITLE
Rundeck upgrade to 2.5.1 failed due to java.lang.ClassNotFoundException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter

### ISSUE THREAD

**Issue by mjaberster** [rundeck/rundeck#1334]
I upgraded from 2.3 to 2.5.1, first it worked with one user role problem, After I updated the web.xml file and restarted the rundeckd service I got 
HTTP ERROR: 503

Problem accessing /rundeck. Reason:

    Service Unavailable

My service.log file shows:

java.lang.ClassNotFoundException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:92)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:71)
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:84)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
2015-07-15 16:17:04.243:WARN:oejuc.AbstractLifeCycle:FAILED sitemesh: javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:91)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
2015-07-15 16:17:04.244:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/rundeck,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:91)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
2015-07-15 16:17:04.267:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

Please help
Thanks

**Comment by mjaberster** [comment]
I found the solution in the upgrade notes :)

The web.xml file has changed significantly from 2.4.x to Rundeck 2.5.x.

For this reason, if you have modified your web.xml file, located at /var/lib/rundeck/exp/webapp/WEB-INF/web.xml, for example to change the <security-role><role-name>user</role-name><security-role>, then you may need to back it up, and re-apply the changes you made after upgrading to 2.5.x.

If you receive a "Service Unavailable" error on startup, and the service.log file contains this message:

java.lang.ClassNotFoundException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
Then that means your web.xml file is out of date. Replace it with the one from 2.5 installation, then re-apply your changes to <role-name>.


Thanks
