### ISSUE TITLE
After deleting a project, Log file storage resume might cause exception in logs

### ISSUE THREAD

**Issue by joshuaspence** [rundeck/rundeck#1384]
I attempted to delete a project through the UI but I suspect that it didn't work properly. I'm not getting this exception:

```
2015-08-06 09:37:04,082 [main] ERROR org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener - Error initializing Grails: Project does not exist: FLN
FrameworkException{message='Project does not exist: FLN', resource='FrameworkProjectMgr{name=name, baseDir=/var/rundeck/projects}'}
    at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:159)
    at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:27)
    at rundeck.services.FrameworkService.getFrameworkProject(FrameworkService.groovy:156)
    at rundeck.services.FrameworkService.getFrameworkPropertyResolver(FrameworkService.groovy:260)
    at rundeck.services.LogFileStorageService$_resumeIncompleteLogStorage_closure7.doCall(LogFileStorageService.groovy:302)
    at rundeck.services.LogFileStorageService.resumeIncompleteLogStorage(LogFileStorageService.groovy:297)
    at BootStrap$_closure1.doCall(BootStrap.groovy:272)
    at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
    at grails.util.Environment.executeForEnvironment(Environment.java:320)
    at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
    at org.eclipse.jetty.server.Server.doStart(Server.java:261)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
    at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
    at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
```

**Comment by gschueler** [comment]
are you using db storage for project configuration?  If not try just creating the directory: `/var/rundeck/projects/FLN`

**Comment by joshuaspence** [comment]
I ended up just deleting a bunch of stuff from the database.
