### ISSUE TITLE
unable to use pam with rundeck on debian jessie

### ISSUE THREAD

**Issue by rdezavalia** [rundeck/rundeck#1451]
using this guide http://rundeck.org/docs/administration/authenticating-users.html I'm getting this error while using pam:

Sep 21, 2015 5:28:26 PM org.rundeck.jaas.pam.AbstractPamLoginModule debug
INFO: PAM authentication trying (sshd) for: r.dezavalia
2015-09-21 17:28:26.661:WARN:oejpj.JAASLoginService:
javax.security.auth.login.LoginException: java.lang.UnsatisfiedLinkError: Can't obtain static newInstance method for class com.sun.jna.Structure|?at com.sun.jna.Native.initIDs(Native Method)|?at com.sun.jna.Native.<clinit>(Native.java:113)|?at com.sun.jna.Structure.<clinit>(Structure.java:110)|?at org.jvnet.libpam.PAM.<init>(PAM.java:73)|?at org.rundeck.jaas.pam.AbstractPamLoginModule.authenticate(AbstractPamLoginModule.java:85)|?at org.rundeck.jaas.AbstractSharedLoginModule.login(AbstractSharedLoginModule.java:78)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:606)|?at javax.security.auth.login.LoginContext.invoke(LoginContext.java:762)|?at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:690)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:688)|?at java.security.AccessController.doPrivileged(Native Method)|?at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:687)|?at javax.security.auth.login.LoginContext.login(LoginContext.java:595)|?at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:217)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:183)|?at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:456)|?at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)|?at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)|?at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)|?at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)|?at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)|?at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)|?at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)|?at org.eclipse.jetty.server.Server.handle(Server.java:349)|?at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)|?at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)|?at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)|?at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)|?at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)|?at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)|?at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)|?at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)|?at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)|?at java.lang.Thread.run(Thread.java:745)|
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:864)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:690)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:687)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:595)
        at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:217)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:183)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:456)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ahonor** [comment]
Please reopen if this remains a concern
