### ISSUE TITLE
Setting server UUID

### ISSUE THREAD

**Issue by joshuaspence** [rundeck/rundeck#1455]
I am trying to enable cluster mode, but am getting the following error in the logs:

```
2015-09-24 18:44:42,415 [main] ERROR org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener - Error initializing Grails: Cluster mode: 'r
undeck.server.uuid' in framework.properties was not a valid UUID: undef. 
java.lang.RuntimeException: Cluster mode: 'rundeck.server.uuid' in framework.properties was not a valid UUID: undef. 
        at BootStrap$_closure1.doCall(BootStrap.groovy:138)
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
        at grails.util.Environment.executeForEnvironment(Environment.java:320)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
        at org.eclipse.jetty.server.Server.doStart(Server.java:261)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
```

I'm not sure what I should be setting this value to?

**Comment by gschueler** [comment]
you will need to generate a unique id for each server.  You can use `uuidgen` (on unix) to do so.

e.g.:

    echo "rundeck.server.uuid="$(uuidgen) >> /etc/rundeck/framework.properties

**Comment by joshuaspence** [comment]
OK, thanks
