### ISSUE TITLE
Can not running rundeck 2.6.0 

### ISSUE THREAD

**Issue by netroby** [rundeck/rundeck#1466]
```
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	... 15 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:472)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:391)
	... 15 more
2015-10-09 14:24:05,583 ERROR GrailsContextLoaderListener - Error initializing Grails: Error creating bean with name 'annotationHandlerAdapter': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'annotationHandlerAdapter': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
	at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
	at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)
	at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
	at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	... 15 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:472)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:391)
	... 15 more


```

i am using rundeck 2.5.3, then i upgrade it to 2.6.0 , but it not work at all

**Comment by gschueler** [comment]
how are you installing Rundeck?  What OS and version of Java are you using?

**Comment by netroby** [comment]
CentOS 6 x64, Oracle JDK 8u60

**Comment by netroby** [comment]
I deleted all files. then i run 2.6.0 fresh. it was ok . but all project files lost.
