### ISSUE TITLE
SCM: sometimes fails to commit job moved to another group / subgroup

### ISSUE THREAD

**Issue by michaelPf85** [rundeck/rundeck#1533]
We moved several jobs around, changing their group. Sometimes, when commiting, we come across the following error message.
In this case we moved the `Check boîte...` job from `Système` to `Système/Mails` group. Maybe it's because we moved it in a subgroup / subfolder ?

###### An Error Occurred
Entry not found by path: Système/Check boîte GEM srv-mail-c70a4943-d4a9-48a7-850e-0f0f067b269d.xml
###### Error details
Request: `/scm/exportActionSubmit?pluginProperties.tagName=&pluginProperties=%5BtagName%3A%2C+message%3ARangement%2C+_push%3A%5D&orig.push=&orig=%5Bpush%3A%2C+tagName%3A%2C+message%3A%5D&submit=Commit&pluginProperties.message=Rangement&_jobIds=&SYNCHRONIZER_URI=%2Fscm%2FexportAction&orig.tagName=&project=Securimut&renamedPaths.c70a4943-d4a9-48a7-850e-0f0f067b269d=Syst%C3%A8me%2FCheck+bo%C3%AEte+GEM+srv-mail-c70a4943-d4a9-48a7-850e-0f0f067b269d.xml&renamedPaths=%5Bc70a4943-d4a9-48a7-850e-0f0f067b269d%3ASyst%C3%A8me%2FCheck+bo%C3%AEte+GEM+srv-mail-c70a4943-d4a9-48a7-850e-0f0f067b269d.xml%5D&jobIds=c70a4943-d4a9-48a7-850e-0f0f067b269d&integration=export&orig.message=&actionId=project-commit&allJobs=&SYNCHRONIZER_TOKEN=62a95226b8907a82f1131699c8b54aeb1a16b4d1bd093e0638087084ca18cc07&pluginProperties._push=`
Message: `Entry not found by path: Système/Check boîte GEM srv-mail-c70a4943-d4a9-48a7-850e-0f0f067b269d.xml`
Caused by: `Entry not found by path: Système/Check boîte GEM srv-mail-c70a4943-d4a9-48a7-850e-0f0f067b269d.xml`
Class: `ScmController`
At Line: `[374]`
Code Snippet:
###### Stack trace
`org.eclipse.jgit.api.errors.JGitInternalException: Entry not found by path: Système/Check boîte GEM srv-mail-c70a4943-d4a9-48a7-850e-0f0f067b269d.xml
	at org.eclipse.jgit.api.CommitCommand.createTemporaryIndex(CommitCommand.java:468)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:238)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction.perform(CommitJobsAction.groovy:131)
	at org.rundeck.plugin.scm.git.GitExportPlugin.export(GitExportPlugin.groovy:143)
	at rundeck.services.ScmService.performExportAction(ScmService.groovy:917)
	at rundeck.controllers.ScmController.exportActionSubmit(ScmController.groovy:374)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by gschueler** [comment]
It appears you were using 2.6.0.  Have you tried using 2.6.1, which fixed a number of bugs with scm?

**Comment by michaelPf85** [comment]
I must have forgotten to update my server recently, sorry. It's updated now, so if there are still bugs i'll probably run into them soon enough.
Thanks for your help.
