### ISSUE TITLE
rundeck on tomcat7

### ISSUE THREAD

**Issue by vinitkhandagle** [rundeck/rundeck#1542]
I was trying to install on ubuntu 14.04. I put the war file in `/var/lib/tomcat7/webapps`. I created a `$RDECK_BASE` in `/etc/tomcat7/rdbase`. When I try to start the tomcat server I am getting the following error. I think I just need to create a lo4j.properties file or something but not clearly sure about that.

```
INFO: Deploying web application archive /var/lib/tomcat7/webapps/rundeck-2.6.0.war
Nov 10, 2015 2:39:32 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags is already defined
2015-11-10 14:40:00,793 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
	... 5 more
2015-11-10 14:40:00,808 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
	... 5 more
```

**Comment by vinitkhandagle** [comment]
I got this to work I created a log4j.properties file in "`/var/lib/tomcat7/webapps/rundeck/WEB-INF/classes/log4j.properties`". Also since the `$RDECK_BASE` is in `/etc/tomcat7/`. I need to make sure the user tomcat7 has write permission on the `$RDECK_BASE`.
