### ISSUE TITLE
NullPointerException in InitialContext.getURLScheme when using LDAP

### ISSUE THREAD

**Issue by tchiunam** [rundeck/rundeck#1588]
These are the packages I am using.

```
rundeck-2.6.1-1.12.GA.noarch
rundeck-repo-4-0.noarch
rundeck-config-2.6.1-1.12.GA.noarch
```

I am following the online rundeck [doc](http://rundeck.org/docs/jp/administration/09-authentication.html#login-module-configuration) to setup ldap config. **profile** has been set to point to the **jaas-ldap.conf** with **ldap** module.

```
export RDECK_JVM="-Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf \
        -Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG \
        -Dloginmodule.name=ldap \
        -Drdeck.config=/etc/rundeck \
        -Drdeck.base=/var/lib/rundeck \
        -Drundeck.server.configDir=/etc/rundeck \
        -Dserver.datastore.path=/var/lib/rundeck/data \
        -Drundeck.server.serverDir=/var/lib/rundeck \
        -Drdeck.projects=/var/rundeck/projects \
        -Drdeck.runlogs=/var/lib/rundeck/logs \
        -Drundeck.config.location=/etc/rundeck/rundeck-config.properties \
        -Djava.io.tmpdir=$RUNDECK_TEMPDIR"
```

This is our **jaas-ldap.conf** with _host_ pointing to our ldap server; _company_ as our DC.

```
ldap {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
        debug="true"
        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
        providerUrl="ldap://<host>:389"
        authenticationMethod="simple"
        forceBindingLogin="true"
        userBaseDn="CN=Users,DC=hk,DC=<company>,DC=com"
        userRdnAttribute="sAMAccountName"
        userIdAttribute="sAMAccountName"
        userPasswordAttribute="unicodePwd"
        userObjectClass="user"
        roleBaseDn="CN=Users,DC=hk,DC=<company>,DC=com"
        roleNameAttribute="cn"
        roleMemberAttribute="member"
        roleObjectClass="group"
        reportStatistics="true";
};
```

rundeckd can be started successfully.

```
INFO  StdSchedulerFactory: Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
INFO  StdSchedulerFactory: Quartz scheduler version: 2.2.1
INFO  QuartzScheduler: JobFactory set to: grails.plugins.quartz.GrailsJobFactory@39159b14
INFO  EventsImpl: Reloading events listeners
INFO  EventsImpl: Register event listener rundeck.services.JobEventsService#jobChanged for topic jobChanged and namespace app and proxy support true
WARN  EventsImpl: Event listener rundeck.services.JobEventsService#jobChanged declared for topic jobChanged and namespace app but no such event is declared
, you may never receive it
INFO  QuartzScheduler: Scheduler quartzScheduler_$_NON_CLUSTERED started.
INFO  BootStrap: Starting Rundeck 2.6.1-1...
INFO  BootStrap: using rdeck.base config property: /var/lib/rundeck
INFO  BootStrap: loaded configuration: /etc/rundeck/framework.properties
INFO  events: get:[file]:projects/trading_service/etc/project.properties:[Rundeck-content-modify-time:2015-11-17T03:16:44Z, Rundeck-content-type:text/x-jav
a-properties, Rundeck-content-creation-time:2015-11-17T03:16:44Z]: -
INFO  BootStrap: RSS feeds disabled
INFO  BootStrap: Rundeck is ACTIVE: executions can be run.
2015-12-10 11:39:46.493:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
2015-12-10 11:39:46.560:INFO:/:Initializing Spring FrameworkServlet 'grails'
2015-12-10 11:39:46.663:INFO:oejus.SslContextFactory:Enabled Protocols [SSLv2Hello, TLSv1, TLSv1.1, TLSv1.2] of [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2
]
2015-12-10 11:39:46.701:INFO:oejs.AbstractConnector:Started SslSelectChannelConnector@0.0.0.0:4443
```

However we are getting NPE when try to login.

```
java.lang.NullPointerException
        at javax.naming.InitialContext.getURLScheme(InitialContext.java:294)
        at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:343)
        at javax.naming.directory.InitialDirContext.getURLOrDefaultInitDirCtx(InitialDirContext.java:106)
        at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:286)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getUserCredentials(JettyCachingLdapLoginModule.java:338)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getUserInfo(JettyCachingLdapLoginModule.java:273)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.authenticate(JettyCachingLdapLoginModule.java:671)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.login(JettyCachingLdapLoginModule.java:599)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:217)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:183)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:456)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:191)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:745)
2015-12-10 11:57:37.078:WARN:oejpj.JAASLoginService:
javax.security.auth.login.LoginException: Error obtaining user info.
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.authenticate(JettyCachingLdapLoginModule.java:696)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.login(JettyCachingLdapLoginModule.java:599)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:217)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:183)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:456)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:191)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:745)
```

I have checked the rundeck and javax.naming source code but I have no idea why it failed to get the URL scheme. In https://github.com/rundeck/rundeck/blob/7ce2d894213c26e490d9d2c89e5b219c29016d27/rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java, I see I am configuring correctly:

```
_providerUrl = (String) options.get("providerUrl");
```

At the same time, the deprecated use of **hostname** and **port** is confusing because it creates an url in this way - "ldap://hostname/:port/". Anyway I tried configuring **hostname** and **port** but no luck.

```
String url = null;
        if(_providerUrl != null) {
            url =  _providerUrl;
        } else {
            if (_hostname != null) {
                url = "ldap://" + _hostname + "/";
                if (_port != 0) {
                    url += ":" + _port + "/";
                }

                LOG.warn("Using hostname and port.  Use providerUrl instead: " + url);
            }
        }
```

The NPE is thrown before it can talk to our ldap. Any idea?

**Comment by gschueler** [comment]
what java version are you using?

The stacktrace indicates there might be a problem with the "userBaseDn" value.  it seems it tries to parse it as a URL if possible (if it contains `:` and optionally `/` characters).  Is that the case?

**Comment by tchiunam** [comment]
You are correct. 

For testing purpose, I tried these versions. 2-7 below generated the same error. I test by setting ```JAVA_HOME=/usr/java/<version``` in ```/etc/init.d/rundeckd``` and restart rundeckd.
1. 1.6.0_10x64 (com/dtolabs/rundeck/RunServer : Unsupported major.minor version 51.0) expected for this old version
2. 1.6.0_45x64
3. 1.7.0_55x64
4. 1.8.0_05x64
5. 1.8.0_20x64
6. 1.8.0_25x64
7. 1.8.0_45x64

*_userBaseDn* is passed as 1st arguemnt to *search()*.

```
NamingEnumeration results = _rootContext.search(_userBaseDn, filter, filterArguments,
                    ctls);
```

It's calling *javax.naming.directory.InitialDirContext* which passes the 1st argument (*_userBaseDn*) to *getURLOrDefaultInitDirCtx*.

```
279   public NamingEnumeration<SearchResult>
280        More ...search(String name,
281               String filterExpr,
282               Object[] filterArgs,
283               SearchControls cons)
284        throws NamingException
285    {
286        return getURLOrDefaultInitDirCtx(name).search(name, filterExpr,
287                                                      filterArgs, cons);
```

*_userBaseDn* is then passed into *getURLOrDefaultInitCtx*.

```
104    private DirContext More ...getURLOrDefaultInitDirCtx(String name)
105            throws NamingException {
106        Context answer = getURLOrDefaultInitCtx(name);
107        if (!(answer instanceof DirContext)) {
108            if (answer == null) {
109                throw new NoInitialContextException();
110            } else {
111                throw new NotContextException(
112                    "Not an instance of DirContext");
113            }
114        }
115        return (DirContext)answer;
116    }
```

*getURLScheme* is called to extract the URL scheme from *_userBaseDn*.

```
338    protected Context More ...getURLOrDefaultInitCtx(String name)
339        throws NamingException {
340        if (NamingManager.hasInitialContextFactoryBuilder()) {
341            return getDefaultInitCtx();
342        }
343        String scheme = getURLScheme(name);
344        if (scheme != null) {
345            Context ctx = NamingManager.getURLContext(scheme, myProps);
346            if (ctx != null) {
347                return ctx;
348            }
349        }
350        return getDefaultInitCtx();
351    }
```

Finally it returns **null** because there is no ```:``` and ```/```.

```
293    private static String More ...getURLScheme(String str) {
294        int colon_posn = str.indexOf(':');
295        int slash_posn = str.indexOf('/');
296
297        if (colon_posn > 0 && (slash_posn == -1 || colon_posn < slash_posn))
298            return str.substring(0, colon_posn);
299        return null;
300    }
```

I see the same line ```_rootContext.search(_userBaseDn ...)``` in 2.5.2 release branch so it doesn't seem to relate to new changes.
Any workaround I can do in the config? Or do you know which java version is working with this Rundeck 2.6.1 + LDAP?

**Comment by kmusard** [comment]
I was never able to get LDAP auth to an Active Directory working while binding as the authenticating user.  I can confirm that it works using a bindDn and bindPassword on Rundeck 2.6.2 with Java 1.8.0_66.  The documentation at http://rundeck.org/docs/administration/authenticating-users.html says the following about forceBindingLogin:

forceBindingLogin

"true/false" - if true, bind as the user that is authenticating, otherwise bind as the manager and perform a search to verify user password. NOTE: This module can only verify passwords hashed with MD5 or CRYPT. If your LDAP directory contains other hashes you'll likely need to set this to true to be able to authenticate.

I am not an AD expert.  Is possible it uses a default hash type which is incompatible with this module?
