### ISSUE TITLE
Error 500 when calling [PUT] /api/14/project/<project>/import

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1625]
Hi,
I have built a tool/script that interact with Rundeck API to perform a bunch of actions, one of those is promoting jobs from development to production by using the project import endpoint.

Very often when I try to promote I get a 500 error, this is easy to fix the issue temporarily by just restarting Rundeck service on the Rundeck instance (The one you are connecting to perform the PUT)

Just a restart and the exactly same script/command works, after that you can replay with no error for a while, I guess there is something else, some other of my scheduled API calls to backup, sync etc that could be causing this issue... I mean looks like it start to fail just after something else I still couldn't tell what is it.

I'm using 2.6.1-1 version, at this moment I don't have much more information, but I'll be watching and I plan to update this issue with more tests/clues, find here the full exception is raised

Regards

```
2016-01-12 04:02:28,686 [qtp1267032364-27] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - IOException occurred when processing request: [PUT] /api/14/project/LSS/import
No such file or directory. Stacktrace follows:
java.io.IOException: No such file or directory
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at com.dtolabs.rundeck.util.ZipReader.copyToTemp(ZipReader.groovy:141)
        at rundeck.services.ProjectService$_importToProject_closure16_closure44_closure45_closure49.doCall(ProjectService.groovy:632)
        at com.dtolabs.rundeck.util.ZipReader.readFile(ZipReader.groovy:170)
        at com.dtolabs.rundeck.util.ZipReader.read(ZipReader.groovy:218)
        at rundeck.services.ProjectService.importToProject(ProjectService.groovy:628)
        at rundeck.controllers.ProjectController.apiProjectImport(ProjectController.groovy:1415)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by snebel29** [comment]
I ran all my other scripts that are interacting with Rundeck trough the API however after that I still can import with no error 500.

At this moment I can't figure out what could be triggering state that cause the error

**Comment by gschueler** [comment]
`java.io.File.createTempFile` is the point of failure, this implies there is some problem creating a file in the temp directory.  The default for Java is usually `/tmp`, but you can change it. It might be a permissions problem in that dir, or whichever dir is used for temp files.

**Comment by snebel29** [comment]
Hi @gschueler,
I'm pretty sure I checked that there was space available on /tmp (I did not change the default path) and that there was no rights issues, however I didn't checked specifically inside /tmp/rundeck

I was unable to catch another error like this since last time, I'll keep watching and will add additional info with extended debug to the /tmp directory once the problem occurs again.

If you don't mind we can keep the issue open for a while.

~Regards

**Comment by snebel29** [comment]
Hi,
I didn't see this error again, i think that make sense to say i missed something within /tmp folder so no need to keep this issue open.

**Comment by snebel29** [comment]
I finally found whats happening!

I'm working on a centos 7.1 instance, where /tmp is cleaned for files older than 10 days, within /tmp there is usually a directory called "rundeck" where rundeck store its stuff, folder date is updated when anything happens inside. Because on those instances there was no activity (This is happening on my training/test instances) the directory was removed.

Rundeck seems failing to "create" this directory on that specific case "not sure about others", once you restart the service this folder is created so the problem is fixed.

I think that to make Rundeck more reliable would be nice to create /tmp/rundeck directory if this does not exists when trying to write to these path.

Regards

**Comment by ahonor** [comment]
Please reopen if this remains a concern
