### ISSUE TITLE
Commands with more than 2673 characters throws an exception

### ISSUE THREAD

**Issue by mscifo** [rundeck/rundeck#1630]
When running a remote command against a node, if the command is greater than 2673 characters, rundeck fails with the following...

```
Request: /project/*********/job/runJobNow/cc40197d-7c8e-401c-8dd4-1aa6cbcdb53d?extra.argString=&extra=%5BargString%3A%2C+loglevel%3AINFO%2C+option.SQL%3A[TRUNCATED_VERY_LONG_SQL_QUERY]&follow=true
Message: 
Caused by: Executing action [runJobNow] of controller [rundeck.controllers.ScheduledExecutionController] caused exception: Runtime error executing action 
Class: Unknown 
At Line: [-1] 
Code Snippet:
Stack Trace
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [runJobNow] of controller [rundeck.controllers.ScheduledExecutionController]  caused exception: Runtime error executing action
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        <truncated>
```

Trying it with one less character in the SQL results in a success.

Using version 2.4.2-1.

**Comment by ahonor** [comment]
A script step is another approach to this. Please reopen if this remains a concern
