### ISSUE TITLE
Error in "run" command

### ISSUE THREAD

**Issue by amitk75** [rundeck/rundeck#1693]
I have Rundeck 2.6.2 deployed as war file on Tomcat 8 running in Ubuntu 14.04. I unzipped the CLI tools and required libs into a separate folder. When I try to execute "run" command, I get error "Error: host parameter is null"

Below is the command I am trying to execute:
RUNDECK_URL=http://localhost:8080/rundeck RUNDECK_USER=admin RUNDECK_PASS=password  /opt/tomcat/rdbase/tools/bin/run -p TestProject -j TestJob -v -r

Stacktrace:

java.lang.IllegalArgumentException: host parameter is null
        at org.apache.commons.httpclient.HttpConnection.setHost(HttpConnection.java:248)
        at org.apache.commons.httpclient.SimpleHttpConnectionManager.getConnectionWithTimeout(SimpleHttpConnectionManager.java:163)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:152)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
        at com.dtolabs.client.utils.BaseFormAuthenticator.authenticate(BaseFormAuthenticator.java:287)
        at com.dtolabs.client.utils.BaseHttpClientChannel.doAuthentication(BaseHttpClientChannel.java:128)
        at com.dtolabs.client.utils.HttpClientChannel.makeRequest(HttpClientChannel.java:325)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:201)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:144)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:100)
        at com.dtolabs.client.services.RundeckAPICentralDispatcher.reallistStoredJobs(RundeckAPICentralDispatcher.java:1494)
        at com.dtolabs.client.services.RundeckAPICentralDispatcher.queueDispatcherJob(RundeckAPICentralDispatcher.java:1591)
        at com.dtolabs.rundeck.core.cli.run.RunTool.jobrunAction(RunTool.java:463)
        at com.dtolabs.rundeck.core.cli.run.RunTool.go(RunTool.java:415)
        at com.dtolabs.rundeck.core.cli.BaseTool.run(BaseTool.java:161)
        at com.dtolabs.rundeck.core.cli.run.RunTool.main(RunTool.java:135)
Error: host parameter is null

**Comment by gschueler** [comment]
I think this might occur if you do not have a `grails.serverURL` value set in your `rundeck-config.properties` file.  Rundeck uses that for the absolute URL used when sending 302 redirects to the client (such as CLI tools).  If it is unset it may be only sending relative URLs.

**Comment by amitk75** [comment]
That doesn't seem to be the case, I have grails.serverURL set in the rundeck-config.properties.

One possibility could be: I am running Rundeck in a Docker container. The grails.serverURL is pointing to the <docker-host-ip>:<port>/rundeck whereas Rundeck is running in some other container having say <container-ip>. Also, Rundeck is deployed as a war file on Tomcat with port 8080 and not the default 4440 port of Rundeck.

I don't know if the above combination affects the CLI tools.

**Comment by gschueler** [comment]
fixed from #1774
