### ISSUE TITLE
SCM commit JOB in Windows

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#1708]
When I try to commit a change in a Job using SCM in a Windows (testing in windows server 2012 and windows 10), I got the following error: 

Entry not found by path: Satellite\Satellite Registration-b9925c02-d608-468c-a3cb-57464ea1c682.yaml

It is similar to this case: https://github.com/rundeck/rundeck/issues/1533

This is only when the Job has associated a group (when it is not it works), so the YAML file is created inside a folder in the SCM folder. For example:

 rundeck\projects\TestMsm\scm
<DIR>          Satellite
Test-2adcac83-d54b-407c-aee5-184cd206bb7a.yaml           --->commit works
Test Job-f1526447-8083-4122-8498-27ef0d5178c1.yaml     --->commit works

rundeck\projects\TestMsm\scm\Satellite
Satellite Registration-b9925c02-d608-468c-a3cb-57464ea1c682.yaml --->commit dosen't work

I tested in Ubuntu 15 and Red Hat 6.5 and it works fine. In all cases I checked that the GIT version it is the same (2.7.2)

The rundeck version is 2.6.2 (I tested also in 2.6.1)

Here is the full error:
--------------------------------------------------------------------------------------------------------
An Error Occurred
Entry not found by path: Satellite\Satellite Registration-b9925c02-d608-468c-a3cb-57464ea1c682.yaml

Error Details
Request: /project/TesMsm/job/b9925c02-d608-468c-a3cb-57464ea1c682/scm/export/performActionSubmit?submit=Commit&orig.push=&orig=%5Bpush%3A%2C+message%3A%2C+tagName%3A%5D&allJobs=&pluginProperties.message=test+commit+JOB+whit+group+WINDOWS&pluginProperties=%5Bmessage%3Atest+commit+JOB+whit+group+WINDOWS%2C+tagName%3A%2C+_push%3A%5D&pluginProperties.tagName=&SYNCHRONIZER_URI=%2Fproject%2FTesMsm%2Fjob%2Fb9925c02-d608-468c-a3cb-57464ea1c682%2Fscm%2Fexport%2FperformAction&pluginProperties._push=&actionId=job-commit&_id=&orig.message=&orig.tagName=&SYNCHRONIZER_TOKEN=7f997e62fb1e7fe573aab21c4709fed1fe9f6e08c963b73c5e81becd1705bd09
Message: Entry not found by path: Satellite\Satellite Registration-b9925c02-d608-468c-a3cb-57464ea1c682.yaml
Caused by: Entry not found by path: Satellite\Satellite Registration-b9925c02-d608-468c-a3cb-57464ea1c682.yaml
Class: ScmController
At Line: [1155]
Code Snippet:
Stack Trace

org.eclipse.jgit.api.errors.JGitInternalException: Entry not found by path: Satellite\Satellite Registration-b9925c02-d608-468c-a3cb-57464ea1c682.yaml
	at org.eclipse.jgit.api.CommitCommand.createTemporaryIndex(CommitCommand.java:468)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:238)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction.perform(CommitJobsAction.groovy:133)
	at org.rundeck.plugin.scm.git.GitExportPlugin.export(GitExportPlugin.groovy:126)
	at rundeck.services.ScmService.performExportAction(ScmService.groovy:963)
	at rundeck.controllers.ScmController.performActionSubmit(ScmController.groovy:1155)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)

**Comment by gschueler** [comment]
thanks for the report. I think the git library expects unix-style paths
