### ISSUE TITLE
Jasypt exception thrown, no further information provided

### ISSUE THREAD

**Issue by isuftin** [rundeck/rundeck#1785]
https://gist.github.com/isuftin/debf46f08f216e62b3a5bc691865108e

Using 2.6.4-1 against a MySQL RDS. When using no encryption, keys get created without issue.

No further stack trace seems to be available to me in any of the rundeck logs

**Comment by isuftin** [comment]
Looks like a possible classloader issue... ?

```
ERROR FrameworkService: Converter Plugin jasypt-encryption threw exception during CREATE: org/rundeck/plugin/encryption/JasyptEncryptionConverterPlugin$EncryptStream
org.rundeck.storage.api.StorageException: Converter Plugin jasypt-encryption threw exception during CREATE: org/rundeck/plugin/encryption/JasyptEncryptionConverterPlugin$EncryptStream
        at com.dtolabs.rundeck.core.storage.StorageConverterPluginAdapter.filter(StorageConverterPluginAdapter.java:53)
        at com.dtolabs.rundeck.core.storage.StorageConverterPluginAdapter.convertCreateData(StorageConverterPluginAdapter.java:75)
        at com.dtolabs.rundeck.core.storage.StorageConverterPluginAdapter.convertCreateData(StorageConverterPluginAdapter.java:15)
        at org.rundeck.storage.conf.ConverterTree.filterCreateData(ConverterTree.java:44)
        at org.rundeck.storage.conf.ConverterTree.createResource(ConverterTree.java:84)
        at org.rundeck.storage.impl.DelegateTree.createResource(DelegateTree.java:65)
        at org.rundeck.storage.impl.StringToPathTree.createResource(StringToPathTree.java:66)
        at rundeck.services.ProjectManagerService.$tt__createProjectFileResource(ProjectManagerService.groovy:261)
        at rundeck.services.ProjectManagerService.$tt__writeProjectFileResource(ProjectManagerService.groovy:276)
        at rundeck.services.ProjectManagerService.storeProjectConfig(ProjectManagerService.groovy:359)
        at rundeck.services.ProjectManagerService.$tt__createFrameworkProject(ProjectManagerService.groovy:405)
        at rundeck.services.ProjectManagerService.$tt__createFrameworkProjectStrict(ProjectManagerService.groovy:433)
        at rundeck.services.FrameworkService.createFrameworkProject(FrameworkService.groovy:216)
        at rundeck.controllers.FrameworkController.createProjectPost(FrameworkController.groovy:903)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:191)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/rundeck/plugin/encryption/JasyptEncryptionConverterPlugin$EncryptStream
        at org.rundeck.plugin.encryption.JasyptEncryptionConverterPlugin.encrypt(JasyptEncryptionConverterPlugin.java:381)
        at org.rundeck.plugin.encryption.JasyptEncryptionConverterPlugin.createResource(JasyptEncryptionConverterPlugin.java:365)
        at com.dtolabs.rundeck.core.storage.StorageConverterPluginAdapter.filter(StorageConverterPluginAdapter.java:46)
        ... 60 more
Caused by: java.lang.ClassNotFoundException: org.rundeck.plugin.encryption.JasyptEncryptionConverterPlugin$EncryptStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
        at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:42)
        at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:28)
```

**Comment by isuftin** [comment]
It seems like a working configuration looks like:

```
rundeck.projectsStorageType=db
rundeck.storage.converter.1.config.password=<pass>
rundeck.storage.converter.1.path=keys
rundeck.storage.converter.1.type=jasypt-encryption
rundeck.storage.provider.1.path=keys
rundeck.storage.provider.1.type=db
```

However, if I add:
```
rundeck.config.storage.converter.1.type=jasypt-encryption
rundeck.config.storage.converter.1.path=<anything here>
rundeck.config.storage.converter.1.config.password=<pass>
```
...it fails pretty hard

**Comment by juris** [comment]
Exactly the same here for 2.6.7-1 with MariaDB RDS

**Comment by isuftin** [comment]
Still having this issue. Not sure where to go from here.

**Comment by fliphess** [comment]
I managed to solve the same error on an ubuntu server by installing libjasypt-java:

` apt-get install libjasypt-java`

**Comment by hekaldama** [comment]
@juris @isuftin did you resolve? I am getting this now when I downgraded from 2.9* to 2.8

**Comment by AndrewSwerlick** [comment]
I'm having this issue running inside a docker container on 2.6.11. I've created a repo with a dockerfile and associated configuration files to demonstrate the failure.

https://github.com/AndrewSwerlick/rundeck-encryption-error

**Comment by shoelzle** [comment]
Gleiches Problem mit 2.6.10 und MySQL.

**Comment by gschueler** [comment]
# bug research

1. Jasypt encryption plugin must be in libext dir on startup, to allow storage converter to be loaded
	* fix: the embedded plugins must be extracted *prior* to other spring beans which require plugins

				Caused by:
			java.lang.IllegalArgumentException: StorageConverter Plugin named "jasypt-encryption" could not be loaded
				at com.dtolabs.rundeck.server.storage.StorageTreeFactory.loadPlugin(StorageTreeFactory.java:387)
				at com.dtolabs.rundeck.server.storage.StorageTreeFactory.buildConverterPlugin(StorageTreeFactory.java:284)
				at com.dtolabs.rundeck.server.storage.StorageTreeFactory.configureConverterPlugin(StorageTreeFactory.java:268)
				at com.dtolabs.rundeck.server.storage.StorageTreeFactory.buildTree(StorageTreeFactory.java:150)
				at com.dtolabs.rundeck.server.storage.StorageTreeFactory.getObject(StorageTreeFactory.java:109)
				at com.dtolabs.rundeck.server.storage.StorageTreeFactory.getObject(StorageTreeFactory.java:56)
				at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
				at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
				at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
				at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
				at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
				at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
				at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
				at org.eclipse.jetty.server.Server.doStart(Server.java:261)
				at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
				at com.dtolabs.rundeck.RunServer.run(RunServer.java:120)
				at com.dtolabs.rundeck.RunServer.main(RunServer.java:80)
				at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
				at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)
				at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
				at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)

2. After startup, embedded plugins are extracted to libext dir, later this forces a reload via dir scanner
3. Reload via scanner is expiring original Jasypt plugin, causing classloading issues because the old classloader is closed and the cached libs are deleted
	* fix: expired plugins do not remove cached libs/files and close classloaders
	* todo fix: determine when to properly close classloaders and remove cache files
4. Still, BouncyCastle provider is not available by name "BC", and class is not directly usable due to Jasypt's classloading
	* Jasypt uses Thread context class loader, which does not include have the plugin's class loader
	* fix: load BouncyCastle provider statically in jasypt plugin?
	* fix: override Thread context loader in plugin methods to use plugin classloader?

**Comment by AndrewSwerlick** [comment]
@gschueler Thanks for this, is there anything I can do with the docker setup in particular to fix the problem? I confess I'm pretty ignorant about the inner working of java and it's class loading, so I didn't quite follow if your post had anything actionable in it from a workaround perspective, or if this is all stuff that has to be handled by rundeck internal.

**Comment by gschueler** [comment]
@AndrewSwerlick i need to try some more stuff, but I think likely we need to update the code.

**Comment by gschueler** [comment]
@AndrewSwerlick a possible workaround (haven't tested):
* extract *all* plugin files before startup (not just the jasypt encryption plugin)
    * this will prevent the plugin loader from forcing reload later
* extract jasypt.jar and bcprov.jar into `server/exp/webapp/WEB-INF/lib` before startup
