### ISSUE TITLE
SSH: when node has blank hostname, it attempts to connect to localhost.

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#1790]
commonly occuring in ec2 plugin when no public IP is set on a node, the hostname ends up blank, but remote execution targetting the node does not fail fast, it attempts to connect to ":22" (localhost)

**Comment by hekaldama** [comment]
Interesting. Everytime I don't supply a hostname I get a stack trace of:

```
java.lang.IllegalArgumentException: Null hostname value
	at com.dtolabs.rundeck.core.common.NodeEntryImpl.containsUserName(NodeEntryImpl.java:204)
	at com.dtolabs.rundeck.core.common.NodeEntryImpl.extractUserName(NodeEntryImpl.java:221)
	at com.dtolabs.rundeck.core.common.NodeEntryImpl.extractUserName(NodeEntryImpl.java:241)
	at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListenerImpl.getLoggingContext(WorkflowExecutionListenerImpl.java:102)
	at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.getContext(ContextualExecutionListener.java:117)
	at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListenerImpl.getContext(WorkflowExecutionListenerImpl.java:45)
	at com.dtolabs.rundeck.core.execution.Contextual$getContext.call(Unknown Source)
	at com.dtolabs.rundeck.app.internal.logging.ThreadBoundLogOutputStream.resetEventBuffer(ThreadBoundLogOutputStream.groovy:89)
	at com.dtolabs.rundeck.app.internal.logging.ThreadBoundLogOutputStream.getOrReset(ThreadBoundLogOutputStream.groovy:79)
	at com.dtolabs.rundeck.app.internal.logging.ThreadBoundLogOutputStream.write(ThreadBoundLogOutputStream.groovy:58)
	at com.dtolabs.rundeck.core.utils.ThreadBoundOutputStream.write(ThreadBoundOutputStream.java:123)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at java.io.PrintStream.write(PrintStream.java:480)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	at java.io.PrintStream.write(PrintStream.java:527)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:823)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
	at java.lang.Throwable.printStackTrace(Throwable.java:655)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:147)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Null hostname value
```

I am running 2.6.4-1 cafe bonbon firebrick music.
