### ISSUE TITLE
Cannot delete executions since upgrade to 2.6.6

### ISSUE THREAD

**Issue by makered** [rundeck/rundeck#1844]
I have a scheduled script that uses the `executions/delete` call to purge old executions. The script was running successfully until I upgraded from 2.6.5 to 2.6.6. Now attempting to delete executions via this call results in errors similar to:

```Failed to delete execution {{Execution 698948}}: deleted object would be re-saved by cascade (remove deleted object from associations): [rundeck.LogFileStorageRequest#730662]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [rundeck.LogFileStorageRequest#730662]```

I have two independent Rundeck servers that started exhibiting this same behavior after upgrade.

any ideas?

Thanks

**Comment by jenulis** [comment]
I got a similar error message when trying to delete a project. The project was created in pro 1.3.5 (2.6.4-1).  After I upgraded to 1.3.6 (2.6.7-1) and ried to delete the project I get the stack trace below.  If I back out the upgrade, I can delete the project.

INFO   | jvm 1    | 2016/05/09 15:45:39 | 2016-05-09 15:45:39,533 ERROR GrailsExceptionResolver - ObjectDeletedException occurred when processing request: [POST] /rundeckpro/project/Database/delete
INFO   | jvm 1    | 2016/05/09 15:45:39 | deleted object would be re-saved by cascade (remove deleted object from associations): [rundeck.LogFileStorageRequest#4131]. Stacktrace follows:
INFO   | jvm 1    | 2016/05/09 15:45:39 | org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [rundeck.LogFileStorageRequest#4131]
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at rundeck.services.ProjectManagerService.$tt__removeFrameworkProject(ProjectManagerService.groovy:493)
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at rundeck.services.ProjectService.deleteProject(ProjectService.groovy:1125)
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at rundeck.controllers.ProjectController$_delete_closure8.doCall(ProjectController.groovy:313)
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at rundeck.controllers.ProjectController.delete(ProjectController.groovy:286)
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
INFO   | jvm 1    | 2016/05/09 15:45:39 | 	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)

**Comment by philippevidal80** [comment]
+1 on Project deletion:

Message: deleted object would be re-saved by cascade (remove deleted object from associations): [rundeck.LogFileStorageRequest#1]

org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [rundeck.LogFileStorageRequest#1]
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at rundeck.services.ProjectManagerService.$tt__removeFrameworkProject(ProjectManagerService.groovy:493)
	at rundeck.services.ProjectService.deleteProject(ProjectService.groovy:1125)
	at rundeck.controllers.ProjectController$_delete_closure8.doCall(ProjectController.groovy:313)
	at rundeck.controllers.ProjectController.delete(ProjectController.groovy:286)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:191)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nilroy** [comment]
I am also facing the same issue while deleting execution. The bug is there in 2.6.7 also. Any idea when we can expect it to be resolved?

**Comment by gschueler** [comment]
we are estimating that the next release will be next week, including a fix for this

**Comment by nilroy** [comment]
@gschueler That would be great.. Eagerly waiting for the next release :)

**Comment by gschueler** [comment]
I merged in a fix, however I was unable to write an integration test that would successfully reproduce the issue. If you are able to test the latest code, that would be helpful to know it solves the issue for you, otherwise the 2.6.8 release will contain it
