### ISSUE TITLE
LDAP SSL CN validation prevents using multiple LDAP hosts (failover)

### ISSUE THREAD

**Issue by viktorradnai** [rundeck/rundeck#1853]
We are trying to configure multiple LDAP servers for login, using com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule in our JAAS config. It seems that the underlying Java libraries support a provider url with multiple servers (or rather, multiple URLs separated by spaces) in the form of:

```
providerUrl="ldaps://dc01:636/ ldaps://dc02:636/"
```

When  ldapsVerifyHostname is set to "false" in the jaas config, this works as expected (authentication will succeed as long as one of the LDAP servers is reachable). When ldapsVerifyHostname is set to "true", we get the following exception (please note that the LDAP server hostnames have been edited):

2016-05-20 20:37:54.062:WARN:oejpj.JAASLoginService:
javax.security.auth.login.LoginException: java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in authority at index 8: ldaps://dc01:636/ ldaps://dc02:636/|?at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getEnvironment(JettyCachingLdapLoginModule.java:967)

This is using Rundeck 2.6.6. The offending code is in 'rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java':

```
    // Set the SSLContextFactory to implementation that validates cert subject
    if (url != null && url.startsWith("ldaps") && _ldapsVerifyHostname) {
        try {
            URI uri = new URI(url);
            HostnameVerifyingSSLSocketFactory.setTargetHost(uri.getHost());
            env.put("java.naming.ldap.factory.socket",
                    "com.dtolabs.rundeck.jetty.jaas.HostnameVerifyingSSLSocketFactory");
        }
        catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }
```

The providerUrl (url variable) should be split by space and each URL verified separately. I think the correct behaviour should be to print a warning if a certificate name doesn't match one of the hostnames but continue to work as long as there is one LDAP server that matches.

**Comment by driseley** [comment]
This appears to be addressed by a JDK improvement in JDK 8u181 or later:

https://www.oracle.com/technetwork/java/javase/8u181-relnotes-4479407.html#JDK-8200666

> Endpoint identification has been enabled on LDAPS connections.
> To improve the robustness of LDAPS (secure LDAP over TLS) connections, endpoint identification algorithms have been enabled by default.

So, counter intuitively, if you set `ldapsVerifyHostname="false"` in the JAAS LDAP configuration, this disables the custom hostname verification but allows the JDK version to take place, so the space separated providerUrl now works.

Should the custom HostName verification code now be removed , or at least a documentation update be done to indicate how this works?

**Comment by digitalray** [comment]
Could authenticationMethod="simple" be changed to "StartTLS"? Currently our LDAP requires us to use TLS.

```
[2019-10-31 03:40:29.846] ERROR JettyCachingLdapLoginModule --- [qtp585212380-29] Naming error

javax.naming.OperationNotSupportedException: [LDAP: error code 53 - A secure connection cannot be established. To admin: This service requires TLS.]
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3227)
```

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
