### ISSUE TITLE
Rundeck: Communications link failure during rollback(). Transaction resolution unknown.

### ISSUE THREAD

**Issue by atlasloewenherz** [rundeck/rundeck#1888]
Hi everyone,

following problem occure always after a long time of inactivity ( 4-6 hours)

![screen shot 2016-06-09 at 11 33 37](https://cloud.githubusercontent.com/assets/3721197/15925106/267b3564-2e36-11e6-8fb2-8e4e75738cc9.png)

my deploying:
- INFO: Starting Servlet Engine: Apache Tomcat/7.0.68
- INFO  BootStrap: Starting Rundeck 2.6.7-1...
- INFO  BootStrap: Rundeck is ACTIVE: executions can be run.
- INFO  BootStrap: Rundeck startup finished in 1075ms
- INFO: Deployment of configuration descriptor /opt/rundeck/apache-tomcat-7.0.68/conf/Catalina/localhost/ROOT.xml has finished in 33,113 ms

**Database releavant configurations in rundeck-config:**

```

rundeck.v14.rdbsupport=true
dataSource.pooled =true
dataSource.testWhileIdle=true
dataSource.testOnBorrow=true
dataSource.validationQuery=SELECT 1
dataSource.dbCreate =update
dataSource.driverClassName =com.mysql.jdbc.Driver
dataSource.url =jdbc:mysql://10.10.1.99:3306/rundeck?autoReconnect=true
dataSource.dialect =org.hibernate.dialect.MySQL5InnoDBDialect
dataSource.username =rundeck
dataSource.password =xxxxxxx


```

**rundeck logs:**

```
2016-06-10 10:29:39,362 [http-bio-8080-exec-2] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - The last packet successfully received from the server was 59,725,497 milliseconds ago.  The last packet sent successfully to the server was 59,725,497 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
2016-06-10 10:29:39,402 [http-bio-8080-exec-2] ERROR org.springframework.transaction.interceptor.TransactionInterceptor - Application exception overridden by rollback exception
org.hibernate.exception.JDBCConnectionException: could not prepare statement
        at rundeck.services.DbStorageService.listDirectory(DbStorageService.groovy:183)
        at com.dtolabs.rundeck.core.storage.ResolvedExtTree.listDirectory(ResolvedExtTree.java:62)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.conf.ListenerTree.listDirectory(ListenerTree.java:81)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.impl.StringToPathTree.listDirectory(StringToPathTree.java:50)
        at rundeck.services.ConfigStorageService.$tt__listDirPaths(ConfigStorageService.groovy:55)
        at rundeck.services.AuthorizationService.loadStoredPolicies(AuthorizationService.groovy:133)
        at rundeck.services.AuthorizationService.getStoredPolicies(AuthorizationService.groovy:116)
        at rundeck.services.AuthorizationService.getRoleList(AuthorizationService.groovy:66)
        at rundeck.services.FrameworkService.getFrameworkRoles(FrameworkService.groovy:652)
        at org.rundeck.web.infosec.ContainerRoleSource.getUserRoles(ContainerRoleSource.groovy:19)
        at rundeck.filters.AuthorizationFilters$_createAuthSubject_closure2.doCall(AuthorizationFilters.groovy:156)
        at rundeck.filters.AuthorizationFilters.createAuthSubject(AuthorizationFilters.groovy:154)
        at rundeck.filters.AuthorizationFilters$_closure1_closure4_closure7.doCall(AuthorizationFilters.groovy:64)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 59,725,497 milliseconds ago.  The last packet sent successfully to the server was 59,725,497 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3609)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2417)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
        at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4852)
        ... 23 more
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3591)
        ... 27 more
2016-06-10 10:29:39,638 [http-bio-8080-exec-2] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - MySQLNonTransientConnectionException occurred when processing request: [GET] /project/CM/jobs
Communications link failure during rollback(). Transaction resolution unknown.. Stacktrace follows:
org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: rollback failed
        at rundeck.services.FrameworkService.getFrameworkRoles(FrameworkService.groovy:652)
        at org.rundeck.web.infosec.ContainerRoleSource.getUserRoles(ContainerRoleSource.groovy:19)
        at rundeck.filters.AuthorizationFilters$_createAuthSubject_closure2.doCall(AuthorizationFilters.groovy:156)
        at rundeck.filters.AuthorizationFilters.createAuthSubject(AuthorizationFilters.groovy:154)
        at rundeck.filters.AuthorizationFilters$_closure1_closure4_closure7.doCall(AuthorizationFilters.groovy:64)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.TransactionException: rollback failed
        ... 11 more
Caused by: org.hibernate.TransactionException: unable to rollback against JDBC connection
        ... 11 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
        at com.mysql.jdbc.Util.getInstance(Util.java:372)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:958)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
        at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4612)
        ... 11 more
```

**catalina.out logs:**

```
ERROR SqlExceptionHelper: The last packet successfully received from the server was 59,725,497 milliseconds ago.  The last packet sent successfully to the server was 59,725,497 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, incr
easing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
ERROR TransactionInterceptor: Application exception overridden by rollback exception
org.hibernate.exception.JDBCConnectionException: could not prepare statement
        at rundeck.services.DbStorageService.listDirectory(DbStorageService.groovy:183)
        at com.dtolabs.rundeck.core.storage.ResolvedExtTree.listDirectory(ResolvedExtTree.java:62)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.conf.ListenerTree.listDirectory(ListenerTree.java:81)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.impl.DelegateTree.listDirectory(DelegateTree.java:55)
        at org.rundeck.storage.impl.StringToPathTree.listDirectory(StringToPathTree.java:50)
        at rundeck.services.ConfigStorageService.$tt__listDirPaths(ConfigStorageService.groovy:55)
        at rundeck.services.AuthorizationService.loadStoredPolicies(AuthorizationService.groovy:133)
        at rundeck.services.AuthorizationService.getStoredPolicies(AuthorizationService.groovy:116)
        at rundeck.services.AuthorizationService.getRoleList(AuthorizationService.groovy:66)
        at rundeck.services.FrameworkService.getFrameworkRoles(FrameworkService.groovy:652)
        at org.rundeck.web.infosec.ContainerRoleSource.getUserRoles(ContainerRoleSource.groovy:19)
        at rundeck.filters.AuthorizationFilters$_createAuthSubject_closure2.doCall(AuthorizationFilters.groovy:156)
        at rundeck.filters.AuthorizationFilters.createAuthSubject(AuthorizationFilters.groovy:154)
        at rundeck.filters.AuthorizationFilters$_closure1_closure4_closure7.doCall(AuthorizationFilters.groovy:64)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 59,725,497 milliseconds ago.  The last packet sent successfully to the server was 59,725,497 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection val
idity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3609)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2417)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
        at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4852)
        ... 23 more
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3591)
        ... 27 more
ERROR GrailsExceptionResolver: MySQLNonTransientConnectionException occurred when processing request: [GET] /project/CM/jobs
Communications link failure during rollback(). Transaction resolution unknown.. Stacktrace follows:
org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: rollback failed
        at rundeck.services.FrameworkService.getFrameworkRoles(FrameworkService.groovy:652)
        at org.rundeck.web.infosec.ContainerRoleSource.getUserRoles(ContainerRoleSource.groovy:19)
        at rundeck.filters.AuthorizationFilters$_createAuthSubject_closure2.doCall(AuthorizationFilters.groovy:156)
        at rundeck.filters.AuthorizationFilters.createAuthSubject(AuthorizationFilters.groovy:154)
        at rundeck.filters.AuthorizationFilters$_closure1_closure4_closure7.doCall(AuthorizationFilters.groovy:64)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.TransactionException: rollback failed
        ... 11 more
Caused by: org.hibernate.TransactionException: unable to rollback against JDBC connection
        ... 11 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
        at com.mysql.jdbc.Util.getInstance(Util.java:372)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:958)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
        at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4612)
        ... 11 more
Jun 10, 2016 10:45:08 AM org.apache.catalina.core.StandardServer await
INFO: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
```

**Comment by Rotnelson** [comment]
Did you ever solve this. I am facing the same issue

**Comment by Kelvin-Chu** [comment]
Also seeing this issue on my end.

**Comment by gstachowiak** [comment]
Hi, your configuration is incorrect. It should look like this:

```
dataSource.url = jdbc:oracle:thin:@localhost:1521:XE
dataSource.driverClassName = oracle.jdbc.driver.OracleDriver
dataSource.dialect = org.hibernate.dialect.Oracle10gDialect
# data source connection pool configuration
dataSource.pooled = true
dataSource.properties.testOnBorrow = true
dataSource.properties.validationQuery = select 1 from dual
dataSource.properties.maxActive = 50
dataSource.properties.maxIdle = 25
dataSource.properties.minIdle = 5
dataSource.properties.initialSize = 5
dataSource.properties.maxWait = 10000
```
