### ISSUE TITLE
rundeck HTTP/503 page

### ISSUE THREAD

**Issue by vdmkenny** [rundeck/rundeck#2018]
I've recently carried over an existing rundeck installation from a previous server (installed as a standalone jar with some scripts around it to manage.) and I'm now receiving 503 errors.
This is the stderror.log:
```
~> cat /var/log/run-deck/run/default-stderror.log
2016-08-19 16:55:01.809:INFO:oejs.Server:jetty-7.6.0.v20120127
2016-08-19 16:55:04.305:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2016-08-19 16:55:05.201:INFO:/:Initializing Spring root WebApplicationContext
2016-08-19 16:55:06.832:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/,file:/home/run-deck/deploy/server/exp/webapp/},/home/run-deck/deploy/server/exp/webapp
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplication' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:120)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:80)
	at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
	at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)
	at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
	at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by: 
java.lang.ExceptionInInitializerError
	at java.lang.Class.forName(Class.java:348)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:120)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:80)
	at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
	at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)
	at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
	at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by: 
groovy.lang.MissingMethodException: No signature of method: org.owasp.html.HtmlPolicyBuilder.withPreprocessor() is applicable for argument types: (rundeck.codecs.SanitizedHTMLCodec$AutoClosingEventProcessor) values: [rundeck.codecs.SanitizedHTMLCodec$AutoClosingEventProcessor@7893c715]
	at rundeck.codecs.SanitizedHTMLCodec.<clinit>(SanitizedHTMLCodec.groovy:81)
	at java.lang.Class.forName(Class.java:348)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:120)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:80)
	at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:690)
	at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:647)
	at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:304)
	at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
2016-08-19 16:55:06.855:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

```
What could be causing this? All the files are identical to before, when it was working.

**Comment by gschueler** [comment]
did you upgrade to a newer version?  possibly there are older dependent jars in the lib dir.

you can remove server/exp (preserve any changes to server/exp/webapp/WEB-INF/web.xml and server/exp/webapp/WEB-INF/classes/log4j.properties), then run the launcher again to restore the lib dir appropriately

**Comment by vdmkenny** [comment]
Thanks, that did the trick :)
