### ISSUE TITLE
SCM Export Fails - ClassNotFoundException

### ISSUE THREAD

**Issue by seunaw** [rundeck/rundeck#2031]
I am running into an error with the SCM export plugin.  I thought the plugin was bundled with rundeck so jar files should be included.  Please see screenshot

![screen shot 2016-08-26 at 11 12 07 am](https://cloud.githubusercontent.com/assets/5809894/18015860/5e4123c0-6b7e-11e6-8ef5-85f0b209701b.png)

**Comment by jamieps** [comment]
@seunaw check you have a `rundeck-git-plugin-2.6.9.jar` in `libext` under the Rundeck launcher home directory and whether there is more than one version of it.

```
jamie@avior:/tmp/rundeck$ ls -al
total 89368
drwxrwxr-x  8 jamie jamie     4096 Aug 26 22:38 .
drwxrwxrwt 26 root  root   1409024 Aug 26 22:43 ..
drwxrwxr-x  2 jamie jamie     4096 Aug 26 22:38 etc
drwxrwxr-x  3 jamie jamie     4096 Aug 26 22:38 libext
drwxrwxr-x  2 jamie jamie     4096 Aug 26 22:37 projects
[...]
jamie@avior:/tmp/rundeck$ ls -al libext/
total 5268
drwxrwxr-x 3 jamie jamie    4096 Aug 26 22:38 .
drwxrwxr-x 8 jamie jamie    4096 Aug 26 22:38 ..
drwxrwxr-x 2 jamie jamie    4096 Aug 26 22:37 cache
-rw-rw-r-- 1 jamie jamie    3913 Aug 26 22:38 rundeck-copyfile-plugin-2.6.10-SNAPSHOT.jar
-rw-rw-r-- 1 jamie jamie    2309 Aug 26 22:38 rundeck-flow-control-plugin-2.6.10-SNAPSHOT.jar
-rw-rw-r-- 1 jamie jamie 2766528 Aug 26 22:38 rundeck-git-plugin-2.6.10-SNAPSHOT.jar
[...]
```

**Comment by seunaw** [comment]
It is there

[root@localhost libext]# ls -l *git*
-rw-r--r-- 1 rundeck rundeck 2766314 Aug  3 22:24
rundeck-git-plugin-2.6.9.jar
[root@localhost libext]#

**Comment by seunaw** [comment]
@jamieps The jar for the git plugin exists in libext but I still get the class not found error.  Any thoughts why this is

**Comment by nbr** [comment]
Running into the same issue as @seunaw. The plugin exists under `libext`. Running from pre-built JAR. Adding `-cp .../libext` to the java command doesn't help either. I tried this with both Java 7/8.

```
java.lang.ClassNotFoundException: org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction$_getInputView_closure1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:42)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:28)
	at org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction.getInputView(CommitJobsAction.groovy:33)
	at org.rundeck.plugin.scm.git.GitExportPlugin.getInputViewForAction(GitExportPlugin.groovy:116)
	at rundeck.services.ScmService.getExportInputView(ScmService.groovy:207)
	at rundeck.services.ScmService.getInputView(ScmService.groovy:196)
	at rundeck.controllers.ScmController.performAction(ScmController.groovy:1034)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:58)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:910)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gschueler** [comment]
Unhappy about this weird problem 😿 .

I suspect there is something going on in the CommitJobsAction.groovy code.  It does a static import of an external method called `inputView` and later calls it within the `getInputView` method. In groovy a call to `.getX` also will also try to resolve a property named `X`, and maybe that's confusing it? But odd that it only happens for some folks.

What JVM are you all using?

I will try to change the method names and usage of static import..

**Comment by nbr** [comment]
@gschueler 

```
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```
