### ISSUE TITLE
Problems using rundeck with ldap

### ISSUE THREAD

**Issue by abdelbassit** [rundeck/rundeck#2034]
Hello,

I'm trying to use ldap with rundeck, but when I Try to access with ldap users I can't, I have this errors:

```
 2016-08-29 09:46:42.080:WARN:oejpj.JAASLoginService:
 javax.security.auth.login.LoginException: Error obtaining user info.
at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.authenticate(JettyCachingLdapLoginModule.java:696)
at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.login(JettyCachingLdapLoginModule.java:599)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at javax.security.auth.login.LoginContext.invoke(LoginContext.java:762)
at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)
at javax.security.auth.login.LoginContext$4.run(LoginContext.java:690)
at javax.security.auth.login.LoginContext$4.run(LoginContext.java:688)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:687)
at javax.security.auth.login.LoginContext.login(LoginContext.java:595)
at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:217)
at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:183)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:456)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
at org.eclipse.jetty.server.Server.handle(Server.java:349)
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
at java.lang.Thread.run(Thread.java:745)
```

My ldap file configuration is that:

```
ldap {
 com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
  debug="true"
  contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
  providerUrl="ldap://ldap.mysite.com:389"
  bindDn="cn=admin,dc=mysite,dc=com"
  bindPassword="secret"
  authenticationMethod="simple"
  forceBindingLogin="true"
  userBaseDn="dc=mysite,dc=com"
  userRdnAttribute="uid"
  userIdAttribute="uid"
  userPasswordAttribute="userPassword"
  userObjectClass="account"
  roleBaseDn="dc=mysite,dc=com"
  roleNameAttribute="cn"
  roleUsernameMemberAttribute="memberUid"
  roleMemberAttribute="memberUid"
  roleObjectClass="posixGroup"
  cacheDurationMillis="300000"
  reportStatistics="true";

  org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule required
  debug="true"
  file="/etc/rundeck/realm.properties";
```

};

In **realm.properties** I have this configuration:

```
   #
   # This sets the default user accounts for the Rundeck app
   #
    admin:admin,user,admin,architect,deploy,build
```

Any suggestion or help to solve this problem?

Thanks,

**Comment by ARentz07** [comment]
Is this more of a usage question than an issue with rundeck itself?

There should be more to that log, where you can find a specific error code for LDAP that gives more detail of what the failure was. 

I also found this helpful when setting up LDAP - http://www.bitester.com/2015/12/ldap-authentication-with-rundeck.html

**Comment by zodman** [comment]
my ldap rundeck config works great!

**Comment by louisdj** [comment]
@abdelbassit Have you found the error? Having the same issue...

**Comment by ktraister** [comment]
We had an issue similar to this, the problem ended up being a strange LDAP configuration that resulted in the various attributes being mapped incorrectly. We had to use the 'ldapsearch' tool to dig through the records and figure out how the attribute mapping was done

**Comment by sjrd218** [comment]
The reported error is usually a result of a misconfiguration. Please see the docs for instructions on configuring LDAP with Rundeck. https://docs.rundeck.com/docs/administration/security/authenticating-users.html#ldap

**Comment by AuditeMarlow** [comment]
> https://docs.rundeck.com/docs/administration/security/authenticating-users.html#ldap

This link is now dead. Are these docs found elsewhere nowadays?
