### ISSUE TITLE
provider data issue in Rundeck 2.6.9-1

### ISSUE THREAD

**Issue by looprock** [rundeck/rundeck#2057]
I'm using the rpm release of Rundeck 2.6.9-1 and there seems to be an odd glitch in the provider interaction.  I have a job that triggers two or more ad hoc jobs, and after upgrading instance of the ad hoc job consistently fails. I have a job that creates virtual instances, then deploys to those instances via ad hoc jobs. The ad hoc jobs are exactly the same except for the target systems. The first deploy always fails, unable to find the node:

```
19:05:49 [dland@localhost _][ERROR] com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={hostname=VM-1e19bbc4-d6e4-4ec4-9b64-c3be079c8323.usaacs.oak.vast.com, dominant=false, }}
19:05:49 [dland@localhost _][ERROR] 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.validateNodeSet(NodeFirstWorkflowStrategy.java:350)
19:05:49 [dland@localhost _][ERROR] 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:88)
19:05:49 [dland@localhost _][ERROR] 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
19:05:49 [dland@localhost _][ERROR] 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
19:05:49 [dland@localhost _][ERROR] Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={hostname=VM-1e19bbc4-d6e4-4ec4-9b64-c3be079c8323.usaacs.oak.vast.com, dominant=false, }}
19:05:49 [dland@localhost _][ERROR] No matched nodes: NodeSet{includes={hostname=VM-1e19bbc4-d6e4-4ec4-9b64-c3be079c8323.usaacs.oak.vast.com, dominant=false, }}
```

Subsequent jobs, using the same provider as part of the same project work. It's as if the provider data for the project is getting cached and only refreshes after the first job executed.  I verified the provider is returning the proper dataset:

```
2016-09-07 21:05:49,332 DEBUG: <project>
<node name="VM-52b0f4d8-2f15-4395-9d01-9056bad136b6.usaacs.oak.vast.com" type="Node" description="VM-52b0f4d8-2f15-4395-9d01-9056bad136b6.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-52b0f4d8-2f15-4395-9d01-9056bad136b6.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-52b0f4d8-2f15-4395-9d01-9056bad136b6.usaacs.oak.vast.com/edit"/>
<node name="VM-f46aca6b-68ae-4a82-a29b-9880cb1b5a47.usaacs.oak.vast.com" type="Node" description="VM-f46aca6b-68ae-4a82-a29b-9880cb1b5a47.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-f46aca6b-68ae-4a82-a29b-9880cb1b5a47.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-f46aca6b-68ae-4a82-a29b-9880cb1b5a47.usaacs.oak.vast.com/edit"/>
<node name="VM-0cbbcd45-08ca-439c-8633-93426641f415.usaacs.oak.vast.com" type="Node" description="VM-0cbbcd45-08ca-439c-8633-93426641f415.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-0cbbcd45-08ca-439c-8633-93426641f415.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-0cbbcd45-08ca-439c-8633-93426641f415.usaacs.oak.vast.com/edit"/>
<node name="VM-ae031c07-166e-420b-927e-aa5cb0af1bda.usaacs.oak.vast.com" type="Node" description="VM-ae031c07-166e-420b-927e-aa5cb0af1bda.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-ae031c07-166e-420b-927e-aa5cb0af1bda.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-ae031c07-166e-420b-927e-aa5cb0af1bda.usaacs.oak.vast.com/edit"/>
<node name="VM-44a84b77-0176-4019-b54e-abeabe2b0e73.usaacs.oak.vast.com" type="Node" description="VM-44a84b77-0176-4019-b54e-abeabe2b0e73.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-44a84b77-0176-4019-b54e-abeabe2b0e73.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-44a84b77-0176-4019-b54e-abeabe2b0e73.usaacs.oak.vast.com/edit"/>
<node name="VM-4556028a-f647-422f-bd2c-67ff588e583c.usaacs.oak.vast.com" type="Node" description="VM-4556028a-f647-422f-bd2c-67ff588e583c.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-4556028a-f647-422f-bd2c-67ff588e583c.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-4556028a-f647-422f-bd2c-67ff588e583c.usaacs.oak.vast.com/edit"/>
<node name="VM-6f4155fa-c791-44d3-92d5-8e7ecbdcd4f7.usaacs.oak.vast.com" type="Node" description="VM-6f4155fa-c791-44d3-92d5-8e7ecbdcd4f7.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-6f4155fa-c791-44d3-92d5-8e7ecbdcd4f7.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-6f4155fa-c791-44d3-92d5-8e7ecbdcd4f7.usaacs.oak.vast.com/edit"/>
<node name="VM-aa915bff-6a09-4b3f-8d22-d733c0fafe86.usaacs.oak.vast.com" type="Node" description="VM-aa915bff-6a09-4b3f-8d22-d733c0fafe86.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-aa915bff-6a09-4b3f-8d22-d733c0fafe86.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-aa915bff-6a09-4b3f-8d22-d733c0fafe86.usaacs.oak.vast.com/edit"/>
<node name="VM-1e19bbc4-d6e4-4ec4-9b64-c3be079c8323.usaacs.oak.vast.com" type="Node" description="VM-1e19bbc4-d6e4-4ec4-9b64-c3be079c8323.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-1e19bbc4-d6e4-4ec4-9b64-c3be079c8323.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-1e19bbc4-d6e4-4ec4-9b64-c3be079c8323.usaacs.oak.vast.com/edit"/>
<node name="VM-10399b5c-0a51-46cd-9fb6-9b8873bd9133.usaacs.oak.vast.com" type="Node" description="VM-10399b5c-0a51-46cd-9fb6-9b8873bd9133.usaacs.oak.vast.com" osArch="x86_64" osFamily="unix" osName="centos" osVersion="cloudstack" tags="cloudstack" username="rundeck" hostname="VM-10399b5c-0a51-46cd-9fb6-9b8873bd9133.usaacs.oak.vast.com" editUrl="http://chef.vast.com:4040/nodes/VM-10399b5c-0a51-46cd-9fb6-9b8873bd9133.usaacs.oak.vast.com/edit"/>
</project>

2016-09-07 21:05:49,337 INFO: 200 GET /usaa-oakland/providevirtualmachines (127.0.0.1) 157.26ms
```

You can see that in the node exists in the provider dataset, but I would guess the job is somehow using stale data from the previous run where the node hadn't been created yet. Any help would be appreciated. Thanks!

**Comment by gschueler** [comment]
have you tried disabling the nodes cache for the project?

**Comment by looprock** [comment]
Yep caching is set to false.

**Comment by looprock** [comment]
This is the cache setting you were referring to right?

resources.source.2.config.cache=false
resources.source.2.config.timeout=30
resources.source.2.config.url=xxxx
resources.source.2.type=url

**Comment by gschueler** [comment]
@looprock no, there is a new-ish per-project caching system, which can be disabled for the project

**Comment by looprock** [comment]
Hi Greg, can you point me at a reference? I'm not seeing it readily. Perhaps I'm searching for the wrong strings..

**Comment by gschueler** [comment]
@looprock it is shown in the project config GUI as "Project Nodes > [ ] Use Asynchronous Cache"

for project.properties it is:

~~~{.properties}
project.nodeCache.delay=30
project.nodeCache.enabled=false
~~~

**Comment by looprock** [comment]
Thank you!

**Comment by gschueler** [comment]
Did that fix it for you?

**Comment by looprock** [comment]
It's hard for me to test, but I'll know in a bit. Thanks!
