### ISSUE TITLE
Delete button not found

### ISSUE THREAD

**Issue by robidson** [rundeck/rundeck#2094]
# Bug report

**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: rpm
- OS Name/version: RedHat 6.6

**Expected Behavior**
Click button "Delete" for deleting jobs and projects
Commande line rd-jobs for deleting the jobs

**Actual Behavior**
Non button "Delete" on the job/project
The command line rd-jobs return this:

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
log4j:ERROR Could not read configuration file [/etc/rundeck/cli-log4j.properties].
java.io.FileNotFoundException: /etc/rundeck/cli-log4j.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
        at com.dtolabs.rundeck.core.cli.jobs.JobsTool.main(JobsTool.java:373)
log4j:ERROR Ignoring configuration file [/etc/rundeck/cli-log4j.properties].
log4j:ERROR Could not read configuration file [/etc/rundeck/cli-log4j.properties].
java.io.FileNotFoundException: /etc/rundeck/cli-log4j.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
        at com.dtolabs.rundeck.core.cli.BaseTool.run(BaseTool.java:158)
        at com.dtolabs.rundeck.core.cli.jobs.JobsTool.main(JobsTool.java:379)
log4j:ERROR Ignoring configuration file [/etc/rundeck/cli-log4j.properties].
ERROR BaseFormAuthenticator: Form-based auth failed
Error: Error making server request to http://rundeck:4440: Unable to authenticate user: admin

**How to reproduce Behavior**
Try to delete a job or project on the web interface.
# Enhancement request

(_For enhancements_: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by willemdh** [comment]
Do you mean this button?

![image](https://cloud.githubusercontent.com/assets/6462991/20368054/a2a9a068-ac52-11e6-9251-c6762dc02eaf.png)

**Comment by gschueler** [comment]
Delete button is shown in GUI if appropriate permissions are allowed.

It is expecting the file `/etc/rundeck/cli-log4j.properties` to exist, try creating it (can be empty)


rd-jobs has been removed in 2.7.0
