### ISSUE TITLE
[ Unable to execute an inline script ]

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#2126]
Hello,

I just installed the latest version of Rundeck (2.6.9-4 RPM version) on a Centos 7.2 KVM vm.

It just work when I run a command on a node; but when I try to execute an inline script, I get this error:

```
Failed dispatching to node lrundeck2: error writing script to tempfile: No such file or directory
17:21:25			Failed dispatching to node lrundeck2: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: error writing script to tempfile: No such file or directory	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:101)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:57)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:149)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:177)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:258)
	at com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:79)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy$DispatchedWorkflow.dispatch(NodeFirstWorkflowStrategy.java:383)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:118)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:64)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:196)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWFSectionNodeDispatch(NodeFirstWorkflowStrategy.java:189)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:110)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Caused by: com.dtolabs.rundeck.core.execution.service.FileCopierException: error writing script to tempfile: No such file or directory
	at com.dtolabs.rundeck.core.execution.impl.common.DefaultFileCopierUtil.writeScriptTempFile(DefaultFileCopierUtil.java:138)
	at com.dtolabs.rundeck.core.execution.impl.common.DefaultFileCopierUtil.writeScriptTempFile(DefaultFileCopierUtil.java:61)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.writeScriptToTempFile(DefaultScriptFileNodeStepUtils.java:147)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:82)
	... 20 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at com.dtolabs.rundeck.core.execution.script.ScriptfileUtils.createTempFile(ScriptfileUtils.java:264)
	at com.dtolabs.rundeck.core.execution.impl.common.DefaultFileCopierUtil.writeScriptTempFile(DefaultFileCopierUtil.java:107)
	... 23 more
```

Could you help me with that issue ?

I think Rundeck is unable to create the temporary script on the Rundeck node before sending it to the target node. But where does that temp file get created ?

Thank you for your help

Best regards
Jérôme

**Comment by jerome83136** [comment]
EDIT: the issue seems to be due to a wrong configuration which I made on the Rundeck's profile file.
After reinstalling Rundeck from scratch, all is working fine.

Best regards
Jérôme
