### ISSUE TITLE
Error start Rundeck SSL since last update 2.7.0

### ISSUE THREAD

**Issue by charlescoupeau** [rundeck/rundeck#2217]
Hello,

since today and the update 2.7.0, I could not restart Rundeck :

Dec 01 04:01:37 Updated: rundeck-config.noarch 2.7.0-1.24.GA
Dec 01 04:01:44 Updated: rundeck.noarch 2.7.0-1.24.GA

In the service.log :

2016-12-01 11:14:20.151:INFO:oejs.ServerConnector:main: Started ServerConnector@240c626d{HTTP/1.1}{0.0.0.0:4443}
2016-12-01 11:14:20.152:WARN:oejuc.AbstractLifeCycle:main: FAILED ServerConnector@53a645a2{SSL-HTTP/1.1}{0.0.0.0:4443}: java.net.BindException: Address already in use
java.net.BindException: Address already in use

But I have no other service use the port 4443.

Thanks,
Charles.

[profile.txt](https://github.com/rundeck/rundeck/files/627227/profile.txt)

**Comment by reecewebb** [comment]
I'm having the exact same issue. I'm coming from 2.6.10, just went to 2.7 this morning. I followed the upgrade instructions. I have Rundeck behind a reverse proxy (nginx), which listens on 80/443.

Rundeck;
RDECK_HTTP_PORT=8080
RDECK_HTTPS_PORT=8443

service.log;
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
2016-12-02 13:02:13.499:INFO:oejs.Server:main: jetty-9.0.7.v20131107
2016-12-02 13:02:15.270:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2016-12-02 13:02:15.889:INFO:/:main: Initializing Spring root WebApplicationContext
INFO  BootStrap: Starting Rundeck 2.7.0-1 (2016-12-01) ...
INFO  BootStrap: using rdeck.base config property: /var/lib/rundeck
INFO  BootStrap: loaded configuration: /etc/rundeck/framework.properties
INFO  BootStrap: RSS feeds disabled
INFO  BootStrap: Preauthentication is disabled
INFO  BootStrap: Rundeck is ACTIVE: executions can be run.
INFO  BootStrap: Rundeck startup finished in 388ms
2016-12-02 13:02:28.092:INFO:/:main: Initializing Spring FrameworkServlet 'grails'
2016-12-02 13:02:28.108:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@6ed043d3{/,file:/var/lib/rundeck/exp/webapp/,AVAILABLE}{/var/lib/rundeck/exp/webapp}
2016-12-02 13:02:28.122:INFO:oejs.ServerConnector:main: Started ServerConnector@7a90f33d{HTTP/1.1}{0.0.0.0:8443}
2016-12-02 13:02:28.122:WARN:oejuc.AbstractLifeCycle:main: FAILED ServerConnector@7c7b27c{SSL-HTTP/1.1}{0.0.0.0:8443}: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:264)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.server.Server.doStart(Server.java:303)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:119)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:79)
2016-12-02 13:02:28.131:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.Server@2bd8c8f1: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:264)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.server.Server.doStart(Server.java:303)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:119)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:79)
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:264)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.server.Server.doStart(Server.java:303)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:119)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:79)
