### ISSUE TITLE
After upgrade from 2.6.9 to 2.7.1 Server not starting Correctly

### ISSUE THREAD

**Issue by stubevan** [rundeck/rundeck#2220]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: launcher
* OS Name/version: OSX 10.12.1

**Expected Behavior**

Server starts and normal login page available

**Actual Behavior**

Server starts and schedules executions but log in page reduced as per attachment and logging fails and generates the following log entry

2016-12-03 18:53:06,110 INFO  BootStrap - Rundeck startup finished in 711ms
2016-12-03 18:53:06.271:INFO:/:main: Initializing Spring FrameworkServlet 'grails'
2016-12-03 18:53:06.312:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@73e93c3a{/,file:/usr/local/rundeck/server/exp/webapp/,AVAILABLE}{/usr/local/rundeck/server/exp/webapp}
2016-12-03 18:53:06.370:INFO:oejs.ServerConnector:main: Started ServerConnector@7768ffae{HTTP/1.1}{127.0.0.1:4440}
2016-12-03 18:53:06,607 WARN  ScheduledExecutionService - Attempt to schedule job Backups/Cleanups/Cleanup Web Server -  ebf6eb95-0601-4469-8422-b3d7e130f06a in project Backups, but job execution is disabled.
2016-12-03 18:53:06,631 WARN  ScheduledExecutionService - Attempt to schedule job Cleanups/Cleanup BoppyBadger - Remove old rsync baskups 1b678c5d-27eb-4700-a0c2-3b946eb81ba2 in project Backups, but job execution is disabled.
2016-12-03 18:55:09.164:WARN:oejs.ServletHandler:qtp904808047-67: /assets/rundeck-6815ac306db9d356a79b55faeabe3fbd.css
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: asset.pipeline.AssetPipelineResponseBuilder(java.lang.String, null, null)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1723)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1526)
	at groovy.lang.ExpandoMetaClass.invokeConstructor(ExpandoMetaClass.java:675)
	at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:198)
	at asset.pipeline.grails.AssetPipelineFilter.doFilter(AssetPipelineFilter.groovy:110)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:540)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)

**How to reproduce Behavior**

Start server
![screenshot 2016-12-03 19 05 18](https://cloud.githubusercontent.com/assets/1203716/20861577/7994f95c-b98b-11e6-946d-b7ddd841d9a1.png)

# Enhancement request

(*For enhancements*: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by gschueler** [comment]
try cleaning out your old install, remove the `server/exp` subdirectory.  If you have modified `server/exp/webapp/WEB-INF/web.xml` or `server/exp/webapp/WEB-INF/classes/log4j.properties`, make sure to back those up first.  Then restart the launcher

**Comment by stubevan** [comment]
Hi Greg

Thanks for the swift response …  That’s fixed the look and feel but I still can’t login.  I get the following in the log file.  I’m using plain old flat file logins.   I did have an MD5 password but have also tried returning to plaintext … but that doesn’t work either

Thanks

Stu


2016-12-05 19:15:02.583:WARN:oejj.JAASLoginService:qtp904808047-67: 
javax.security.auth.login.LoginException: unable to find LoginModule class: org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:794)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gschueler** [comment]
hi, please read the Upgrading notes, this is addressed: http://rundeck.org/docs/upgrading/index.html#jetty-embedded-server-was-upgraded-to-9.0.x

**Comment by stubevan** [comment]
The shame :( RTFM properly

My apologies for wasting your time …

Thanks

**Comment by stubevan** [comment]
Great Support - Thanks
