### ISSUE TITLE
Unix Error Start SSL 2.7.1

### ISSUE THREAD

**Issue by charlescoupeau** [rundeck/rundeck#2223]
Hello,

I have again an SSl error with the version 2.7.1 when I start Rundeck.

WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
Exception in thread "main" java.lang.SecurityException: class "javax.servlet.HttpConstraintElement"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.dtolabs.rundeck.RunServer.createWebAppContext(RunServer.java:281)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:111)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:79)

In my profile : 

RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx4096m -Xms4096m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-ldap.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-multiauth}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=${RDECK_HTTPS_PORT:-4443

RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=$RDECK_SERVER_CONFIG/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT}"

My ssl.properties is in the directory /etc/rundeck/ssl why this error?

I removed the parameter -XX:MaxPermSize=256m with java 8

service.log : 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

Thanks,
Charles Coupeau.

**Comment by gschueler** [comment]
How did you install rundeck?

This seems like two different issues:

1. 

> java.lang.SecurityException: class "javax.servlet.HttpConstraintElement"'s signer information does not match signer information of other classes in the same package

I've not seen that before, but Google reveals it might be caused by having multiple jar files for the servlet api.  Did you use the launcher and upgrade in place? perhaps try removing `$RDECK_BASE/server/exp` and relaunching.  Be sure to back up any modified files (log4j.properties, web.xml etc).

2. 

> WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable

This will appear if the `rundeck.ssl.config` system property is not set, *or* the `keystore` property within that config is pointing at an invalid (e.g. missing) file path.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
