### ISSUE TITLE
Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)

### ISSUE THREAD

**Issue by lancepowell** [rundeck/rundeck#2228]
# Bug report

Upgraded to 2.7.1 from 2.6.11, jobs not completing

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: rpm (rpm,deb,war,launcher)
* OS Name/version: CentOS 7

**Expected Behavior**

Jobs finishing successfully. They do complete all the steps but rundeck stays in a running job state

**Actual Behavior**

Job stays running and the log shows:

Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255) ... All node names ... (14155)

rundeck-config.properties:

dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true
quartz.props.threadPool.threadCount = 30

**Comment by lancepowell** [comment]
I also see it do this for FILTER_APPLIED VARCHAR(255) too.

**Comment by jjethwa** [comment]
I'm also having the same issue.  However, my succeeded_node_list column is set to longtext.  I'm using mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

```
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
        at rundeck.services.ReportService.reportExecutionResult(ReportService.groovy:65)
        at rundeck.services.ExecutionService.logExecution(ExecutionService.groovy:843)
        at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2227)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2148)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:509)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:447)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:519)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:162)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:90)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:89)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
        ... 13 more
```

**Comment by lmagstad** [comment]
I am having the same issue.  I found that if I run a job agains a few nodes, it complete successfully.  If the job runs agains 100+ nodes I get this:

2016-12-08 07:54:01,467 [qtp1480010240-17] INFO  grails.app.services.rundeck.services.ScheduledExecutionService - scheduling temp job: TEMP:lmagstad:42582
2016-12-08 07:55:12,101 [quartzScheduler_Worker-4] INFO  grails.app.services.rundeck.services.ExecutionUtilService - Execution successful: 42582 in project XXX
2016-12-08 07:55:12,111 [quartzScheduler_Worker-4] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: value too long for type character varying(255)
2016-12-08 07:55:12,114 [quartzScheduler_Worker-4] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Execution 42582 save result status: caught exception: Hibernate operation: could not execute statement; SQL [n/a]; ERROR: value too long for type character varying(255); nested exception is org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; ERROR: value too long for type character varying(255); nested exception is org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
        at rundeck.services.ReportService.reportExecutionResult(ReportService.groovy:65)
        at rundeck.services.ExecutionService.logExecution(ExecutionService.groovy:843)
        at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2227)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2148)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:509)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:447)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:519)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:162)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:90)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:89)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:363)
        ... 13 more

**Comment by lancepowell** [comment]
Ditto. Only occurs with large amount of nodes.

**Comment by jjethwa** [comment]
Occurs for > 10 nodes on my instance

**Comment by jamieps** [comment]
Rundeck 2.7.2-SNAPSHOT (at 2f5001d) on Tomcat 7

It doesn't look like there is any migration of the existing columns, e.g. on `base_report`, the `succeeded_node_list` column is still `varchar(255)` rather than `longtext` - as it is on `execution`:
```
mysql> describe base_report;
<...>
| failed_node_list    | varchar(255)  | YES  |     | NULL    |                |
| filter_applied      | varchar(255)  | YES  |     | NULL    |                |
| succeeded_node_list | varchar(255)  | YES  |     | NULL    |                |
+---------------------+---------------+------+-----+---------+----------------+
```
Compared to the `execution` table:
```
mysql> describe execution;
+---------------------------+--------------+------+-----+---------+----------------+
| Field                     | Type         | Null | Key | Default | Extra          |
+---------------------------+--------------+------+-----+---------+----------------+
| id                        | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| version                   | bigint(20)   | NO   |     | NULL    |                |
| abortedby                 | varchar(255) | YES  |     | NULL    |                |
| arg_string                | longtext     | YES  |     | NULL    |                |
<...>
| failed_node_list          | longtext     | YES  |     | NULL    |                |
<...>
| succeeded_node_list       | longtext     | YES  |     | NULL    |                |
<...>
```
Then it still fails when it tries to write to the table:
```
ERROR SqlExceptionHelper: Data truncation: Data too long for column 'failed_node_list' at row 1                                                                                                                                                                             
ERROR ExecutionJob: Execution 1091 save result status: caught exception: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'failed_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'failed_node_list' at row 1
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'failed_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'failed_node_list' at row 1
>...at rundeck.services.ReportService.reportExecutionResult(ReportService.groovy:65)
>...at rundeck.services.ExecutionService.logExecution(ExecutionService.groovy:843)
>...at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2227)
>...at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2148)
>...at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:509)
>...at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:447)
>...at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:519)
>...at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:162)
>...at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:90)
>...at com.codahale.metrics.Timer.time(Timer.java:99)
>...at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:89)
>...at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
>...at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```
It is possible to just `ALTER COLUMN` to change the datatype but I thought the migration might have been handled automatically?

**Comment by gschueler** [comment]
@jamieps there is no automatic migration (yet), sorry

**Comment by rophy** [comment]
So this is how to fix it manually, right?  Am I missing any column?

```
alter table base_report change column filter_applied filter_applied longtext;
alter table base_report change column succeeded_node_list succeeded_node_list  longtext;
alter table base_report change column failed_node_list failed_node_list  longtext;
```

**Comment by jtobard** [comment]
@rophy that's it, just those fields

**Comment by rophy** [comment]
thanks @jtobard and all, works perfectly for my env (MySQL).

**Comment by aristosv** [comment]
@rophy 
can you explain how to run these commands to fix the issue?
I'm running rundeck on debian.
thanks

**Comment by ameissnersofi** [comment]
@gschueler i installed with the jar and for some reason don't have a service.log at ${RDECK_BASE}/server/logs

**Comment by gschueler** [comment]
@ameissnersofi if you run the launcher jar there is a "rundeck.log"file  and other logging on stdout

**Comment by ameissnersofi** [comment]
@gschueler `rundeck.log` is littered with 

```
2016-12-30 10:00:00,188 [quartzScheduler_Worker-7] ERROR org.quartz.core.JobRunShell - Job Monitors:Consul_Monitor:STALLS/PYTHON.19341:Consul_Monitor threw an unhandled Exception: 
rundeck.services.ExecutionServiceException: Job "Consul_Monitor" {{Job ac0c4097-0f43-494f-ab42-d7fdbb3f8c9d}} is currently being executed {{Execution 500227}}
	at rundeck.services.ExecutionService.createExecution(ExecutionService.groovy:1965)
	at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:291)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:111)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:90)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:89)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2016-12-30 10:00:00,193 [quartzScheduler_Worker-7] ERROR org.quartz.core.ErrorLogger - Job (Monitors:Consul_Monitor:STALLS/PYTHON.19341:Consul_Monitor threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: rundeck.services.ExecutionServiceException: Job "Consul_Monitor" {{Job ac0c4097-0f43-494f-ab42-d7fdbb3f8c9d}} is currently being executed {{Execution 500227}}]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: rundeck.services.ExecutionServiceException: Job "Consul_Monitor" {{Job ac0c4097-0f43-494f-ab42-d7fdbb3f8c9d}} is currently being executed {{Execution 500227}}
	at rundeck.services.ExecutionService.createExecution(ExecutionService.groovy:1965)
	at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:291)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:111)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:90)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:89)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
```

**Comment by rophy** [comment]
@aristosv those are SQL statements, which you run in CLI of your database (MySQL in my case).

**Comment by jasonkeithscott** [comment]
The info in this thread was helpful, but I did not have MySQL. If you're using H2, you can still fix this.

`# see if you're using H2
$ grep h2 /etc/rundeck/rundeck-config.properties
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true;TRACE_LEVEL_FILE=4

# stop rundeckd however your setup requires

# connect to the h2 db file, change paths as your config specifies. 'sa' is the default user, with no password.
java -cp /var/lib/rundeck/h2-1.4.193.jar org.h2.tools.Shell -url jdbc:h2:file:/var/lib/rundeck/data/rundeckdb -user sa

# Alter the columns
ALTER TABLE BASE_REPORT ALTER COLUMN FAILED_NODE_LIST LONGTEXT;
ALTER TABLE BASE_REPORT ALTER COLUMN FILTER_APPLIED LONGTEXT;
ALTER TABLE BASE_REPORT ALTER COLUMN SUCCEEDED_NODE_LIST LONGTEXT;

# check column types
SHOW COLUMNS FROM BASE_REPORT;
FIELD               | TYPE                | NULL | KEY | DEFAULT
...
FAILED_NODE_LIST    | CLOB(2147483647)    | YES  |     | NULL
FILTER_APPLIED      | CLOB(2147483647)    | YES  |     | NULL
SUCCEEDED_NODE_LIST | CLOB(2147483647)    | YES  |     | NULL

# restart rundeckd
`

**Comment by aristosv** [comment]
root@rundeck:~# clear
root@rundeck:~# grep h2 /etc/rundeck/rundeck-config.properties
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true
root@rundeck:~# java -cp /var/lib/rundeck/h2-1.4.193.jar org.h2.tools.Shell -url jdbc:h2:file:/var/lib/rundeck/data/rundeckdb -user sa
Error: Could not find or load main class org.h2.tools.Shell

**Comment by gschueler** [comment]
@aristosv `/var/lib/rundeck/h2-1.4.193.jar` is probably not the right path

**Comment by aristosv** [comment]
actually that jar file doesn't exist in that path at all.

**Comment by jasonkeithscott** [comment]
@aristosv `find / -name h2*.jar` should help you locate it. Else grab a copy from http://repo2.maven.org/maven2/com/h2database/h2/

**Comment by aristosv** [comment]
found the file. New problem now.

root@rundeck:~# java -cp /var/lib/rundeck//var/lib/rundeck/exp/webapp/WEB-INF/lib/h2-1.4.193.jar org.h2.tools.Shell -url jdbc:h2:file:/var/lib/rundeck/data/rundeckdb -user sa
Error: Could not find or load main class org.h2.tools.Shell

**Comment by methom90wh** [comment]
Here's the code for anyone looking to convert these columns that has an Oracle data source.

These commands will convert the three columns from VARCHAR2 to CLOB and will migrate data as well.

-- Add the new COLB columns with temporary names
ALTER TABLE BASE_REPORT ADD (TMP_FAILED_NODE_LIST CLOB, TMP_FILTER_APPLIED CLOB, TMP_SUCCEEDED_NODE_LIST CLOB);

-- Migrate the data from the VARCHAR2 to CLOB
UPDATE BASE_REPORT 
   SET TMP_FAILED_NODE_LIST=FAILED_NODE_LIST
      ,TMP_FILTER_APPLIED=FILTER_APPLIED
      ,TMP_SUCCEEDED_NODE_LIST=SUCCEEDED_NODE_LIST;
COMMIT;

-- Drop the VARCHAR2 columns (check the update has worked first!)
ALTER TABLE BASE_REPORT DROP (FAILED_NODE_LIST, FILTER_APPLIED, SUCCEEDED_NODE_LIST);

-- Finally rename the CLOB columns to the correct column names
ALTER TABLE BASE_REPORT RENAME COLUMN TMP_FAILED_NODE_LIST TO FAILED_NODE_LIST;
ALTER TABLE BASE_REPORT RENAME COLUMN TMP_FILTER_APPLIED TO FILTER_APPLIED;
ALTER TABLE BASE_REPORT RENAME COLUMN TMP_SUCCEEDED_NODE_LIST TO SUCCEEDED_NODE_LIST;

Hope this helps.

**Comment by n4rk0o** [comment]
Hello, I had the same behavior with the native H2 database.

I use rundeck on a Windows Server 2012 R2 with the launcher and I chose to use MSSQL as database server.

I modified the three columns and everything is working like a charm now!

**Comment by DerfOh** [comment]
Still having this problem with the H2 database despite applying the changes mentioned by @jasonkeithscott. Is there any other columns that may need to be edited?

**Comment by methom90wh** [comment]
I only changed the 3 columns in my post above and have had no issues since.
