### ISSUE TITLE
import scm job fails when trying to import rundeck 2.7.0 job into 2.6.11 server

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#2252]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: rpm
* OS Name/version: centos 7

**Expected Behavior**

Import scm job should success.

___

**Actual Behavior**

Import scm job fails with error:

```
Request: /project/GSSC/scm/import/performActionSubmit?chosenTrackedItem=common%2Fwep%2FAdd+Members+to+Project.yaml&submit=Import&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&_chosenTrackedItem=&actionId=import-all&allJobs=&SYNCHRONIZER_URI=%2Fproject%2FGSSC%2Fjob%2F5d5decfc-407e-4289-a469-f297256340ee%2Fscm%2Fimport%2FperformAction&SYNCHRONIZER_TOKEN=cccaf71760889a6fc75ae06f8335fc224fb0a7bac1b81ffa5888356978f10b62
Message: possible nonthreadsafe access to session 
Caused by: possible nonthreadsafe access to session 
Class: ScmController 
At Line: [1202] 
Code Snippet:
```

Stake Trace:
```
org.hibernate.AssertionFailure: possible nonthreadsafe access to session
	at rundeck.controllers.ScmController.performActionSubmit(ScmController.groovy:1202)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)
```
___

**How to reproduce Behavior**

1. Export a job in rundeck 2.7.0 to git as yaml
2. Manually update the yaml file to remove `nodeFilterEditable: true` (since this did not exist in 2.6)
3. In rundeck 2.6.11 server, perform scm import, select the target job (preserve uuid)

**Comment by rophy** [comment]
I found the root cause. In rundeck 2.7, node selection strategy `step first` is renamed to `step-first` and will reflect in yaml if you edit and save the job:

```diff
-    strategy: sequential
+    strategy: step-first
```

Probably not a real problem, though it took me a while to figure out.
