### ISSUE TITLE
Error scm git commit job 

### ISSUE THREAD

**Issue by daikirinet** [rundeck/rundeck#2294]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1-1
* install type: deb
* OS Name/version: Debian 7
* JVM : Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
* Rundeck Datasource: mysql
**Expected Behavior**

___

**Actual Behavior**
After activating git for scm, I have the following message when committing (on all jobs)

* An Error Occurred : org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction$_getInputView_closure1

* Error Details :Request: /project/AS_Pvo/job/6b535a9d-f79d-4b6e-ab61-aa711f101f1a/scm/export/performAction?actionId=job-commit
Message: org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction$_getInputView_closure1 
Caused by: org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction$_getInputView_closure1 
Class: ScmController 
At Line: [1050] 

* Stack Trace :
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [performAction] of controller [rundeck.controllers.ScmController]  caused exception: Runtime error executing action
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 44 more
Caused by: java.lang.reflect.InvocationTargetException
	... 44 more
Caused by: java.lang.NoClassDefFoundError: org/rundeck/plugin/scm/git/exp/actions/CommitJobsAction$_getInputView_closure1
	at org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction.getInputView(CommitJobsAction.groovy:46)
	at org.rundeck.plugin.scm.git.GitExportPlugin.getInputViewForAction(GitExportPlugin.groovy:132)
	at rundeck.services.ScmService.getExportInputView(ScmService.groovy:226)
	at rundeck.services.ScmService.getInputView(ScmService.groovy:215)
	at rundeck.controllers.ScmController.performAction(ScmController.groovy:1050)

___

...

**Comment by gschueler** [comment]
I think this is related to some issues found with jasypt plugin: https://github.com/rundeck/rundeck/issues/1785#issuecomment-265814468
