### ISSUE TITLE
WebUI is stuck when viewing job report for > 3000 nodes

### ISSUE THREAD

**Issue by n4rk0o** [rundeck/rundeck#2313]
# Bug report

(Note: Please fill in the blank `___` about your rundeck installation below. You can remove this line.)

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: launcher
* OS Name/version: Windows 2012 R2
* JVM : -Xms1024m -Xmx2048m

**Expected Behavior**

Reports for a job execution with almost 3000 nodes.

**Actual Behavior**

The reports page is very slow and my web browser freeze and is stuck.

**How to reproduce Behavior**

Just check a report on GUI for a job execution with almost 3000 nodes.

**Extra**

The job execution is fast regarding Rundeck engine but the WEB UI is very slow.

I have this kind of error when I browse the execution:

```
java.io.IOException: An established connection was aborted by the software in yo
ur host machine
        at sun.nio.ch.SocketDispatcher.writev0(Native Method)
        at sun.nio.ch.SocketDispatcher.writev(Unknown Source)
        at sun.nio.ch.IOUtil.write(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:167)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:335)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:125
)
        at org.eclipse.jetty.server.HttpConnection$ContentCallback.process(HttpC
onnection.java:802)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.ja
va:81)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:373)

        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:65
4)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:684)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:198)
        at java.io.ByteArrayOutputStream.writeTo(Unknown Source)
        at org.eclipse.jetty.server.Utf8HttpWriter.write(Utf8HttpWriter.java:183
)
        at java.io.PrintWriter.write(Unknown Source)
        at org.codehaus.groovy.grails.web.util.StreamCharBuffer$AllocatedBuffer.
writeTo(StreamCharBuffer.java:1606)
        at org.codehaus.groovy.grails.web.util.StreamCharBuffer.writeToImpl(Stre
amCharBuffer.java:649)
        at org.codehaus.groovy.grails.web.util.StreamCharBuffer.writeTo(StreamCh
arBuffer.java:612)
        at org.codehaus.groovy.grails.web.util.StreamCharBuffer.flushToConnected
(StreamCharBuffer.java:1027)
        at org.codehaus.groovy.grails.web.util.StreamCharBuffer.access$1300(Stre
amCharBuffer.java:251)
        at org.codehaus.groovy.grails.web.util.StreamCharBuffer$StreamCharBuffer
Writer.flushWriter(StreamCharBuffer.java:1306)
        at org.codehaus.groovy.grails.web.util.StreamCharBuffer$StreamCharBuffer
Writer.flush(StreamCharBuffer.java:1334)
        at org.codehaus.groovy.grails.web.util.GrailsPrintWriter.flush(GrailsPri
ntWriter.java:172)
        at org.codehaus.groovy.grails.web.util.GrailsPrintWriterAdapter.flush(Gr
ailsPrintWriterAdapter.java:122)
        at org.codehaus.groovy.grails.web.sitemesh.GrailsRoutablePrintWriter.flu
sh(GrailsRoutablePrintWriter.java:259)
        at java.io.FilterWriter.flush(Unknown Source)
        at org.codehaus.groovy.grails.web.util.GrailsPrintWriter.flush(GrailsPri
ntWriter.java:172)
        at org.codehaus.groovy.grails.web.pages.GroovyPageOutputStack$GroovyPage
ProxyWriterGroup.flushActive(GroovyPageOutputStack.java:184)
        at org.codehaus.groovy.grails.web.pages.GroovyPageOutputStack$GroovyPage
ProxyWriterGroup.activateWriter(GroovyPageOutputStack.java:177)
        at org.codehaus.groovy.grails.web.pages.GroovyPageOutputStack$GroovyPage
ProxyWriterGroup.reset(GroovyPageOutputStack.java:172)
        at org.codehaus.groovy.grails.web.pages.GroovyPageOutputStack.pop(Groovy
PageOutputStack.java:372)
        at org.codehaus.groovy.grails.web.pages.GroovyPage.cleanup(GroovyPage.ja
va:259)
        at org.codehaus.groovy.grails.web.pages.GroovyPageWritable.doWriteTo(Gro
ovyPageWritable.java:220)
        at org.codehaus.groovy.grails.web.pages.GroovyPageWritable.writeTo(Groov
yPageWritable.java:128)
        at org.codehaus.groovy.grails.web.servlet.view.GroovyPageView.renderTemp
late(GroovyPageView.java:71)
        at org.codehaus.groovy.grails.web.servlet.view.AbstractGrailsView.render
WithinGrailsWebRequest(AbstractGrailsView.java:49)
        at org.codehaus.groovy.grails.web.servlet.view.AbstractGrailsView.render
MergedOutputModel(AbstractGrailsView.java:33)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView
.java:267)
        at org.codehaus.groovy.grails.web.sitemesh.SpringMVCViewDecorator.render
(SpringMVCViewDecorator.java:69)
        at org.codehaus.groovy.grails.web.sitemesh.GrailsLayoutView.renderTempla
te(GrailsLayoutView.java:60)
        at org.codehaus.groovy.grails.web.servlet.view.AbstractGrailsView.render
WithinGrailsWebRequest(AbstractGrailsView.java:49)
        at org.codehaus.groovy.grails.web.servlet.view.AbstractGrailsView.render
MergedOutputModel(AbstractGrailsView.java:33)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView
.java:267)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherSe
rvlet.java:1221)
        at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDisp
atch(GrailsDispatcherServlet.java:391)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:852)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696
)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1515)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(Pag
eFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter
.java:63)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(D
elegatingFilterProxy.java:344)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(Delegat
ingFilterProxy.java:261)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:136)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
        at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequest
ForUrlMappingInfo(UrlMappingUtils.java:178)
        at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequest
ForUrlMappingInfo(UrlMappingUtils.java:144)
        at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequest
ForUrlMappingInfo(UrlMappingUtils.java:135)
        at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFil
terInternal(UrlMappingsFilter.java:216)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doF
ilterInternal(GrailsWebRequestFilter.java:69)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilte
rInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(Abst
ractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.jav
a:74)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern
al(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(D
elegatingFilterProxy.java:344)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(Delegat
ingFilterProxy.java:261)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:529)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.jav
a:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConn
ection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:532)
        at java.lang.Thread.run(Unknown Source)
```

# Enhancement request

...

**Comment by n4rk0o** [comment]
I'm trying with RHEL 7.2 and mariaDB and have the same behavior.

According to https://github.com/rundeck/rundeck/issues/2228, I modified the columns table on the database rundeck but that is not better.

**Comment by wreyes94** [comment]
@n4rk0o Hey, My team ran into the same issue. We are trying to execute against 20,000+ nodes and currently using version 2.10.5 with mariadb. Do you have a good work around that you might have used?

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
