### ISSUE TITLE
Jobs get stuck in running state even after completed, impossible to kill

### ISSUE THREAD

**Issue by bluikko** [rundeck/rundeck#2381]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.7.3-1
* install type: rpm
* OS Name/version: CentOS 6.8 x64 fully updated with java-1.8.0-openjdk-headless-1.8.0.121-0.b13.el6_8.x86_64

**Expected Behavior**
Job stops after executed on all nodes.

**Actual Behavior**
The job is kept in running state even after all nodes have been executed. The job runs completely to the end, it shows a summary of failed nodes at the end.

It seems to happen at least in two cases:
- Every time when an ad-hoc command is run
- If the job has failures

This started in 2.7.0 or 2.7.1 and got worse in 2.7.3. Prior to 2.7.3 it was possible to go to "activity" and then kill the job, now it is impossible and instead of killing the job an error is displayed:
"Failed to kill Job: The request did not include a valid token, or the token has expired. Please try your request again"

Now I have several jobs in this stuck state and cannot run those jobs unless I change the setting to allow multiple executions. Restarting the server did not help and the jobs are still stuck in "running" state.

**How to reproduce Behavior**
Run any ad-hoc command or a job that fails on at least one node.

**Comment by molkmeister** [comment]
has there been any update on this problem. Just came across it now.
Seeing it on jobs were I am trying to run against multiple nodes at the same time. The job gets to the end but doesnt complete.
Try to kill the job but then cant

**Comment by nilroy** [comment]
I am facing similar issue with normal scheduled job that run some command on a remote node. And then the job get stucked after ending and can't kill the job from the UI or throgh API. It always shows  token invalid whereas I am the admin user and having full access.

**Comment by bluikko** [comment]
I just ran a few ad-hoc commands that completed normally. So the commands do not get stuck 100% of executions. I have not managed to find an exact pattern to what is happening.

For those having similar issues: please include more information like your Rundeck, Java, OS version etc.

**Comment by nilroy** [comment]
My rundeck version is 2.7.3-1, OS ubuntu 14.04 and JAVA openjdk version "1.8.0_111"

**Comment by nilroy** [comment]
@gschueler please help

**Comment by molkmeister** [comment]
@nilroy @bluikko 
I am running 
Rundeck 2.7.1-1    - install type: rpm
CentOS Linux release 7.3.1611 (Core)
openjdk version "1.8.0_121"

**Comment by gschueler** [comment]
this message "The request did not include a valid token, or the token has expired. Please try your request again" happens if the "synchronizer token" submitted in the form is not valid...it might happen if you click the Abort job button a second time after it fails the first time.

I'm not sure of the cause.  If you upgraded from 2.6.x to 2.7.x you might be hitting a DB schema problem.

Please send:

* `/var/log/rundeck/service.log` content if there are errors in the log
* any errors seen in the javascript console of your browser after you encounter the "token" error

**Comment by dpomnean** [comment]
#2228 Fixed the issue for me by modifying the 3 columns for MySQL.

**Comment by bluikko** [comment]
The three columns from #2228 were wrong type for me too. Using h2. Will update here if the jobs still not hang or close this bug if the error does not happen anymore.

**Comment by nilroy** [comment]
@gschueler 

I tried the request multiple times and everytime it failed with the same error. Did not find any interesting log. But I upgraded from 2.6.9 to 2.7.3. I shall try the fix in https://github.com/rundeck/rundeck/issues/2228

**Comment by nilroy** [comment]
@gschueler 

Seems like the the db columns are already fixed somehow

```
mysql> describe base_report;
+---------------------+---------------+------+-----+---------+----------------+
| Field               | Type          | Null | Key | Default | Extra          |
+---------------------+---------------+------+-----+---------+----------------+
| id                  | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| version             | bigint(20)    | NO   |     | NULL    |                |
| action_type         | varchar(256)  | NO   |     | NULL    |                |
| author              | varchar(255)  | NO   |     | NULL    |                |
| ctx_name            | varchar(255)  | YES  |     | NULL    |                |
| ctx_project         | varchar(255)  | NO   |     | NULL    |                |
| ctx_type            | varchar(255)  | YES  |     | NULL    |                |
| date_completed      | datetime      | NO   |     | NULL    |                |
| date_started        | datetime      | NO   |     | NULL    |                |
| mapref_uri          | varchar(255)  | YES  |     | NULL    |                |
| message             | longtext      | NO   |     | NULL    |                |
| node                | varchar(255)  | YES  |     | NULL    |                |
| report_id           | varchar(3072) | YES  |     | NULL    |                |
| status              | varchar(256)  | NO   |     | NULL    |                |
| tags                | varchar(255)  | YES  |     | NULL    |                |
| title               | longtext      | NO   |     | NULL    |                |
| class               | varchar(255)  | NO   |     | NULL    |                |
| aborted_by_user     | varchar(255)  | YES  |     | NULL    |                |
| adhoc_execution     | bit(1)        | YES  |     | NULL    |                |
| adhoc_script        | longtext      | YES  |     | NULL    |                |
| ctx_command         | varchar(255)  | YES  |     | NULL    |                |
| ctx_controller      | varchar(255)  | YES  |     | NULL    |                |
| jc_exec_id          | varchar(255)  | YES  |     | NULL    |                |
| jc_job_id           | varchar(255)  | YES  |     | NULL    |                |
| failed_node_list    | longtext      | YES  |     | NULL    |                |
| filter_applied      | longtext      | YES  |     | NULL    |                |
| succeeded_node_list | longtext      | YES  |     | NULL    |                |
+---------------------+---------------+------+-----+---------+----------------+
27 rows in set (0.01 sec)

mysql> describe execution;
+---------------------------+--------------+------+-----+---------+----------------+
| Field                     | Type         | Null | Key | Default | Extra          |
+---------------------------+--------------+------+-----+---------+----------------+
| id                        | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| version                   | bigint(20)   | NO   |     | NULL    |                |
| abortedby                 | varchar(255) | YES  |     | NULL    |                |
| arg_string                | longtext     | YES  |     | NULL    |                |
| cancelled                 | bit(1)       | NO   |     | NULL    |                |
| date_completed            | datetime     | YES  |     | NULL    |                |
| date_started              | datetime     | YES  |     | NULL    |                |
| do_nodedispatch           | bit(1)       | YES  |     | NULL    |                |
| failed_node_list          | longtext     | YES  |     | NULL    |                |
| filter                    | longtext     | YES  |     | NULL    |                |
| loglevel                  | varchar(255) | YES  |     | NULL    |                |
| node_exclude              | longtext     | YES  |     | NULL    |                |
| node_exclude_name         | longtext     | YES  |     | NULL    |                |
| node_exclude_os_arch      | longtext     | YES  |     | NULL    |                |
| node_exclude_os_family    | longtext     | YES  |     | NULL    |                |
| node_exclude_os_name      | longtext     | YES  |     | NULL    |                |
| node_exclude_os_version   | longtext     | YES  |     | NULL    |                |
| node_exclude_precedence   | bit(1)       | YES  |     | NULL    |                |
| node_exclude_tags         | longtext     | YES  |     | NULL    |                |
| node_include              | longtext     | YES  |     | NULL    |                |
| node_include_name         | longtext     | YES  |     | NULL    |                |
| node_include_os_arch      | longtext     | YES  |     | NULL    |                |
| node_include_os_family    | longtext     | YES  |     | NULL    |                |
| node_include_os_name      | longtext     | YES  |     | NULL    |                |
| node_include_os_version   | longtext     | YES  |     | NULL    |                |
| node_include_tags         | longtext     | YES  |     | NULL    |                |
| node_keepgoing            | bit(1)       | YES  |     | NULL    |                |
| node_rank_attribute       | varchar(255) | YES  |     | NULL    |                |
| node_rank_order_ascending | bit(1)       | YES  |     | NULL    |                |
| node_threadcount          | int(11)      | YES  |     | NULL    |                |
| orchestrator_id           | bigint(20)   | YES  | MUL | NULL    |                |
| outputfilepath            | longtext     | YES  |     | NULL    |                |
| project                   | varchar(255) | NO   |     | NULL    |                |
| retry                     | longtext     | YES  |     | NULL    |                |
| retry_attempt             | int(11)      | YES  |     | NULL    |                |
| retry_execution_id        | bigint(20)   | YES  | MUL | NULL    |                |
| scheduled_execution_id    | bigint(20)   | YES  | MUL | NULL    |                |
| server_nodeuuid           | varchar(36)  | YES  |     | NULL    |                |
| status                    | varchar(255) | YES  |     | NULL    |                |
| succeeded_node_list       | longtext     | YES  |     | NULL    |                |
| timed_out                 | bit(1)       | YES  |     | NULL    |                |
| timeout                   | longtext     | YES  |     | NULL    |                |
| rduser                    | varchar(255) | NO   |     | NULL    |                |
| will_retry                | bit(1)       | YES  |     | NULL    |                |
| workflow_id               | bigint(20)   | YES  | MUL | NULL    |                |
| execution_type            | varchar(30)  | YES  |     | NULL    |                |
| node_filter_editable      | bit(1)       | YES  |     | NULL    |                |
+---------------------------+--------------+------+-----+---------+----------------+
```

**Comment by nilroy** [comment]
For me the problem does not come always. So its hard to reproduce also in my environment :(.

**Comment by ben-garside** [comment]
@nilroy try using a long filter (with lots of nodes), that should cause the error as it is to do with the length of the data being put in to ``succeeded_node_list``, ``failed_node_list`` and ``filter_applied`` in the ``base_report`` table

**Comment by bluikko** [comment]
I have seen no more stuck jobs after the fix in #2228 by alter 3 columns.

**Comment by dpomnean** [comment]
After a few jobs running 200+ nodes, I have not seen any errors since the change yesterday.

**Comment by LoovtO** [comment]
I too have this issue but stayed with Rundeck 2.7.2-1 so I'm still able to kill remaining processes. I'm using Centos 6.7 and OpenJDK 1.7.0_131.
I upgraded from Rundeck 2.6 and issues started after 2.7.1 upgrade.
I tried #2228 alter columns solution with no progress. Anyway I encounter this behaviour on some jobs with only one target.
I don't see pertinent errors in service.log.
Not sure if I am in the same situation than others because I encounter an exception in jobs logs (from the moment Rundeck is leaving the server to the first Rundeck class) : 

    ^2017-04-09T13:25:14Z|nodeend||{node=myserver|step=1|stepctx=1|user=myuser}|^
    ^2017-04-09T13:25:14Z||VERBOSE|{node=myserver|step=1|stepctx=1|user=myuser}|Disconnecting from myserver port 22^
    
    ^2017-04-09T13:25:14Z||VERBOSE|{node=localhost|step=1|stepctx=1|user=rundeckuser}|[workflow] finishExecuteNodeStep(myserver): NodeDispatch: Succeeded^
    ^2017-04-09T13:25:14Z||VERBOSE|{node=localhost|step=1|stepctx=1|user=rundeckuser}|1: Workflow step finished, result: Dispatch successful (1 nodes)^
    
    ^2017-04-09T13:25:14Z||VERBOSE|{node=myserver|step=1|stepctx=1|user=myuser}|Caught an exception, leaving main loop due to Socket closed^
    ^2017-04-09T13:25:14Z|stepend||{node=localhost|step=1|stepctx=1|user=rundeckuser}|^
    
    ^2017-04-09T13:25:14Z||VERBOSE|{node=localhost|user=rundeckuser}|[workflow] Finish step: 1,NodeDispatch^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|Exception in thread "pool-13147-thread-1" java.lang.IllegalStateException: output was closed^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)^
    ^2017-04-09T13:25:14Z||ERROR|{node=localhost|user=rundeckuser}|        at com.dtolabs.rundeck.app.internal.logging.FSStreamingLogWriter.addEven

When this happens, all steps are OK in the report tab, but the job will not finish until I kill it.
I checked system load, tried to raise quartz.props.threadPool.threadCount, watched opened files number and many others things but I can't figure the reason for this behaviour.

I can open another thread if you consider this not directly linked.

**Comment by LoovtO** [comment]
@bluikko @nilroy Did you encounter this kind of error since April ?
I still have it even after altering the 3 columns. Maybe I have to be in 2.7.3 with good columns setting but I'd like to have your feedback after one month before upgrading...

**Comment by nilroy** [comment]
@LoovtO I am running 2.7.3 and still seeing this thing from time to time

**Comment by vinillum** [comment]
@LoovtO We are having the same issue. Our jobs is scheduled to run on a single node (localhost) and we can see that the job has finished in the logs, and it's no longer in the "ps" output, but the job just won't finish - we have to manually kill it. We are running 2.8.2 and we have applied the database changes in MySQL.

**Comment by vinillum** [comment]
Just killed the job and it finished with the following:
`11:30:36			java.lang.IllegalStateException: output was closed
11:30:36				at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
11:30:36				at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
11:30:36				at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
11:30:36				at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
11:30:36				at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
11:30:36				at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
11:30:36				at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
11:30:36				at com.dtolabs.rundeck.app.internal.logging.FSStreamingLogWriter.addEvent(FSStreamingLogWriter.groovy:72)
11:30:36				at sun.reflect.GeneratedMethodAccessor413.invoke(Unknown Source)
11:30:36				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:30:36				at java.lang.reflect.Method.invoke(Method.java:498)
11:30:36				at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
11:30:36				at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
11:30:36				at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
11:30:36				at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
11:30:36				at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
11:30:36				at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
11:30:36				at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
11:30:36				at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:166)
11:30:36				at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:174)
11:30:36				at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:181)
11:30:36				at rundeck.services.logging.MultiLogWriter.addEvent(MultiLogWriter.groovy:45)
11:30:36				at com.dtolabs.rundeck.core.logging.StreamingLogWriter$addEvent$1.call(Unknown Source)
11:30:36				at rundeck.services.logging.LoglevelThresholdLogWriter.addEvent(LoglevelThresholdLogWriter.groovy:38)
11:30:36				at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
11:30:36				at com.dtolabs.rundeck.core.logging.ContextLogWriter.verbose(ContextLogWriter.java:54)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.log(ContextualExecutionListener.java:96)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListenerImpl.log(WorkflowExecutionListenerImpl.java:45)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.log(ContextualExecutionListener.java:60)
11:30:36				at com.dtolabs.rundeck.core.execution.ExecutionListener$log$1.call(Unknown Source)
11:30:36				at com.dtolabs.rundeck.app.internal.workflow.MultiWorkflowExecutionListener.log(MultiWorkflowExecutionListener.groovy:124)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor$1.onEvent(EngineWorkflowExecutor.java:391)
11:30:36				at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:276)
11:30:36				at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:269)
11:30:36				at com.dtolabs.rundeck.core.rules.WorkflowEngine.processOperations(WorkflowEngine.java:219)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.executeWorkflowImpl(EngineWorkflowExecutor.java:306)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:317)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor$DispatchedWorkflow.dispatch(NodeFirstWorkflowExecutor.java:383)
11:30:36				at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:118)
11:30:36				at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:64)
11:30:36				at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:162)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWFSectionNodeDispatch(NodeFirstWorkflowExecutor.java:189)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:110)
11:30:36				at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:317)
11:30:36				at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
11:30:36			Exception: class java.lang.IllegalStateException: output was closed
11:30:36			output was closed
`

**Comment by sdepablos** [comment]
@LoovtO @nilroy @vinillum are you using any kind of notification plugin? We found that in our case it happened when trying to send a notification to Datadog. If for any reason there was a problem with the connection, an as per default the URL Java object waits forever, the connection was never closed and the job got stuck indefinitely. Here's the change we did in the Datadog plugin https://github.com/ulabox/rundeck-datadog-monitoring-plugin/commit/d5d9b8f7a5cfe717d584d1ed286956ff727a6c23

**Comment by LoovtO** [comment]
Wasn't here for a while but this issue was resolved on our side after 2.10.x upgrade.
@nilroy Can you tell us if it has been resolved on your side too ?

**Comment by hemraj43** [comment]
i am facing the same issue in rundeck 2.9.2
java version "1.8.0_141"
install type rpm

**Comment by yogeshkumark** [comment]
we are facing the same issue on the rundeck2.9.2 . 
The jobs were completed less than 1 min. Still the rundeck show the status as running.

**Comment by PabloLemos** [comment]
I have the 3.3.7 version and the same is true for me. Work completed correctly in all the nodes (11) but the rundeck task is not finished and remains hanging infinitely with no possibility of removing it.
I tried to set a timeout in the job definition but it doesn't work either.

<img width="1175" alt="Captura de pantalla 2021-01-13 a las 13 43 19" src="https://user-images.githubusercontent.com/353683/104454012-8b4d5d00-55a5-11eb-816a-eda539382be8.png">

On all machines I get the message:
```
[SaltRemoteCmdNodeStep]: result code: 0
[workflow] finishExecuteNodeStep(d1sajava134.srv.gva.es): NodeDispatch: Step successful

```
I have found that if I reduce the number of machines to 10, all the tasks that I have subsequently launched will be completed by rundeck.

<img width="1177" alt="Captura de pantalla 2021-01-13 a las 13 46 05" src="https://user-images.githubusercontent.com/353683/104454206-cbacdb00-55a5-11eb-904b-5249fbf9e5d1.png">

Thanks a lot

**Comment by mcaltabiano** [comment]
Same here Rundeck 3.1.2-20190927.

**Comment by PabloLemos** [comment]
I don't know if anyone is working on this problem but it seems to persist between versions since 2.7.3. I see that this is marked as an enhancement but it really is a problem, right now I have to group my works into groups of 10 machines to avoid getting hang out with no possibility of removal.

Thank you

**Comment by PabloLemos** [comment]
Mention that the problem only occurs when you generate a job, in the command execution module the problem is not reproduced finishing the execution correctly:

<img width="1146" alt="Captura de pantalla 2021-01-20 a las 6 03 43" src="https://user-images.githubusercontent.com/353683/105129681-e3281e80-5ae5-11eb-806d-fce6cd69c8b5.png">

If we run it as a job on the same machines the job does not end and cannot be killed
<img width="1171" alt="Captura de pantalla 2021-01-20 a las 6 05 27" src="https://user-images.githubusercontent.com/353683/105129733-fd61fc80-5ae5-11eb-8ead-5e68eac4ed1b.png">

If we reduce the number of machines below 10 the job ends correctly:
<img width="1167" alt="Captura de pantalla 2021-01-20 a las 6 10 09" src="https://user-images.githubusercontent.com/353683/105129849-3c904d80-5ae6-11eb-9cc0-ac3a1685a198.png">

Can someone please check these problems?

Thank you

**Comment by PabloLemos** [comment]
Note that in the recently released version 3.3.8 the same thing is still happening; I have succeeded in expanding to 11 hosts where I can launch the job but if I increase the number of hosts the job stays stuck in running state even after completed.

**Comment by umomany** [comment]
I see this is still happening as well, reproduced on version 3.3.7
multiple jobs stuck in running state after completion and can't be killed

**Comment by ThaSami** [comment]
still happening on 3.3.10

**Comment by PabloLemos** [comment]
I have additional information; because the server where rundeck resided was a redhat enterprise server version 6 I have taken the opportunity to migrate both the operating system and rundeck and set up a backend with postgres instead of H2.

With all this I was able to create jobs against 101 nodes without any problems. 

It should be noted that the version I had of rundeck had been upgraded from version 2.7. Now I have done a clean install.

**Comment by yogeshkumark** [comment]
Hi,

 I have not seen any kind of issues while migrating the jobs . Better do
the export and import of jobs backup. Which will fix the problem.

YOGESH KUMAR
(09884343891)

A computer is like air conditioning: it becomes useless when you open
windows.
<-Fighting 4 Freedom->

**Comment by LMAdrien** [comment]
@sdepablos I confirm. I had forgotten the email notification and I use local postfix relay.  Jobs was stuck and when I restarting postfix all jobs are done immediately. Should be interesting to send notification async of jobs or a timeout settings. After updated settings of  postfix all works fine.

Thanks @sdepablos

Rundeck: 3.3.9
JVM  1.8.0_161
OS: Debian 10

**Comment by sdepablos** [comment]
@LMAdrien you're welcome

**Comment by menicolas89** [comment]
I just ran into this issue again, no kill button and the job is stuck not doing anything. This happened after a crash.
In my case I resolved it by updating Rundeck's SQL table "execution"

update [mydb].[dbo].[execution] set [status]= 'succeeded' where id = myexecutionid
update [mydb].[dbo].[execution] set [date_completed]= '2022-06-03 11:38:34.2670000' where id = myexecutionid

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
