### ISSUE TITLE
API Call to run a Job failed

### ISSUE THREAD

**Issue by hifx-azad** [rundeck/rundeck#2387]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version:  Rundeck 2.6.9-1
* install type: 
* OS Name/version: amazon linux

**Expected Behavior**
Should be run the Job using APi CALL

**Actual Behavior**

==> /var/log/rundeck/service.log <==
ERROR GrailsExceptionResolver: MissingMethodException occurred when processing request: [POST] /api/17/job/406316fc-34b0-469d-91f1-0550812d63e1/run
No signature of method: static rundeck.services.FrameworkService.parseOptsFromString() is applicable for argument types: (org.codehaus.groovy.grails.web.json.JSONObject) values: [[tag_or_branch:master]]
Possible solutions: parseOptsFromString(java.lang.String). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: static rundeck.services.FrameworkService.parseOptsFromString() is applicable for argument types: (org.codehaus.groovy.grails.web.json.JSONObject) values: [[tag_or_branch:master]]
Possible solutions: parseOptsFromString(java.lang.String)
	at rundeck.services.ExecutionService.selectSecureOptionInput(ExecutionService.groovy:1844)
	at rundeck.services.ExecutionService.executeJob(ExecutionService.groovy:1602)
	at rundeck.controllers.ScheduledExecutionController.apiJobRun(ScheduledExecutionController.groovy:3172)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)

==> /var/log/rundeck/rundeck.log <==
2017-03-27 10:25:31,110 [qtp1445765339-34] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - MissingMethodException occurred when processing request: [POST] /api/17/job/406316fc-34b0-469d-91f1-0550812d63e1/run
No signature of method: static rundeck.services.FrameworkService.parseOptsFromString() is applicable for argument types: (org.codehaus.groovy.grails.web.json.JSONObject) values: [[tag_or_branch:master]]
Possible solutions: parseOptsFromString(java.lang.String). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: static rundeck.services.FrameworkService.parseOptsFromString() is applicable for argument types: (org.codehaus.groovy.grails.web.json.JSONObject) values: [[tag_or_branch:master]]
Possible solutions: parseOptsFromString(java.lang.String)
	at rundeck.services.ExecutionService.selectSecureOptionInput(ExecutionService.groovy:1844)
	at rundeck.services.ExecutionService.executeJob(ExecutionService.groovy:1602)
	at rundeck.controllers.ScheduledExecutionController.apiJobRun(ScheduledExecutionController.groovy:3172)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)

**How to reproduce Behavior**
use curl request to POST /api/1/job/[ID]/run  -H "Content-Type: application/json" -d '{"argString":{"tag_or_branch":"master"} }'

**Comment by pancho-villa** [comment]
Same issue here:

**My Rundeck detail**

    Rundeck version: Rundeck 2.6.9-1 cafe bonbon indigo tower
    OS Name/version: Oracle Server 6.6 

**Expected Behavior**
  It should return a JSON payload when setting `content-type: application/json`
I didn't have any error messages at all that hifx-azad found in their log.

**Actual Behavior**

    curl -H "Accept: application/json" 'http://localhost:4440/api/1/job/JOB_ID/run?authtoken=TOKEN' -X POST            
    <result error='true' apiversion='17'>
    <error code='api.error.item.unsupported-format'>
        <message>The format is not valid: json</message>
    </error>
    </result>

    curl -H "Accept: application/xml" 'http://localhost:4440/api/1/job/JOB_ID/run?authtoken=TOKEN' -X POST                                     
    <result success='true' apiversion='17'>
    <executions count='1'>
        <execution id='449' href='http://localhost:4440/project/Test/execution/show/449' permalink='' status='running' project='Test'>
        <user>admin</user>
        <date-started unixtime='1508975045776'>2017-10-25T23:44:05Z</date-started>
        <job id='JOB_ID' averageDuration='17669' href='http://localhost:4440/api/17/job/JOB_ID' permalink='http://localhost:4440/project/Test/job/show/JOB_ID'>
            <name>True</name>
            <group></group>
            <project>Test</project>
            <description></description>
        </job>
        <description>#!/bin/bash


    /bin/true</description>
        <argstring />
        </execution>
    </executions>
    </result>

**Comment by gschueler** [comment]
use API version `14` or later for JSON support
