### ISSUE TITLE
Job seems to still run after the last node

### ISSUE THREAD

**Issue by fduranti** [rundeck/rundeck#2390]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.7.3
* install type: rpm
* OS Name/version: RHEL 7.3

**Expected Behavior**
Job Finishing

**Actual Behavior**
Job seems to still run after the last node
![image](https://cloud.githubusercontent.com/assets/1173084/24412835/d95b0fc2-13d9-11e7-9ae9-903bf44e67cf.png)

**How to reproduce Behavior**
Not sure if this is the problem but as it seems that rundeck still try to update the table for a long time it could be it's related.

It seems that something goes wrong when i select too many nodes:

I get this kind of error in the service.log:
```
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "FAILED_NODE_LIST VARCHAR(255)": "'long listof node comma separed.................. (267)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:335)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784)
	at org.h2.command.dml.Insert.insertRows(Insert.java:151)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	... 13 more

Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)": "'long node list ....................................................... (308)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:335)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784)
	at org.h2.command.dml.Insert.insertRows(Insert.java:151)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	... 13 more
WARN  ExecutionJob: Execution 8397 save result status: failed (attempts=8/10), retrying in 86860ms

```
I see this old Issue already closed for 2.0.1 (#661) should I apply the script to my installation?

**Comment by fduranti** [comment]
Found the solution in #2228
