### ISSUE TITLE
Database Storage Problems

### ISSUE THREAD

**Issue by golodhrim** [rundeck/rundeck#2451]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: rpm
* OS Name/version: centos 7.2 
* DB Type/version: postgres 9.2.18

**Expected Behavior**
It should update the tables for Rundeck when it starts after an upgrade

**Actual Behavior**
seems to miss some stuff, this time not giving an error so one could see where it fails in upgrading the schema

**How to reproduce Behavior**
Update from Rundeck 2.8.1 to 2.8.2

Stacktrace from Rundeck log:

org.postgresql.util.PSQLException: ERROR: column this_.SIZE does not exist
  Position: 491
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at rundeck.services.FileUploadService.findRecords(FileUploadService.groovy:392)
	at rundeck.controllers.ExecutionController.show(ExecutionController.groovy:235)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AgustiLumbreras** [comment]
The same problem for me

it seems that is a problem with size column. In postgresql the fields are case sensitive. The fieldname is size, and when the application try to query it with uppercase, it fails

< 2017-04-26 08:35:40.095 CEST >FEHLER:  Spalte this_.SIZE existiert nicht bei Zeichen 491
< 2017-04-26 08:35:40.095 CEST >ANWEISUNG:  select this_.id as id1_3_0_, this_.version as version2_3_0_, this_.date_created as date_cre3_3_0_, this_.execution_id as executio4_3_0_, this_.expiraion_date as expirati5_3_0_, this_.file_name as file_nam6_3_0_, this_.file_state as file_sta7_3_0_, this_.job_id as job_id8_3_0_, this_.last_updated as last_upd9_3_0_, this_.project as project103_0_, this_.record_name as record_11_3_0_, this_.record_type as record_12_3_0_, this_.server_nodeuuid as server_13_3_0_, this_.sha as sha14_3_0_, this_."SIZE" as SIZE15_3_0_, this_.storage_metaas storage16_3_0_, this_.storage_reference as storage17_3_0_, this_.storage_type as storage18_3_0_, this_.rduser as rduser19_3_0_, this_.uuid as uuid20_3_0_ from job_file_record this_ where thi_.execution_id=$1 and this_.record_type=$2

rundeck=> select aa."size" from rundeck.job_file_record aa;
 size
------
(0 Zeilen)

rundeck=> select aa."SIZE" from rundeck.job_file_record aa;
FEHLER:  Spalte aa.SIZE existiert nicht
ZEILE 1: select aa."SIZE" from rundeck.job_file_record aa;

**Comment by golodhrim** [comment]
thx that solved, it, should be included in the upgrade of the sql schemata, cause it is not nice to work around with table altering on ones own...

**Comment by blackside** [comment]
We have a similar problem but with the default h2 db:

Caused by: Column "THIS_.RDUSER" not found;
