### ISSUE TITLE
Ad hoc scheduled executions could not be rescheduled after a restart and will be killed

### ISSUE THREAD

**Issue by zionio** [rundeck/rundeck#2470]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 2.8.2-1
* install type: rpm (repository: rundeck-release-bintray)
* OS Name/version: CentOS Linux release 7.2.1511
* DB Type/version: mysql
* Login module: java.security.auth.login.config: /etc/rundeck/jaas-activedirectory.conf (The currently used login module: activedirectory )

**Expected Behavior**
To have the scheduled job (a.k.a. "Run Job Later") still present after a restart.

**Actual Behavior**
Job 'failed' and killed by Rundeck with the following error in `service.log`

ERROR ScheduledExecutionService: Ad hoc job not rescheduled: testjob: getAuthContextForUserAndRoles: Cannot get AuthContext with
out user, roles: null, []
java.lang.RuntimeException: getAuthContextForUserAndRoles: Cannot get AuthContext without user, roles: null, []
        at rundeck.services.FrameworkService.getAuthContextForUserAndRoles(FrameworkService.groovy:656)
        at rundeck.services.ScheduledExecutionService$_rescheduleJobs_closure16.doCall(ScheduledExecutionService.groovy:628)
        at rundeck.services.ScheduledExecutionService.rescheduleJobs(ScheduledExecutionService.groovy:605)
        at rundeck.services.ScheduledExecutionService$_rescheduleJobsAsync_closure14.doCall(ScheduledExecutionService.groovy:566)
        at grails.plugin.executor.PersistenceContextRunnableWrapper$_run_closure1.doCall(PersistenceContextRunnableWrapper.groovy:34)
        at grails.plugin.executor.PersistenceContextWrapper.wrap(PersistenceContextWrapper.groovy:35)
        at grails.plugin.executor.PersistenceContextRunnableWrapper.run(PersistenceContextRunnableWrapper.groovy:34)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
**ERROR ScheduledExecutionService: 1 ad hoc scheduled executions could not be rescheduled and will be killed**

**How to reproduce Behavior**
Open project >
click on the job > 
click on "Run Job Later" >
configure date and time >
click on "Schedule Job" >
restart Rundeck daemon ( `# systemctl restart rundeckd` on my CentOS 7)

**Comment by sheinbergon** [comment]
Looks like this issue interests quite a few people, self included. 
I sure do hope we'll get to see it as part of 2.8.3

https://github.com/rundeck/rundeck/issues/2271

**Comment by gschueler** [comment]
ref #2167
