### ISSUE TITLE
[doc] missing install of dependency for libpam (libpam4j-java)

### ISSUE THREAD

**Issue by arthurlogilab** [rundeck/rundeck#2499]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: Rundeck 2.8.2-1 cafe cubano olive flag 2017-04-19
* install type: deb
* OS Name/version: debian jessie
* DB Type/version: default (jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true)
* java

```
#java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Expected Behavior**

Follow the docs http://rundeck.org/docs/administration/authenticating-users.html#pam and Authenticate easily with pam. 

**Actual Behavior**

Auth fails and I get this in the logs

```
2017-05-10 15:28:01.880:WARN:oejj.JAASLoginService:qtp2065951873-74: 
javax.security.auth.login.LoginException: java.lang.UnsatisfiedLinkError: Unable to load library 'pam': libpam.so: cannot open shared object file: No such file or directory|?at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)|?at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)|?at com.sun.jna.Library$Handler.<init>(Library.java:140)|?at com.sun.jna.Native.loadLibrary(Native.java:372)|?at com.sun.jna.Native.loadLibrary(Native.java:357)|?at org.jvnet.libpam.impl.PAMLibrary.<clinit>(PAMLibrary.java:132)|?at sun.misc.Unsafe.ensureClassInitialized(Native Method)|?at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)|?at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)|?at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)|?at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)|?at java.lang.reflect.Field.get(Field.java:393)|?at com.sun.jna.Native.loadLibraryInstance(Native.java:396)|?at com.sun.jna.Native.getStructureAlignment(Native.java:505)|?at com.sun.jna.Structure.setAlignType(Structure.java:189)|?at com.sun.jna.Structure.<init>(Structure.java:147)|?at com.sun.jna.Structure.<init>(Structure.java:143)|?at com.sun.jna.Structure.<init>(Structure.java:139)|?at com.sun.jna.Structure.<init>(Structure.java:130)|?at org.jvnet.libpam.impl.PAMLibrary$pam_conv.<init>(PAMLibrary.java:107)|?at org.jvnet.libpam.PAM.<init>(PAM.java:73)|?at org.rundeck.jaas.pam.AbstractPamLoginModule.authenticate(AbstractPamLoginModule.java:85)|?at org.rundeck.jaas.AbstractSharedLoginModule.login(AbstractSharedLoginModule.java:78)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:498)|?at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)|?at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)|?at java.security.AccessController.doPrivileged(Native Method)|?at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)|?at javax.security.auth.login.LoginContext.login(LoginContext.java:587)|?at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)|?at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)|?at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)|?at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)|?at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)|?at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)|?at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)|?at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)|?at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)|?at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)|?at org.eclipse.jetty.server.Server.handle(Server.java:446)|?at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)|?at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)|?at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)|?at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)|?at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)|?at java.lang.Thread.run(Thread.java:745)|
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:856)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
        at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
```

```apt-get -uVf install libpam4j-java``` "solves" this (another error to follow)

**Comment by mmihir82** [comment]
Can someone help with the above issue, I'm also having the error: 

Could not initialize class org.jvnet.libpam.impl.PAMLibrary$pam_conv|?at org.jvnet.libpam.PAM

**Comment by sjrd218** [comment]
The docs have been updated to reflect the libpam4j-java installation requirement.
