### ISSUE TITLE
Could not initialize class org.jvnet.libpam.impl.PAMLibrary

### ISSUE THREAD

**Issue by arthurlogilab** [rundeck/rundeck#2501]
Follow up of  #2499

**My Rundeck detail**

* Rundeck version: Rundeck 2.8.2-1 cafe cubano olive flag 2017-04-19
* install type: deb
* OS Name/version: debian jessie
* DB Type/version: default (jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true)
* java

```
#java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Expected Behavior**

Authenticate with pam.

**Actual Behavior**

```
2017-05-10 15:37:38.405:WARN:oejj.JAASLoginService:qtp2065951873-82: 
javax.security.auth.login.LoginException: java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.libpam.impl.PAMLibrary$pam_conv|?at org.jvnet.libpam.PAM.<init>(PAM.java:73)|?at org.rundeck.jaas.pam.AbstractPamLoginModule.authenticate(AbstractPamLoginModule.java:85)|?at org.rundeck.jaas.AbstractSharedLoginModule.login(AbstractSharedLoginModule.java:78)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:498)|?at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)|?at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)|?at java.security.AccessController.doPrivileged(Native Method)|?at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)|?at javax.security.auth.login.LoginContext.login(LoginContext.java:587)|?at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)|?at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)|?at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)|?at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)|?at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)|?at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)|?at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)|?at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)|?at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)|?at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)|?at org.eclipse.jetty.server.Server.handle(Server.java:446)|?at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)|?at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)|?at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)|?at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)|?at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)|?at java.lang.Thread.run(Thread.java:745)|
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:856)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
        at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
```

**How to reproduce Behavior**

**Comment by arthurlogilab** [comment]
Documentation says java 7 is required http://rundeck.org/docs/administration/installation.html#java

Debian package depends on  
```
Depends: openssh-client, java7-runtime | java7-runtime-headless | java8-runtime | java8-runtime-headless , adduser (>= 3.11), uuid-runtime
```

do I have to downgrade to java7 ?

**Comment by arthurlogilab** [comment]
Is this related to the absence of libjna-posix-java on my system ? trying to install it suggests dowgrading to java7

**Comment by gschueler** [comment]
@arthurlogilab for rundeck 2.8, java 8 is required, those docs are out of date.

**Comment by arthurlogilab** [comment]
@gschueler ok, I'll stick to java 8, but what about the bug I describe ? (am a bit stuck)

**Comment by ahonor** [comment]
@arthurlogilab Are you still stuck?

**Comment by mmihir82** [comment]
I'm getting same error, some how not able to authenticate with local users
RDpropertyfilelogin {

    org.rundeck.jaas.jetty.JettyPamLoginModule required
    debug="true"
    service="sshd"
    supplementalRoles="xxxx,readonly"
    useUnixGroups="true"
    storePass="true";

    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
    debug="true"
    useFirstPass="true"
    file="/etc/rundeck/realm.properties";

};

**Comment by mmihir82** [comment]
does the rundeck user needs to same role as root access?

**Comment by ahonor** [comment]
@mmihir82 No rundeck should not need root access. I wonder if the libpam java library is not java8 compatible.

**Comment by mmihir82** [comment]
Have you tested with libpam that is compatible with java8? Does this
libpam is compatible?
https://github.com/kohsuke/libpam4j, i don't know how to compile it.

Thank you for followup. As I'm stuck and unable to use PAM.

**Comment by sjrd218** [comment]
@arthurlogilab Have you tried your PAM configuration with the latest version of Rundeck? It should work just fine. Please open a new issue if you run into a problem.
