### ISSUE TITLE
jsch channel is not opened

### ISSUE THREAD

**Issue by avinchakov** [rundeck/rundeck#2536]
Issue type: Bug report
**My Rundeck detail**

* Rundeck version: 2.8.2-1
* install type: deb
* OS Name/version: Ubuntu 14.04.5 LTS
* DB Type/version: percona-server-common-5.6

**Expected Behavior**
Running the script on a remote host

**Actual Behavior**
Very, very often I get an error: "Failed dispatching to node <remote host>: [jsch-scp] Failed copying the file: channel is not opened."

**How to reproduce Behavior**
I don't know. There is a suggestion that at the same time several jobs started

**Comment by cmietzner** [comment]
I am also getting this error on the same version of rundeck.

Stack Trace: 

Failed dispatching to node CTx-DW-QTC-026: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: [jsch-scp] Failed copying the file: channel is not opened.	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:123)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:61)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:115)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:143)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:65)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:82)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:360)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:732)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor$2.call(EngineWorkflowExecutor.java:423)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor$2.call(EngineWorkflowExecutor.java:417)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowStepOperation.call(EngineWorkflowStepOperation.java:54)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowStepOperation.call(EngineWorkflowStepOperation.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.dtolabs.rundeck.core.execution.service.FileCopierException: [jsch-scp] Failed copying the file: channel is not opened.
	at com.dtolabs.rundeck.core.execution.impl.jsch.JschScpFileCopier.handleBuildException(JschScpFileCopier.java:277)
	at com.dtolabs.rundeck.core.execution.impl.jsch.JschScpFileCopier.copyFile(JschScpFileCopier.java:186)
	at com.dtolabs.rundeck.core.execution.impl.jsch.JschScpFileCopier.copyFile(JschScpFileCopier.java:302)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.fileCopyFile(ExecutionServiceImpl.java:212)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:108)
	... 17 more
Caused by: com.jcraft.jsch.JSchException: channel is not opened.
	at org.apache.tools.ant.taskdefs.optional.ssh.Scp.execute(Scp.java:245)
	at com.dtolabs.rundeck.core.execution.impl.jsch.JschScpFileCopier.copyFile(JschScpFileCopier.java:184)
	... 20 more
Caused by: com.jcraft.jsch.JSchException: channel is not opened.
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:765)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at org.apache.tools.ant.taskdefs.optional.ssh.ScpToMessage.doSingleTransfer(ScpToMessage.java:157)
	at org.apache.tools.ant.taskdefs.optional.ssh.ScpToMessage.execute(ScpToMessage.java:144)
	at org.apache.tools.ant.taskdefs.optional.ssh.Scp.upload(Scp.java:337)
	at org.apache.tools.ant.taskdefs.optional.ssh.Scp.execute(Scp.java:226)
	... 21 more

**Comment by davalente** [comment]
Any solution on this issue?
Having the some problem.

**Comment by ahonor** [comment]
Does it happen after a delay? Was looking at this article too: https://stackoverflow.com/questions/33895500/com-jcraft-jsch-jschexception-channel-is-not-opened-when-opening-a-channel-in-j

**Comment by cmietzner** [comment]
The issue seems to be resolved by making sure the minion is on the same version as master. When I do an apt-get update && apt-get upgrade && apt-get dist-upgrade, I no longer have this issue.

**Comment by ahonor** [comment]
Thanks

**Comment by davalente** [comment]
I can't solve the problem, I'm not using "salt"

**Comment by ahonor** [comment]
@davalente ok reopening

**Comment by avinchakov** [comment]
The problem continues to this day, but has become less frequent. I have about 200 jobs and the problem occurs when many crowns are simultaneously launched

**Comment by davalente** [comment]
Thanks @ahonor 
Looking forward to see the solution.

**Comment by avinchakov** [comment]
I have "UseDNS No" everywhere

**Comment by kwaio** [comment]
Just for the record, we are facing the same issue randomly on a setup where Rundeck and its does are on the same virtual environment/subnet which means very little chance of network lag/issues

**Comment by imbkr** [comment]
we are seeing this issue too, anyone able to resolve it?

**Comment by avinchakov** [comment]
I almost don't see the problem in the latest releases. Only when I see this problem is when the remote server is overloaded
