### ISSUE TITLE
Exception: property not found: framework.var.dir

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2538]
Issue type: Bug report

Sometimes an exception is produced during node loading.  It may be a race condition with the deferred framework.properties loading and the node properties loading.

**My Rundeck detail**

* Rundeck version: 2.8 (or earlier?)
* install type: any
* OS Name/version: any 
* DB Type/version: any

**Expected Behavior**

no error message

**Actual Behavior**

~~~
Message: property not found: framework.var.dir Caused by: property not found: framework.var.dir Class: ScheduledExecutionController At Line: [409] Code Snippet: Stack Trace com.dtolabs.rundeck.core.utils.PropertyLookupException: property not found: framework.var.dir at com.dtolabs.rundeck.core.utils.PropertyLookup.getProperty(PropertyLookup.java:194) at com.dtolabs.rundeck.server.projects.RundeckProjectConfig.getProperty(RundeckProjectConfig.java:53) at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getResourceModelSourceFileCacheForType(ProjectNodeSupport.java:285) at com.dtolabs.rundeck.core.common.ProjectNodeSupport.createCachingSource(ProjectNodeSupport.java:364) at rundeck.services.NodeService.loadNodes(NodeService.groovy:212) at rundeck.services.NodeService$3.load(NodeService.groovy:117) at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) at com.google.common.cache.LocalCache.get(LocalCache.java:3937) at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) at rundeck.services.NodeService.getNodes(NodeService.groovy:297) at com.dtolabs.rundeck.server.projects.RundeckProject.getProjectNodes(RundeckProject.java:145) at com.dtolabs.rundeck.server.projects.RundeckProject.getNodeSet(RundeckProject.java:63) at rundeck.services.FrameworkService$_filterNodeSet_closure3.doCall(FrameworkService.groovy:289) at com.codahale.metrics.Timer.time(Timer.java:99) at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:190) at rundeck.services.FrameworkService.filterNodeSet(FrameworkService.groovy:288) at rundeck.controllers.ScheduledExecutionController._prepareExecute(ScheduledExecutionController.groovy:2514) at rundeck.controllers.ScheduledExecutionController.show(ScheduledExecutionController.groovy:409) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198) at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261) at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:446) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) at java.lang.Thread.run(Thread.java:748)
~~~

**How to reproduce Behavior**

unsure

**Comment by gschueler** [comment]
ref https://github.com/rundeck/rundeck/pull/2433#issuecomment-302181699

> When I set framework.always-set-pty=true or project.always-set-pty=true, I get an error when I try to run a job. When it is removed, the job runs again. framework.var.dir IS defined.
