### ISSUE TITLE
2.8: ACL policy causes exception for matching clause of a resource attribute that is not present

### ISSUE THREAD

**Issue by tomdeblende** [rundeck/rundeck#2559]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 2.8.2-1
* install type: rpm
* OS Name/version:  Amazon Linux AMI release 2017.03
* DB Type/version: h2

**Expected Behavior**
List of EC2 jobs when going to http://x.x.x.x:4440/project/Manage_EC2_Nodes/activity

**Actual Behavior**
```
An Error Occurred

Error Details 
Request: /reports/index
Message: 
Caused by: Error applying layout : base 
Class: gsp_rundeck_common_topbar_gsp 
At Line: [0] 
Code Snippet:
Stack Trace
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : base
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: null
	... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: null
	at gsp_rundeck_layoutsbase_gsp$_run_closure2.doCall(gsp_rundeck_layoutsbase_gsp.groovy:178)
	at gsp_rundeck_layoutsbase_gsp.run(gsp_rundeck_layoutsbase_gsp.groovy:189)
	... 44 more
Caused by: java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator$RegexPredicate.test(RuleEvaluator.java:735)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator$RegexPredicate.test(RuleEvaluator.java:727)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator$11.test(RuleEvaluator.java:826)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator$11.test(RuleEvaluator.java:823)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.applyTest(RuleEvaluator.java:823)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.predicateMatchRules(RuleEvaluator.java:781)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.ruleMatchesMatchSection(RuleEvaluator.java:711)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.includes(RuleEvaluator.java:530)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.ruleIncludesResourceAction(RuleEvaluator.java:506)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.internalEvaluate(RuleEvaluator.java:427)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.evaluate(RuleEvaluator.java:236)
	at com.dtolabs.rundeck.core.authorization.RuleEvaluator.evaluate(RuleEvaluator.java:217)
	at rundeck.services.TimedAuthorization$_evaluate_closure2.doCall(TimedAuthorization.groovy:76)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.services.TimedAuthorization.evaluate(TimedAuthorization.groovy:75)
	at com.dtolabs.rundeck.core.authorization.MultiAuthorization.evaluate(MultiAuthorization.java:69)
	at com.dtolabs.rundeck.core.authorization.SubjectAuthContext.evaluate(SubjectAuthContext.java:70)
	at rundeck.AuthTagLib$_closure5.doCall(AuthTagLib.groovy:217)
	at gsp_rundeck_common_topbar_gsp.run(gsp_rundeck_common_topbar_gsp.groovy:201)
	... 46 more
```

**How to reproduce Behavior**

Log in with an AD authenticated user and list Jobs. Local user from file works fine. Same config worked fine in 2.7.3.

**Comment by tomdeblende** [comment]
It looks to be something with rendering the top bar. When the top bar is just the Rundeck link, all is well. When additional buttons need to be added: problem. 

Everything works for local users, not for AD users. 

I don't think it is admin.aclpolicy related. When I give an AD user full admin rights, the error still remains the same.

**Comment by tomdeblende** [comment]
Additional info from rundeck.log:
`2017-06-13 16:41:38,908 [qtp1329552164-18] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /project/Manage_EC2_Nodes/activity
Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : base`

**Comment by gschueler** [comment]
the NullPointerException seems to be caused by ACL policy parsing, perhaps there is something in one of your ACL policy files that is invalid.  try validating the files with the `rd-acl` tool

**Comment by tomdeblende** [comment]
Thanks for the feedback. I did the test and as far as I can see all is well:

`[rundeck@server ~]$ rd-acl validate /etc/rundeck/admin.aclpolicy
Using configured Rundeck etc dir: /etc/rundeck
The validation passed`

Which makes sense, as all I did was upgrade from version 2.7.3 to 2.8.2 and from java 1.7.0 to 1.8.0.

**Comment by tomdeblende** [comment]
I did some further testing. I have an instance with the working 2.7.3 version and an instance with the broken upgraded 2.8.2.

This works on 2.7.3:
`[rundeck@oldserver ~]$ rd-acl list -g ITOPS -p Manage_EC2_Nodes
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Using configured Rundeck etc dir: /etc/rundeck
# Application Context access for group ITOPS

- admin: project named "Manage_EC2_Nodes" [REJECTED]
- configure: project named "Manage_EC2_Nodes" [REJECTED]
- delete: project named "Manage_EC2_Nodes" [REJECTED]
- delete_execution: project named "Manage_EC2_Nodes" [REJECTED]
- export: project named "Manage_EC2_Nodes" [REJECTED]
- import: project named "Manage_EC2_Nodes" [REJECTED]
+ read: project named "Manage_EC2_Nodes"

(No project_acl (-P) specified, skipping Application context actions for a ACLs for a specific project.)


(No storage path (-s) specified, skipping Application context actions for a specific storage path.)

- admin: system [REJECTED_NO_RULES_DECLARED]
- disable_executions: system [REJECTED_NO_RULES_DECLARED]
- enable_executions: system [REJECTED_NO_RULES_DECLARED]
- read: system [REJECTED_NO_RULES_DECLARED]
- create: project [REJECTED_NO_RULES_DECLARED]
- admin: system_acl [REJECTED_NO_RULES_DECLARED]
- create: system_acl [REJECTED_NO_RULES_DECLARED]
- delete: system_acl [REJECTED_NO_RULES_DECLARED]
- read: system_acl [REJECTED_NO_RULES_DECLARED]
- update: system_acl [REJECTED_NO_RULES_DECLARED]
- admin: job [REJECTED_NO_RULES_DECLARED]
- admin: user [REJECTED_NO_RULES_DECLARED]

# Project "Manage_EC2_Nodes" access for group ITOPS

- kill: Adhoc executions [REJECTED]
- killAs: Adhoc executions [REJECTED]
- read: Adhoc executions [REJECTED]
- run: Adhoc executions [REJECTED]
- runAs: Adhoc executions [REJECTED]

(No job (-j) specified, skipping Project context actions for a specific job.)


(No node (-n) or tags (-t) specified, skipping Project context actions for a specific node or node tags.)

- create: node [REJECTED]
- read: node [REJECTED]
- refresh: node [REJECTED]
- update: node [REJECTED]
- create: job [REJECTED]
- delete: job [REJECTED]
+ create: event
+ read: event`

This fails in 2.8.2 (very same config):
`[rundeck@newserver ~]$ rd-acl list -g ITOPS -p Manage_EC2_Nodes
Using configured Rundeck etc dir: /etc/rundeck
# Application Context access for group ITOPS

- admin: project named "Manage_EC2_Nodes" [REJECTED]
- configure: project named "Manage_EC2_Nodes" [REJECTED]
- delete: project named "Manage_EC2_Nodes" [REJECTED]
- delete_execution: project named "Manage_EC2_Nodes" [REJECTED]
- export: project named "Manage_EC2_Nodes" [REJECTED]
- import: project named "Manage_EC2_Nodes" [REJECTED]
+ read: project named "Manage_EC2_Nodes"

(No project_acl (-P) specified, skipping Application context actions for a ACLs for a specific project.)


(No storage path (-s) specified, skipping Application context actions for a specific storage path.)

- admin: apitoken [REJECTED]
- generate_service_token: apitoken [REJECTED]
- generate_user_token: apitoken [REJECTED]
- admin: system [REJECTED]
- disable_executions: system [REJECTED]
- enable_executions: system [REJECTED]
- read: system [REJECTED]
- create: project [REJECTED]
- admin: system_acl [REJECTED]
- create: system_acl [REJECTED]
- delete: system_acl [REJECTED]
- read: system_acl [REJECTED]
- update: system_acl [REJECTED]
- admin: job [REJECTED]
- admin: user [REJECTED]

# Project "Manage_EC2_Nodes" access for group ITOPS

java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator$RegexPredicate.test(RuleEvaluator.java:735)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator$RegexPredicate.test(RuleEvaluator.java:727)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator$11.test(RuleEvaluator.java:826)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator$11.test(RuleEvaluator.java:823)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.applyTest(RuleEvaluator.java:823)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.predicateMatchRules(RuleEvaluator.java:781)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.ruleMatchesMatchSection(RuleEvaluator.java:711)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.includes(RuleEvaluator.java:530)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.ruleIncludesResourceAction(RuleEvaluator.java:506)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.internalEvaluate(RuleEvaluator.java:427)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.evaluate(RuleEvaluator.java:236)
        at com.dtolabs.rundeck.core.authorization.RuleEvaluator.evaluate(RuleEvaluator.java:217)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.logDecisions(AclTool.java:772)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.listAction(AclTool.java:669)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.go(AclTool.java:570)
        at com.dtolabs.rundeck.core.cli.BaseTool.run(BaseTool.java:155)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.main(AclTool.java:155)
Error: null`

**Comment by gschueler** [comment]
@tomdeblende can you send me the acl file(s)?

**Comment by tomdeblende** [comment]
@gschueler it's in your mail! :)

**Comment by gschueler** [comment]
thanks, i discovered a problem in the aclpolicy file.  you have some clauses like this:

~~~{.yaml}
adhoc:
    - match:
        name: 'BI.*'
      allow: [read,run,kill]
~~~

however the `adhoc` resource type does not have a name, so it was causing an exception when attempting to match the `name`.  The solution is to change the clause to this:

~~~{.yaml}
adhoc:
    - allow: [read,run,kill]
~~~

I will rename the issue title as a bug in the aclpolicy evaluator

**Comment by tomdeblende** [comment]
Confirmed that it works now. Weird that 2.7.3 has no issues with it :)

I suppose this change has no effect on any user rights?
