### ISSUE TITLE
Notification mail fails if no output from job

### ISSUE THREAD

**Issue by tkald** [rundeck/rundeck#2605]
Issue type: Bug report

If I set job to send email notification with "Attach output log" checked AND job produces no output, no email is sent.

Error in rundeck service log:

> ERROR NotificationService: Error sending notification: Notification{eventTrigger='onsuccess', type='email', content='{"recipients":"my@e.mail","subject":"${job.name} success","attachLog":true}'}: class java.io.IOException: No such file or directory
java.io.IOException: No such file or directory
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at rundeck.services.NotificationService.copyExecOutputToTempFile(NotificationService.groovy:121)
        at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:262)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:147)
        at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:89)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:86)
        at rundeck.services.ExecutionService$_saveExecutionState_closure62.doCall(ExecutionService.groovy:2391)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2292)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:526)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:464)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:536)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:164)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**My Rundeck detail**

* Rundeck version: 2.8.3
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: mysql

**Expected Behavior**
Get email with no output attached

**Actual Behavior**
No email is sent

**Comment by gschueler** [comment]
That error seems to indicate that it cannot create a Temp file.  does the `/tmp` dir exist, or the value of `-Djava.io.tmpdir` that you specified exist?

I cannot reproduce this with a job which has no output

**Comment by tkald** [comment]
Yeah, can't reproduce it either.
Got e-mail with empty output as expected.
Must have been misconfiguration on my side.
