### ISSUE TITLE
NullPointerException with jasypt-encryption

### ISSUE THREAD

**Issue by avinchakov** [rundeck/rundeck#2606]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version:  2.8.3
* install type: deb
* OS Name/version: Ubuntu 14.04.05 LTS
* DB Type/version: mysql

**Expected Behavior**
jasypt-encryption will encrypt my password for key Storage

**Actual Behavior**
```
ERROR GrailsExceptionResolver: NullPointerException occurred when processing request: [POST] /storage/upload/keys
Stacktrace follows:
java.lang.NullPointerException
```

**How to reproduce Behavior**
rundeck.storage.converter.1.type=jasypt-encryption
rundeck.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.storage.converter.1.config.passwordEnvVarName=ENC_PASSWORD
rundeck.storage.converter.1.path=keys
rundeck.storage.converter.1.config.provider=BC

Then I try to add new password to keys.

**Comment by gschueler** [comment]
is there any more data in the logs? the full stacktrace?

**Comment by avinchakov** [comment]
Hi, yes:
```
Request: /storage/upload/keys?id=uploadKeyForm&uploadPassword=test-password&fileName=test&relativePath=&uploadKeyType=password&inputType=text&SYNCHRONIZER_URI=%2Fmenu%2Fstorage&SYNCHRONIZER_TOKEN=cb8e0f12289d31029c0a3c5d927ef6aefdb214534105df32112a63c4d43fb228&storagefile=org.springframework.web.multipart.commons.CommonsMultipartFile%40367db76b
Message: 
Caused by: 
Class: StorageController 
At Line: [411] 
Code Snippet:
```
```
Stack Trace
java.lang.NullPointerException
	at org.jasypt.encryption.pbe.config.SimplePBEConfig.getPasswordCharArray(SimplePBEConfig.java:434)
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.resolveConfigurationPassword(StandardPBEByteEncryptor.java:783)
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.initialize(StandardPBEByteEncryptor.java:598)
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.encrypt(StandardPBEByteEncryptor.java:873)
	at org.rundeck.plugin.encryption.JasyptEncryptionConverterPlugin$EncryptStream.getInputStream(JasyptEncryptionConverterPlugin.java:428)
	at com.dtolabs.rundeck.core.storage.BaseStreamResource.getInputStream(BaseStreamResource.java:42)
	at com.dtolabs.rundeck.core.storage.BaseStreamResource.getInputStream(BaseStreamResource.java:42)
	at com.dtolabs.rundeck.core.storage.BaseStreamResource.getInputStream(BaseStreamResource.java:42)
	at rundeck.services.DbStorageService.saveStorage(DbStorageService.groovy:281)
	at rundeck.services.DbStorageService.createResource(DbStorageService.groovy:272)
	at com.dtolabs.rundeck.core.storage.ResolvedExtTree.createResource(ResolvedExtTree.java:93)
	at com.dtolabs.rundeck.core.storage.ResolvedExtTree.createResource(ResolvedExtTree.java:33)
	at org.rundeck.storage.impl.DelegateTree.createResource(DelegateTree.java:81)
	at org.rundeck.storage.impl.DelegateTree.createResource(DelegateTree.java:81)
	at org.rundeck.storage.conf.ListenerTree.createResource(ListenerTree.java:116)
	at org.rundeck.storage.impl.DelegateTree.createResource(DelegateTree.java:81)
	at org.rundeck.storage.conf.ConverterTree.createResource(ConverterTree.java:100)
	at org.rundeck.storage.impl.DelegateTree.createResource(DelegateTree.java:81)
	at org.rundeck.storage.conf.ConverterTree.createResource(ConverterTree.java:100)
	at org.rundeck.storage.impl.DelegateTree.createResource(DelegateTree.java:81)
	at org.rundeck.storage.conf.ConverterTree.createResource(ConverterTree.java:100)
	at org.rundeck.storage.impl.DelegateTree.createResource(DelegateTree.java:81)
	at com.dtolabs.rundeck.core.storage.AuthRundeckStorageTree.createResource(AuthRundeckStorageTree.java:202)
	at rundeck.services.StorageService.createResource(StorageService.groovy:50)
	at rundeck.controllers.StorageController.keyStorageUpload(StorageController.groovy:411)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gschueler** [comment]
is the `ENC_PASSWORD` environment variable set when you start rundeck?

**Comment by avinchakov** [comment]
ohh, I missed. Sorry.

**Comment by tydonk** [comment]
I'm having the same issue.  I tried setting the ENC_PASSWORD env var and it didn't work.  More to the point, I'm trying to encrypt a password and it seems that it will always be visible in plain text somewhere.  Setting the ENC_PASSWORD var exposes it to the environment and the only way I could get it to work was putting the password in the rundeck-config.properties file.  Putting it in that file will encrypt it and put it in the store but leaves it in plain text in the .properties file.  Any suggestions?  Thanks in advance.
