### ISSUE TITLE
Mysql syntax error after login

### ISSUE THREAD

**Issue by simple365** [rundeck/rundeck#2609]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version:  rundeck-launcher-2.8.3.jar
* install type: launcher
* OS Name/version:  amazon emr 
* DB Type/version: 5.5.54 MySQL Community Server (GPL)

**Expected Behavior**
I start the launcher and login as admin/admin .

**Actual Behavior**
I got an error on home page

~~~
MySQLSyntaxErrorException occurred when processing request: [GET] /menu/home
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') group by this_.project' at line 1. Stacktrace follows:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') group by this_.project' at line 1
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2034)
	at rundeck.controllers.MenuController.loadSummaryProjectStatsOrig(MenuController.groovy:1561)
	at rundeck.controllers.MenuController$_cachedSummaryProjectStats_closure63.doCall(MenuController.groovy:1485)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:190)
	at rundeck.controllers.MenuController.cachedSummaryProjectStats(MenuController.groovy:1481)
	at rundeck.controllers.MenuController.home(MenuController.groovy:1446)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)
~~~

**How to reproduce Behavior**

**Comment by gschueler** [comment]
what is your dataSource configuration?

**Comment by simple365** [comment]
like this
`#dataSource.url = jdbc:h2:file:D:/rundeck/server/data/grailsdb;MVCC=true`
`dataSource.url = jdbc:mysql://127.0.0.1:3309/rundeck?autoReconnect=true`
`dataSource.username = rundeck`
`dataSource.password = 123456`

**Comment by simple365** [comment]
I think it's related to the project .When there is no project, I see
![1](https://user-images.githubusercontent.com/2282908/27945181-2046e5c6-631e-11e7-94c4-78395fe57896.png)
After I create one ,then:
![2](https://user-images.githubusercontent.com/2282908/27945185-26ced9a8-631e-11e7-940f-a35b7e4f86f1.png)

**Comment by jjethwa** [comment]
v2.8.3 / debian stretch / mariadb
I'm not sure if this is related, but I'm seeing these errors in the service.log when starting fresh as well:

```
2017-07-07 06:49:58,281 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index EXEC_REPORT_IDX_0 on base_report (ctx_project, date_completed, jc_exec_id, jc_job_id)
2017-07-07 06:49:58,286 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
2017-07-07 06:49:58,288 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index EXEC_REPORT_IDX_1 on base_report (ctx_project, jc_job_id)
2017-07-07 06:49:58,288 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
2017-07-07 06:49:58,289 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index BASE_REPORT_IDX_2 on base_report (ctx_project, date_completed, date_started)
2017-07-07 06:49:58,289 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
2017-07-07 06:49:58,290 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index EXEC_IDX_1 on execution (id, date_completed, project)
2017-07-07 06:49:58,290 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
2017-07-07 06:49:58,290 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index EXEC_IDX_3 on execution (date_completed, project)
2017-07-07 06:49:58,291 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
2017-07-07 06:49:58,291 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index EXEC_IDX_2 on execution (date_started, status)
2017-07-07 06:49:58,292 [main] ERROR hbm2ddl.SchemaUpdate  - Specified key was too long; max key length is 767 bytes
```

**Comment by isuftin** [comment]
Just kicked off Rundeck 2.8.3-1 against MySQL 5.6.35 AWS RDS instance. Seeing the same issue.

` You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') group by this_.project' at line 1 `

```

stats: uptime | stats: cpu | stats: memory | stats: scheduler | stats: threads | timestamp | rundeck | executions | os | jvm
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

datetime | 2017-07-07T16:50:43Z
duration | 26m

loadAverage | 0.03%
processors | 2

allocated | 39%39% Complete
free | 180.15 MiB
heapusage | 54%54% Complete
max | 1,007.38 MiB
total | 399.35 MiB
used | 219.2 MiB

ratio | 0%0% Complete
running | 0
threadPoolSize | 20

active | 37

datetime | 2017-07-07T17:17:20Z

base | /var/lib/rundeck
build | 2.8.3-1
node | owirundeck-development.usgs.chs.ead
serverUUID |  
version | 2.8.3

active | true
executionMode | ACTIVE

arch | amd64
name | Linux
version | 3.10.0-514.21.2.el7.x86_64

implementationVersion | 25.131-b11
name | Java HotSpot(TM) 64-Bit Server VM
vendor | Oracle Corporation
version | 1.8.0_131
```

**Comment by gschueler** [comment]
both of the errors sound related to this change https://github.com/rundeck/rundeck/pull/2457

the error with `MenuController.loadSummaryProjectStatsOrig` seems odd because that is using the original query implementation.  The alternate implementation can be enabled with `rundeck.menuController.projectStats.queryAlt=true`, but I suspect it would cause the same issue if there is a problem doing a "group by" query.

The reason I asked for dataSource configuration from @simple365 is because I was wondering if there is a specific Dialect configured.

**Comment by joshpollara** [comment]
I'm seeing the same error. Creating a project clears things up.
