### ISSUE TITLE
New version of rundeck problem

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2635]
curl -H'x-rundeck-auth-token：a9ghNoVsy4EjlHHcoApw2oOU5GSoWMhu'--data-urlencode“argString = --one a24”--data-urlencode“argString = -two a23” http://10.99.2.200:4440/api/ 1 / job / 4685ce98-08e4-4d6c-b439-02be96958ac1 / run （Can not）

curl -H'x-rundeck-auth-token：a9ghNoVsy4EjlHHcoApw2oOU5GSoWMhu'--data-urlencode“argString = -one a24” http://10.99.2.200:4440/api/1/job/4685ce98-08e4-4d6c-b439- 02be96958ac1 / run （can）

我进行了一些测试，发现当引入参数时可以通过api方式成功，但是引入两个参数时工作不能通过api

**Comment by qicaihuoyan** [comment]
rundeck.controllers.ScheduledExecutionController$__prepareExecute_closure72: method <init>(Ljava/lang/Object;Ljava/lang/Object;)V not found

**Comment by qicaihuoyan** [comment]
<pre>groovy.lang.MissingMethodException: No signature of method: static rundeck.services.FrameworkService.parseOptsFromString() is applicable for argument types: ([Ljava.lang.String;) values: [[-Module 1, -code 2, -maven_parameter 3, -project_name 4]]
Possible solutions: parseOptsFromString(java.lang.String), parseOptsFromArray([Ljava.lang.String;)
	at rundeck.services.ExecutionService.selectSecureOptionInput(ExecutionService.groovy:2043)
	at rundeck.services.ExecutionService.executeJob(ExecutionService.groovy:1643)
	at rundeck.controllers.ScheduledExecutionController.apiJobRun(ScheduledExecutionController.groovy:3426)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:540)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)

**Comment by qicaihuoyan** [comment]
There are no problems running the task through the web page. The problem seems to have occurred in the api

**Comment by qicaihuoyan** [comment]
Not all jobs can not run through the api, no entry of any parameters of the job can be run through the api

**Comment by qicaihuoyan** [comment]
I can not even delete the "Activity" now

The request did not include a valid token, or the token has expired. Please try your request again.

**Comment by qicaihuoyan** [comment]
You can not create a project as well

**Comment by qicaihuoyan** [comment]
![2222222222222222](https://user-images.githubusercontent.com/13148034/28666377-a4840a0e-72f9-11e7-86de-09dd4adb46eb.png)
Whether it has a relationship with this? This can not be deleted

**Comment by qicaihuoyan** [comment]
The current version is:2.8.3-1
I upgraded from 2.8.1, through the api running job error message:

Not authorized for action "Run" for Job ID 532e59ed-256c-4ce7-9ea5-9c17bf90ec4c
I run the curl command is:
curl -H 'x-rundeck-auth-token:0FZN9Zqf0N0Fe988QYWK1oJDj2NLpSj3' --data-urlencode "argString=-Module ceshi1" --data-urlencode "argString=-maven_parameter ceshi2" --data-urlencode "argString=-code ceshi3" --data-urlencode "argString=-project_name ceshi4" --data-urlencode "filter=name: 172.16.123.251" http://10.99.2.200:4440/api/1/job/532e59ed-256c-4ce7-9ea5-9c17bf90ec4c/run

This is what happens? Is it that the prompt is not authorized? But my token is the latest generation

**Comment by qicaihuoyan** [comment]
curl -H 'x-rundeck-auth-token:a9ghNoVsy4EjlHHcoApw2oOU5GSoWMhu' --data-urlencode "argString=-one a24" --data-urlencode "argString=-two a23" http://10.99.2.200:4440/api/1/job/4685ce98-08e4-4d6c-b439-02be96958ac1/run  (Can not)

curl -H 'x-rundeck-auth-token:a9ghNoVsy4EjlHHcoApw2oOU5GSoWMhu' --data-urlencode "argString=-one a24" http://10.99.2.200:4440/api/1/job/4685ce98-08e4-4d6c-b439-02be96958ac1/run    (can)



I carried out some tests and found that when the introduction of a parameter when the job can be successful through the api way, but the introduction of two parameters when the job can not run through the api

**Comment by qicaihuoyan** [comment]
The problem has been solved, curl parameters become the following

curl -H 'x-rundeck-auth-token:a9ghNoVsy4EjlHHcoApw2oOU5GSoWMhu' --data-urlencodeg=-Module 111111 -code 222222 -maven_parameter 333333 -project_name 444444" http://10.99.2.200:4440/api/1/job/532e59ed-256c-4ce7-9ea5-9c17bf90ec4c/run

Do not set more than one "--data-urlencodeg",What happens to what happens?
