### ISSUE TITLE
Error on Log Output tab on rundeck 2.9.0

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2667]
rundeck version:2.9.0

Through the web page to perform a task, point out the log output display:
Error performing request (loadMoreOutputTail): /execution/tailExecutionOutput?format=json

I have chosen json in the log filter
![2222222222](https://user-images.githubusercontent.com/13148034/28952389-86f6a464-7903-11e7-974f-eb64d6fadd4d.png)

**Comment by qicaihuoyan** [comment]
Do not fill out the contents of the log filter, the implementation of the results also show this error

**Comment by qicaihuoyan** [comment]
2017-08-04 13:01:07,430 ERROR GrailsExceptionResolver - NumberFormatException occurred when processing request: [POST] /execution/tailExecutionOutput
null. Stacktrace follows:
java.lang.NumberFormatException: null
        at java.lang.Long.parseLong(Long.java:552)
        at java.lang.Long.parseLong(Long.java:631)
        at rundeck.controllers.ExecutionController.tailExecutionOutput(ExecutionController.groovy:840)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)

**Comment by qicaihuoyan** [comment]
But through the api interface can be run the results

**Comment by ioannisas** [comment]
Same issue here.

Trying 2.9.0 as an update from 2.8.2-1 and from scratch. This occurs on both setups.

I'm using MySQL as Rundeck database.
I can extract log via API but from UI the above issue is happening.

No matter what type of job and the log level you choose. Also, no matter what the Render Formatted Data option is configured to be.

**Comment by kurlzor** [comment]
Exact same problem after upgrading from 2.8.4. A new instance also exhibits the same behavior.

**Comment by kurlzor** [comment]
@qicaihuoyan You might want to change the title of this issue to something a bit more explicit, like "Error on Log Output tab on rundeck 2.9.0" so affected people can upvote it instead of creating new issues.

**Comment by qicaihuoyan** [comment]
谢谢

**Comment by qicaihuoyan** [comment]
Thanks for reminding

**Comment by RANGERBEE** [comment]
running 2.9.0-1 fresh instance and same error as above.  Please advise of fix.

**Comment by parlacom** [comment]
Having the same issue here version 3

**Comment by xulongju** [comment]
Hello, I also have this problem, I am running version 2.11.14。
#### error log:

      (loadMoreOutputTail):/execution/tailExecutionOutput?format=json

**Comment by fl-nishida** [comment]
I have same problem, after I rebooted rundeck2.8.3-1 server from OS.
I didn't change anything,,, just monthly reboot due to rundeck's memory leaking problem,,,
anyway to avoid this? anyone. Thank you.
