### ISSUE TITLE
OutOfMemEx repeatingly occurring, but Job independent

### ISSUE THREAD

**Issue by t-o-c** [rundeck/rundeck#2699]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.7.3-1
* install type: war
* OS Name/version: Debian
* DB Type/version: H2

**Expected Behavior**

**Actual Behavior**

Our Rundeck manages multiple JOBs (aprox 30) and starts them on request or by a given schedule. Not more than 3 Jobs get executed in parallel. The memory footprint is always the same and 50% of the memory is usually free, no Ramp up (currently set to 4GB for testing purposes, usually 2GB in Prod). In the last two months we ran into OutOfMem issues multiple times, always with the same stacktrace:

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587)
	at java.lang.StringBuilder.append(StringBuilder.java:214)
	at java.util.AbstractMap.toString(AbstractMap.java:522)
	at java.lang.String.valueOf(String.java:2849)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at com.dtolabs.rundeck.core.rules.DataState.toString(DataState.java:120)
	at java.lang.String.valueOf(String.java:2849)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at com.dtolabs.rundeck.core.rules.StateLogger.toString(StateLogger.java:62)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2838)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2718)
	at java.util.Formatter.format(Formatter.java:2488)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2792)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.processOperations(WorkflowEngine.java:106)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.executeWorkflowImpl(EngineWorkflowExecutor.java:305)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:317)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor$DispatchedWorkflow.dispatch(NodeFirstWorkflowExecutor.java:383)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:118)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:64)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:165)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWFSectionNodeDispatch(NodeFirstWorkflowExecutor.java:189)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:110)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:317)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
```

This affects all Jobs, means there is no particular Job which may always cause an OOME, it's random in time and Job. Maybe it is a race condition which initially causes this behaviour, because whenever it happens it looks like two Jobs were started closely together, but sometimes it just working for days before it again fails. 

When looking at the Source it's just a Map<String, String> which gets concatenated so I wonder how many elements are needed to exceed the StringBuilder 1GB capacity or if there is a infinite loop while performing toString()? 

While googling I found a similar issue related to a JSON Parser which just went mad and added chars in loop due to a parser bug. At the very end the StringBuilder char[] limit was reached causing an OOME (https://github.com/spray/spray-json/issues/122) similar to what I get.

**How to reproduce Behavior**

Difficult, occurs randomly

Thanks in advance

Jens

**Comment by gschueler** [comment]
how many steps and nodes do the jobs operate on?

**Comment by t-o-c** [comment]
It's a single node deployment. Each Job usually consists of one step, all executed locally

**Comment by ahonor** [comment]
@t-o-c Can you show your JVM settings?

**Comment by t-o-c** [comment]
sure!

RDBASE=/home/tomcat/app-data/rundeck
now=`date "+%F_%H.%M.%S"`

CATALINA_OPTS="-Xmx4096m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps \
-Xloggc:$CATALINA_BASE/logs/gc_$now.log \
-Drdeck.base=$RDBASE \
-Drundeck.config.location=$RDBASE/rundeck-config.properties \
-Dfile.encoding=utf-8"
