### ISSUE TITLE
Authentication Issue / HTTP ERROR 403 !role

### ISSUE THREAD

**Issue by s31t0n** [rundeck/rundeck#2717]
Issue type: Bug report/Enhancement Request

Hi all,
i'm getting the following error on Active Directory authentication
```
2017-08-26 17:16:29.576:INFO:cdrjj.JettyCachingLdapLoginModule:qtp722378544-19: Attempting authentication: CN=TestRundeck,CN=Users,DC=testlab,DC=local
2017-08-26 17:16:29.757:WARN:cdrjj.JettyCachingLdapLoginModule:qtp722378544-19: JettyCachingLdapLoginModule: User 'testrundeck' **## has no role membership; role query configuration may be incorrect**
```

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: launcher
* OS Name/version: Mac Os Sierra 10.12.6

My configuration files;

**# realm.properties**
Default setup

**# jaas-activedirectory.conf**
```

activedirectory {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldap://testlab.local:389"
    bindDn="rundeck.sync@testlab.local"
    bindPassword="nowayToGetItWorking_"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn="CN=Users,DC=testlab,DC=local"
    userRdnAttribute="cn"
    userIdAttribute="cn"
    userPasswordAttribute="unicodePwd"
    userObjectClass="user"
    roleBaseDn="CN=Users,DC=Testlab,DC=local"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="0"
    reportStatistics="true";
    };
```
my **# profile**
```

RDECK_BASE=/Users/testLab/Desktop/rundeck
export RDECK_BASE

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
export JAVA_HOME

PATH=$JAVA_HOME/bin:$RDECK_BASE/tools/bin:$PATH
export PATH

export JAVA_CMD=$JAVA_HOME/bin/java

if test -n "$JRE_HOME"
then
   unset JRE_HOME
fi

LIBDIR=$RDECK_BASE/tools/lib

CLI_CP=
for i in `ls $LIBDIR/*.jar`
do
 CLI_CP=${CLI_CP}:${i}
done
export CLI_CP


#
# Set min/max heap size
#
export RDECK_JVM="$RDECK_JVM -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server"
export RDECK_JVM="-Xmx1024m -Dloginmodule.conf.name=jaas-activedirectory.conf -Djava.security.auth.login.config=jaas-activedirectory.conf -Dloginmodule.name=activedirectory "

export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=$RDECK_BASE/etc/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

umask 002

```
And the **## web.xml** file has the default setup,
```
	<security-role>
		<role-name>user</role-name>
	</security-role>
```
Could you please advise on what i'm doing wrong here? 
Thanks in advance.

**Comment by gschueler** [comment]
The `roleBaseDn` should be the base DN for directory path to whatever you consider 
as "groups"/"roles".  The value `CN=Users,DC=Testlab,DC=local` seems like it is pointing at the Users group.

`has no role membership;` is telling you that the directory search for groups/roles for the user is not matching anything.  This probably means your roleBaseDn or other role* attributes for the jaas configuration are not correct.

The error `!role` means one thing: the roles found for the user (in your case, none) do not match the required `<security-role>` in web.xml.  Typically people leave the value in web.xml as `user` in the `<security-role>` and use it as a dummy role. You can then add `supplementalRoles="user"` in your jaas config, which will append `user` to any roles discovered via the directory.  This will let any user who can log in to your AD also log in to Rundeck.  In cases where that is not desired, you would change web.xml to specify an actual role/group name that you require them to be in to access Rundeck.

Since you do not have `supplementalRoles`, and perhaps your role query is wrong, you are apparently logging in to AD correctly, but ending up with 0 roles, and since `user` is not among them, you are getting the `!role` response.  HTH

**Comment by s31t0n** [comment]
Hi gschueler
so you saying that if i change on my web.xml the security role from user to Users, it will work?
in any case when ever i change the value on web.xml, on next restart they get overwritten to default.
By the way, i need also a couple of other features please, i need hybric authetication Local and Active Directory Users, and also if there is any possibility to add multiple roles?

Thanks in advance.

**Comment by s31t0n** [comment]
Hi gschueler,
finaly i configured it out to work with active directory and multiple roles,
now i'm trying to configure hybrid logins AD and Local users,
but i'm gettin the follwing errors,

```
`2017-08-31 06:28:34.721:WARN:oejj.JAASLoginService:qtp1128032093-14: 
javax.security.auth.login.LoginException: java.lang.IllegalStateException: JettyRolePropertyFileLoginModule must have useFirstPass or tryFirstPass set to true|?at org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule.initialize(JettyRolePropertyFileLoginModule.java:57)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)|?at java.lang.reflect.Method.invoke(Unknown Source)|?at javax.security.auth.login.LoginContext.invoke(Unknown Source)|?at javax.security.auth.login.LoginContext.access$000(Unknown Source)|?at javax.security.auth.login.LoginContext$4.run(Unknown Source)|?at javax.security.auth.login.LoginContext$4.run(Unknown Source)|?at java.security.AccessController.doPrivileged(Native Method)|?at javax.security.auth.login.LoginContext.invokePriv(Unknown Source)|?at javax.security.auth.login.LoginContext.login(Unknown Source)|?at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)|?at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)|?at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)|?at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)|?at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)|?at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)|?at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)|?at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)|?at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)|?at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)|?at org.eclipse.jetty.server.Server.handle(Server.java:446)|?at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)|?at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)|?at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)|?at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)|?at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)|?at java.lang.Thread.run(Unknown Source)|
	at javax.security.auth.login.LoginContext.invoke(Unknown Source)
	at javax.security.auth.login.LoginContext.access$000(Unknown Source)
	at javax.security.auth.login.LoginContext$4.run(Unknown Source)
	at javax.security.auth.login.LoginContext$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(Unknown Source)
	at javax.security.auth.login.LoginContext.login(Unknown Source)
	at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Unknown Source)

`
```
My configuration,
```
    cacheDurationMillis="0"
    reportStatistics="true";

    org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
    debug="true"
    file="/opt/rundeck/server/config/realm.properties";
};

```
Could you please advice?.

Thanks.
