### ISSUE TITLE
Is it supported: JAAS JDBC MySQL: No suitable driver found

### ISSUE THREAD

**Issue by oben59** [rundeck/rundeck#2723]
I installed Rundeck 2.9.3-1 in Debian Stretch with a deb package

I found description on How to implement JAAS for propertyfile and LDAP. I would like to use a MySQL JDBC connection to authenticate my users but there is no documentation. Is it supported? 

I tried this configuration in /etc/rundeck/jaas-loginmodule.conf:     
```
RDjdbclogin {       
org.eclipse.jetty.jaas.spi.JDBCLoginModule required   
debug="true"    
dbUrl="jdbc:mysql://rundeck_mysql/rundeckdb?autoReconnect=true"    
dbUserName="rundeck"   
dbPassword="*****"   
dbDriver="com.mysql.jdbc.Driver"    
userTable="user"   
userField="user"   
credentialField="password"    
userRoleTable="userrole"   
userRoleUserField="user"   
userRoleRoleField="role";    
};
```
And changed the login module name to RDjdbclogin
The MySQL Connector is available in classpath, I don't have a Class not found exception but I get:

> javax.security.auth.login.LoginException: java.sql.SQLException: No suitable driver found for jdbc:mysql://rundeck_mysql/rundeckdb?autoReconnect=true
	at org.eclipse.jetty.jaas.spi.AbstractLoginModule.login(AbstractLoginModule.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)

Tried to add directly a jar with the Driver in the bootstrap but no success

Thanks in advance

**Comment by krzwalko** [comment]
Try download MySQL Connector/J and then put proper JDBC driver jar file (ie. mysql-connector-java-5.1.44-bin.jar) into your server/lib directory.

**Comment by oben59** [comment]
Thanks for your response but it doesn't work.
In fact there is already a mysql-connector jar in this directory
```
ls -la /var/lib/rundeck/exp/webapp/WEB-INF/lib/ | grep mysql
-rw-r--r-- 1 rundeck rundeck  968668 Apr 13  2015 mysql-connector-java-5.1.35.jar
```
With it or the newer version it still raises the SQLException no suitable driver

I think the class is available in classpath (it can be used for the projects configuration) as if I put an invalid classname instead of com.mysql.jdbc.Driver I'm getting a ClassNotFoundException. 

Just started looking at the sources. I'm no java developer so I'm quite lost. I'm searching for where the login module is loaded from the configuration.

**Comment by gschueler** [comment]
@oben59 try putting it under `/var/lib/rundeck/bootstrap`

**Comment by oben59** [comment]
Hello @gschueler, thank you for your response. Just tried again, still not working
In fact I also did this just to test:
``` 
find /var/lib/rundeck -type d -exec cp /var/lib/rundeck/exp/webapp/WEB-INF/lib/mysql-connector-java-5.1.35.jar {} \;
``` 
This command copies the mysql connector jar everywhere in the /var/lib/rundeck folders and subfolders. And I still have the same error in log! :/

It seems the issue is not about the mysql Driver missing, but something about it not being able to handle the connection in this context. 
I just double checked and I can connect using the same connection string in a simple main.

Am I wrong stating that all the authentication and the JdbcLoginModule loading is handled by Jetty itself? I don't see anything apart from the configureJaasRealms in RunServer

**Comment by gschueler** [comment]
yes the jetty server handles the login via jaas.  If you put it in the bootstrap dir and it still fails with `No suitable driver found for ...` then I don't know why

**Comment by sjrd218** [comment]
@oben59 Please try your configuration with Rundeck 3.x and let us know if the issue is resolved.
