### ISSUE TITLE
Random job failure (percona xtradb cluster)

### ISSUE THREAD

**Issue by moreiramarti** [rundeck/rundeck#2771]
Issue type: Bug report

* Rundeck version: 2.9.2
* install type: deb
* OS Name/version: Debian 9
* DB Type/version: percona xtradb cluster and proxysql to loadbalance connections

**Expected Behavior**

Job run every minute.

**Actual Behavior**

Randomly, I got an error on the job. In the interface, I have : 
Execution Summary and Report detail is not available.

When I check the logs, I have :

2017-09-21 14:50:00,409 [quartzScheduler_Worker-10] [SERVER] ERROR grails.app.jobs.rundeck.quartzjobs.ExecutionJob - Failed execution 147426 : No row with the given identifier exists: [rundeck.Execution#147426]; nested exception is org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.Execution#147426]
org.springframework.orm.hibernate4.HibernateObjectRetrievalFailureException: No row with the given identifier exists: [rundeck.Execution#147426]; nested exception is org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.Execution#147426]
	at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy:915)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:530)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:468)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:540)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:164)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)

Here some logs from mysql : 
*** Priority TRANSACTION:
TRANSACTION 30097332, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
MySQL thread id 6, OS thread handle 140328475150080, query id 2041200 wsrep: writing row for write-set (5237463)
, undo log entries 1
*** Victim TRANSACTION:
MySQL thread id 21059, OS thread handle 140318399395584, query id 2041188 eileo_proxysql.1.22v5fi5aezdsyelqdwu4v7zb4.eileo_percona 10.0.2.17 rundeck
, undo log entries 8
TRANSACTION 30097328, ACTIVE 0 sec
*** WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 900 page no 2668 n bits 176 index PRIMARY of table `rundeckdb`.`workflow_step` trx id 30097328 lock mode S
2017-09-21T12:37:00.106221Z 6 [Note] WSREP: --------- CONFLICT DETECTED --------
2017-09-21T12:37:00.106231Z 6 [Note] WSREP: cluster conflict due to high priority abort for threads:
   SQL: (null)
   THD: 6, mode: applier, state: executing, conflict: no conflict, seqno: 5237463
2017-09-21T12:37:00.106241Z 6 [Note] WSREP: Winning thread: 
2017-09-21T12:37:00.106247Z 6 [Note] WSREP: Victim thread: 
   THD: 21059, mode: local, state: idle, conflict: no conflict, seqno: -1
   SQL: (null)

**How to reproduce Behavior**

I think you can do it by setting up a percona cluster and run a job every minute. It seems to happen when 2 mysql session try to modify workflow or workflow_step table.

**Comment by zhjchen** [comment]
I experience the same issue.

ENV:
docker swarm 
Rundeck 2.9.2
galera maria two instances.

scheduled job supposed to run every hour. Sometimes see the following issues.  

```
ERROR ExecutionJob: Failed execution 1750 : No row with the given identifier exists: [rundeck.Execution#1750]; nested exception is org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.Execution#1750]
org.springframework.orm.hibernate4.HibernateObjectRetrievalFailureException: No row with the given identifier exists: [rundeck.Execution#1750]; nested exception is org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.Execution#1750]
	at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy:915)
	at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:344)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:143)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.Execution#1750]
	... 8 more

```

**Comment by moreiramarti** [comment]
@zhjchen I switched to a single mysql node until rundeck supports mysql with galera mode
