### ISSUE TITLE
Job completes all steps successfully and gets stuck until it is killed by a timeout exception

### ISSUE THREAD

**Issue by tomkregenbild** [rundeck/rundeck#2776]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.3
* install type: deb
* OS Name/version: ubuntu 14.04
* DB Type/version: mysql

**Expected Behavior**
Scheduled jobs should finish with "Succeeded" status when all steps are done succesfuly 

**Actual Behavior**
Randomly, all steps end properly but the job itself continue running until it is killed by the timeout. 

The log output looks like this:
`Caught an exception, leaving main loop due to Socket closed
[workflow] finishExecuteNodeStep(SERVER1): NodeDispatch: Succeeded
1: Workflow step finished, result: Dispatch successful (1 nodes)
[workflow] Finish step: 1,NodeDispatch
Exception in thread "pool-161057-thread-1" java.lang.IllegalStateException: output was closed
	at sun.reflect.GeneratedConstructorAccessor422.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.dtolabs.rundeck.app.internal.logging.FSStreamingLogWriter.addEvent(FSStreamingLogWriter.groovy:72)
	at sun.reflect.GeneratedMethodAccessor537.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:176)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:183)
	at rundeck.services.logging.MultiLogWriter.addEvent(MultiLogWriter.groovy:45)
	at com.dtolabs.rundeck.core.logging.StreamingLogWriter$addEvent$0.call(Unknown Source)
	at rundeck.services.logging.LoglevelThresholdLogWriter.addEvent(LoglevelThresholdLogWriter.groovy:38)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.addEvent(OverridableStreamingLogWriter.java:48)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.addEvent(OverridableStreamingLogWriter.java:48)
	at com.dtolabs.rundeck.core.logging.ContextLogWriter.verbose(ContextLogWriter.java:54)
	at com.dtolabs.rundeck.core.execution.workflow.LoggerWithContext.logInternal(LoggerWithContext.java:72)
	at com.dtolabs.rundeck.core.execution.workflow.LoggerWithContext.log(LoggerWithContext.java:44)
	at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.log(ContextualExecutionListener.java:82)
	at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListenerImpl.log(WorkflowExecutionListenerImpl.java:39)
	at com.dtolabs.rundeck.core.execution.ExecutionLogger$log.call(Unknown Source)
	at com.dtolabs.rundeck.app.internal.workflow.MultiWorkflowExecutionListener.log(MultiWorkflowExecutionListener.groovy:125)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.lambda$buildWorkflowSystem$34(EngineWorkflowExecutor.java:315)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:224)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:217)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor$1.onSuccess(WorkflowEngineOperationsProcessor.java:203)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor$1.onSuccess(WorkflowEngineOperationsProcessor.java:200)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: output was closed
	at sun.reflect.GeneratedConstructorAccessor422.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.dtolabs.rundeck.app.internal.logging.FSStreamingLogWriter.addEvent(FSStreamingLogWriter.groovy:72)
	at sun.reflect.GeneratedMethodAccessor537.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:176)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:183)
	at rundeck.services.logging.MultiLogWriter.addEvent(MultiLogWriter.groovy:45)
	at com.dtolabs.rundeck.core.logging.StreamingLogWriter$addEvent$0.call(Unknown Source)
	at rundeck.services.logging.LoglevelThresholdLogWriter.addEvent(LoglevelThresholdLogWriter.groovy:38)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.addEvent(OverridableStreamingLogWriter.java:48)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.addEvent(OverridableStreamingLogWriter.java:48)
	at com.dtolabs.rundeck.core.logging.ContextLogWriter.verbose(ContextLogWriter.java:54)
	at com.dtolabs.rundeck.core.execution.workflow.LoggerWithContext.logInternal(LoggerWithContext.java:72)
	at com.dtolabs.rundeck.core.execution.workflow.LoggerWithContext.log(LoggerWithContext.java:44)
	at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.log(ContextualExecutionListener.java:82)
	at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListenerImpl.log(WorkflowExecutionListenerImpl.java:39)
	at com.dtolabs.rundeck.core.execution.ExecutionLogger$log.call(Unknown Source)
	at com.dtolabs.rundeck.app.internal.workflow.MultiWorkflowExecutionListener.log(MultiWorkflowExecutionListener.groovy:125)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.lambda$buildWorkflowSystem$34(EngineWorkflowExecutor.java:315)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:224)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:217)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:213)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.continueProcessing(WorkflowEngineOperationsProcessor.java:126)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.beginProcessing(WorkflowEngineOperationsProcessor.java:79)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.processOperations(WorkflowEngine.java:96)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.executeWorkflowImpl(EngineWorkflowExecutor.java:249)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor$DispatchedWorkflow.dispatch(NodeFirstWorkflowExecutor.java:451)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:133)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:67)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:203)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:179)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWFSectionNodeDispatch(NodeFirstWorkflowExecutor.java:246)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:113)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:120)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
Exception: class java.lang.IllegalStateException: output was closed
[workflow] Finish execution:  node-first: [Workflow result: , exception: java.lang.IllegalStateException: output was closed, flow control: Continue, status: failed]
output was closed
java.lang.IllegalStateException: output was closed
	at sun.reflect.GeneratedConstructorAccessor422.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.dtolabs.rundeck.app.internal.logging.FSStreamingLogWriter.addEvent(FSStreamingLogWriter.groovy:72)
	at sun.reflect.GeneratedMethodAccessor537.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:176)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:183)
	at rundeck.services.logging.MultiLogWriter.addEvent(MultiLogWriter.groovy:45)
	at com.dtolabs.rundeck.core.logging.StreamingLogWriter$addEvent$0.call(Unknown Source)
	at rundeck.services.logging.LoglevelThresholdLogWriter.addEvent(LoglevelThresholdLogWriter.groovy:38)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.addEvent(OverridableStreamingLogWriter.java:48)
	at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:37)
	at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.addEvent(OverridableStreamingLogWriter.java:48)
	at com.dtolabs.rundeck.core.logging.ContextLogWriter.verbose(ContextLogWriter.java:54)
	at com.dtolabs.rundeck.core.execution.workflow.LoggerWithContext.logInternal(LoggerWithContext.java:72)
	at com.dtolabs.rundeck.core.execution.workflow.LoggerWithContext.log(LoggerWithContext.java:44)
	at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.log(ContextualExecutionListener.java:82)
	at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListenerImpl.log(WorkflowExecutionListenerImpl.java:39)
	at com.dtolabs.rundeck.core.execution.ExecutionLogger$log.call(Unknown Source)
	at com.dtolabs.rundeck.app.internal.workflow.MultiWorkflowExecutionListener.log(MultiWorkflowExecutionListener.groovy:125)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.lambda$buildWorkflowSystem$34(EngineWorkflowExecutor.java:315)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:224)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:217)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.event(WorkflowEngine.java:213)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.continueProcessing(WorkflowEngineOperationsProcessor.java:126)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.beginProcessing(WorkflowEngineOperationsProcessor.java:79)
	at com.dtolabs.rundeck.core.rules.WorkflowEngine.processOperations(WorkflowEngine.java:96)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.executeWorkflowImpl(EngineWorkflowExecutor.java:249)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor$DispatchedWorkflow.dispatch(NodeFirstWorkflowExecutor.java:451)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:133)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:67)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:203)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:179)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWFSectionNodeDispatch(NodeFirstWorkflowExecutor.java:246)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:113)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:120)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
`

**How to reproduce Behavior**
Create a very frequent schedule job with one easy step and a timeout and look for the jobs that fail with a timeout exception

**Comment by gschueler** [comment]
If you run the job with Debug level logging, is there any indication of why the job does not complete?

**Comment by tomkregenbild** [comment]
@gschueler The relevant line to the failure is this:
`
Exception in thread "pool-64410-thread-1" java.lang.IllegalStateException: output was closed
`

If for example the job is running for 10 seconds I will get the line above at the end of the step, after it was completed successfully and then nothing else will happen in the log until the timeout 

When the timeout hits I see the following lines:
`
Exception: class java.lang.IllegalStateException: output was closed
--
05:30:00 |   |   | [workflow] Finish execution:  node-first: [Workflow result: , exception: java.lang.IllegalStateException: output was closed, flow control: Continue, status: failed]
05:30:00 |   |   | output was closed

`

**Comment by tomkregenbild** [comment]
Can anyone provide any guidelines on how to debug this? the job log is on Debug and the output above is the only thing I see
