### ISSUE TITLE
2.9.x jvm issue

### ISSUE THREAD

**Issue by lancepowell** [rundeck/rundeck#2850]
Issue type: Bug report

**My Rundeck detail**
JVM Settings:
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx12288m -Xms12288m -XX:MaxMetaspaceSize=256m -server}"

Java Version:
java version "1.8.0_144"

* Rundeck version: 2.9.4
* install type: (rpm,deb,war,launcher?) RPM
* OS Name/version: Centos 7
* DB Type/version: mysql

**Expected Behavior**
Have around 1000 nodes that we run multiple jobs on. Expect these jobs to complete and run on the specified nodes. We run without issues on 2.8 and prior with the same number of nodes and the same jvm settings.

**Actual Behavior**
Getting the below:
Exception while executing step [1]: [java.lang.OutOfMemoryError: unable to create new native thread]

Exception in thread "pool-242-thread-1" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:484)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-396-thread-1" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**How to reproduce Behavior**

Doesn't happen with smaller nodes jobs, only with the larger nodes.

**Comment by gschueler** [comment]
try removing or reducing the `-Xms` setting (minimum size).

**Comment by lancepowell** [comment]
Was thinking that was going to be it, but unfortunately not. Same behavior, tried a few lower ones and removing it. The box is fine too, has about 16 GB on it.

**Comment by gschueler** [comment]
what is your system info from rundeck? (specifically number of concurrent threads and jobs being run, memory usage)
what is your `ulimit -a`?

**Comment by lancepowell** [comment]
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63444
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
we run rundeck at 30 concurrent threads
`quartz.props.threadPool.threadCount = 30`

Only 1 or 2 jobs ran at a time, we only have rundeck on the box and run around 80% memory used.

Looks like a thread issue but just don't see what with 2.9 would be causing it with our config vs 2.8.

**Comment by lancepowell** [comment]
Fixed. ulimit issue with max user processes. When watching threads with `ps -elfT |wc -l ` we would hit around 25000. Set the rundeck user to 65535 via the /etc/security/limits.conf file
```
rundeck soft nproc 65535
rundeck hard nproc 65535
```
