### ISSUE TITLE
java.lang.IllegalStateException: stack is empty

### ISSUE THREAD

**Issue by vinillum** [rundeck/rundeck#2914]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.0, 2.9.4
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux 6.7
* DB Type/version: mysql 14.14

**Expected Behavior**

Job succeeds

**Actual Behavior**

Job fails with the following:

```
11:44:03 | localhost | 29. Checking server state | Exception while executing step [29]: [java.lang.IllegalStateException: stack is empty]
-- | -- | -- | --
11:44:03 |   |   | java.lang.RuntimeException: java.lang.IllegalStateException: stack is empty
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:87)
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:73)
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:31)
11:44:03 |   |   | at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$processRunnableOperations$27(WorkflowEngineOperationsProcessor.java:197)
11:44:03 |   |   | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:44:03 |   |   | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11:44:03 |   |   | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11:44:03 |   |   | at java.lang.Thread.run(Thread.java:745)
11:44:03 |   |   | Caused by: java.lang.IllegalStateException: stack is empty
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.ContextStack.pop(ContextStack.java:69)
11:44:03 |   |   | at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.removeOverride(OverridableStreamingLogWriter.java:99)
11:44:03 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.end(LoggingManagerImpl.java:154)
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:100)
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:291)
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:687)
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
11:44:03 |   |   | ... 7 more
11:44:03 |   |   | Exception while executing step [29]: 	[java.lang.RuntimeException: java.lang.IllegalStateException: stack is empty]
11:44:03 |   |   | Exception in thread "Thread-27790" java.lang.IllegalStateException: stack is empty
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.workflow.ContextStack.pop(ContextStack.java:69)
11:44:03 |   |   | at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.removeOverride(OverridableStreamingLogWriter.java:99)
11:44:03 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.end(LoggingManagerImpl.java:154)
11:44:03 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:134)
11:44:03 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
11:44:03 |   |   | Execution failed: 2610262 in project xxxx: null
```

**How to reproduce Behavior**

I have not found a way to reproduce this error, it seems to happen randomly, however this issue only started since we upgraded from 2.9.2 to 2.10.0 (same issue spotted even in 2.9.4 after we downgraded to it).

**Comment by vinillum** [comment]
Worth mentioning that even on the same job, with the same parameters, it fails with this error on different steps each time.

**Comment by puremourning** [comment]
I have seen this regularly on 2.9.4 also. Along with random NullPointerExceptions (with no stack trace) and the other IllegalStateExceptions. I'm hoping that they are all fixed by https://github.com/rundeck/rundeck/issues/2887

**Comment by pbenas** [comment]
I have just seen the same stacktrace in my Rundeck 2.10.0.

**Comment by gschueler** [comment]
I believe this is the same as #2887 , if you want to try the 2.10.1-SNAPSHOT, it is available here https://bintray.com/rundeck/

**Comment by luyidong** [comment]
me too,how to solve?

os system : debian-8.6
rundeck : rundeck-launcher-2.10.2.jar

output log:

Workflow is empty. Stacktrace follows:
java.lang.Exception: Workflow is empty
at rundeck.services.ExecutionUtilService.createExecutionItemForWorkflow(ExecutionUtilService.groovy:139)
at rundeck.services.ScheduledExecutionService.validateWorkflowStrategyPlugin(ScheduledExecutionService.groovy:3462)
at rundeck.services.ScheduledExecutionService._dovalidate(ScheduledExecutionService.groovy:3266)
at rundeck.services.ScheduledExecutionService._dosave(ScheduledExecutionService.groovy:2928)
at rundeck.controllers.ScheduledExecutionController$_save_closure70.doCall(ScheduledExecutionController.groovy:2436)
at org.grails.plugins.web.rest.api.ControllersRestApi.withForm(ControllersRestApi.groovy:53)
at rundeck.controllers.ScheduledExecutionController.save(ScheduledExecutionController.groovy:2430)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:446)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
at java.lang.Thread.run(Thread.java:745)
