### ISSUE TITLE
Issue with SmarterCommerce SOAP check (System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: )

### ISSUE THREAD

**Issue by SumantMaurya** [rundeck/rundeck#2926]
I am getting following error wile doing SOAP check. Please suggest

First parameter is http://pite1sc02d.amer.thermo.com/SmarterCommerce_PaymentService40/PaymentProcessingService.asmx
Second parameter is http://www.premierway.com/webservices/SubmitAuthorization
Third paramer is /home/jde900/soap/SC/req.xml
Curl invoke command used
+ curl -s -k -H $'SOAPACTION: \'http://www.premierway.com/webservices/SubmitAuthorization\'' -X POST -H 'Content-type: text/xml;charset=UTF-8' -d @/home/jde900/soap/SC/req.xml http://pite1sc02d.amer.thermo.com/SmarterCommerce_PaymentService40/PaymentProcessingService.asmx
+ 1> result.xml
\n The result of the SOAP call :
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault>**<faultcode>soap:Client</faultcode><faultstring>System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: 'http://www.premierway.com/webservices/SubmitAuthorization'.**
   at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.RouteRequest(SoapServerMessage message)
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean&amp; abortProcessing)</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>-----------------------------
Result is Failure

**Comment by ahonor** [comment]
This does not look Rundeck specific.
