### ISSUE TITLE
Jobs with file upload fail to run

### ISSUE THREAD

**Issue by leonboot** [rundeck/rundeck#2989]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.0-1
* install type: deb (using the bintray repo)
* OS Name/version: Ubuntu 16.04.3
* DB Type/version: mysql

**Expected Behavior**

Creating jobs with a file upload field should run fine, but actually result in an SQL error when running the job.

**How to Reproduce**

* Create a job with a file upload field named 'myfile'
* Add a script step and echo the file name and its contents:
  ```shell
  echo @myfile.file.fileName@
  cat "@myfile.file@"
  ```
* Save the job and run it
* An error appears: `Field 'user' doesn't have a default value`

**Additional info**

I have installed Rundeck using the Bintray repo waybackwhen, probably when it was still at version 2.7. Rundeck was updated by `apt upgrade` ever since. Maybe the database migrations of a certain update did not perform the correct structure updates?

Here's the stack trace from the Rundeck logs:
```
2017-12-11 11:10:01,804 [qtp189568618-46240] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - SQLException occurred when processing request: [POST] /project/myproject/job/index
Field 'user' doesn't have a default value. Stacktrace follows:
java.sql.SQLException: Field 'user' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at rundeck.services.FileUploadService.createRecord(FileUploadService.groovy:237)
	at rundeck.services.FileUploadService.$tt__receiveFile(FileUploadService.groovy:147)
	at rundeck.controllers.ScheduledExecutionController.handleUploadFiles(ScheduledExecutionController.groovy:3067)
	at rundeck.controllers.ScheduledExecutionController.scheduleJob(ScheduledExecutionController.groovy:2965)
	at rundeck.controllers.ScheduledExecutionController$_runOrScheduleJob_closure86.doCall(ScheduledExecutionController.groovy:2873)
	at org.grails.plugins.web.rest.api.ControllersRestApi.withForm(ControllersRestApi.groovy:53)
	at rundeck.controllers.ScheduledExecutionController.runOrScheduleJob(ScheduledExecutionController.groovy:2872)
	at rundeck.controllers.ScheduledExecutionController.runJobNow(ScheduledExecutionController.groovy:2862)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gschueler** [comment]
it sounds like your schema differs from the one created in a fresh install, I think.

the JobFileRecord table should have a `rduser` column (not `user`), that might be the problem

**Comment by leonboot** [comment]
@gschueler thanks for the info; it seems the table has both fields here. Probably the result of a faulty database migration between version updates? Anyway, removing the `user` field from the table fixed the issue! 👍
