### ISSUE TITLE
Error initializing the application in IDEA

### ISSUE THREAD

**Issue by dulio** [rundeck/rundeck#2992]
Issue type: report

* Rundeck version: 2.9.4
* OS Name/version: Windows10
* DB Type/version: mysql

I can package Rundeck normally by gradle build
However, I debug Rundeck in IDEA by grails. I received error message:

```
ERROR  error, Error initializing the application: Cannot invoke method registerApiMarshallers() on null object
java.lang.NullPointerException: Cannot invoke method registerApiMarshallers() on null object
	at BootStrap$_closure1.doCall(BootStrap.groovy:77)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:788)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:434)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:780)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:284)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1322)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:732)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:490)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
	at org.eclipse.jetty.server.Server.start(Server.java:342)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
	at org.eclipse.jetty.server.Server.doStart(Server.java:290)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.grails.jetty.JettyServer.startServer(JettyServer.groovy:138)
	at org.grails.jetty.JettyServer.start(JettyServer.groovy:104)
	at _GrailsRun$_run_closure1.doCall(_GrailsRun.groovy:60)
	at RunApp$_run_closure1.doCall(RunApp:33)
```

I just need some advices, Thanks!

**Comment by sjrd218** [comment]
Rundeck 3.x is much easier to set up. Please try it, and open a new issue if you have problems setting up the new version.
