### ISSUE TITLE
java internal error message for log output when using job timeout 

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#2998]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.1-1 cafe mocha tomato knight 2017-11-21
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: h2

Not much a real bug, it's just disturbing getting an internal java exception as execution log when it's only an error due to the fact the execution timeout expired.

Here's a sample with a job set to a 2h execution timeout, and calling a bash script only looping on a sleep : (time is a little off because of a bad math test)
```
06:00:00			Current PID:53438
06:00:00			----------------------------------------------
06:00:01			Waiting ...
06:59:10			Still waiting after 1 hour
07:59:18			Still waiting after 2 hour
08:00:01			
08:00:01			java.util.concurrent.CancellationException
08:00:01				at java.util.concurrent.FutureTask.report(FutureTask.java:121)
08:00:01				at java.util.concurrent.FutureTask.get(FutureTask.java:192)
08:00:01				at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:135)
08:00:01				at com.google.common.util.concurrent.Futures$4.run(Futures.java:1158)
08:00:01				at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:00:01				at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:00:01				at java.lang.Thread.run(Thread.java:748)
08:00:01			Cancellation while running step [1]
08:00:01			Execution failed: 1146 in project reseau.local: [Workflow result: , step failures: {1=Interrupted: Cancellation while running step [1]}, status: failed]
```

Having instead of the java error log a real message would be helpful.   
Something similar to "Timeout execution time reached (2h) : job cancelled while running step [1]

**Comment by majkinetor** [comment]
I got this problem too and was confused. Job timeout happened after 5s instead of 5m I wanted (I enetered only 5). Then this error appears, and job gets restarted and stucked before doing anything.

**Comment by Daryes** [comment]
For the record, still happening with 4.17.
At least the job is in the "Timeout" state, but the cryptic error message is still here :
```
Failed: Interrupted: java.lang.InterruptedException: Execution interrupted with code: 143
```

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
