### ISSUE TITLE
Failed to update job when importing via API

### ISSUE THREAD

**Issue by vinillum** [rundeck/rundeck#3016]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.2
* install type: rpm
* OS Name/version: RedHat Enterprise Linux 6.8
* DB Type/version: mysql 14.14

**Expected Behavior**

When importing a job via API, we are using the following call:
`curl -kSsv --header "X-Rundeck-Auth-Token:$API_TOKEN" -F xmlBatch=@"job.yaml" "https://localhost:4440/api/21/project/PROJECT/jobs/import?format=yaml&dupeOption=update&uuidOption=remove"`

If the job doesn't exist, then a new job is created just fine, but if you run it a second time, the job fails to update with the following error:

```
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : base
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:540)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag &lt;g:render&gt;: object references an unsaved transient instance - save the transient instance before flushing: rundeck.Workflow
        ... 44 more
```

However, if a remove one of the options (enforced multi-select) from job.yaml, then the job import succeeds everytime:

```
- description: ProduceSDiff?
    enforced: true
    name: DI_ProduceSDiff
    required: true
    value: YES
    values:
    - NO
    - YES

```

However, the now successfully imported job still has the DI_ProduceSDiff option on the job page, but the choice is empty.

**How to Reproduce**

Use the following job definition:

```
- id: 5a3dbabc-6108-41fa-942b-91051becddce
  project: PROJECT
  loglevel: INFO
  sequence:
    keepgoing: false
    strategy: node-first
    commands:
    - description: Producing SDiff
      exec: tclsh ProduceSDiff}"
  description: Produce SDiff
  name: ProduceSDiff
  uuid: 5a3dbabc-6108-41fa-942b-91051becddce
  group: TESTING/DIFF
  options:
  - description: Table to use for old version
    name: DI_OldVersionTable
    required: true
    value: DI
  - description: Table to use for new version
    name: DI_NewVersionTable
    required: true
    value: DI
  - delimiter: ','
    description: Fields to filter
    multivalued: true
    name: DI_FilterFields
  - description: ProduceSDiff?
    enforced: true
    name: DI_ProduceSDiff
    required: true
    value: YES
    values:
    - NO
    - YES
```

Import the job using curl once to create it (it should succeed), then do it again to update (it should now fail).

Then remove the DI_ProduceSDiff option from the file and import again (it should succeed).

Then open the Rundeck page for this job (TESTING/DIFF/ProduceSDiff), you should still see the DI_ProduceSDiff option, but the drop-down menu is hidden.

**Comment by vinillum** [comment]
So the issue seems to stem from the values in DI_ProduceSDiff. If change them to "Y" and "N", instead of "YES" and "NO", then the import succeeds everytime

**Comment by vinillum** [comment]
Closing the issue, if the values are quoted it works as normal, i.e 'YES' instead of YES.

**Comment by gschueler** [comment]
going to reopen the issue to figure out why unquoted `YES` would cause an error
