### ISSUE TITLE
Job fails to find server node

### ISSUE THREAD

**Issue by majkinetor** [rundeck/rundeck#3021]
Issue type: Bug report

I have a project with single job that runs every 5 minutes (there are other projects on the server too). I have bunch of jobs that fail periodically (but generally work OK) with the following output (`testwsd` is the name of the rundeck server). It complains it can't find server node ( I dont use any other nodes ).

```
11:45:00 | testwsd |   | com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[testwsd]}
-- | -- | -- | --
11:45:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
11:45:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
11:45:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
11:45:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
11:45:00 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
11:45:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
11:45:00 |   |   | Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[testwsd]}
11:45:00 |   |   | No matched nodes: MultiNodeSelector{nodenames=[testwsd]}
```

**My Rundeck detail**

* Rundeck version: Rundeck 2.10.1-1
* install type: chocolatey
* OS Name/version:  Windows Server 2012 R2
* DB Type/version: h2

**Comment by majkinetor** [comment]
This is the duplicate of #2942 so I will close this and continue there.
