### ISSUE TITLE
Email notification fails when "Attach output log" 

### ISSUE THREAD

**Issue by bobanahalf** [rundeck/rundeck#3034]
Issue type: Bug report

* Rundeck version: 2.9.3-1
* install type: RPM
* OS Name/version: centos-release-7-3.1611.el7.centos.x86_64
* DB Type/version: h2

**Configuration**
I found a similar issue at #1758. The problem there was nailed down to permissions, so I reviewed my configuration:

- framework.properties is configured with:
`framework.var.dir=/var/lib/rundeck/var`
`framework.tmp.dir=/var/lib/rundeck/var/tmp`
- permissions on these directories are:
 /var/lib/rundeck/var == 775
 /var/lib/rundeck/var/tmp == 775

**Expected Behavior**
Receive an email at the specified addresses.

**Actual Behavior**
When I run a job with "Attach output log", no email is sent. I get the following in service.log.

`INFO  ExecutionUtilService: Execution successful: 281 in project eVIP
ERROR NotificationService: Error sending notification: Notification{eventTrigger='onsuccess', type='email', content='{"recipients":"bobby@vtinfo.com, ann@vtinfo.com","subject":"${job.name} #${job.execid}: Success","attachLog":true}'}: class java.io.IOException: No such file or directory
java.io.IOException: No such file or directory
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at rundeck.services.NotificationService.copyExecOutputToTempFile(NotificationService.groovy:121)
        at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:262)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:147)
        at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:89)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:86)
        at rundeck.services.ExecutionService$_saveExecutionState_closure64.doCall(ExecutionService.groovy:2545)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2446)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:530)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:468)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:540)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:164)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
INFO  ExecutionService: updated scheduled Execution`

**How to Reproduce**
When I run it with "Attach output log" checked, no email.
When I run it with "Attach output log" not checked, I get an email.

Curiously, this was running on Dec 19, then I went on vacation :)

**Comment by gschueler** [comment]
`No such file or directory at java.io.File.createTempFile(File.java:2024)` this implies your java Temp dir setting is not set to a directory that exists or that has appropriate permissions.

I just added a new entry in the FAQ: https://github.com/rundeck/rundeck/wiki/Faq#i-see-an-ioexception-with-a-stacktrace-coming-from-javaiofilecreatetempfile

hth

**Comment by bobanahalf** [comment]
Creating the default tmp directory `/tmp/rundeck` solved my problem. Thank you.

Incidentally, I installed with RPM, but do not have a file at `/etc/sysconfig/rundeckd` as specified in the FAQ.
