### ISSUE TITLE
Slow responsivity & 503 Service Unavailable errors on tomcat-7.0.76

### ISSUE THREAD

**Issue by kristian-lesko** [rundeck/rundeck#3039]
Issue type: Bug report

**My Rundeck detail**
* Rundeck version: 2.9.3, 2.10.1, 2.10.2
* install type: WAR in Tomcat
* OS Name/version: CentOS 7.4
* DB Type/version: postgres

**Expected Behavior**
Rundeck should behave smoothly when working with the UI, and it should not return any 503 Service Unavailable errors when displaying job execution log.

**How to Reproduce**
1. Deploy Rundeck from WAR on tomcat-7.0.76 (available in CentOS 7.4).
2. Run a job and follow its execution's Log Output.

**Additional information**
The following stacktrace appears in Tomcat logs:
```
org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [default] in context with path [] threw exception [org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response] with root cause
java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at java.io.FilterWriter.flush(FilterWriter.java:100)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:113)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Please note that this doesn't happen on **tomcat-7.0.69**, only **tomcat-7.0.76**. I am not 100 % sure whether this is a bug in the way Rundeck interfaces with Tomcat or a regression in Tomcat itself. I hope someone will have encountered a similar problem or will be able to help me debug this. 

Thanks a lot for any insight anyone might provide.

**Comment by gschueler** [comment]
can you try a newer Tomcat 7, or Tomcat 8? if the bug only happens on a specific tomcat version, I'm inclined to not consider that a rundeck issue
