### ISSUE TITLE
No signature of method: com.dtolabs.rundeck.core.logging.LoggingManagerImpl.createManager() when executing Job Reference step

### ISSUE THREAD

**Issue by strdn** [rundeck/rundeck#3137]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.6-1
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: CentOS Linux release 7.4.1708
* DB Type/version: mysql? postgres? h2?.. h2

**Actual Behavior**
Job reference step failed with exception:

```
Exception while executing step [2]: [groovy.lang.MissingMethodException: No signature of method: com.dtolabs.rundeck.core.logging.LoggingManagerImpl.createManager() is applicable for argument types: (java.util.ArrayList) values: [[]]]
```

Full stacktrace:
```
Exception while executing step [2]: [groovy.lang.MissingMethodException: No signature of method: com.dtolabs.rundeck.core.logging.LoggingManagerImpl.createManager() is applicable for argument types: (java.util.ArrayList) values: [[]]]
			java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: com.dtolabs.rundeck.core.logging.LoggingManagerImpl.createManager() is applicable for argument types: (java.util.ArrayList) values: [[]]
  at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:87)
  at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:73)
  at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:31)
  at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$processRunnableOperations$16(WorkflowEngineOperationsProcessor.java:197)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: groovy.lang.MissingMethodException: No signature of method: com.dtolabs.rundeck.core.logging.LoggingManagerImpl.createManager() is applicable for argument types: (java.util.ArrayList) values: [[]]
  at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
  at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:87)
  at rundeck.services.ExecutionService.createJobReferenceContext(ExecutionService.groovy:3088)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1163)
  at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
  at rundeck.services.ExecutionService$_runJobRefExecutionItem_closure81.doCall(ExecutionService.groovy:3191)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  at groovy.lang.Closure.call(Closure.java:414)
  at groovy.lang.Closure.call(Closure.java:430)
  at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:90)
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
  at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:87)
  at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
  at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
  at rundeck.ScheduledExecution.withTransaction(ScheduledExecution.groovy)
  at rundeck.ScheduledExecution$withTransaction$27.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
  at rundeck.services.ExecutionService.runJobRefExecutionItem(ExecutionService.groovy:3172)
  at rundeck.services.ExecutionService.runJobRefExecutionItem(ExecutionService.groovy)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
  at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
  at rundeck.services.ExecutionService.executeWorkflowStep(ExecutionService.groovy:2803)
  at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:97)
  at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:291)
  at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:687)
  at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
  ... 7 more
Exception while executing step [2]: 	[java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: com.dtolabs.rundeck.core.logging.LoggingManagerImpl.createManager() is applicable for argument types: (java.util.ArrayList) values: [[]]]
Execution failed: 161871 in project DI: [Workflow result: , step failures: {2=Unknown: Exception while executing step [2]: 	[java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: com.dtolabs.rundeck.core.logging.LoggingManagerImpl.createManager() is applicable for argument types: (java.util.ArrayList) values: [[]]]}, Node failures: {remotenode1=[]}, status: failed]

```

**How to Reproduce**
add a Job Reference step as a Workflow step to any job (The others steps are not required)

**Comment by gschueler** [comment]
I have not been able to reproduce this issue.

some questions:

* was this an upgrade install?
* if so, were the referenced jobs created before upgrading?
* if you export the job definitions and re-import them, do you still have the problem?
* if you still have the problem, can you post samples of those job definitions?

thanks

**Comment by gjvc** [comment]
I had the same problem when attempting an upgrade from 2.10.8-1 to 2.11.5-1.56.GA

Attempting to run a command on a single node results ( on Rundeck 2.11.5-1 cappuccino seagreen tower 2018-02-02 ) in the following exception.

Failed to start execution: groovy.lang.MissingMethodException: No signature of method: rundeck.services.ExecutionService.pluginControlService() is applicable for argument types: (com.dtolabs.rundeck.core.common.PluginControlServiceImpl) values: [com.dtolabs.rundeck.core.common.PluginControlServiceImpl@651e6e9e]
--
