### ISSUE TITLE
Moderate SCM api usage causes Rundeck to lock up (memory leak?)

### ISSUE THREAD

**Issue by GroovyCarrot** [rundeck/rundeck#3138]
Issue type: Bug report
* Rundeck version: 2.10.6-1
* install type: deb
* OS Name/version: Linux 4.4.0-112-generic
* DB Type/version: local + LDAP

I have a cron job scheduled every 5 minutes that synchronises jobs for each project from it's version control. The cron job runs as a user with a token configured on disk (`/etc/rundeck/tokens.properties`) and has an ACL policy allowing `configure` on `project` for it's username - there is no admin account, as users are controlled with LDAP groups.

It sequentially steps through each project and runs:
* `rd projects scm enable -i import -t git-import`
projects are installed automatically with ansible, so this has to run
* `rd projects scm perform -i import -a initialize-tracking` - with values from `/var/rundeck/projects/${PROJECT}/etc/scm-import.properties`
This seems to be necessary, otherwise it doesn't work properly - it might be a separate bug?
* `rd projects scm status`
* `rd projects scm perform -i import -a remote-pull`
* `rd projects scm perform -i import -a import-all`
* Checks for orphaned jobs, and removes them by comparing ids extracted from:
`rd projects scm inputs -i import -a import-all`
`rd jobs list`
A command for getting/removing orphaned jobs might even be a nice feature?

After running for several hours,`rd` throws the following exception every time it is ran, and Rundeck is completely unusable, and has to be `kill`ed and restarted.
```
java.net.SocketTimeoutException: timeout
        okio.Okio$3.newTimeoutException(Okio.java:210)
        okio.AsyncTimeout.exit(AsyncTimeout.java:288)
        okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
        okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
        okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
        okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
        okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        okhttp3.RealCall.execute(RealCall.java:60)
        retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        org.rundeck.client.util.Client.checkErrorResponseDowngradable(Client.java:157)
        org.rundeck.client.util.Client.apiWithErrorResponseDowngradable(Client.java:595)
        org.rundeck.client.tool.commands.AppCommand.apiWithErrorResponseDowngradable(AppCommand.java:147)
        org.rundeck.client.tool.commands.AppCommand.apiWithErrorResponse(AppCommand.java:76)
        org.rundeck.client.tool.commands.projects.SCM.perform(SCM.java:370)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:498)
        com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:801)
        com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:504)
        com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:371)
        com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:504)
        com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:371)
        com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:504)
        com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:371)
        com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:332)
        org.rundeck.client.tool.Main.main(Main.java:69)
Caused by: java.net.SocketException: Socket closed
        java.net.SocketInputStream.read(SocketInputStream.java:204)
        java.net.SocketInputStream.read(SocketInputStream.java:141)
        okio.Okio$2.read(Okio.java:138)
        okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
#011... 45 more
```

And in the logs for Rundeck, I can see that this exception is thrown every time `rd` sends a `remote-pull` API call (4 projects * 12 times an hour = 48 calls / hour)
```
2018-02-14 19:15:27,632 [qtp1329552164-50585] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [POST] /api/21/project/Services/s
cm/import/action/remote-pull
Cannot get property 'error' on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot get property 'error' on null object
        at rundeck.services.ScmService.performImportAction(ScmService.groovy:1214)
        at rundeck.controllers.ScmController.performScmAction(ScmController.groovy:991)
        at rundeck.controllers.ScmController.apiProjectActionPerform(ScmController.groovy:903)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:540)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:748)
```

Related to #2505? What's interesting is that it doesn't seem to crash Rundeck immediately though.
Some observations:
* `12:10` Start running cron, no issues.
* `19:31:14` The first time the timeout occurs while processing the last project (of 4) and was importing the jobs from quite a large repository - even though it was only importing a single job using the pattern: `rundeck/*\\.ya?ml`.
* `19:36:12` On the next cron run, this time on the second project, while just trying to find orphaned jobs.
* The next cron run it happens again `19:40:48`, second project, all it's doing is running `status`
* All subsequent runs throw the same error, fluctuating over any step on the first and second projects.
* `21:45` all API calls fail.

It's almost certainly resource related. It feels like there's a memory leak somewhere; given that Rundeck locks up on any API call, and seems to free some resource between cron runs - but eventually just lock up. The `NullPointerException` exception may just be a red-herring?

For now I'll just turn the cron down and see how it fares running every 15 minutes.

**Comment by GroovyCarrot** [comment]
Turning the cron down seem to just delay the issue, and systemctl reported normal memory usage, so it isn't likely to be a memory leak? It's almost like the request is just getting stuck somewhere, and rundeck never sends a response.

**Comment by GroovyCarrot** [comment]
So I had a quick look yesterday and noticed it had climbed quite high to 80% after about 4 hours of restarting it. I restarted again and logged memory stats every 30 seconds to see what was happening:
[rundeck-memory.log](https://github.com/rundeck/rundeck/files/1747388/rundeck-memory.log)
I swapped it to log all the stats in case any of them specifically would be helpful.

It actually seems to be constantly consuming more memory, until maybe garbage collection kicks in and frees it up? It has been sitting at >90% memory for 2 hours now though. I don't suppose anything is particularly obvious from the log?

The cron I have runs every 15 minutes from the hour. Sometimes the memory spikes, sometimes it actually dips like 19:45 90%~>50% - but might just be coincidence.

**Comment by SpencerMalone** [comment]
I'm having a similar issue, running 3.0.13. We only use the SCM API to set up version controlled project configuration automatically, so maybe that's unrelated, but we slowly run out of memory once every few weeks. Our heap is rather large (15 gigs+?) with a fairly small set of projects and jobs (10ish projects, maybe a hundred jobs max?), but here is our memory's behavior:

<img width="1656" alt="Screen Shot 2019-03-14 at 11 48 29 AM" src="https://user-images.githubusercontent.com/8786752/54371136-4544ac80-464f-11e9-9a42-217675998b1d.png">

I went and got a heap dump using `jmap`, and here is what I see, with our heap usage at ~62%:

<img width="1239" alt="Screen Shot 2019-03-14 at 11 46 06 AM" src="https://user-images.githubusercontent.com/8786752/54371217-67d6c580-464f-11e9-903b-2ca570cb9668.png">

So, the byte[][], int[][], and long[]s take up a ton of space, and the shown byte[] and int[] seem to be the nested arrays in the byte[][] and int[][]s. When I dig into what these objects are, and their references, they almost all look like this:

<img width="1236" alt="Screen Shot 2019-03-14 at 11 42 33 AM" src="https://user-images.githubusercontent.com/8786752/54371411-b8e6b980-464f-11e9-9746-e38e0f118c41.png">
<img width="1230" alt="Screen Shot 2019-03-14 at 11 43 24 AM" src="https://user-images.githubusercontent.com/8786752/54371415-ba17e680-464f-11e9-80ed-f5eb68beea87.png">
<img width="1228" alt="Screen Shot 2019-03-14 at 11 43 46 AM" src="https://user-images.githubusercontent.com/8786752/54371419-bbe1aa00-464f-11e9-89e2-336007be3042.png">
<img width="1239" alt="Screen Shot 2019-03-14 at 11 44 00 AM" src="https://user-images.githubusercontent.com/8786752/54371424-bd12d700-464f-11e9-8550-b6d5206ae127.png">

Our SCM repo is rather small (it's purely some bash scripts and the job files), so I don't think it's our repo's size at fault, but there are millions of these objects, and they trace back to the git plugins:
<img width="1090" alt="Screen Shot 2019-03-14 at 11 55 01 AM" src="https://user-images.githubusercontent.com/8786752/54371658-298dd600-4650-11e9-971b-418d12f086c1.png">
<img width="1107" alt="Screen Shot 2019-03-14 at 11 55 50 AM" src="https://user-images.githubusercontent.com/8786752/54371664-2c88c680-4650-11e9-813b-c7f083442f96.png">

If y'all think this is unrelated or deserves a new issue, LMK. I'm also willing to provide our heap dump privately.

**Comment by SpencerMalone** [comment]
I think that my memory issues are related to this. Attached is a graph that shows off the derivative of our two instances memory usage. Toward the final day on the graph, I disabled the SCM API and restarted the primary rundeck instance (which causes the backup to temporarily have a memory spike and then drop again as it goes from backup -> primary -> backup). Before disabling the SCM API, the primary always had a much higher memory derivative than the backup, with the only difference being that the primary was serving traffic while the backup did not. After disabling the SCM API usage, they have startlingly similar memory behaviors.

<img width="1668" alt="Image 2019-03-15 at 9 30 12 AM" src="https://user-images.githubusercontent.com/8786752/54435210-5e5c6480-4706-11e9-8625-dd75227dd803.png">

**Comment by SpencerMalone** [comment]
Further evidence now that I've given it a little more time. This is a graph of heap memory used as reported by jmx. The big drop lines up in when I restarted the instance shown in the prior image, but now the long term slope (or lack thereof) is easier to visualize:
<img width="1622" alt="Screen Shot 2019-03-20 at 12 03 03 AM" src="https://user-images.githubusercontent.com/8786752/54658411-a9c69800-4aa3-11e9-997a-124730566ffc.png">

**Comment by sjrd218** [comment]
Managed in issue #5301. This is now fixed.
