### ISSUE TITLE
API Attempting to enable/disable schedule on a job without a schedule throws 500

### ISSUE THREAD

**Issue by guice** [rundeck/rundeck#3164]
Issue type: Bug report

POST to `job/[id]/schedule/enable` or disable for a job without a schedule results in an ugly 500 error. On page:

(formatted for prettiness)
```
No signature of 
   method: rundeck.services.ApiService.renderErrorFormat() is applicable for argument 
   types: (java.lang.Integer, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse) 
   values: 
[500, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse@4247e7d5] 

Possible solutions: renderErrorFormat(javax.servlet.http.HttpServletResponse, java.util.Map)
```

**Headers**
```
X-Rundeck-Auth-Token: dUgkT2ujA8xkzi4IANzSxQPQJytiQlaF
Content-Type: application/json
Accept: application/json
```

**Service.log**
```
==> service.log <==
ERROR GrailsExceptionResolver: MissingMethodException occurred when processing request: [POST] /api/21/job/e640ba7d-6939-46ec-80d9-28e72bff4d30/schedule/disable
No signature of method: rundeck.services.ApiService.renderErrorFormat() is applicable for argument types: (java.lang.Integer, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse) values: [500, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse@638ba7d4]
Possible solutions: renderErrorFormat(javax.servlet.http.HttpServletResponse, java.util.Map). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: rundeck.services.ApiService.renderErrorFormat() is applicable for argument types: (java.lang.Integer, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse) values: [500, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse@638ba7d4]
Possible solutions: renderErrorFormat(javax.servlet.http.HttpServletResponse, java.util.Map)
	at rundeck.controllers.ScheduledExecutionController.apiFlipScheduleEnabled(ScheduledExecutionController.groovy:1302)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:540)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)
```

**My Rundeck detail**

* Rundeck version:  2.10.6

**Expected Behavior**

POST to `job/[id]/schedule/[enable|disable]` on a job without a Schedule should result in the same error provided by `jobs/schedule/enable` 
* `api.error.job.toggleSchedule.notScheduled `: `Cannot toggle schedule for Job {{Job e640ba7d-6939-46ec-80d9-28e72bff4d30}}: not a scheduled Job`

**How to Reproduce**

* Create a new job, don't give it a schedule
* Attempt to enable/disable the schedule directly via the `job/[id]/` API

**Comment by fgutierrezz** [comment]
The issue also happens in 3.0.20
