### ISSUE TITLE
Cannot get property 'executionState' on null object

### ISSUE THREAD

**Issue by zhjchen** [rundeck/rundeck#3165]
Issue type: Bug report/Enhancement Request

> Request: /project/compaction/activity?max=20&offset=0
Message: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:form>: Error executing tag <g:render>: Cannot get property 'executionState' on null object
Caused by: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:form>: Error executing tag <g:render>: Cannot get property 'executionState' on null object
Class: gsp_rundeck_reports_baseReport_gsp
At Line: [528]
Code Snippet:

> Stack Trace
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:form>: Error executing tag <g:render>: Cannot get property 'executionState' on null object
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:446)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <g:form>: Error executing tag <g:render>: Cannot get property 'executionState' on null object
at gsp_rundeck_reportsindex_gsp$_run_closure2.doCall(gsp_rundeck_reportsindex_gsp.groovy:91)
at gsp_rundeck_reportsindex_gsp.run(gsp_rundeck_reportsindex_gsp.groovy:94)
... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:form>: Error executing tag <g:render>: Cannot get property 'executionState' on null object
at gsp_rundeck_reports_eventsFragment_gsp.run(gsp_rundeck_reports_eventsFragment_gsp.groovy:192)
... 46 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Cannot get property 'executionState' on null object
at gsp_rundeck_reports_eventsFragment_gsp$_run_closure3.doCall(gsp_rundeck_reports_eventsFragment_gsp.groovy:137)
at rundeck.UtilityTagLib$_closure51.doCall(UtilityTagLib.groovy:1100)
... 47 more
Caused by: java.lang.NullPointerException: Cannot get property 'executionState' on null object
at gsp_rundeck_reports_baseReport_gsp.run(gsp_rundeck_reports_baseReport_gsp.groovy:67)
... 49 more

**My Rundeck detail**

* Rundeck version: 2.10.6-1
* install type: deb
* OS Name/version: EL7
* DB Type/version: mysql
rundeck run as root,
`root        19 10.6  1.1 18368748 2199824 ?    Sl   21:34   4:19 java -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf -Dloginmodule.name=RDpropertyfilelogin -Drdeck.config=/etc/rundeck -Drdeck.base=/var/lib/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/lib/rundeck/data -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Dloginmodule.name=ldap -Djava.io.tmpdir=/tmp/rundeck -Drundeck.jetty.connector.forwarded=true -Xmx8192m -Xms512m -server -cp /var/lib/rundeck/bootstrap/jetty-jaas-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jna-3.2.2.jar:/var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-io-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-server-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/libpam4j-1.5.jar:/var/lib/rundeck/bootstrap/not-yet-commons-ssl-0.3.17.jar:/var/lib/rundeck/bootstrap/jetty-http-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/log4j-1.2.16.jar:/var/lib/rundeck/bootstrap/javax.servlet-3.0.0.v201112011016.jar:/var/lib/rundeck/bootstrap/jetty-util-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/rundeck-jetty-server-2.10.6.jar:/var/lib/rundeck/bootstrap/jetty-security-9.0.7.v20131107.jar: com.dtolabs.rundeck.RunServer /var/lib/rundeck 4441
`

**What I did**

I delete all logs from table execution and table log_file_storage_request, but still get the above exception when I try to access Activity page

**Comment by dfraga3** [comment]
Was there ever any information on this?  I get the same exact error.  Would be really nice to know how to resolve it.  And I cannot seem to find much on this.

**Comment by gschueler** [comment]
I think you will also need to delete the rows from the "base_report" table as well.  When an execution occurs, a report entry is created which links to the execution entry.  simply deleting the contents of "execution" table will probably leave reports with broken links.
