### ISSUE TITLE
PAM authentication failed if rundeck user is not in shadow group

### ISSUE THREAD

**Issue by yoborider** [rundeck/rundeck#3226]
Issue type: Enhancement Request (Documentation)

**My Rundeck detail**

* Rundeck version: 2.10.5-1
* install type: deb
* OS Name/version: Debian Stretch 9.3
* DB Type/version: postgreSQL

**Expected Behavior**

Adding user rundeck to group shadow is required to allow rundeck (and libpam4j) to work with pam service sshd. Authentication success log in service.log :

`2018-03-27 13:08:08.805:INFO:oejs.ServerConnector:main: Started ServerConnector@4202bfe8{HTTP/1.1}{0.0.0.0:4440}
mars 27, 2018 1:08:32 PM org.rundeck.jaas.pam.AbstractPamLoginModule debug
INFOS: PAM authentication trying (sshd) for: adminsys
mars 27, 2018 1:08:32 PM org.rundeck.jaas.pam.AbstractPamLoginModule debug
INFOS: PAM authentication succeeded for: adminsys`

---> Have to apply that command : 
        $ sudo addgroup rundeck shadow

**How to Reproduce**

Default PAM configuration in Rundeck PAM documentation
[authenticating-users](http://rundeck.org/docs/administration/authenticating-users.html)
**Without rundeck user in shadow group, an error is produced in service.log** :
Logging failed (/var/log/rundeck/service.log)  : 

`INFOS: PAM authentication trying (sshd) for: adminsys
mars 27, 2018 1:32:26 PM org.rundeck.jaas.pam.AbstractPamLoginModule debug
INFOS: pam_authenticate failed : authentication failed
org.jvnet.libpam.PAMException: pam_authenticate failed : authentication failed
        at org.jvnet.libpam.PAM.check(PAM.java:106)
        at org.jvnet.libpam.PAM.authenticate(PAM.java:124)
        at org.rundeck.jaas.pam.AbstractPamLoginModule.authenticate(AbstractPamLoginModule.java:85)
        at org.rundeck.jaas.AbstractSharedLoginModule.login(AbstractSharedLoginModule.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at`
`2018-03-27 13:32:26.627:WARN:oejj.JAASLoginService:qtp1338668845-15:
javax.security.auth.login.LoginException: Login Failure: all modules ignored
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:906)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
        at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
        at `

Similar case : [https://groups.google.com/forum/#!topic/rundeck-discuss/fTg_S6dCvUw](https://groups.google.com/forum/#!topic/rundeck-discuss/fTg_S6dCvUw)

** Other manual action required **

`$ sudo apt install libpam4j-java`
otherwise
`INFOS: PAM authentication trying (sshd) for: adminsys
2018-03-26 15:48:43.278:WARN:oejj.JAASLoginService:qtp1338668845-16:
javax.security.auth.login.LoginException: java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.libpam.impl.PAMLibrary|?at sun.misc.Unsafe.ensureClassInitialized(Native Method)|?at `

`$ sudo ln -s /lib/x86_64-linux-gnu/libpam.so.0 /lib/x86_64-linux-gnu/libpam.so`
otherwise
`INFOS: PAM authentication trying (sshd) for: adminsys
2018-03-26 16:21:57.004:WARN:oejj.JAASLoginService:qtp1338668845-16:
javax.security.auth.login.LoginException: java.lang.UnsatisfiedLinkError: Unable to load library 'pam': libpam.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type|?at `

**Comment by sjrd218** [comment]
@yoborider Thanks for your input!

https://github.com/rundeck/docs/pull/150
