### ISSUE TITLE
HTTP ERROR 403  localhost:4440

### ISSUE THREAD

**Issue by VimalKumarS** [rundeck/rundeck#3239]
Issue type: Error on launching rundeck

**My Rundeck detail**

* Rundeck version:  - rundeck-launcher-2.10.8 /rundeck-launcher-2.10.2
* install type: (rpm,deb,war,launcher?)  Jar
* OS Name/version:  Windows 10
* DB Type/version: mysql? postgres? h2?..

**Getting forbidden error**
HTTP ERROR 403
Problem accessing /. Reason:
    Forbidden
Powered by Jetty://

**How to Reproduce**
set CURDIR=%~dp0
call %CURDIR%\profile.bat
java %RDECK_CLI_OPTS% -jar rundeck-launcher-2.10.8.jar --skipinstall -d

profile.bat
set CURDIR=%~dp0
set Path=%JAVA_HOME%\bin;%CURDIR%\tools\bin;%Path%
set RDECK_CLI_OPTS=-Xms64m 
set RD_LIBDIR=%CURDIR%\tools\lib

**Comment by ahonor** [comment]
@VimalKumarS do you get to the login page?

**Comment by VimalKumarS** [comment]
No didn't get login page.
 i deleted 
rundeck\server\exp\webapp\WEB-INF\web.xml
and log4j.properties. 

Console log
VERBOSE: --skipinstall: Not extracting.
VERBOSE: Start server with com.dtolabs.rundeck.RunServer.main([C:\Dexter\rundeck])
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=C:/Dexter/rundeck/server/config/ssl.properties to enable.
2018-03-30 09:06:02.507:INFO:oejs.Server:main: jetty-9.0.7.v20131107
2018-03-30 09:06:05.119:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2018-03-30 09:06:05.142:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@39c0f4a{/,file:/C:/Dexter/rundeck/server/exp/webapp/,AVAILABLE}{C:\Dexter\rundeck\server\exp\webapp}
2018-03-30 09:06:05.371:INFO:oejs.ServerConnector:main: Started ServerConnector@1f28c152{HTTP/1.1}{0.0.0.0:4440}

**Comment by ahonor** [comment]
@VimalKumarS those two files are required so you will need to restore those.  What OS version are you using?
Are you following these instructions? http://rundeck.org/docs/administration/installation.html#install-on-windows

**Comment by ahonor** [comment]
What java version are you using?

**Comment by VimalKumarS** [comment]
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by ahonor** [comment]
@VimalKumarS not sure why removing the log4j.properties and web.xml allows it to proceed further. Try removing just the log4j.properties but leave the web.xml. Also I am curious if there are some badly expanded path names inside the log4j.properties file.  Eg, in unix os family I would run: 

`grep 'file=' "$RDECK_BASE/server/exp/webapp/WEB-INF/classes/log4j.properties"`

**Comment by VimalKumarS** [comment]
After including web.xml, i  see login page but not able to login  using admin/admin.
But still didn't included log4j, i verified all path are correct

**Comment by VimalKumarS** [comment]
2018-03-31 11:20:17.883:INFO:oejs.ServerConnector:main: Started ServerConnector@4e7b89b6{HTTP/1.1}{0.0.0.0:4440}
2018-03-31 11:21:06.771:WARN:oejj.JAASLoginService:qtp932172204-76:
javax.security.auth.login.FailedLoginException
        at org.eclipse.jetty.jaas.spi.AbstractLoginModule.login(AbstractLoginModule.java:260)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
        at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:748)

**Comment by VimalKumarS** [comment]
Instruction in rundeck documentation is for rundeck-launcher-2.6.10.jar  not for rundeck-launcher-2.10.8.jar 

on install only option it was not generating etc folder with correct profile.bat which look for ssl setting. i copied etc folder from older version of setting using old rundeck jar, and started the service it worked.

Thanks for your help @ahonor

**Comment by ahonor** [comment]
@VimalKumarS ok great.
