### ISSUE TITLE
Database may be already in use: "Waited for database closing longer than 1 minute"

### ISSUE THREAD

**Issue by Hackeruncle** [rundeck/rundeck#3244]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: Rundeck 2.10.7-1
* install type: (rpm,deb,war,launcher?)  war
* OS Name/version:  CentOS7.3
* DB Type/version: mysql? postgres? h2?..  H2

**Error:**
**SQL state [90020]; error code [90020]; Database may be already in use: "Waited for database closing longer than 1 minute".** Possible solutions: close all other connection(s); use the server mode [90020-193]; nested exception is org.h2.jdbc.JdbcSQLException: Database may be already in use: "Waited for database closing longer than 1 minute". Possible solutions: close all other connection(s); use the server mode [90020-193]
        at rundeck.services.ExecutionService$_saveExecutionState_closure64.doCall(ExecutionService.groovy:2512)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2511)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:548)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:487)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:558)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:166)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:93)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:92)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: "Waited for database closing longer than 1 minute". Possible solutions: close all other connection(s); use the server mode [90020-193]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.engine.Engine.openSession(Engine.java:184)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
        at org.h2.engine.Engine.createSession(Engine.java:137)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:115)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        ... 11 more
2018-04-03 02:52:59,010 WARN  ExecutionJob - Execution 282732 save result status: failed (attempts=1/10), retrying in 8139ms

**Comment by Hackeruncle** [comment]
![rundeck](https://user-images.githubusercontent.com/20901151/38464759-889ad470-3b45-11e8-91f8-548944eef420.png)

**Comment by vivekgkwd** [comment]
How did you resolve this?
