### ISSUE TITLE
Job execution stuck @ 100%

### ISSUE THREAD

**Issue by dataenligne** [rundeck/rundeck#3268]
Issue type: Bug report/Enhancement Request

Hi,

Our job execution isn't able to complete successfully. It is getting stuck @ 100% - killing the job won't work neither.

The job is running on a specific set of objects which count a total of 14 VMs.
The commands seem to be fully executed on all these VMs, however, the job won't be able to finish.

By taking a look at the /var/log/rundeck/service.log logifle, we're seeing the following:
(please note we have replaced our servers name by "some-servers-here...":

```
ERROR SqlExceptionHelper: Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)": "'some-servers-here... (317)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]
ERROR ExecutionJob: Execution 3127 save result status: caught exception: Hibernate operation: could not execute statement; SQL [n/a]; Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)": "'some-servers-here... (317)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]; nested exception is org.h2.jdbc.JdbcSQLException: Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)": "'some-servers-here... (317)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)": "'some-servers-here... (317)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]; nested exception is org.h2.jdbc.JdbcSQLException: Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)": "'some-servers-here... (317)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]
        at rundeck.services.ReportService.reportExecutionResult(ReportService.groovy:66)
        at rundeck.services.ExecutionService.logExecution(ExecutionService.groovy:887)
        at rundeck.services.ExecutionService$_saveExecutionState_closure64.doCall(ExecutionService.groovy:2590)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2511)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:548)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:487)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:558)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:166)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:93)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:92)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "SUCCEEDED_NODE_LIST VARCHAR(255)": "'some-servers-here... (317)"; SQL statement:
insert into base_report (id, version, action_type, author, ctx_name, ctx_project, ctx_type, date_completed, date_started, mapref_uri, message, node, report_id, status, tags, title, aborted_by_user, adhoc_execution, adhoc_script, ctx_command, ctx_controller, failed_node_list, filter_applied, jc_exec_id, jc_job_id, succeeded_node_list, class) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'rundeck.ExecReport') [22001-193]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.table.Column.validateConvertUpdateSequence(Column.java:335)
        at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784)
        at org.h2.command.dml.Insert.insertRows(Insert.java:151)
        at org.h2.command.dml.Insert.update(Insert.java:114)
        at org.h2.command.CommandContainer.update(CommandContainer.java:98)
        at org.h2.command.Command.executeUpdate(Command.java:258)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
        ... 13 more

```

We currently running the following:
* Rundeck version: 2.10.8-1 
* install type: deb package
* OS Name/version: Ubuntu 16.04.4 LTS
* DB Type/version: h2

Please let me know if you need further information.

Thanks!

**Comment by dataenligne** [comment]
It appears the following fixed our issue:
https://github.com/rundeck/rundeck/issues/2228#issuecomment-274495273
