### ISSUE TITLE
Accessing "Access Control" shows java.lang.ClassCastException

### ISSUE THREAD

**Issue by majkinetor** [rundeck/rundeck#3299]
Issue type: Bug report

![image](https://user-images.githubusercontent.com/85767/39145386-d16b6b70-4733-11e8-9979-18f1e056b50c.png)

Version: Rundeck 2.10.8-1 cafe mocha dodgerblue bell 2018-03-23

<details>
<pre>
java.lang.ClassCastException: org.yaml.snakeyaml.events.MappingEndEvent cannot be cast to org.yaml.snakeyaml.events.NodeEvent
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:146)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:105)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:501)
	at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$3.next(YamlParsePolicy.java:630)
	at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$3.next(YamlParsePolicy.java:621)
	at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$4$1$1.next(YamlParsePolicy.java:673)
	at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$4$1$1.next(YamlParsePolicy.java:660)
	at com.dtolabs.rundeck.core.authorization.providers.YamlPolicyCollection.load(YamlPolicyCollection.java:86)
	at com.dtolabs.rundeck.core.authorization.providers.YamlPolicyCollection.<init>(YamlPolicyCollection.java:56)
	at com.dtolabs.rundeck.core.authorization.providers.YamlPolicyFactoryV2.policiesFromSource(YamlPolicyFactoryV2.java:39)
	at com.dtolabs.rundeck.core.authorization.providers.YamlProvider.policiesFromSource(YamlProvider.java:134)
	at rundeck.services.AuthorizationService$_validateYamlPolicy_closure2.doCall(AuthorizationService.groovy:125)
	at rundeck.services.AuthorizationService.validateYamlPolicy(AuthorizationService.groovy:121)
	at rundeck.controllers.MenuController.loadSystemPolicyFS(MenuController.groovy:1451)
	at rundeck.controllers.MenuController$_systemAclsModel_closure42.doCall(MenuController.groovy:1468)
	at rundeck.controllers.MenuController.systemAclsModel(MenuController.groovy:1467)
	at rundeck.controllers.MenuController.acls(MenuController.groovy:1445)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)
</pre>
</details>

**Comment by gschueler** [comment]
i'm guessing there's some syntax error in one of your aclpolicy files in your `$RDECK_BASE/etc` directory.  If you use the `rd-acl` tool to validate them, is there any info about it?

**Comment by majkinetor** [comment]
Sorry, I deleted it, but here is a screenshot I have. Its just badly idented yaml all the way plus one group was without a value.

![image](https://user-images.githubusercontent.com/85767/39148419-9021e46a-473c-11e8-893d-96c1a54ed1f9.png)

Here  is the tool output:

```
Using configured Rundeck etc dir: C:\rundeck/etc
java.lang.ClassCastException: org.yaml.snakeyaml.events.MappingEndEvent cannot be cast to org.yaml.snakeyaml.events.NodeEvent
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:146)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:105)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:501)
        at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$3.next(YamlParsePolicy.java:630)
        at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$3.next(YamlParsePolicy.java:621)
        at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$4$1$1.next(YamlParsePolicy.java:673)
        at com.dtolabs.rundeck.core.authorization.providers.YamlParsePolicy$4$1$1.next(YamlParsePolicy.java:660)
        at com.dtolabs.rundeck.core.authorization.providers.YamlPolicyCollection.load(YamlPolicyCollection.java:86)
        at com.dtolabs.rundeck.core.authorization.providers.YamlPolicyCollection.<init>(YamlPolicyCollection.java:56)
        at com.dtolabs.rundeck.core.authorization.providers.YamlPolicyFactoryV2.policiesFromSource(YamlPolicyFactoryV2.java:39)
        at com.dtolabs.rundeck.core.authorization.providers.PolicyCollectionFactory.validate(PolicyCollectionFactory.java:68)
        at com.dtolabs.rundeck.core.authorization.providers.YamlProvider.validate(YamlProvider.java:92)
        at com.dtolabs.rundeck.core.authorization.providers.YamlProvider.validate(YamlProvider.java:79)
        at com.dtolabs.rundeck.core.authorization.providers.YamlProvider.validate(YamlProvider.java:83)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.validatePolicies(AclTool.java:1415)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.validateAction(AclTool.java:1379)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.go(AclTool.java:579)
        at com.dtolabs.rundeck.core.cli.BaseTool.run(BaseTool.java:155)
        at com.dtolabs.rundeck.core.cli.acl.AclTool.main(AclTool.java:155)
C:\rundeck\etc\users.aclpolicy:
        org.yaml.snakeyaml.events.MappingEndEvent cannot be cast to org.yaml.snakeyaml.events.NodeEvent
C:\rundeck\etc\users.aclpolicy[1]:
        Error parsing the policy document: while scanning an alias; expected alphabetic or numeric character, but found but found
The validation failed
```

**Comment by gschueler** [comment]
@majkinetor thanks
