### ISSUE TITLE
Foreign key contraints when deleting jobs or job history...

### ISSUE THREAD

**Issue by gufertum** [rundeck/rundeck#3360]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.11.0-1
* install type: deb
* OS Name/version: CentOS 7
* DB Type/version: mysql 5.7.21

**Expected Behavior**
Being able to delete unused jobs.

**How to Reproduce**
Try to delete an unused job (including 'delete all executions of this job') fails with this error:  Cannot delete or update a parent row: a foreign key constraint fails (`rundeck`.`referenced_execution`, CONSTRAINT `FK_3mt49npi8lq1353afwwuuf48t` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`))

**Log output**

2018-05-08 15:26:30,535 [qtp1480010240-17702] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Cannot delete or update a parent row: a foreign key constraint fails (`rundeck`.`referenced_execution`, CONSTRAINT `FK_3mt49npi8lq1353afwwuuf48t` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`))
2018-05-08 15:26:30,546 [qtp1480010240-17702] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - MySQLIntegrityConstraintViolationException occurred when processing request: [POST] /scheduledExecution/delete
Cannot delete or update a parent row: a foreign key constraint fails (`rundeck`.`referenced_execution`, CONSTRAINT `FK_3mt49npi8lq1353afwwuuf48t` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`)). Stacktrace follows:
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`rundeck`.`referenced_execution`, CONSTRAINT `FK_3mt49npi8lq1353afwwuuf48t` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`))
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at rundeck.services.ScheduledExecutionService$_deleteScheduledExecution_closure24.doCall(ScheduledExecutionService.groovy:914)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
	at rundeck.services.ScheduledExecutionService.deleteScheduledExecution(ScheduledExecutionService.groovy:887)
	at rundeck.services.ScheduledExecutionService.deleteScheduledExecutionById(ScheduledExecutionService.groovy:982)
	at rundeck.controllers.ScheduledExecutionController$_delete_closure41.doCall(ScheduledExecutionController.groovy:1413)
	at org.grails.plugins.web.rest.api.ControllersRestApi.withForm(ControllersRestApi.groovy:53)
	at rundeck.controllers.ScheduledExecutionController.delete(ScheduledExecutionController.groovy:1409)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tomprogrammer** [comment]
This issue is fixed in version 2.11.1-1 for me.

For reference, the bug is https://github.com/rundeck/rundeck/issues/3346 as mentioned in the release notes.

**Comment by gufertum** [comment]
For me it was fixed with the update as mentioned earlier.

**Comment by gturri** [comment]
Hi,

I know it's an old issue, but is there a known workaround for cases where upgrading rundeck is not an option?
(yes, I know that running old software is bad and may incur security issues, but this decision is not really in my hands :-/ )
