### ISSUE TITLE
auto schedule execution job error

### ISSUE THREAD

**Issue by chenlingmin** [rundeck/rundeck#3375]
Hi.

I'm used Rundeck 2.11.1-1 .

```
ERROR ExceptionPrinterJobListener: Exception occurred in job:
org.quartz.JobExecutionException: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: rundeck.services.ExecutionServiceException: Job "check-prod-server" {{Job da8d7b23-4451-4f15-95f6-3a6457acc42c}} is currently being executed {{Execution 163334}}] [See nested exception: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: rundeck.services.ExecutionServiceException: Job "check-prod-server" {{Job da8d7b23-4451-4f15-95f6-3a6457acc42c}} is currently being executed {{Execution 163334}}]]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:218)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: rundeck.services.ExecutionServiceException: Job "check-prod-server" {{Job da8d7b23-4451-4f15-95f6-3a6457acc42c}} is currently being executed {{Execution 163334}}]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
Caused by: rundeck.services.ExecutionServiceException: Job "check-prod-server" {{Job da8d7b23-4451-4f15-95f6-3a6457acc42c}} is currently being executed {{Execution 163334}}
	at rundeck.services.ExecutionService.createExecution(ExecutionService.groovy:2282)
	at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:324)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:117)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:96)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:95)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
```

**Comment by isca0** [comment]
+1

**Comment by dirkniblick** [comment]
+1 I'm getting this on Rundeck 3.0.8 on CentOS 7 via RPM.

```
2018-11-14 13:20:05.005 ERROR --- [eduler_Worker-8] g.p.q.l.ExceptionPrinterJobListener      : Exception occurred in job
: Moves completed reports to the website's tables
Schedule: Every minute, five seconds for the hours of 06:00 and 21:00 (i.e., 06:00:05 to 21:59:05) every day

org.quartz.JobExecutionException: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception
: rundeck.services.ExecutionServiceException: Job "SS EXPORTED Move Reports To Web" {{Job 4091da29-833e-4b6a-8d52-d7cb11
745c7e}} is currently being executed {{Execution 8449896}}]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:218)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        ... 1 common frames omitted
Caused by: rundeck.services.ExecutionServiceException: Job "SS EXPORTED Move Reports To Web" {{Job 4091da29-833e-4b6a-8d
52-d7cb11745c7e}} is currently being executed {{Execution 8449896}}
        at sun.reflect.GeneratedConstructorAccessor443.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(Construc
torSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:258)
        at rundeck.services.ExecutionService.$tt__createExecution(ExecutionService.groovy:2334)
        at sun.reflect.GeneratedMethodAccessor716.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
        at rundeck.services.ExecutionService$_createExecution_closure39.doCall(ExecutionService.groovy)
        at sun.reflect.GeneratedMethodAccessor715.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at rundeck.services.ExecutionService.createExecution(ExecutionService.groovy)
        at rundeck.services.ExecutionService.createExecution(ExecutionService.groovy)
        at rundeck.services.ExecutionService$createExecution$10.call(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:332)
        at rundeck.quartzjobs.ExecutionJob$initialize$6.callCurrent(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:119)
        at sun.reflect.GeneratedMethodAccessor694.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:98)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy)
        at sun.reflect.GeneratedMethodAccessor693.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$3.call(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:97)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 common frames omitted
```

**Comment by yogeshkumark** [comment]
+1 
Rundeck 3.1.0-20190731

I am also facing the same error. 
`[2019-12-02 17:53:30.432] ERROR ExceptionPrinterJobListener --- [uler_Worker-289] Exception occurred in job: This job will take the records from RECON.VVM_MASTER and hit the MSP API to crea
te voicemail and stores result in RECON.VVM_DETAIL

org.quartz.JobExecutionException: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.OutOfMemoryError: Metaspace]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:218)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        ... 1 common frames omitted
Caused by: java.lang.OutOfMemoryError: Metaspace

[2019-12-02 17:53:33.988] ERROR ExecutionJob --- [uler_Worker-186] Execution 4016905 finishExecution: failed (attempts=10/10) with exception: Metaspace
[2019-12-02 17:53:34.010] ERROR ExecutionJob --- [uler_Worker-186] Failed execution 4016905 : Execution 4016905 failed: Metaspace

java.lang.RuntimeException: Execution 4016905 failed: Metaspace
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:258)
        at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:467)
        at rundeck.quartzjobs.ExecutionJob$executeCommand$5.callCurrent(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:157)
        at sun.reflect.GeneratedMethodAccessor1691.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
`

**Comment by fdevans** [comment]
If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
