### ISSUE TITLE
"Cannot get property 'extid' on null object" when viewing job definition

### ISSUE THREAD

**Issue by isuftin** [rundeck/rundeck#3474]
**Describe the bug**
When clicking on a specific job through the UI, I get an error as stated below. This only happens on a specific job though I've not done a thorough search of other jobs this may effect. Any jobs linked to this job show the same error.

**My Rundeck detail**

* Rundeck version: 2.11.3
* RPM via Chef cokobook
* OS Name/version: CentOS 7
* DB Type/version: MySQL 5.6.35

**To Reproduce**
1. Sign into Rundeck
2. Click on project (Helpers)
3. Click on job to view definition
4. Error: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <auth:resourceAllowed>: Error executing tag <g:form>: Cannot get property 'extid' on null object

```
Stacktrace:
ERROR GrailsExceptionResolver: NullPointerException occurred when processing request: [GET] /project/Helpers/job/show/b0b9ef5d-cadf-4d21-b4a2-590880c0cc40
Cannot get property 'extid' on null object. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <auth:resourceAllowed>: Error executing tag <g:form>: Cannot get property 'extid' on null object
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <auth:resourceAllowed>: Error executing tag <g:form>: Cannot get property 'extid' on null object
        at gsp_rundeck_scheduledExecutionshow_gsp$_run_closure2.doCall(gsp_rundeck_scheduledExecutionshow_gsp.groovy:68)
        at gsp_rundeck_scheduledExecutionshow_gsp.run(gsp_rundeck_scheduledExecutionshow_gsp.groovy:73)
        ... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <auth:resourceAllowed>: Error executing tag <g:form>: Cannot get property 'extid' on null object
        at gsp_rundeck_scheduledExecution_show_gsp.run(gsp_rundeck_scheduledExecution_show_gsp.groovy:19)
        ... 46 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <auth:resourceAllowed>: Error executing tag <g:form>: Cannot get property 'extid' on null object
        at gsp_rundeck_scheduledExecution_showHead_gsp.run(gsp_rundeck_scheduledExecution_showHead_gsp.groovy:119)
        ... 47 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <auth:resourceAllowed>: Error executing tag <g:form>: Cannot get property 'extid' on null object
        at gsp_rundeck_scheduledExecution_jobActionButton_gsp.run(gsp_rundeck_scheduledExecution_jobActionButton_gsp.groovy:214)
        ... 48 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:form>: Cannot get property 'extid' on null object
        at gsp_rundeck_scheduledExecution_jobActionButton_gsp$_run_closure3.doCall(gsp_rundeck_scheduledExecution_jobActionButton_gsp.groovy:209)
        at rundeck.AuthTagLib$_closure3.doCall(AuthTagLib.groovy:123)
        ... 49 more
Caused by: java.lang.NullPointerException: Cannot get property 'extid' on null object
        at gsp_rundeck_scheduledExecution_jobActionButton_gsp$_run_closure3$_closure8.doCall(gsp_rundeck_scheduledExecution_jobActionButton_gsp.groovy:196)
        at rundeck.UtilityTagLib$_closure51.doCall(UtilityTagLib.groovy:1100)
        ... 51 more
```

**Expected behavior**
View job definition in UI

**Desktop (please complete the following information):**
 - OS: MacOS, Windows
 - Browser: Chrome
 - Version: 66.0.3359.181

**Additional context**
Recently upgraded from 2.10.x to 2.11.3

**Comment by isuftin** [comment]
Seeing this issue on a few other jobs in Rundeck (but not all). It seems as though downloading the job definition, deleting the job and re-uploading the job with the same UUID fixes things but I still am unsure as to what could be causing the issue?

**Comment by chiefzor** [comment]
I'm having the same error while trying to import a new job in xml format:
After getting that error, the API will response to any query with "Authenticating is required" untill I restart the service.

StackTrace:
`java.lang.NullPointerException: Cannot get property 'extid' on null object
	at rundeck.services.ScheduledExecutionService$_loadJobs_closure31.doCall(ScheduledExecutionService.groovy:1661)
	at rundeck.services.ScheduledExecutionService.loadJobs(ScheduledExecutionService.groovy:1554)
	at rundeck.controllers.ScheduledExecutionController.apiJobsImport(ScheduledExecutionController.groovy:3408)
	at rundeck.controllers.ScheduledExecutionController.apiJobsImportv14(ScheduledExecutionController.groovy:3344)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:540)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by isuftin** [comment]
We also noticed today that we see this error in other jobs in the same project when we delete an unrelated job in the same project.

**Comment by fishikles** [comment]
I'm seeing the same issue (see details [Issue-Detail.txt](https://github.com/rundeck/rundeck/files/2128039/Issue-Detail.txt))

**My Rundeck detail**
- Rundeck version: 2.11.4-1
- install type: tomcat
- OS Name/version: RedHat Enterprise Linux 6.9
- DB Type/version: MySQL 5.7.18

Having done some investigation I believe the issue occurs when trying to view a job that was run as a "Job Reference" step for another job that has been deleted.
What I believe is happening is that when the job is view it is looking up the "parent" (referencing) job based on the previous executions, which is returning null as the job has been deleted.

I think this was introduced by 43c236c, specifically:
 `<g:link controller="scheduledExecution" action="show" id="${job.extid}">`
here: https://github.com/rundeck/rundeck/blob/b5ea30afd26884973cc8b7e456387b5e614339f3/rundeckapp/grails-app/views/scheduledExecution/_jobActionButton.gsp#L265-L275

As a work around delete all execution when deleting a job that references other jobs. This can be done by selecting the "Delete this Job..." option from the "Action" menu while view the job in question. Then checking the " Delete all executions of this Job" check box before clicking Delete.

**Comment by isuftin** [comment]
Thank you so much

**Comment by sparr** [comment]
@chiefzor did 2.11.5 fix this problem for you? I am having an import problem like this, and want to compare to you before I open a new issue.
