### ISSUE TITLE
Moved from /tmp with file-copy-destination-dir but jobs fail

### ISSUE THREAD

**Issue by makered** [rundeck/rundeck#3737]
**Describe the bug**
For security we need to maintain noexec on /tmp so we needed to ensure Rundeck jobs ran from an alternate directory. I configured `framework.file-copy-destination-dir = /home/myuser/tmp` in `framework.properties` and in job debug log I see:

`
copying file: '/var/lib/rundeck/var/tmp/dispatch9198016955930785284.tmp' to: 'devops_rundeck:/home/myuser/tmp/0-24307-devops_rundeck-dispatch-script.tmp.sh'
`

However, there is also an error initially:

> [workflow] finishExecuteNodeStep(devops_rundeck): NodeDispatch: Unknown: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: failed to map segment from shared object: Operation not permitted
> 14:53:33 |   |   | Failed dispatching to node devops_rundeck: java.lang.UnsatisfiedLinkError: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: failed to map segment from shared object: Operation not permitted
> 14:53:33 |   |   | Failed dispatching to node devops_rundeck: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: java.lang.UnsatisfiedLinkError: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: failed to map segment from shared object: Operation not permitted	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:127) 	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116) 	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:146) 	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:65) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:85) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:360) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:732) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor$3.call(EngineWorkflowExecutor.java:433) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor$3.call(EngineWorkflowExecutor.java:427) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowStepOperation.call(EngineWorkflowStepOperation.java:54) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowStepOperation.call(EngineWorkflowStepOperation.java:12) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.UnsatisfiedLinkError: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: /tmp/rundeck/jna-1550481844/jna4727356443528974785.tmp: failed to map segment from shared object: Operation not permitted 	at java.lang.ClassLoader$NativeLibrary.load(Native Method) 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) 	at java.lang.Runtime.load0(Runtime.java:809) 	at java.lang.System.load(System.java:1086) 	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761) 	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736) 	at com.sun.jna.Native.<clinit>(Native.java:131) 	at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary.<clinit>(JNAUSocketFactory.java:47) 	at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory.open(JNAUSocketFactory.java:114) 	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.open(SSHAgentConnector.java:93) 	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:54) 	at com.jcraft.jsch.agentproxy.ConnectorFactory.createConnector(ConnectorFactory.java:104) 	at com.dtolabs.rundeck.core.tasks.net.SSHTaskBuilder.openSession(SSHTaskBuilder.java:124) 	at com.dtolabs.rundeck.core.tasks.net.ExtSSHExec.openSession(ExtSSHExec.java:583) 	at com.dtolabs.rundeck.core.tasks.net.ExtSSHExec.execute(ExtSSHExec.java:307) 	at com.dtolabs.rundeck.core.execution.impl.jsch.JschNodeExecutor.executeCommand(JschNodeExecutor.java:367) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeCommand(ExecutionServiceImpl.java:302) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeRemoteScript(DefaultScriptFileNodeStepUtils.java:286) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeRemoteScript(DefaultScriptFileNodeStepUtils.java:247) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:127) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:61) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:118) 	... 15 more
> 

and on subsequent runs:

> [workflow] finishExecuteNodeStep(devops_rundeck): NodeDispatch: Unknown: Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary
> 15:00:17 |   |   | Failed dispatching to node devops_rundeck: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary
> 15:00:17 |   |   | Failed dispatching to node devops_rundeck: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:127) 	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116) 	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:58) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:146) 	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:65) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:85) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:360) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:732) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor$3.call(EngineWorkflowExecutor.java:433) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor$3.call(EngineWorkflowExecutor.java:427) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowStepOperation.call(EngineWorkflowStepOperation.java:54) 	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowStepOperation.call(EngineWorkflowStepOperation.java:12) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary 	at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory.open(JNAUSocketFactory.java:114) 	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.open(SSHAgentConnector.java:93) 	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:54) 	at com.jcraft.jsch.agentproxy.ConnectorFactory.createConnector(ConnectorFactory.java:104) 	at com.dtolabs.rundeck.core.tasks.net.SSHTaskBuilder.openSession(SSHTaskBuilder.java:124) 	at com.dtolabs.rundeck.core.tasks.net.ExtSSHExec.openSession(ExtSSHExec.java:583) 	at com.dtolabs.rundeck.core.tasks.net.ExtSSHExec.execute(ExtSSHExec.java:307) 	at com.dtolabs.rundeck.core.execution.impl.jsch.JschNodeExecutor.executeCommand(JschNodeExecutor.java:367) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeCommand(ExecutionServiceImpl.java:302) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeRemoteScript(DefaultScriptFileNodeStepUtils.java:286) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeRemoteScript(DefaultScriptFileNodeStepUtils.java:247) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:127) 	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:61) 	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:118)

**My Rundeck detail**

* Rundeck version: [2.7.3-1]
* install type: [deb]
* OS Name/version: [ubuntu 14.04]
* DB Type/version: [mysql]

**Expected behavior**
Jobs continue to run successfully with scripts running on remote nodes from /home/myuser/tmp

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [e.g. 67]

**Comment by makered** [comment]
Found a fix by accident, needed to also set `Djava.io.tmpdir=` to the new tmp dir location apparently (in `/etc/rundeck/profile`).
