### ISSUE TITLE
Rundeck 3 new JAAS properties absent from rpm/deb profile

### ISSUE THREAD

**Issue by ProTip** [rundeck/rundeck#3757]
First reported in #3755

It appears that with Rundeck 3 and the switch to Grails 3 it is necessary to specify as a JVM system property `rundeck.jaaslogin=true`. The file `/etc/rundeck/profile` in the current rpm and deb packages does not account for this.

As well, it looks like supplying `-Djava.security.auth.login.config=` per the documentation is deprecated in favor of using `-Dloginmodule.conf.name=` which path joins with `configDir`:
https://github.com/rundeck/rundeck/blob/3223d0052a73079480b139ee64b58f4fd780f35a/rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy#L363

It looks like we may need to update `/etc/rundeck/profile` and the docs + upgrade docs to account for these changes. If there is no downside, it may make sense to simply default `jaaslogin=true` and allow an override via the `/etc/default/rundeckd` file.

**My Rundeck detail**

* Rundeck version: [3.0.0]
* install type: [rpm]
* OS Name/version: [centos 7]
* DB Type/version: [N/A]

### Workaround

((Edit `/etc/rundeck/profile`:**  
* Replace `-Djava.security.auth.login.config=` with `-Dloginmodule.conf.name=`
* Add `-Drundeck.jaaslogin=true`
* Ensure the conf file is located in `/etc/rundeck`

**Comment by dpomnean** [comment]
I second this. I was having the same issue with my setup and tried the workaround and it is now working for me.

**Comment by ahonor** [comment]
+1 I think it makes sense to default jaaslogin=true.

**Comment by dpomnean** [comment]
@ahonor The part that helped me was a combination of default 'jaaslogin=true' and changing the java flag for the config file.

**Comment by sparr** [comment]
workaround failed for me because my old `/etc/sysconfig/rundeckd` sets `JAAS_CONF=$RDECK_CONFIG/jaas-auth.conf` which was previously used as `-Djava.security.auth.login.config=$JAAS_CONF` and the workaround changed to `-Dloginmodule.conf.name=$JAAS_CONF` which leads to an attempt to load `/etc/rundeck/etc/rundeck/jaas-auth.conf`

I changed JAAS_CONF to just jaas-auth.conf and now the workaround seems to work for me.

**Comment by jplassnibatt** [comment]
WORKAROUND:
First of all you shouldn't edit /etc/rundeck/profile file.

**RPM** is working fine with below /etc/sysconfig/rundeckd options:
example: jaas-ldap.conf in /etc/rundeck/ and module named ldap:
```
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -server -Drundeck.jaaslogin=true -Djava.security.auth.login.config=jaas-ldap.conf -Dloginmodule.name=ldap}"
```

or
```
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -server -Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf -Dloginmodule.name=ldap}"
```

or
```
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -server -Drundeck.jaaslogin=true}"
JAAS_CONF="jaas-ldap.conf"
LOGIN_MODULE="ldap"
```

or
```
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -server -Drundeck.jaaslogin=true}"
JAAS_CONF="/etc/rundeck/jaas-ldap.conf"
LOGIN_MODULE="ldap"
```

**DEB** is only working with below /etc/default/rundeckd option:
```
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -server -Drundeck.jaaslogin=true -Dloginmodule.conf.name=jaas-ldap.conf -Dloginmodule.name=ldap}"
```

**Comment by ecarrascos** [comment]
Hi Everyone!

[Rundeck 3.0.1 has been released!](http://rundeck.org/news/2018/08/03/rundeck-3.0.1.html) 

This Release includes the [fix that restores the jaas config compatibility with 2.x](https://github.com/rundeck/rundeck/pull/3758). Also, check the [Documentation](http://rundeck.org/docs/administration/security/authenticating-users.html), as it was updated to reflect the changes. Thank you all so much for your feedback! 

Eduardo.

**Comment by Poil** [comment]
Hi,

On my CentOS7, I've upgraded Rundeck 2 to 3.0.1 and it's not working out of the box, still need to patch RDECK_JVM

Best regardsn

**Comment by Poil** [comment]
Also, I have this in the new property but it's not used

```
# build classpath without lone : that includes .
for jar in $(find $RDECK_INSTALL/cli -name '*.jar') ; do
  CLI_CP=${CLI_CP:+$CLI_CP:}$jar
done
```

So I have these errors when starting rundeck :

```
2018-08-07 11:13:15.449  WARN --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Bean creation exception on non-lazy FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
2018-08-07 11:13:15.483  WARN --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
2018-08-07 11:13:15.483  WARN --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
2018-08-07 11:13:15.530 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1634)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at rundeckapp.Application.main(Application.groovy:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
	at org.springframework.util.ResourceUtils.getURL(ResourceUtils.java:135)
	at org.springframework.util.Log4jConfigurer.initLogging(Log4jConfigurer.java:69)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:265)
	at org.springframework.beans.factory.config.MethodInvokingBean.invokeWithTargetException(MethodInvokingBean.java:119)
	at org.springframework.beans.factory.config.MethodInvokingFactoryBean.afterPropertiesSet(MethodInvokingFactoryBean.java:106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1692)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	... 29 common frames omitted
```

**Comment by paulholden** [comment]
@Poil - that's already documented in the [3.0 release notes](http://rundeck.org/news/2018/07/27/rundeck-3.0.0.html#known-issues-and-limitations), under _Known Issues and Limitations_:

> Startup error about log4j
>
> If you update and get an error about Log4j configuration, add a line to your rundeck-config file: rundeck.log4j.config.file=/.../server/config/log4j.properties and specify the correct path to a log4j.properties file.
