### ISSUE TITLE
Failure loading execution info if no 'Accept-Encoding ' header is sent: Jobs containing other jobs won't run

### ISSUE THREAD

**Issue by alexray92** [rundeck/rundeck#3871]
**Describe the bug**
After upgrading from 2.11 to 3.0 and then to 3.0.2, jobs defined as a series of other jobs do not execute - no output even indicating the steps are run, or the jobs contained in the steps.

**My Rundeck detail**

* Rundeck version: 3.0.2
* install type: deb
* OS Name/version: Debian Stretch
* DB Type/version:  Whatever the installer chose?  I originally set it up with text files.

**To Reproduce**
1. Create job with node executor winrm, set step to execute shell command on remote server, set node filter on job.  Job run succeeds
2. Create another job, add step with the last job created
3. Run that new job, and it fails, and output doesn't show anything

**Expected behavior**
Output, or at least an error, from the steps attempted to run.

**Additional context**
I'm using rundeck behind nginx for reverse-proxy/TLS.  All of this worked flawlessly before upgrading to 3.x.

I do get this error when running a job containing jobs as steps, but not the 'base' jobs themselves:

`2018-08-22 07:33:48.478 ERROR --- [qtp181083292-25] o.g.web.errors.GrailsExceptionResolver   : NullPointerException occurred when processing request: [GET] /execution/ajaxExecNodeState/39011
Cannot invoke method contains() on null object. Stacktrace follows:

java.lang.NullPointerException: Cannot invoke method contains() on null object
        at rundeck.controllers.ControllerBase.renderCompressed(ControllerBase.groovy:88)
        at rundeck.controllers.ExecutionController.ajaxExecNodeState(ExecutionController.groovy:492)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by alexray92** [comment]
The error in the log happens when the browser tries to request this:

https://myrundeckfqdn/execution/ajaxExecNodeState/39015?node=mynode

This gives the "Cannot invoke method contains() on null object" 500 error.

**Comment by alexray92** [comment]
Seems to somehow be this line?

request.getHeader("Accept-Encoding").contains("gzip")){

Maybe caused by no Accept-Encoding header being received?

I've tried playing around with framework.properties too, as relates to the nginx reverse-proxy, but haven't seem to have had any affect there.

**Comment by gschueler** [comment]
are you able to tweak your nginx to allow that header to be forwarded?  I believe browsers normally send that header, so you are probably right that it is not being received by Rundeck and that is causing the error.

**Comment by alexray92** [comment]
Update: I had Accept-Encoding set to "".  I tried gzip, which didn't do anything, but moreover it appears that nginx has to be manually recompiled to get gzip support (the distro version doesn't have it).

---

As for output, I just ran it in Debug and got the following behavior:

Job shows completed successfully, but the report for the remote node shows "Waiting to run 1 Step still"

Log Output only shows info for execution on the local rundeck server, not the remote node (no output at all, no errors, shown when not in debug).

Output log only mentions the job-step in the following location:
1: Workflow step executing: JobReferenceItem{jobIdentifier='db02d564-bd85-4ae2-aab2-691273f49efb', nodeStep=false}
1: Workflow step finished, result: Step successful

Full debug log below:

---
[workflow] Begin execution: node-first
Start EngineWorkflowExecutor
Building initial state and rules...
Update conditional state: {before.step.1=true, after.step.1=false}
start conditions for step [1]: []
Create rule engine with rules: RuleEngine{ruleSet=[Rule: Conditions([(step.any.flowcontrol.halt == 'true')]) => DataState{state={workflow.done=true}}, Rule: Conditions([(step.any.state.failed == 'true'), (workflow.keepgoing == 'false')]) => DataState{state={workflow.done=true}}, Rule: Conditions([]) => DataState{state={step.1.start=true}}]}
Create workflow engine with state: StateLogger{state=DataState{state={job.successOnEmptyNodeFilter=false, job.executionType=user, job.url=https://rundeckfqdn/project/RestartServices/execution/follow/39022, job.filter=remoteserver, job.id=044f452c-20d5-4daf-b000-6c0f50ea68d4, job.loglevel=DEBUG, job.wasRetry=false, job.project=RestartServices, before.step.1=true, option.action=start, after.step.1=false, job.retryInitialExecId=0, job.username=myuser, job.retryAttempt=0, job.user.name=myuser, job.group=Operations/generic/service, workflow.keepgoing=false, job.execid=39022, job.serverUrl=https://rundeckfqdn/, job.name=Manipulate foobar Service (remoteserver), job.threadcount=1, option.service=FOOBAR_SERVICE_NAME}}}
Begin: Workflow begin
WillProcessStateChange: saw state changes: {workflow.state=started}
Update conditional state: {workflow.state=started}
Update conditional state: {step.1.start=true}
DidProcessStateChange: applied state changes and rules (changed? true): StateLogger{state=DataState{state={job.successOnEmptyNodeFilter=false, job.executionType=user, job.url=https://rundeckfqdn/project/RestartServices/execution/follow/39022, job.filter=remoteserver, job.id=044f452c-20d5-4daf-b000-6c0f50ea68d4, job.loglevel=DEBUG, job.wasRetry=false, job.project=RestartServices, before.step.1=true, step.1.start=true, option.action=start, after.step.1=false, workflow.state=started, job.retryInitialExecId=0, job.username=myuser, job.retryAttempt=0, job.user.name=myuser, job.group=Operations/generic/service, workflow.keepgoing=false, job.execid=39022, job.serverUrl=https://rundeckfqdn/, job.name=Manipulate foobar Service (remoteserver), job.threadcount=1, option.service=FOOBAR_SERVICE_NAME}}}
WillRunOperation: operation starting: Step{stepNum=1, label='null'}
LoopProgress: Pending(1) => run(1), skip(0), remain(0)
[workflow] Begin step: 1,rundeck-jobref
1: Workflow step executing: JobReferenceItem{jobIdentifier='db02d564-bd85-4ae2-aab2-691273f49efb', nodeStep=false}
1: Workflow step finished, result: Step successful
[workflow] Finish step: 1,rundeck-jobref
OperationSuccess: operation succeeded: StepSuccess{stepNum=1, stepResultCapture=StepResultCapture{stepResult=Step successful, stepSuccess=true, statusString='null', controlBehavior=Step successful, resultData=MultiDataContextImpl(map={}, base=null)}, newState=DataState{state={step.1.completed=true, step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true}}}
WillProcessStateChange: saw state changes: {step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true, step.1.completed=true}
Update conditional state: {step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true, step.1.completed=true}
Update conditional state: {step.1.start=true}
DidProcessStateChange: applied state changes and rules (changed? true): StateLogger{state=DataState{state={job.url=https://rundeckfqdn/project/RestartServices/execution/follow/39022, job.id=044f452c-20d5-4daf-b000-6c0f50ea68d4, job.loglevel=DEBUG, step.any.state.success=true, option.action=start, after.step.1=true, workflow.state=started, job.retryInitialExecId=0, job.user.name=myuser, job.name=Manipulate foobar Service (remoteserver), step.1.state=success, job.successOnEmptyNodeFilter=false, job.executionType=user, job.filter=remoteserver, step.1.completed=true, job.wasRetry=false, job.project=RestartServices, before.step.1=false, step.1.start=true, job.username=myuser, job.retryAttempt=0, job.group=Operations/generic/service, workflow.keepgoing=false, job.execid=39022, job.serverUrl=https://rundeckfqdn/, job.threadcount=1, option.service=FOOBAR_SERVICE_NAME}}}
LoopProgress: Pending(0) => run(0), skip(0), remain(0)
EndOfChanges: No more state changes expected, finishing workflow.
WillShutdown: Workflow engine shutting down
Complete: Workflow complete: [Step{stepNum=1, label='null'}: StepSuccess{stepNum=1, stepResultCapture=StepResultCapture{stepResult=Step successful, stepSuccess=true, statusString='null', controlBehavior=Step successful, resultData=MultiDataContextImpl(map={}, base=null)}, newState=DataState{state={step.1.completed=true, step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true}}}]
[workflow] Finish execution:  node-first: [Workflow result: , status: succeeded]

**Comment by alexray92** [comment]
To clarify, my job setup is like this:

**Job: Manipulate REMOTESERVER service** 
This just takes an 'action' and 'name' parameter as uses them to stop or start a service on the remote server, specified in the node filter for the job.

**Job: Manipulate FOOBAR service (REMOTESERVER)**
This has a restricted CSV list of service names and a start/stop CSV restricted action parameter, and passes those manually on to the previous job

I then have several other jobs that will stop/start groups of specifically named services using that second job I listed, and restart jobs that call stop/start in sequence.  So there's quite a bit of nesting.

**Comment by alexray92** [comment]
I just tried again and confirmed that it's not merely a problem displaying job execution results, but rather the job-step doesn't seem to run at all.  If I go to the 'base' job, I can verify it is able to stop the service on the remote server, but when the same parameter is passed to it as a step on another job, nothing happens on the remote server.  The output log looks normal when I do it directly, too, as in I get the CLI feedback from the remote server.  

I do also get a "SLF4J: Class path contains multiple SLF4J bindings." warning, but I think that's unrelated.

**Comment by alexray92** [comment]
Actually, could I just override rundeck.ajax.compression='gzip' from Config.groovy somewhere?

I tried this in rundeck-config.properties:

rundeck.ajax.compression='none'
grails.rundeck.ajax.compression='none'
server.rundeck.ajax.compression='none'

rundeck.ajax.compression=''
grails.rundeck.ajax.compression=''
server.rundeck.ajax.compression=''

To no effect

**Comment by gschueler** [comment]
can you post your job definition, and any other error info from the service.log? Also feel free to email it if you don't want to post it publicly

**Comment by alexray92** [comment]
So here's the bizarre thing - I fixed it.

All I did is edit the winrmPassword argument, change from Secure Remote Authentication to Plain Text and back again, save.  The job that called it started working, and I've repeated it with two different sets of such jobs.

**Comment by alexray92** [comment]
I think it might be because the job was created before there was an option for a keyfile for the secure authentication value, and I upgraded the software for many versions without ever actually changing the job definition?

**Comment by alexray92** [comment]
I exported the YAML of a job before and after repeating that process, and the only difference is the first line:

**Old file:**
- description: ''

**New file:**
- defaultTab: summary

**Comment by gschueler** [comment]
It sounds like possibly there is an problem passing the secureRemoteAuth option value to sub-jobs

**Comment by alexray92** [comment]
The auth option was actually set on the job that was being called as a step from another job, rather than being passed.  Based on the YAML, it also looks like maybe it wasn't related to auth at all, but perhaps any change to the job might have added the '- defaultTab: summary' at the top
