### ISSUE TITLE
ERROR GrailsExceptionResolver - StackOverflowError - GUI is inaccessible until rundeck is restarted

### ISSUE THREAD

**Issue by asinha093** [rundeck/rundeck#3886]
**Describe the bug**
Repeated errors in the rundeck logs and 500 Internal server error in the GUI. The process is up and running but the GUI becomes unavailable. When rundeckd service is restarted, rundeck continues to work but the issues repeats after a few hours or so. The on going jobs do not resume when rundeckd is restarted and are marked as incomplete (jobs should resume their execution). Find the error log below in the additional context section

**My Rundeck detail**

* Rundeck version: [2.11.0]
* install type: [launcher]
* OS Name/version: [Linux 3.10.0-693.11.1.el7.x86_64]
* DB Type/version: [postgres]

**To Reproduce**
1. Go to 'var/log/service.log'
2. See errors in the log file
Also GUI is inaccessible with 500 Internal Server Error

**Expected behavior**
GUI should be accessible without seeing errors in the log file. No restart of service is required

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS - Darwin 16.7.0/ Windows 10]
 - Browser [chrome and safari]

**Additional context**
See the below snippet for error in the service.log log file:
```
2018-08-22 11:04:27,219 ERROR GrailsExceptionResolver - StackOverflowError occurred when processing request: [GET] /menu/homeSummaryAjax
Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [homeSummaryAjax] of controller [rundeck.controllers.MenuController]  caused exception: Runtime error executing action
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 44 more
Caused by: java.lang.reflect.InvocationTargetException
	... 44 more
Caused by: java.lang.StackOverflowError
	at java.util.Properties.enumerate(Properties.java:1098)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
  at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
	... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
	at gsp_rundeck_layoutsbase_gsp$_run_closure2.doCall(gsp_rundeck_layoutsbase_gsp.groovy:171)
	at gsp_rundeck_layoutsbase_gsp.run(gsp_rundeck_layoutsbase_gsp.groovy:186)
	... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
	at gsp_rundeck_common_topbar_gsp.run(gsp_rundeck_common_topbar_gsp.groovy:118)
	... 46 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
	at gsp_rundeck_framework_projectSelect_gsp.run(gsp_rundeck_framework_projectSelect_gsp.groovy:60)
	... 47 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <auth:resourceAllowed>: null
	at gsp_rundeck_framework_projectSelect_gsp$_run_closure2.doCall(gsp_rundeck_framework_projectSelect_gsp.groovy:46)
	at rundeck.BootstrapTagLib$_closure1.doCall(BootstrapTagLib.groovy:25)
	... 48 more
Caused by: java.lang.StackOverflowError
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
  at java.util.Properties.enumerate(Properties.java:1094)
at java.util.Properties.enumerate(Properties.java:1094)
at java.util.Properties.enumerate(Properties.java:1094)
at java.util.Properties.enumerate(Properties.java:1094)
at java.util.Properties.enumerate(Properties.java:1094)
at java.util.Properties.enumerate(Properties.java:1094)
2018-08-22 11:04:27,415 WARN  MemoryPageFragmentCachingFilter - Throwable thrown during doFilter on request with URI: /grails/menu/homeSummaryAjax.dispatch and Query: null : Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : base
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : base
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:446)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : base
... 44 more
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
at gsp_rundeck_layoutsbase_gsp$_run_closure2.doCall(gsp_rundeck_layoutsbase_gsp.groovy:171)
at gsp_rundeck_layoutsbase_gsp.run(gsp_rundeck_layoutsbase_gsp.groovy:186)
... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
at gsp_rundeck_common_topbar_gsp.run(gsp_rundeck_common_topbar_gsp.groovy:118)
... 46 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <bs:dropdown>: Error executing tag <auth:resourceAllowed>: null
at gsp_rundeck_framework_projectSelect_gsp.run(gsp_rundeck_framework_projectSelect_gsp.groovy:60)
... 47 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <auth:resourceAllowed>: null
at gsp_rundeck_framework_projectSelect_gsp$_run_closure2.doCall(gsp_rundeck_framework_projectSelect_gsp.groovy:46)
at rundeck.BootstrapTagLib$_closure1.doCall(BootstrapTagLib.groovy:25)
... 48 more
	at java.util.Properties.enumerate(Properties.java:1098)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
	at java.util.Properties.enumerate(Properties.java:1094)
```

**Comment by asinha093** [comment]
@ahonor @gschueler please give this a read and share your views.

**Comment by asinha093** [comment]
@ahonor any help here please?

**Comment by ahonor** [comment]
@asinha093 you should try the newest 2.11.x version or try out the newest 3.0.x one.

**Comment by asinha093** [comment]
@ahonor can you tell me how different the newer versions are in context of the above issue?

**Comment by ahonor** [comment]
@asinha093 there are bug fixes in all those newer releases. Ideally, you should try the newest 3.0 because it also has a newer version of the app framework.

**Comment by asinha093** [comment]
@ahonor thanks will update to 3.0.3 and see how it works over there
