### ISSUE TITLE
Cannot get property 'argString' on null object - when use "Activity for this Job"

### ISSUE THREAD

**Issue by isca0** [rundeck/rundeck#3887]
**Can't list executions history on Activity for this Job**
I'm trying to list the execution for the "Activity for this job", and whatever the options I choose, if it's recent, failed or "by you", always get this stacktrace on my rundeck logs:

```
rundeck    | rundeck stdout | 2018-08-23 09:51:22,571 ERROR GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /project/OnGoing/events/eventsAjax
rundeck    | Cannot get property 'argString' on null object. Stacktrace follows:
rundeck    | java.lang.NullPointerException: Cannot get property 'argString' on null object
rundeck    |    at rundeck.controllers.ReportsController$_eventsAjax_closure6.doCall(ReportsController.groovy:323)
rundeck    |    at rundeck.controllers.ReportsController.eventsAjax(ReportsController.groovy:293)
rundeck    |    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
rundeck    |    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
rundeck    |    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
rundeck    |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
rundeck    |    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
rundeck    |    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
rundeck    |    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
rundeck    |    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
rundeck    |    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
rundeck    |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
rundeck    |    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
rundeck    |    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
rundeck    |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
rundeck    |    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
rundeck    |    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
rundeck    |    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
rundeck    |    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
rundeck    |    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
rundeck    |    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
rundeck    |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
rundeck    |    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
rundeck    |    at org.eclipse.jetty.server.Server.handle(Server.java:446)
rundeck    |    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
rundeck    |    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
rundeck    |    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
rundeck    |    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
rundeck    |    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
rundeck    |    at java.lang.Thread.run(Thread.java:748)
```
However if I try to list the executions trough the project Activity the executions is been listed normally.

**My Rundeck detail**

* Rundeck version: [ Rundeck 2.10.1-1 cafe mocha tomato knight 2017-11-21]
* install type: [launcher]
* OS Name/version: [docker/alpine]
* DB Type/version: [mysql]

**To Reproduce**
1. Go to 'myrundecksession/project/[SomeProjec]t/job/show/[the-job-id]'
2. Click on 'Activity'
3. No execution will be listed, and the error will be displayed on logs.

**Expected behavior**
Click on 'Activity' and see a list of the executions for this job.

**Screenshots**
![](https://ibin.co/4DBY8HSBAZUo.jpg?raw=true)

**Desktop:**
 - OS: [Arch Linux x86-64]
 - Browser [Firefox]
 - Version [59.0.2 (64-bit)]

**Comment by gschueler** [comment]
Please try using Rundeck 2.11 or 3.0.  If this remains a problem, please reopen the issue.
