### ISSUE TITLE
UI Error: "Project does not exist" when working on another project

### ISSUE THREAD

**Issue by marcoc610** [rundeck/rundeck#3905]
**Describe the bug**

Trying to add a job to a project named "LNX", the UI throws an error "Project does not exist" referring to another project "Anvils" that has been deleted.

```
Error 500: Internal Server Error

URI
    /rundeck/project/LNX/job/create
Class
    com.dtolabs.rundeck.core.common.NoSuchResourceException
Message
    Project does not exist: Anvils
```
**My Rundeck detail**

* Rundeck version: 3.0.2
* install type: deb
* OS Name/version: Ubuntu 16.04
* DB Type/version: h2
* Rundeck runs behind nginx (location: /rundeck/).

**To Reproduce**

1. Create a project "LNX"
2. Create a project "Anvils"
3. Delete "Anvils"
4. Try to create a job in "LNX"

Restarting Rundeck, the error disappears.

**Other information**

Part of the Java Exception
```
com.dtolabs.rundeck.core.common.NoSuchResourceException: Project does not exist: Anvils
        at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:202)
        at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:28)
        at com.dtolabs.rundeck.core.common.FrameworkBase.getProjectProperty(FrameworkBase.java:251)
        at com.dtolabs.rundeck.core.common.PluginControlServiceImpl.listDisabledPlugins(PluginControlServiceImpl.java:33)
        at com.dtolabs.rundeck.core.common.PluginControlServiceImpl.isDisabledPlugin(PluginControlServiceImpl.java:87)
        at rundeck.controllers.ScheduledExecutionController$_create_closure75.doCall(ScheduledExecutionController.groovy:2364)
        at rundeck.controllers.ScheduledExecutionController.create(ScheduledExecutionController.groovy:2363)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
```

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.

**Comment by bigrana** [comment]
I have the same problem after that i have delete a project, when try to modify a Job in another project said that:

An Error Occurred
Project does not exist: Ansible-Test

Error 500: Internal Server Error
URI
/project/Infrastruttura-Interna/job/edit/af536ca3-3cbe-466f-b9a9-2b3fd3f9c58c
Class
com.dtolabs.rundeck.core.common.NoSuchResourceException
Message
Project does not exist: Ansible-Test
Trace
    Line | Method
->>  202 | getFrameworkProject in com.dtolabs.rundeck.core.common.FrameworkProjectMgr
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     28 | getFrameworkProject in     ''
|    251 | getProjectProperty  in com.dtolabs.rundeck.core.common.FrameworkBase
|     33 | listDisabledPlugins in com.dtolabs.rundeck.core.common.PluginControlServiceImpl
|     87 | isDisabledPlugin .  in     ''
|   2030 | doCall              in rundeck.controllers.ScheduledExecutionController$_edit_closure61
|   2029 | edit . . . . . . .  in rundeck.controllers.ScheduledExecutionController
|    223 | invoke              in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke . . . . . .  in org.grails.core.DefaultGrailsControllerClass
|     90 | handle              in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch . . . .  in org.springframework.web.servlet.DispatcherServlet
|    901 | doService           in     ''
|    970 | processRequest . .  in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet               in     ''
|    846 | service . . . . . . in     ''
|    865 | handle              in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter            in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run                 in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . .  in javax.security.auth.Subject
|    105 | doFilter            in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal    in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke . . . . . .  in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter            in     ''
|    331 | doFilter . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter            in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter . . . . .  in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . .  in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . .  in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . .  in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                in javax.security.auth.Subject
|    105 | doFilter . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter . . . . .  in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter . . . . .  in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter . . . . .  in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter . . . . .  in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal .  in org.springframework.security.web.FilterChainProxy
|    177 | doFilter            in     ''
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal    in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal    in org.grails.web.filters.HiddenHttpMethodFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle            in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle              in org.eclipse.jetty.security.SecurityHandler
|    132 | handle . . . . . .  in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle          in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle . . . . .  in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle          in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle . . . . .  in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope           in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope . . . . . . in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope             in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope             in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle              in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle . . . . . .  in org.eclipse.jetty.server.Server
|    352 | handle              in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable . . . .  in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded           in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable . . . . .  in org.eclipse.jetty.io.FillInterest
|    118 | run                 in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask . . . . . . in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce           in     ''
|    168 | tryProduce . . . .  in     ''
|    126 | run                 in     ''
|    366 | run . . . . . . . . in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob              in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run . . . . . . . . in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run                 in java.lang.Thread

**Comment by smazurov** [comment]
Ran into the same issue, restart fixed it.

**Comment by DoomStar** [comment]
Ran into the same issue, restart fixed it.
3.0.13 (docker)

**Comment by reinerrdeck** [comment]
Issue confirmed. 

Rundeck 3.0.14 DEB
DB: H2
OS: Debian 9

Maybe Rundeck keeps some flag pointing to the last project selected before a change to the new project (even if the first it has been removed).

![evidence_302](https://user-images.githubusercontent.com/43051294/53279543-1ee6bd80-36f0-11e9-9ed6-e41e6dde3224.png)

Trace:

```
 Line | Method
->>  202 | getFrameworkProject in com.dtolabs.rundeck.core.common.FrameworkProjectMgr
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     28 | getFrameworkProject in     ''
|    245 | getProjectProperty  in com.dtolabs.rundeck.core.common.FrameworkBase
|     33 | listDisabledPlugins in com.dtolabs.rundeck.core.common.PluginControlServiceImpl
|     87 | isDisabledPlugin .  in     ''
|   2368 | doCall              in rundeck.controllers.ScheduledExecutionController$_create_closure75
|   2367 | create . . . . . .  in rundeck.controllers.ScheduledExecutionController
|    223 | invoke              in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke . . . . . .  in org.grails.core.DefaultGrailsControllerClass
|     90 | handle              in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch . . . .  in org.springframework.web.servlet.DispatcherServlet
|    901 | doService           in     ''
|    970 | processRequest . .  in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet               in     ''
|    846 | service . . . . . . in     ''
|    865 | handle              in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter            in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run                 in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . .  in javax.security.auth.Subject
|    105 | doFilter            in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal    in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal    in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke . . . . . .  in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter            in     ''
|    331 | doFilter . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter            in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter . . . . .  in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal .  in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . .  in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . .  in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . .  in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                in javax.security.auth.Subject
|    105 | doFilter . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter . . . . .  in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter . . . . .  in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter . . . . .  in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter . . . . .  in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter            in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal .  in org.springframework.security.web.FilterChainProxy
|    177 | doFilter            in     ''
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal    in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal    in org.grails.web.filters.HiddenHttpMethodFilter
|   1642 | doFilter . . . . .  in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle            in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle              in org.eclipse.jetty.security.SecurityHandler
|    132 | handle . . . . . .  in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle          in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle . . . . .  in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle          in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle . . . . .  in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope           in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope . . . . . . in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope             in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope             in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle              in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle . . . . . .  in org.eclipse.jetty.server.Server
|    352 | handle              in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable . . . .  in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded           in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable . . . . .  in org.eclipse.jetty.io.FillInterest
|    118 | run                 in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask . . . . . . in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce           in     ''
|    168 | tryProduce . . . .  in     ''
|    126 | run                 in     ''
|    366 | run . . . . . . . . in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob              in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run . . . . . . . . in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run                 in java.lang.Thread 
```

service.log

```
2019-02-22 17:05:32.387 ERROR --- [ qtp30912386-28] o.g.web.errors.GrailsExceptionResolver   : NoSuchResourceException occurred when processing request: [GET] /project/Anvils/job/create
Project does not exist: Prg2. Stacktrace follows:

com.dtolabs.rundeck.core.common.NoSuchResourceException: Project does not exist: Prg2
        at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:202)
        at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:28)
        at com.dtolabs.rundeck.core.common.FrameworkBase.getProjectProperty(FrameworkBase.java:245)
        at com.dtolabs.rundeck.core.common.PluginControlServiceImpl.listDisabledPlugins(PluginControlServiceImpl.java:33)
        at com.dtolabs.rundeck.core.common.PluginControlServiceImpl.isDisabledPlugin(PluginControlServiceImpl.java:87)
        at rundeck.controllers.ScheduledExecutionController$_create_closure75.doCall(ScheduledExecutionController.groovy:2368)
        at rundeck.controllers.ScheduledExecutionController.create(ScheduledExecutionController.groovy:2367)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter.doFilterInternal(RundeckSecurityHeadersFilter.groovy:67)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter.doFilterInternal(GrailsHttpPutFormContentFilter.groovy:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
```
