### ISSUE TITLE
Rundeck 3.0.5 on Ubuntu fails to start service

### ISSUE THREAD

**Issue by jheusser** [rundeck/rundeck#3976]
**Describe the bug**
Installing Rundeck 3.0.5 on a freshly provisioned Ubuntu fails to start rundeckd service.

**My Rundeck detail**
* Rundeck version: 3.0.5.20180828-1.201808282140
* install type: deb
* OS Name/version: Ubuntu 16.04.3 LTS xenial
* DB Type/version: default

**To Reproduce**
1. apt-get install rundeck
2. systemctl status rundeckd --> failed

**Expected behavior**
As described here:
https://rundeck.org/3.0.x-SNAPSHOT/administration/install/ubuntudebian.html

**Additional context**
Exception in `/var/log/rundeck/service.log`:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'log4jConfigurer': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1634)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at rundeckapp.Application.main(Application.groovy:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.io.FileNotFoundException: class path resource [log4j.properties] cannot be resolved to URL because it does not exist
        at org.springframework.util.ResourceUtils.getURL(ResourceUtils.java:135)
        at org.springframework.util.Log4jConfigurer.initLogging(Log4jConfigurer.java:69)
        at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:265)
        at org.springframework.beans.factory.config.MethodInvokingBean.invokeWithTargetException(MethodInvokingBean.java:119)
        at org.springframework.beans.factory.config.MethodInvokingFactoryBean.afterPropertiesSet(MethodInvokingFactoryBean.java:106)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1692)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
        ... 29 common frames omitted
```

**Comment by sjrd218** [comment]
Could you send your rundeck-config.properties?

**Comment by jheusser** [comment]
Thanks @sjrd218 ! My provisioning script actually installed `/etc/rundeck/rundeck-config.properties` from a 2.x version which does not have the `rundeck.log4j.config.file` property, apologies.

For future reference, `apt-get install rundeck` will not touch existing configuration files of previous installations or provisioning scripts which requires this property. So the upgrade steps described at https://rundeck.org/docs/upgrading/upgrade-to-rundeck-3.x.html have to be followed manually.
