### ISSUE TITLE
NullPointerException in node-first exectuor

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck#3996]
**Describe the bug**

Execution fails due to a NullPointerException.

**My Rundeck detail**

* Rundeck version: 2.10.7
* install type: rpm
* OS Name/version: RHEL 6
* DB Type/version: mysql

**To Reproduce**

Race condition or programming error, so I do not have a reliable reproduction, but this happened in our production environment killing an upgrade, so raising without steps to repro, other than:

1. Create a nontrivial series of jobs with some sub-jobs jusing node-first execution
2. Run them hundreds of times?
3. Observe the following stack trace and execution failure:

```

localhost | 6. Server Tasks/Validate server rollback target | java.lang.NullPointerException
-- | -- | --
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.extractWFDispatcherResult(NodeFirstWorkflowExecutor.java:293)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWFSectionNodeDispatch(NodeFirstWorkflowExecutor.java:255)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:113)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutor$executeWorkflow.call(Unknown Source)
10:13:45 |   |   | at rundeck.services.ExecutionService$_runJobRefExecutionItem_closure82$_closure124.doCall(ExecutionService.groovy:3225)
10:13:45 |   |   | at rundeck.services.ExecutionService$_runJobRefExecutionItem_closure82$_closure124.doCall(ExecutionService.groovy)
10:13:45 |   |   | at sun.reflect.GeneratedMethodAccessor1858.invoke(Unknown Source)
10:13:45 |   |   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:45 |   |   | at java.lang.reflect.Method.invoke(Method.java:498)
10:13:45 |   |   | at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
10:13:45 |   |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
10:13:45 |   |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
10:13:45 |   |   | at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
10:13:45 |   |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
10:13:45 |   |   | at groovy.lang.Closure.call(Closure.java:414)
10:13:45 |   |   | at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
10:13:45 |   |   | at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
10:13:45 |   |   | at com.sun.proxy.$Proxy58.get(Unknown Source)
10:13:45 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
10:13:45 |   |   | at sun.reflect.GeneratedMethodAccessor1857.invoke(Unknown Source)
10:13:45 |   |   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:45 |   |   | at java.lang.reflect.Method.invoke(Method.java:498)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:213)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
10:13:45 |   |   | at rundeck.services.ExecutionService$_runJobRefExecutionItem_closure82.doCall(ExecutionService.groovy:3224)
10:13:45 |   |   | at rundeck.services.ExecutionService$_runJobRefExecutionItem_closure82.doCall(ExecutionService.groovy)
10:13:45 |   |   | at sun.reflect.GeneratedMethodAccessor1862.invoke(Unknown Source)
10:13:45 |   |   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:45 |   |   | at java.lang.reflect.Method.invoke(Method.java:498)
10:13:45 |   |   | at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
10:13:45 |   |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
10:13:45 |   |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
10:13:45 |   |   | at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
10:13:45 |   |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
10:13:45 |   |   | at groovy.lang.Closure.call(Closure.java:414)
10:13:45 |   |   | at groovy.lang.Closure.call(Closure.java:408)
10:13:45 |   |   | at com.codahale.metrics.Timer.time(Timer.java:99)
10:13:45 |   |   | at com.codahale.metrics.Timer$time.call(Unknown Source)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
10:13:45 |   |   | at com.codahale.metrics.Timer$time.call(Unknown Source)
10:13:45 |   |   | at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:190)
10:13:45 |   |   | at sun.reflect.GeneratedMethodAccessor563.invoke(Unknown Source)
10:13:45 |   |   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:45 |   |   | at java.lang.reflect.Method.invoke(Method.java:498)
10:13:45 |   |   | at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
10:13:45 |   |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
10:13:45 |   |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
10:13:45 |   |   | at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
10:13:45 |   |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
10:13:45 |   |   | at groovy.lang.Closure.call(Closure.java:414)
10:13:45 |   |   | at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:62)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
10:13:45 |   |   | at rundeck.services.ExecutionService.runJobRefExecutionItem(ExecutionService.groovy:3223)
10:13:45 |   |   | at rundeck.services.ExecutionService.runJobRefExecutionItem(ExecutionService.groovy)
10:13:45 |   |   | at sun.reflect.GeneratedMethodAccessor1995.invoke(Unknown Source)
10:13:45 |   |   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:45 |   |   | at java.lang.reflect.Method.invoke(Method.java:498)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
10:13:45 |   |   | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
10:13:45 |   |   | at rundeck.services.ExecutionService.executeWorkflowStep(ExecutionService.groovy:2803)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:97)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:291)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:687)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:73)
10:13:45 |   |   | at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:31)
10:13:45 |   |   | at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$processRunnableOperations$27(WorkflowEngineOperationsProcessor.java:224)
10:13:45 |   |   | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:13:45 |   |   | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
10:13:45 |   |   | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
10:13:45 |   |   | at java.lang.Thread.run(Thread.java:748)
10:13:45 |   |   | Exception: class java.lang.NullPointerException: null
10:13:45 |   | 5. Install/Common/Upgrade Tasks (Closed Servers) | Step [10] did not run. start conditions: [(after.step.9 == 'true')], skip conditions: []
10:13:45 |   |   | Step [3] did not run. start conditions: [(after.step.2 == 'true')], skip conditions: []
10:13:45 |   |   | Step [4] did not run. start conditions: [(after.step.3 == 'true')], skip conditions: []
10:13:45 |   |   | Step [5] did not run. start conditions: [(after.step.4 == 'true')], skip conditions: []
10:13:45 |   |   | Step [12] did not run. start conditions: [(after.step.11 == 'true')], skip conditions: []
10:13:45 |   |   | Step [7] did not run. start conditions: [(after.step.6 == 'true')], skip conditions: []
10:13:45 |   |   | Step [8] did not run. start conditions: [(after.step.7 == 'true')], skip conditions: []
10:13:45 |   |   | Step [11] did not run. start conditions: [(after.step.10 == 'true')], skip conditions: []
10:13:45 |   |   | Step [6] did not run. start conditions: [(after.step.5 == 'true')], skip conditions: []
10:13:45 |   |   | Step [9] did not run. start conditions: [(after.step.8 == 'true')], skip conditions: []
10:13:45 |   |   | Step [7] did not run. start conditions: [(after.step.6 == 'true')], skip conditions: []
10:13:45 |   |   | Step [8] did not run. start conditions: [(after.step.7 == 'true')], skip conditions: []
10:13:45 |   |   | Step [6] did not run. start conditions: [(after.step.5 == 'true')], skip conditions: []
10:13:45 |   |   | Execution failed: 963235 in project XIT: [Workflow result: , step failures: {5=JobFailed: Job [Install/Common/Upgrade Tasks (Closed Servers)] failed}, flow control: Continue, status: failed]


```

**Expected behavior**

The execution runs and doesn't cause an exception.

**Screenshots**

None.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser; Any
 - Version: Any

**Additional context**

I am requesting the service.log from production operations team and will post anything of note.

**Comment by puremourning** [comment]
There was nothing in the service log related that i could find (i can't post it as it is > 300MB). It didn't really help that the service log doesn't include timestamps. 

I did however see the following, not sure if it is expected or not:

```
ERROR GrailsExceptionResolver: ConcurrentModificationException occurred when processing request: [GET] /project/XIT/job/workflowJson
Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : base
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <bs:dropdown>: null
	... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <bs:dropdown>: null
	at gsp_rundeck_layoutsbase_gsp$_run_closure2.doCall(gsp_rundeck_layoutsbase_gsp.groovy:171)
	at gsp_rundeck_layoutsbase_gsp.run(gsp_rundeck_layoutsbase_gsp.groovy:186)
	... 44 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <bs:dropdown>: null
	at gsp_rundeck_common_topbar_gsp.run(gsp_rundeck_common_topbar_gsp.groovy:117)
	... 46 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <bs:dropdown>: null
	at gsp_rundeck_framework_projectSelect_gsp.run(gsp_rundeck_framework_projectSelect_gsp.groovy:60)
	... 47 more
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at gsp_rundeck_framework_projectSelect_gsp$_run_closure2.doCall(gsp_rundeck_framework_projectSelect_gsp.groovy:48)
	at rundeck.BootstrapTagLib$_closure1.doCall(BootstrapTagLib.groovy:25)
	... 48 more
```

These errors also seem unrelated, but important? There are tons of them.

```
INFO  ExecutionService: updated scheduled Execution
WARN  ExecutionService: Failed to delete file while deleting execution 946895: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946895.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946895: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946895.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946813: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946813.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946813: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946813.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946735: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946735.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946735: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946735.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946657: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946657.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946657: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946657.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946576: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946576.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946576: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946576.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946478: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946478.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946478: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946478.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946400: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946400.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946400: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946400.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946322: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946322.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946322: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946322.state.json
WARN  ExecutionService: Failed to delete file while deleting execution 946245: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946245.rdlog
WARN  ExecutionService: Failed to delete file while deleting execution 946245: /var/lib/rundeck/logs/rundeck/PROD/job/48da3fb2-df2d-4e85-9912-cf4639446ab0/logs/946245.state.json
```


Finally this, but again no idea if it is relevant or even on the same day.

```
INFO  ExecutionService: updated scheduled Execution
ERROR NodeStepPluginAdapter: Error executing node step.
com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: Result code was 1
	at com.dtolabs.rundeck.plugin.localexec.LocalExecNodeStepPlugin.executeNodeStep(LocalExecNodeStepPlugin.java:138)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:115)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:145)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:130)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:61)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:201)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:172)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:65)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:97)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:291)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:687)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:73)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:31)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$processRunnableOperations$27(WorkflowEngineOperationsProcessor.java:224)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ShedPlant** [comment]
Seen the same crash in the same workflow as @puremourning , although at a different step.
Rundeck version is now ASH 2.11.10-1 cappuccino tomato lamp 2019-02-22

This exception was printed at the bottom of the log, and also in /var/logs/rundeck/service.log

```
ERROR NodeStepPluginAdapter: Error executing node step.
com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: Script result code was: 1
        at com.dtolabs.rundeck.core.execution.workflow.steps.node.ScriptPluginNodeStepPlugin.executeNodeStep(ScriptPluginNodeStepPlugin.java:109)
        at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:116)
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:157)
        at com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$ExecNodeStepCallable.call(ParallelNodeDispatcher.java:225)
        at com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$ExecNodeStepCallable.call(ParallelNodeDispatcher.java:192)
        at com.dtolabs.rundeck.core.execution.dispatch.OrchestratorNodeProcessor$OrchestratorRunnable.call(OrchestratorNodeProcessor.java:175)
        at com.dtolabs.rundeck.core.execution.dispatch.OrchestratorNodeProcessor$OrchestratorRunnable.call(OrchestratorNodeProcessor.java:155)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on a current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team

**Comment by mpiscaer** [comment]
I see the same in service.log. I'm using a job where the Orchestrator is set to Random subset. If I change this to "Rank tiered", it fails fine.
With "Random subset" I see
```
[2020-06-22 21:03:04,916] node.NodeStepPluginAdapter ERROR NodeStepPluginAdapter: Error executing node step.
com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: Result code was 1
        at com.dtolabs.rundeck.plugin.localexec.LocalExecNodeStepPlugin.executeNodeStep(LocalExecNodeStepPlugin.java:138)
        at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:166)
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:206)
        at com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$ExecNodeStepCallable.call(ParallelNodeDispatcher.java:225)
        at com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$ExecNodeStepCallable.call(ParallelNodeDispatcher.java:192)
        at com.dtolabs.rundeck.core.execution.dispatch.OrchestratorNodeProcessor$OrchestratorRunnable.call(OrchestratorNodeProcessor.java:228)
        at com.dtolabs.rundeck.core.execution.dispatch.OrchestratorNodeProcessor$OrchestratorRunnable.call(OrchestratorNodeProcessor.java:207)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

With "Rank tiered" I see:

```
[2020-06-22 20:52:28,616] node.NodeStepPluginAdapter ERROR NodeStepPluginAdapter: Error executing node step.
com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: Result code was 1
        at com.dtolabs.rundeck.plugin.localexec.LocalExecNodeStepPlugin.executeNodeStep(LocalExecNodeStepPlugin.java:138)
        at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:166)
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:206)
        at com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$ExecNodeStepCallable.call(ParallelNodeDispatcher.java:225)
        at com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$ExecNodeStepCallable.call(ParallelNodeDispatcher.java:192)
        at com.dtolabs.rundeck.core.execution.dispatch.OrchestratorNodeProcessor$OrchestratorRunnable.call(OrchestratorNodeProcessor.java:228)
        at com.dtolabs.rundeck.core.execution.dispatch.OrchestratorNodeProcessor$OrchestratorRunnable.call(OrchestratorNodeProcessor.java:207)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-06-22 20:52:28.657] ERROR ExecutionUtilService --- [eduler_Worker-3] Execution failed: 1076 in project project1: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [server01: NonZeroResultCode: Result code was 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {server01=[NonZeroResultCode: Result code was 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
```

I use the following job:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: e73cafff-81ef-4051-978e-1b110a703878
  loglevel: INFO
  maxMultipleExecutions: '1'
  name: Hello world
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'tags: compute_all ComputeNodeInPool: true'
  nodesSelectedByDefault: true
  orchestrator:
    configuration:
      count: '5'
    type: subset
  plugins:
    ExecutionLifecycle: null
  retry:
    delay: '0'
    retry: '0'
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: /usr/local/share/rundeck-jobs/helloworld.sh
      description: local Hello World
      nodeStep: true
      type: localexec
    keepgoing: false
    strategy: node-first
  timeZone: Europe/Amsterdam
  uuid: e73cafff-81ef-4051-978e-1b110a703878
```

The helloworld.sh is nothing more then:
```
#!/bin/bash

echo Hello World!

exit 1
```
I'm using Ubuntu 18.04 openjdk version "1.8.0_252" and Rundeck 3.2.8-20200608
