### ISSUE TITLE
Rundeck quit unexpectedly, "Exception while executing step [2]: [java.lang.IllegalStateException: Method on class [rundeck.ScheduledExecution] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.]"

### ISSUE THREAD

**Issue by ShedPlant** [rundeck/rundeck#4033]
**Describe the bug**
Rundeck has been running for weeks/months ok, running scheduled executions 
Rundeck quit unexpectedly early this morning. There were some executions running at the time. It looks to me from the log message like it's failing to save the completed execution state, then quits.

Logged exception in one of the incomplete executions is:

```
Exception while executing step [2]: [java.lang.IllegalStateException: Method on class [rundeck.ScheduledExecution] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.]
java.lang.RuntimeException: java.lang.IllegalStateException: Method on class [rundeck.ScheduledExecution] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:87)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:73)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:31)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$processRunnableOperations$27(WorkflowEngineOperationsProcessor.java:224)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor$$Lambda$89/1180251821.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Method on class [rundeck.ScheduledExecution] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
	at rundeck.ScheduledExecution.currentGormStaticApi(ScheduledExecution.groovy)
	at rundeck.ScheduledExecution.createCriteria(ScheduledExecution.groovy)
	at rundeck.ScheduledExecution$createCriteria$42.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at rundeck.ScheduledExecution$createCriteria$19.call(Unknown Source)
	at rundeck.ScheduledExecution.findAllScheduledExecutions(ScheduledExecution.groovy:906)
	at rundeck.ScheduledExecution$findAllScheduledExecutions$41.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at rundeck.ScheduledExecution$findAllScheduledExecutions$24.call(Unknown Source)
	at rundeck.services.ExecutionService.runJobRefExecutionItem(ExecutionService.groovy:3156)
	at rundeck.services.ExecutionService.runJobRefExecutionItem(ExecutionService.groovy)
	at sun.reflect.GeneratedMethodAccessor3654.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
	at rundeck.services.ExecutionService.executeWorkflowStep(ExecutionService.groovy:2803)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:97)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:291)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:687)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	... 8 more
Exception while executing step [2]: 	[java.lang.RuntimeException: java.lang.IllegalStateException: Method on class [rundeck.ScheduledExecution] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.]
```

[rundeck.log extract](https://github.com/rundeck/rundeck/files/2392397/rundeck.extract.log)
[service.log extract](https://github.com/rundeck/rundeck/files/2392424/service.extract.log)

**My Rundeck detail**

* Rundeck version: Rundeck 2.10.7-1
* install type: rpm
* OS Name/version: Redhat 6.5
* DB Type/version: mysql

**To Reproduce**
Unknown

**Expected behavior**
Stay running

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A that I know of.

**Comment by gschueler** [comment]
When rundeck shuts down, things like DB connection are no longer available, but some processes attempt to retry when they encounter failure. in this case rundeck shut down, then an existing execution retries saving its state.

This was improved in rundeck 2.11.1. https://github.com/rundeck/rundeck/issues/2498

**Comment by ShedPlant** [comment]
Thanks. That doesn’t explain why Rundeck quit, though? Is there any clue in the logs?
		
		

		Ed Plant
	




On Tue, Sep 18, 2018 at 5:58 PM +0100, "Greg Schueler" <notifications@github.com> wrote:












When rundeck shuts down, things like DB connection are no longer available, but some processes attempt to retry when they encounter failure. in this case rundeck shut down, then an existing execution retries saving its state.


This was improved in rundeck 2.11.1. #2498
