### ISSUE TITLE
rd adhoc fails "com.fasterxml.jackson.core.JsonParseException: Non-standard token 'NaN'"

### ISSUE THREAD

**Issue by ShedPlant** [rundeck/rundeck#4085]
**Describe the bug**
A TCL script running as a rundeck job
At its completion, the script calls `rd adhoc` to echo "End" to Rundeck activity log.
```
    exec rd adhoc -p $::g(PROJECT)     \
                  --follow             \
                  --keepgoing          \
                  --quiet              \
                  --                   \
                  {*}$args
```
_Sometimes_ rd adhoc fails with exception as per below.
But not always. There's no cause or pattern that I can see to when it fails.

```
%FAIL:  TestInstallPerforceBasedServerAccountWrappers failed: # Started execution 495976 running 2018-10-05T05:27:22+0100 - https://myrundeckhost:4440/project/myrundeckproject/execution/show/495976 adhoc echo End
com.fasterxml.jackson.core.JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: java.io.InputStreamReader@623a8092; line: 1, column: 171]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1884)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:972)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
	at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
	at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:118)
	at org.rundeck.client.tool.commands.Executions.startFollowOutput(Executions.java:135)
	at org.rundeck.client.tool.commands.Executions.maybeFollow(Executions.java:649)
	at org.rundeck.client.tool.commands.Adhoc.adhoc(Adhoc.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:820)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:351)
	at org.rundeck.client.tool.Main.main(Main.java:69) # Started execution 495976 running 2018-10-05T05:27:22+0100 - https://myrundeckhost:4440/project/myrundeckproject/execution/show/495976 adhoc echo End
com.fasterxml.jackson.core.JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: java.io.InputStreamReader@623a8092; line: 1, column: 171]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1884)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:972)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
	at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
	at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:118)
	at org.rundeck.client.tool.commands.Executions.startFollowOutput(Executions.java:135)
	at org.rundeck.client.tool.commands.Executions.maybeFollow(Executions.java:649)
	at org.rundeck.client.tool.commands.Adhoc.adhoc(Adhoc.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:820)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:351)
	at org.rundeck.client.tool.Main.main(Main.java:69)
    while executing
"exec rd adhoc -p $::g(PROJECT)      --follow              --keepgoing           --quiet               --                    {*}$args"
    (procedure "XitTest::AdHocLocal" line 2)
    invoked from within
"XitTest::AdHocLocal echo "End""

```

**My Rundeck detail**

* Rundeck version: 2.10.7-1
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux Server release 6.8 (Santiago)
* DB Type/version: mysql

**To Reproduce**
1. use rd adhoc with above arguments and a simple "echo test", many times
2. possible extra conditions unknown??

**Expected behavior**
rd adhoc to always work

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
I suppose we could try using the REST API instead.

**Comment by ShedPlant** [comment]
@puremourning

**Comment by ahonor** [comment]
@ShedPlant maybe there is an offending character in the .rdlog file. Can you take a look for the case you get this issue?

**Comment by ShedPlant** [comment]
495976.rdlog
```
^text/x-rundeck-log-v2.0^
^2018-10-05T04:27:23Z|stepbegin||{node=localhost|step=1|stepctx=1|user=admin}|^
^2018-10-05T04:27:23Z|nodebegin||{node=localhost|step=1|stepctx=1|user=rundeck}|^
^2018-10-05T04:27:23Z|||{node=localhost|step=1|stepctx=1|user=rundeck}|End^
^2018-10-05T04:27:24Z|nodeend||{node=localhost|step=1|stepctx=1|user=rundeck}|^
^2018-10-05T04:27:24Z|stepend||{node=localhost|step=1|stepctx=1|user=admin}|^
^END^
```
495976.state.json
```
{"executionId":495976,"nodes":{"localhost":[{"stepctx":"1","executionState":"SUCCEEDED"}]},"serverNode":"localhost","executionState":"SUCCEEDED","completed":true,"targetNodes":["localhost"],"allNodes":["localhost"],"stepCount":1,"updateTime":"2018-10-05T05:27:24Z","startTime":"2018-10-05T05:27:23Z","endTime":"2018-10-05T05:27:24Z","steps":[{"nodeStates":{"localhost":{"executionState":"SUCCEEDED","startTime":"2018-10-05T05:27:23Z","updateTime":"2018-10-05T05:27:24Z","duration":406,"endTime":"2018-10-05T05:27:24Z"}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2018-10-05T05:27:23Z","updateTime":"2018-10-05T05:27:23Z","duration":407,"endTime":"2018-10-05T05:27:24Z"}]}
```

**Comment by ShedPlant** [comment]
The execution id of the parent script was 495847 but I don't see any files of that name in /var/lib/rundeck/logs/rundeck/myproject/run/logs

**Comment by puremourning** [comment]
@ShedPlant how often do we see this?

**Comment by ShedPlant** [comment]
05/10/18
30/10/18
22/11/18

**Comment by ShedPlant** [comment]
We still see this sometimes but the impact is low.

**Comment by puremourning** [comment]
This still happens.

**Comment by fdevans** [comment]
@puremourning Does it happen on the latest release?  Is it still rarely happening?  Has time offered any insight to the pattern or how to reproduce it?

**Comment by mikagika** [comment]
We see this periodically too when using rd to submit jobs. No obvious pattern to it, we use rd hundreds of times a day, but see this maybe once or twice a week. 

com.fasterxml.jackson.core.JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 171]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1880)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:968)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
	at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
	at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:103)
	at org.rundeck.client.tool.commands.Executions.startFollowOutput(Executions.java:143)
	at org.rundeck.client.tool.commands.Executions.maybeFollow(Executions.java:609)
	at org.rundeck.client.tool.commands.Run.run(Run.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:1023)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:624)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:476)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:624)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:476)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:433)
	at org.rundeck.client.tool.Main.main(Main.java:71)

rd version 1.2.4
Rundeck version 2.10.8-1, although I believe we've seen it on v3 Rundeck too.
