### ISSUE TITLE
Job Fails When Scheduled But Passes When Run Manually

### ISSUE THREAD

**Issue by mcgurksean** [rundeck/rundeck#4091]
**Describe the bug**
I have created a job in Rundeck that uses the 'requests' python module (http://docs.python-requests.org/en/master/) to pull a list of projects from various Rundeck servers via the API.

When I run this job manually, the script is able to be executed and the job completes successfully.

However, when I run the same job from a schedule, the job fails with the following error message:

```
16:00:07 | 2018-10-07 15:00:06,452 - rundeck_jobs_backup - INFO - list_projects - Retrieving list of projects from the Rundeck server
-- | --
16:00:07 | Traceback (most recent call last):
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
16:00:07 | (self.host, self.port), self.timeout, **extra_kw)
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\util\connection.py", line 83, in create_connection
16:00:07 | raise err
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\util\connection.py", line 73, in create_connection
16:00:07 | sock.connect(sa)
16:00:07 | ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
16:00:07 |  
16:00:07 | During handling of the above exception, another exception occurred:
16:00:07 |  
16:00:07 | Traceback (most recent call last):
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
16:00:07 | chunked=chunked)
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 356, in _make_request
16:00:07 | conn.request(method, url, **httplib_request_kw)
16:00:07 | File "C:\Python\Python35\lib\http\client.py", line 1083, in request
16:00:07 | self._send_request(method, url, body, headers)
16:00:07 | File "C:\Python\Python35\lib\http\client.py", line 1128, in _send_request
16:00:07 | self.endheaders(body)
16:00:07 | File "C:\Python\Python35\lib\http\client.py", line 1079, in endheaders
16:00:07 | self._send_output(message_body)
16:00:07 | File "C:\Python\Python35\lib\http\client.py", line 911, in _send_output
16:00:07 | self.send(msg)
16:00:07 | File "C:\Python\Python35\lib\http\client.py", line 854, in send
16:00:07 | self.connect()
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\connection.py", line 166, in connect
16:00:07 | conn = self._new_conn()
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\connection.py", line 150, in _new_conn
16:00:07 | self, "Failed to establish a new connection: %s" % e)
16:00:07 | requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x0000000001E3EBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
16:00:07 |  
16:00:07 | During handling of the above exception, another exception occurred:
16:00:07 |  
16:00:07 | Traceback (most recent call last):
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\adapters.py", line 423, in send
16:00:07 | timeout=timeout
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
16:00:07 | _stacktrace=sys.exc_info()[2])
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\packages\urllib3\util\retry.py", line 376, in increment
16:00:07 | raise MaxRetryError(_pool, url, error or ResponseError(cause))
16:00:07 | requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nnsuoc.navimedix.com', port=4440): Max retries exceeded with url: /api/13/projects (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000001E3EBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
16:00:07 |  
16:00:07 | During handling of the above exception, another exception occurred:
16:00:07 |  
16:00:07 | Traceback (most recent call last):
16:00:07 | File "C:\RundeckRepo\RundeckJobScripts\RundeckResources\rundeck_jobs_backup.py", line 62, in <module>
16:00:07 | main()
16:00:07 | File "C:\RundeckRepo\RundeckJobScripts\RundeckResources\rundeck_jobs_backup.py", line 50, in main
16:00:07 | projects = get_project_names(list_projects())
16:00:07 | File "C:\RundeckRepo\RundeckJobScripts\RundeckResources\rundeck_resources.py", line 43, in list_projects
16:00:07 | r = requests.get(url, headers=headers, verify=False)
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\api.py", line 70, in get
16:00:07 | return request('get', url, params=params, **kwargs)
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\api.py", line 56, in request
16:00:07 | return session.request(method=method, url=url, **kwargs)
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\sessions.py", line 488, in request
16:00:07 | resp = self.send(prep, **send_kwargs)
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\sessions.py", line 609, in send
16:00:07 | r = adapter.send(request, **kwargs)
16:00:07 | File "C:\Python\Python35\lib\site-packages\requests\adapters.py", line 487, in send
16:00:07 | raise ConnectionError(e, request=request)
16:00:07 | requests.exceptions.ConnectionError: HTTPConnectionPool(host='xxx.xxx.com', port=4440): Max retries exceeded with url: /api/13/projects (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000001E3EBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
```

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.6-20180917
* install type: rpm
* OS Name/version: Centos
* DB Type/version: mysql

**To Reproduce**
1. Schedule a Rundeck job via either the Simple or CRON tabs
2. Job executes
3. View job details
4. Steps in job fail which causes job to fail

**Expected behavior**
Job should succeed if execution of the same job manually has succeeded

**Screenshots**
![scsbrundeck01_4](https://user-images.githubusercontent.com/1913745/46604304-ae972100-caed-11e8-95cf-11b0ef59533e.PNG)
![scsbrundeck01_5](https://user-images.githubusercontent.com/1913745/46604307-b48d0200-caed-11e8-8517-7fe83f1d0bd3.PNG)

**Desktop (please complete the following information):**
 - OS: Centos
 - Browser: Chrome
 - Version: 67.0.3396.99

**Additional context**
This only happens when the jobs are run via a schedule. When the jobs are run manually, they complete successfully.

**Comment by mcgurksean** [comment]
It's still an issue

**Comment by giturriaga** [comment]
I have the same issue, some help would be nice

**Comment by MegaDrive68k** [comment]
Hi @giturriaga

Which Rundeck version do you have?

Kind regards.

**Comment by giturriaga** [comment]
Rundeck 3.0.24-20190719

**Comment by giturriaga** [comment]
@MegaDrive68k Rundeck 3.0.24-20190719

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
