### ISSUE TITLE
After upgrade to 3.0.7: Some jobs don't execute any longer

### ISSUE THREAD

**Issue by sumpfgottheit** [rundeck/rundeck#4107]
**Describe the bug**
Jobs that, ran without problems until the upgrade to 3.0.7 dont't run any longer.
They fail with "Failed to start execution: java.lang.NullPointerException: null"

Some jobs are still working. Don't know why. Has probably something to to with stored password usage.

**My Rundeck detail**

* Rundeck version: 3.0.7
* install type: rpm
* OS Name/version: RHEL 6.8
* DB Type/version: postgresql

**To Reproduce**
1. Go to Project "KaminoInfrastruktur"
2. Click on "Start Job ZZ Artifactory: Create Release Configuration
3. Follow execution

start via schedule also doesn't word

**Expected behavior**
The job should run

**additional info**

Attaching following files:

During (non) execution, only logentries in audit.log are happending.

* ZZ_Artifactory__Create_Release_Configuration.yaml - Job that should be executed
* Create_release.json.yaml - Job that is called from first job
* audit.log-scheduled-execution: Failing Audit Log entries during schedule
* audit.log-manual-execution: Failing Audit Log entries during manual execution
* admin.aclpolicy - I am in the correct group and _should_ be allowed to do anyhing...

[admin.aclpolicy.txt](https://github.com/rundeck/rundeck/files/2465301/admin.aclpolicy.txt)
[ZZ_Artifactory__Create_Release_Configuration.yaml.txt](https://github.com/rundeck/rundeck/files/2465302/ZZ_Artifactory__Create_Release_Configuration.yaml.txt)
[Create_release.json.yaml.txt](https://github.com/rundeck/rundeck/files/2465303/Create_release.json.yaml.txt)
[audit.log-scheduled-execution.txt](https://github.com/rundeck/rundeck/files/2465304/audit.log-scheduled-execution.txt)
[audit.log-manual-execution.txt](https://github.com/rundeck/rundeck/files/2465305/audit.log-manual-execution.txt)

**Comment by sjrd218** [comment]
@sumpfgottheit Could you post the stacktrace you are seeing in the service log that contains the `Failed to start execution: java.lang.NullPointerException: null`?

**Comment by sumpfgottheit** [comment]
Will post the stracktrace tomorrow morning. (CEST)

**Comment by sumpfgottheit** [comment]
I attach the service.log after restarting rundeck and immediately start one of the failing jobs.

It look like only jobs are failing, the call jobs, that use **stored secrets** (passwords). The Stack Trace would also point in this direction imho.

I can execute the "sub-jobs" without problems....

[service.log.txt](https://github.com/rundeck/rundeck/files/2467538/service.log.txt)

```
2018-10-11 07:54:07.843 ERROR --- [eduler_Worker-1] rundeck.services.ExecutionService        : Failed while starting execution: 350939

java.lang.NullPointerException: null
	at com.dtolabs.rundeck.core.storage.AuthRundeckStorageTree.authorizedPath(AuthRundeckStorageTree.java:59)
	at com.dtolabs.rundeck.core.storage.AuthRundeckStorageTree.getResource(AuthRundeckStorageTree.java:142)
	at com.dtolabs.rundeck.core.storage.AuthRundeckStorageTree.getResource(AuthRundeckStorageTree.java:34)
	at com.dtolabs.rundeck.core.storage.ResolvedExtTree.getResource(ResolvedExtTree.java:68)
	at org.rundeck.storage.impl.DelegateTree.getResource(DelegateTree.java:56)
	at org.rundeck.storage.impl.DelegateTree$getResource.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at com.dtolabs.rundeck.server.plugins.storage.TypedStorageTreeImpl.getResourceWithType(TypedStorageTreeImpl.groovy:43)
	at com.dtolabs.rundeck.server.plugins.storage.TypedStorageTreeImpl$getResourceWithType.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at com.dtolabs.rundeck.server.plugins.storage.TypedStorageTreeImpl.readResourceWithType(TypedStorageTreeImpl.groovy:67)
	at com.dtolabs.rundeck.server.plugins.storage.TypedStorageTree$readResourceWithType.callCurrent(Unknown Source)
....
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:97)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

```

**Comment by johan-blondeau** [comment]
Hi, I have the same problem after upgrade to 3.0.7. Do you have a planned date to integrate this fix in a release ? Should we do a downgrade to 3.0.6 ?
Thanks
