### ISSUE TITLE
node import over script diying in case of "&" in any field

### ISSUE THREAD

**Issue by moutzl** [rundeck/rundeck#4145]
**My Rundeck detail**

build.core.git.branch | HEAD, refs/tags/v3.0.7
build.core.git.commit | 5a2a4dd4ecdfdfcde309b0a600d6123d447ad33e
build.core.git.description | v3.0.7-0-g5a2a4dd
build.ident | 3.0.7-20181008

**To Reproduce**

script added in 'project settings - edit nodes'  is generating xml NODE list, foe:

<node  name="Radisson_Blu_Beach_Resort_&_Spa_Sochi" description="Radisson_Blu_Beach_Resort_&_Spa_Sochi" hostname="xx.yy.zz.zz" country="russia" marsha="bla" ansible-ssh-user="user" ansible-ssh-password="password" osName="linux" ssh-authentication="password" ansible_become="yes" ansible_become_method="su" ansible_become_user="root" ansible_become_pass="somepassword" ansible_ssh_port="22" tags="cacti,linux,russia"/>

**Expected behavior**
have a node list

**logs -service.log**

ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 2.source (script), project: cacti_management]
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: failed to execute: /home/ansbl/inventory_cacti.sh: com.dtolabs.rundeck.core.resources.format.ResourceFormatParserException: com.dtolabs.rundeck.core.common.NodeFileParserException: com.dtolabs.shared.resources.ResourceXMLParserException: org.dom4j.DocumentException: Error on line 57 of document  : The reference to entity "_Spa_Sochi" must end with the ';' delimiter.
        at com.dtolabs.rundeck.core.resources.ScriptResourceModelSource.getNodes(ScriptResourceModelSource.java:170)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$LoadedSource.getNodes(ProjectNodeSupport.java:456)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:138)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:365)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
        at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44)
        at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
        at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:290)
        at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy)
        at sun.reflect.GeneratedMethodAccessor1205.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:57)
        at sun.reflect.GeneratedMethodAccessor1204.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:104)
        at rundeck.services.NodeService.loadNodes(NodeService.groovy:302)
        at sun.reflect.GeneratedMethodAccessor1197.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:95)
        at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy)
        at rundeck.services.NodeService$3.methodMissing(NodeService.groovy)
        at sun.reflect.GeneratedMethodAccessor908.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:951)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1279)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1227)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
        at rundeck.services.NodeService$3.invokeMethod(NodeService.groovy)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy:138)
        at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy)
        at sun.reflect.GeneratedMethodAccessor1253.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:271)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.dtolabs.rundeck.core.resources.ResourceModelSourceException: com.dtolabs.rundeck.core.resources.format.ResourceFormatParserException: com.dtolabs.rundeck.core.common.NodeFileParserException: com.dtolabs.shared.resources.ResourceXMLParserException: org.dom4j.DocumentException: Error on line 57 of document  : The reference to entity "_Spa_Sochi" must end with the ';' delimiter.
        at com.dtolabs.rundeck.core.resources.BaseFileResourceModelSource.loadNodes(BaseFileResourceModelSource.java:277)
        at com.dtolabs.rundeck.core.resources.BaseFileResourceModelSource.getNodes(BaseFileResourceModelSource.java:253)
        at com.dtolabs.rundeck.core.resources.BaseFileResourceModelSource.getNodes(BaseFileResourceModelSource.java:236)
        at com.dtolabs.rundeck.core.resources.FileResourceModelSource.parseFile(FileResourceModelSource.java:249)
        at com.dtolabs.rundeck.core.resources.ScriptResourceUtil.executeScript(ScriptResourceUtil.java:152)
        at com.dtolabs.rundeck.core.resources.ScriptResourceModelSource.getNodes(ScriptResourceModelSource.java:156)
        ... 70 more
Caused by: com.dtolabs.rundeck.core.resources.format.ResourceFormatParserException: com.dtolabs.rundeck.core.common.NodeFileParserException: com.dtolabs.shared.resources.ResourceXMLParserException: org.dom4j.DocumentException: Error on line 57 of document  : The reference to entity "_Spa_Sochi" must end with the ';' delimiter.
        at com.dtolabs.rundeck.core.resources.format.ResourceXMLFormatParser.parseDocument(ResourceXMLFormatParser.java:90)
        at com.dtolabs.rundeck.core.resources.BaseFileResourceModelSource.loadNodes(BaseFileResourceModelSource.java:271)
        ... 75 more
Caused by: com.dtolabs.rundeck.core.common.NodeFileParserException: com.dtolabs.shared.resources.ResourceXMLParserException: org.dom4j.DocumentException: Error on line 57 of document  : The reference to entity "_Spa_Sochi" must end with the ';' delimiter.
        at com.dtolabs.rundeck.core.common.NodesXMLParser.parse(NodesXMLParser.java:103)
        at com.dtolabs.rundeck.core.resources.format.ResourceXMLFormatParser.parseDocument(ResourceXMLFormatParser.java:88)
        ... 76 more
Caused by: com.dtolabs.shared.resources.ResourceXMLParserException: org.dom4j.DocumentException: Error on line 57 of document  : The reference to entity "_Spa_Sochi" must end with the ';' delimiter.
        at com.dtolabs.shared.resources.ResourceXMLParser.parse(ResourceXMLParser.java:141)
        at com.dtolabs.rundeck.core.common.NodesXMLParser.parse(NodesXMLParser.java:101)
        ... 77 more
Caused by: org.dom4j.DocumentException: Error on line 57 of document  : The reference to entity "_Spa_Sochi" must end with the ';' delimiter.
        at org.dom4j.io.SAXReader.read(SAXReader.java:462)
        at org.dom4j.io.SAXReader.read(SAXReader.java:325)
        at com.dtolabs.shared.resources.ResourceXMLParser.parse(ResourceXMLParser.java:113)
        ... 78 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 57; columnNumber: 51; The reference to entity "_Spa_Sochi" must end with the ';' delimiter.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:913)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanAttribute(XMLNSDocumentScannerImpl.java:447)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:250)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.dom4j.io.SAXReader.read(SAXReader.java:445)
        ... 80 more

**Comment by gschueler** [comment]
if you are generating XML, it must be valid xml.  Test your output on a XML syntax validation site.  The `&` character is special in xml, so must be escaped, e.g. as `&amp;`

**Comment by moutzl** [comment]
yeah, I was expecting it will not die on 'data'. of course I escaped the character.

**Comment by plambert** [comment]
@moutzl Are you saying that the Rundeck app is dying when the XML is invalid?

**Comment by moutzl** [comment]
nope, sorry I messed more things together. the crash was related to change of running user, import doesnt crash the app, just no node imported.

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.
