### ISSUE TITLE
No matched nodes

### ISSUE THREAD

**Issue by ahuret** [rundeck/rundeck#4231]
**Describe the bug**

```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=.*, dominant=false, }}
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:83)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:74)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=.*, dominant=false, }}
No matched nodes: NodeSet{includes={name=.*, dominant=false, }}
```

Only occurs when job are scheduled, when I try by hand, it works as expected.
This worked well before moving on new version 3.0.8.

Jobs are scheduled every 8 hours and when I change cron expression to scheduled it to some minutes, it works well, so it is difficult to reproduce with tests.

I also noticed some issues mentionning same problem as #2942.

Nodes are map by a custom plugin looking for nodes from kubernetes. This part seems to works well since there are no error logs from this part.

Projects Node Config:

Use Asynchronous Cache: true
Cache delay: 42
Synchronous First Load: true

**My Rundeck detail**

* Rundeck version: [3.0.8]
* install type: [war]
* OS Name/version: [alpine:3.7]
* DB Type/version: [postgres]

**Comment by antony360** [comment]
@gschueler any idea ?

**Comment by navya35** [comment]
Hello 
I have the same problem in 3.0.9 with a job that execute locally a job, just with echo and sleep bash script.
I tested with cache to 0 as said here https://github.com/rundeck/rundeck/issues/2942 but no solution for now.

**Comment by KroolData** [comment]
We're having same issue on Rundeck 2.10.0-1.
Is the latest version has solved this issue?

**Comment by dpomnean** [comment]
Having the issue in 2.11.7-1

**Comment by ianarsenault** [comment]
Having the same issue on 3.0.2

**Comment by beakerman29** [comment]
Just adding that this is an issue as well with version 3.0.20 as well.

**Comment by atul-chegg** [comment]
Yep, we are also seeing same issue.

**Comment by simocl** [comment]
I am seeing the issue with Rundeck 3.0.22. Any clue when it will be resolved?

**Comment by simocl** [comment]
I am going LIVE in one week and I am willing to pay someone to fix this ASAP. Thanks.

**Comment by gschueler** [comment]
Hi all, i'm sorry you are (still) having this problem, we encountered and fixed an earlier version of this problem but have not seen this particular one. Please include more information about your configuration: what are your node sources,  caching settings, etc, and if possible a simple way for us to reproduce it.

(also, if you are interested in paid support it is included with Rundeck Enterprise: https://rundeck.com)

**Comment by simocl** [comment]
Hi @gschueler, where to get the info you asked for? My Rundeck runs on Fedora 29. No external sources. No cache.

**Comment by gschueler** [comment]
One potential source of this problem: Authorization roles for scheduled jobs are stored with the job. *If you change ACL policies, group memberships, etc* then the roles associated with the previously created job may differ from your new ACL grants, and might restrict the job from accessing the expected nodes.

**Comment by dpomnean** [comment]
@gschueler I have this issue, but I would expect multiple jobs to be affected by this if ACL was the case. I am only seeing it on 1-2 jobs in 2 of our projects.

**Comment by beakerman29** [comment]
So we just switched from IPA as an authentication source to AD. We encountered this particular issue. What happens is that when a user edits a job the roles they are in are added to the scheduled_executions table under the user_role_list column. This only appears to be refreshed when a user edits the job that has the problem. I could see this happening as well if you decided to change the ACL policy to a group that wasn't on the original ACL Policy so say your original group was granted by ACL-Group-A and you changed the ACL to then be ACL-Group-B since the scheduled_executions user_role_list table doesn't contain that in the list it will throw this error. What I would propose in this situation would be the ability to query the table but if it doesn't find what it expects to have a fallback to make sure we don't need to refresh this value. Just my 2 cents

**Comment by simocl** [comment]
I am still getting this:

com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[146.71.79.244]}
--
13:19:59 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:369)
13:19:59 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
13:19:59 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:222)
13:19:59 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:83)
13:19:59 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
13:19:59 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:74)
13:19:59 |   |   | Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[146.71.79.244]}
13:19:59 |   |   | No matched nodes: MultiNodeSelector{nodenames=[146.71.79.244]}

**Comment by sksirajbasha** [comment]
I have this on Rundeck 3.0.4  node source Artifactory. 

Using Async cache 30 seconds.

Timeout 30 secs for node source URL.

This happened after we failed over to stand by node with all configurations set up on a new node.

The node list I see on the GUI for a job in the project is not refreshing at all.No matter what I do.

Tried removing Async, making cache less than 30 secs, or more than 30 seconds.

**Comment by remd** [comment]
Seeing this on 3.0.23 with async cache enabled and cacheDelay set to 30:
```
project.nodeCache.delay=30
project.nodeCache.enabled=true
project.nodeCache.firstLoadSynch=true
```

**Comment by joelsdc** [comment]
Yes, this also happens on current version (Debian package: 3.3.2.20200817-1)

In our case we moved from in-house LDAP to Google Secure LDAP, some of the roles have updated names, we updated rundeck config to match this in the `admin.aclpolicy` file, but the *scheduled* executions fail..

**Comment by weinerdog80** [comment]
Did any one got the solution to this problem ?
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector

**Comment by rpo-fr** [comment]
bug still present,

I have a doubt about the option job.successOnEmptyNodeFilter. 
It seems that if the main job has this option with false, the "slave" jobs are running with false even if the option is defined into with true.
Can someone confirm?

**Comment by wadelu** [comment]
The same issue on 3.3.10, will Rundeck fix it?

**Comment by Gerben-W** [comment]
After upgrading from 3.3 to 4.0 i also have this problem.
Manual runs work as expected, automated runs give:

```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=*, dominant=false, }}
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.validateNodeSet(BaseWorkflowExecutor.java:880)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:92)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:220)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:95)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:77)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=*, dominant=false, }}
No matched nodes: NodeSet{includes={name=*, dominant=false, }}
```

**Comment by Osirisus** [comment]
Still having same issue, using docker version "FROM rundeck/rundeck:3.4.9". One of 100 scheduled execution failed to find nodes, next run for same job success. 
```
project.nodeCache.delay=0
project.nodeCache.enabled=true
project.nodeCache.firstLoadSynch=true
```
