### ISSUE TITLE
Many deadlocks after upgrade

### ISSUE THREAD

**Issue by avinchakov** [rundeck/rundeck#4255]
**Describe the bug**
I see many deadlocks after upgrade from 2.x to 3.x. 
```
2018-11-28 10:03:28.779  WARN --- [132045-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1213, SQLState: 40001
2018-11-28 10:03:28.779 ERROR --- [132045-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Deadlock found when trying to get lock; try restarting transaction
2018-11-28 10:03:28.780 ERROR --- [132045-thread-1] rundeck.services.ExecutionService        : Caught ConcurrencyFailureException, will retry updateScheduledExecStatistics for jobref
```

Many of jobs do not start because of this.

**My Rundeck detail**

* Rundeck version: 3.0.8
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: mysql (percona 5.7)

**To Reproduce**
Launch of many jobs at the same time, about 10-20 at the same time.

**Expected behavior**
In the version 2.9 there were no problems

**Comment by ProTip** [comment]
Hi @avinchakov,

If you have it handy would you be able to run `SHOW ENGINE INNODB STATUS \G` on the database and paste in the information on the latest deadlocks it spits out that look related?

Thanks!

**Comment by avinchakov** [comment]
How to solve this problem?

**Comment by shlomosh** [comment]
I also see this issue.

**Comment by lancepowell** [comment]
seeing the same for some of our bigger jobs that run 100 nodes at a time.

**Comment by kevinjcash** [comment]
Also seeing this issue, only running jobs on the rundeck instance currently, but we have several jobs that run every minute.

**Comment by lancepowell** [comment]
was able to fix it with some properties, increasing the max active connections is a good start, shouldn't need remove abandoned but it's up to each instance. This is in rundeck-config.properties

```
dataSource.pooled=true
dataSource.properties.removeAbandoned=true
dataSource.properties.removeAbandonedTimeout=240
dataSource.properties.testOnBorrow=true
dataSource.properties.maxActive=200
```

**Comment by jtobard** [comment]
The solution from @lancepowell  of increasing the pool of connections can help in environments with a high load. A fix will be released in which you can disable the statistics of the referenced jobs to prevent those errors.

**Comment by avinchakov** [comment]
I also tried migrate to postgres - not helped. I faced a similar problem - https://github.com/rundeck/rundeck/issues/4186

**Comment by avinchakov** [comment]
I tried new Rundeck release and workaround above. After a couple of hours I get:
`2019-01-16 12:21:53.716 ERROR --- [eduler_Worker-3] rundeck.services.ExecutionUtilService    : Execution failed: 136318 in project PS: [Workflow result: , step failures: {1=Unknown: Exception while executing step [1]: 	[java.lang.RuntimeException: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection]}, status: failed]`

`2019-01-16 12:33:14.964  WARN --- [-11021-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null`

`2019-01-16 12:33:14.964 ERROR --- [-11021-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Connection has already been closed.`

`2019-01-16 12:33:14.966 ERROR --- [-11021-thread-1] o.s.t.support.TransactionTemplate        : Application exception overridden by rollback exception
org.hibernate.exception.GenericJDBCException: could not prepare statement
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Connection has already been closed.
	... 131 common frames omitted
`

`2019-01-16 12:33:14.969 ERROR --- [eduler_Worker-2] rundeck.services.ExecutionUtilService    : Execution failed: 136631 in project PS: [Workflow result: , step failures: {1=Unknown: Exception while executing step [1]: 	[java.lang.RuntimeException: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection]}, status: failed]`

**Comment by jtobard** [comment]
@avinchakov this is not the same problem of deadlocks, but do you change the properties mentioned on the changelog of the release?

**Comment by lancepowell** [comment]
@avinchakov if you have removeabandoned turned on, that can cause those errors.

`
dataSource.properties.removeAbandoned=true
`

**Comment by avinchakov** [comment]
@jtobard Yes, I added:
```
dataSource.properties.removeAbandoned=true
dataSource.properties.removeAbandonedTimeout=240
dataSource.properties.testOnBorrow=true
dataSource.properties.maxActive=200
```
@lancepowell Thank you, I will try.
