### ISSUE TITLE
mail notification does not work with rundeck.war

### ISSUE THREAD

**Issue by macgaveck** [rundeck/rundeck#4256]
**Describe the bug**
When use rundeck 3.0x war archive on a tomcat8, openjdk 8 environment, the mail notification does not work.

**My Rundeck detail**

* Rundeck version: [ 3.0.8 ]
* install type: [war]
* OS Name/version: [archlinux]
* DB Type/version: [grailsdb]
* Environment: openjdk8/tomcat8

**To Reproduce**
1. Create simple job whith a "mail notification on success" option
2. Execute the job
3. See error on the catalina.out:
Error sending notification email to address@mail.com for Execution 65393: com.sun.mail.util.TraceInputStream.<i
nit>(Ljava/io/InputStream;Lcom/sun/mail/util/MailLogger;)V

**Expected behavior**
No error and the email is sent

**Desktop (please complete the following information):**
 - OS: [archlinux]
 - Browser [any]
 - Version [any]

**Additional context**
I tried with all loglevels, I was not able to get any stack trace until I add the mail notification plugin(https://github.com/rundeck/rundeck/blob/master/examples/example-groovy-notification-plugins/MailNotificationPlugin.groovy).
When this plugin is on, and that your grails smtp settings are set to use localhost smtp server, you got this stack trace:
java.lang.NoSuchMethodError: com.sun.mail.util.TraceInputStream.<init>(Ljava/io/InputStream;Lcom/sun/mail/util/MailLogger;)V
        at com.sun.mail.smtp.SMTPTransport.initStreams(SMTPTransport.java:2174)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2093)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
        at javax.mail.Service.connect(Service.java:291)
...

The "NoSuchMethodError" let me think that there is a problem with kind of smtp library, checking on my system I found that there are mail libs from rundeck (javax.mail-api-1.5.6.jar, mail-9435b0ac77.jar, javax.mail-1.5.6.jar) but no smtp*.jar.
Thus, I supppose that the smtp from openjdk is used and does not work for any reason.

The workaround here is to download the smtp-1.5.6.jar, to put it on the rundeck/WEB-INF/lib dir and to restart tomcat8.

Shouldn't this library be added to the rundeck war archive to avoid this ?

**Comment by macgaveck** [comment]
Confirmed. Removing the extra mailapi-1.4.3.jar solves the problem.
Thank you.
