### ISSUE TITLE
RD3 Manifest file: /tour-manifest.json does not exist

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#4278]
**Describe the bug**
Something new with the 3.0.9 version , only visible in the service / systemd unit logs and the var/log/{syslog , message} file (depending of the configuration) :

````
2018-12-02 18:21:04.365 ERROR --- [qtp859765585-34] c.rundeck.plugin.localtours.LocalTours   : Manifest file: /tour-manifest.json does not exist
2018-12-02 18:21:04.406 ERROR --- [qtp859765585-34] StackTrace                               : Full Stack Trace:

java.lang.RuntimeException: Manifest file: /tour-manifest.json does not exist
        at com.rundeck.plugin.localtours.LocalTours.getTourManifest(LocalTours.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
	(...)

2018-12-02 18:21:04.459 ERROR --- [qtp859765585-34] o.g.web.errors.GrailsExceptionResolver   : RuntimeException occurred when processing request: [GET] /tour/listAll
Manifest file: /tour-manifest.json does not exist. Stacktrace follows:

java.lang.RuntimeException: Manifest file: /tour-manifest.json does not exist
        at com.rundeck.plugin.localtours.LocalTours.getTourManifest(LocalTours.java:46)
        at rundeck.services.TourLoaderService$_listAllTourManifests_closure1.doCall(TourLoaderService.groovy:22)
        at rundeck.services.TourLoaderService.listAllTourManifests(TourLoaderService.groovy:19)
        at rundeck.controllers.TourController.listAllTourManifests(TourController.groovy:12)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	(...)
````
This happens when a user is logged in, each time a panel is opened.

Even if doesn't seems to have any real effect, the problem is this will happen for each user, thus generating a hefty amount of logs.

**My Rundeck detail**

* Rundeck version: 3.0.9
* install type: deb
* OS Name/version: Ubuntu 18.04
* DB Type/version: H2 db file

**To Reproduce**
1. Install v3.0.9
2. log into Rundeck
3. open any panel
4. switch to another panel
5. check the service/unit log and/or the syslog or message file under /var/log/

**Comment by sjrd218** [comment]
@Daryes Thanks for reporting this bug. To work around it for now please delete the rundeck-local-tours-plugin-3.0.9-20181127.jar from your libext directory and restart.

**Comment by fareschelloug** [comment]
i have exactly the same problème on 

    Rundeck version: 3.0.9
    install type: deb
    OS Name/version: debian 8.11
    DB Type/version: mysql5.7

2018-12-04 12:04:00.780 ERROR --- [tp1526894424-25] c.rundeck.plugin.localtours.LocalTours   : Manifest file: /tour-manifest.json does not exist                                                                                             2018-12-04 12:04:00.780 ERROR --- [tp1526894424-25] StackTrace                               : Full Stack Trace:                                                                                                                                                                                                                                                                                                                                                                          java.lang.RuntimeException: Manifest file: /tour-manifest.json does not exist                                                                                                                                                                        at com.rundeck.plugin.localtours.LocalTours.getTourManifest(LocalTours.java:46)                                                                                                                                                              at sun.reflect.GeneratedMethodAccessor1160.invoke(Unknown Source)                                                                                                                                                                            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                                     at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                                                                          at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)                                                                                                                                                                  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)                                                                                                                                                                                at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)                                                                                                                at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)                                                                                                                       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)                                                                                                                                          at rundeck.services.TourLoaderService$_listAllTourManifests_closure1.doCall(TourLoaderService.groovy:22)                                                                                                                                     at sun.reflect.GeneratedMethodAccessor1152.invoke(Unknown Source)                                                                                                                                                                            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                                     at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                                                                          at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)                                                                                                                                                                  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)                                                                                                                                                                                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)                                                                                                                                            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)                                                                                                                                                                           at groovy.lang.Closure.call(Closure.java:418)                                                                                                                                                                                                at groovy.lang.Closure.call(Closure.java:434)                                                                                                                                                                                                at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5363)                                                                                                                                   at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2202)                                                                                                                                                     at org.codehaus.groovy.runtime.dgm$164.invoke(Unknown Source)                                                                                                                                                                                at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)                                                                                                            at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)                                                                                                                                                  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)                                                                                                                                                     at rundeck.services.TourLoaderService.listAllTourManifests(TourLoaderService.groovy:19)                                                                                                                                                      at rundeck.services.TourLoaderService$listAllTourManifests.call(Unknown Source)                                                                                                                                                              at rundeck.controllers.TourController.listAllTourManifests(TourController.groovy:12)                                                                                                                                                         at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)                                                                                                                            at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)                                                                                                                                                at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)                                                                                                                                  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)                                                                                                                                                  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)                                                                                                                                                   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)                                                                                                                                                at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)                                                                                                                                                         at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)                                                                                                                                                                              at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)                                                                                                                                                       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)                                                                                                                                                                              at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)                                                                                                                                                                    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)                                                                                                                                                   at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)                                                                                                                                       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)                                                                                                                                 at java.security.AccessController.doPrivileged(Native Method)                                                                                                                                                                                at javax.security.auth.Subject.doAs(Subject.java:422)                                                                                                                                                                                        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)                                                                                                                             at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)                                                                                                               at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)                                                                                                                                               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)                                                                                                                             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)                                                                                                                                               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)                                                                                                                                  at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)                                                                                                                    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)                                                                                                                   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)                                                                                                                          at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)                                                                            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)                                                                                                       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)                                                                                               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)                                                                                            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)                                                                                                                                 at java.security.AccessController.doPrivileged(Native Method)                                                                                                                                                                                at javax.security.auth.Subject.doAs(Subject.java:422)                                                                                                                                                                                        at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)                                                                                                                             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)                                                                                          at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)                                                                                                                        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)                                                                                                             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)                                                                                                                              at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)                                                                                                                                  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)                                                                                                                                             at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)                                                                                                                                                     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)                                                                                                                                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)                                                                                                                                               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)                                                                                                                                            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)                                                                                                                                               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)                                                                                                                                 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)                                                                                                                                               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)                                                                                                                                                            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)                                                                                                                                               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)                                                                                                                                     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)                                                                                                                                               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)                                                                                                                                                   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)                                                                                                                                                                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)                                                                                                                                                             at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)                                                                                                                                                               at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)                                                                                                                                                           at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)                                                                                                                                                         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)                                                                                                                                                        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)                                                                                                                                                         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)                                                                                                                                                        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)                                                                                                                                                          at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)                                                                                                                                                                 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)                                                                                                                                                         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)                                                                                                                                                          at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)                                                                                                                                                         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)                                                                                                                                                             at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)                                                                                                                                                           at org.eclipse.jetty.server.Server.handle(Server.java:531)                                                                                                                                                                                   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)                                                                                                                                                                         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)                                                                                                                                                               at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)                                                                                                                                               at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)                                                                                                                                                                         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)                                                                                                                                                                      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)                                                                                                                                                    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)                                                                                                                                                  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)                                                                                                                                                 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)                                                                                                                                                        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)                                                                                                                                  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)                                                                                                                                                          at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)                                                                                                                                                           at java.lang.Thread.run(Thread.java:748)

**Comment by Daryes** [comment]
> 
> @Daryes Thanks for reporting this bug. To work around it for now please delete the rundeck-local-tours-plugin-3.0.9-20181127.jar from your libext directory and restart.

Thanks for the tip. The restart is mandatory, but at least the error stopped being returned and logged endlessly.

**Comment by fareschelloug** [comment]
ok Thx
