### ISSUE TITLE
Semi-regular JGitInternalException LockFailedException from /api/21/project/<project>/jobs endpoint

### ISSUE THREAD

**Issue by SpencerMalone** [rundeck/rundeck#4281]
**Describe the bug**
We have a slack bot service that regularly populates it's model of what our rundeck jobs look like through the API. That service regularly (~20-50 times per day? It doesn't sync that often though, this code path is on a spaced out cron) gets thrown 500s from rundeck when getting a project overview through the API (`/api/21/project/<project-name>/jobs`). When digging through the logs, the error was correlated with the following: https://gist.github.com/SpencerMalone/b21f649c5275650535292d6844bb84df

Summarized, that is...
```
org.eclipse.jgit.api.errors.JGitInternalException: Cannot lock /var/rundeck/projects/<redacted>/scm/.git/index
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:316)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:126)
	at org.rundeck.plugin.scm.git.GitExportPlugin$_clusterFixJobs_closure2.doCall(GitExportPlugin.groovy:529)
	at org.rundeck.plugin.scm.git.GitExportPlugin.clusterFixJobs(GitExportPlugin.groovy:519)
	at rundeck.services.ScmService.fixExportStatus(ScmService.groovy:1332)
	at rundeck.services.ScmService.exportStatusForJobs(ScmService.groovy:1069)
```

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.7-20181008
* install type: rpm, clustered setup behind nginx LB
* OS Name/version: Centos 7.3
* DB Type/version: mysql

**To Reproduce**
Not sure yet? I assume when two users (or services) are interacting with the SCM at the same time?

**Expected behavior**
A 200 should return with project info. It seems like `exportStatusForJobs` is trying to "fix" the export status, but I don't entirely understand the purpose of that, or if we can try/catch that failure?

**Additional context**
I'll be poking at this further to try and figure out what's up

**Comment by SpencerMalone** [comment]
So, that's the code for syncing between clustered instances. What would y'all think about try/catching around `fixExportStatus` in `exportStatusForJobs`?
