### ISSUE TITLE
3.0.9 Error [eduler_Worker-1] rundeck.services.ExecutionService - NoSuchElementException: null

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#4286]
**Describe the bug**
Appeared with 3.0.9, seems there's a problem due to a migration or something else, as I have some jobs launched by the scheduler who will immediately exit with the following error : 
`Failed to start execution: java.util.NoSuchElementException: null`

I've changed the title for #4277 which was opened for the UI cryptic message, but the error itself, after more analysis, was related to this bug, and not a targeted node unavailable due to a downtime (which occurred one hour before)

Java logs are at the end.
There's something troubling as it seems the Scheduler_Worker name is missing the 3 first letters in the error.
The only log in the job execution is the java null error, without any other information.

**My Rundeck detail**

* Rundeck version: 3.0.9
* install type: deb
* OS Name/version: Ubuntu 18.04
* DB Type/version: H2 DB file

**To Reproduce**
No idea how.
I have ~20 jobs running daily through the scheduler, for now in 3 days, only those targeting the Rundeck node had this error since the upgrade (ex : a job with a script for a local backup for Rundeck)
It seems to always occurs for the first job (or 1st and 2nd) launched by the scheduler when the target node is the Rundeck server itself, and only after a Rundeck restart. I will be able to check this tomorrow evening for thursday morning.

**Expected behavior**
shouldn't happen

**Additional context**
````
2018-12-04 06:00:03.851 ERROR --- [eduler_Worker-1] rundeck.services.ExecutionService        : Failed while starting execution: 5412

java.util.NoSuchElementException: null
        at sun.misc.CompoundEnumeration.nextElement(CompoundEnumeration.java:59)
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at com.dtolabs.rundeck.plugins.ServiceTypes.getPluginProviderService(ServiceTypes.java:128)
        at com.dtolabs.rundeck.core.plugins.PluginManagerService.createPluginService(PluginManagerService.java:70)
        at com.dtolabs.rundeck.core.plugins.ServiceProviderLoader$createPluginService.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at com.dtolabs.rundeck.server.plugins.RundeckPluginRegistry.createPluggableService(RundeckPluginRegistry.groovy:99)
        at com.dtolabs.rundeck.core.plugins.PluginRegistry$createPluggableService.call(Unknown Source)
        at rundeck.services.ExecutionService.$tt__executeAsyncBegin(ExecutionService.groovy:994)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
````

````
2018-12-04 06:00:03.852 ERROR --- [eduler_Worker-8] rundeck.services.ExecutionService        : Failed while starting execution: 5419

java.util.NoSuchElementException: null
        at sun.misc.CompoundEnumeration.nextElement(CompoundEnumeration.java:59)
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at com.dtolabs.rundeck.plugins.ServiceTypes.getPluginProviderService(ServiceTypes.java:128)
        at com.dtolabs.rundeck.core.plugins.PluginManagerService.createPluginService(PluginManagerService.java:70)
        at com.dtolabs.rundeck.core.plugins.ServiceProviderLoader$createPluginService.call(Unknown Source)
        at com.dtolabs.rundeck.server.plugins.RundeckPluginRegistry.createPluggableService(RundeckPluginRegistry.groovy:99)
        at com.dtolabs.rundeck.core.plugins.PluginRegistry$createPluggableService.call(Unknown Source)
        at rundeck.services.ExecutionService.$tt__executeAsyncBegin(ExecutionService.groovy:994)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
````

**Comment by reinerrdeck** [comment]
Only to confirm, which java version do you have?

java -version

**Comment by mcgurksean** [comment]
I am getting the same error on version 3.0.19-20190327

**Comment by Daryes** [comment]
Happened again today after updating rundeck yesterday.
Full log at the end.

As I had some jobs running after the update, it appears while the  error is at random, it only occurs for executions scheduled the next day after Rundeck is updated. There's no problem for jobs scheduled the same day the update was done.
 
```
2019-07-13 06:00:05.195 ERROR --- [eduler_Worker-8] rundeck.services.ExecutionService        : Failed while starting execution: 9467

java.util.NoSuchElementException: null
        at sun.misc.CompoundEnumeration.nextElement(CompoundEnumeration.java:59)
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at com.dtolabs.rundeck.plugins.ServiceTypes.getPluginProviderService(ServiceTypes.java:137)
        at com.dtolabs.rundeck.core.plugins.PluginManagerService.createPluginService(PluginManagerService.java:70)
        at com.dtolabs.rundeck.core.plugins.ServiceProviderLoader$createPluginService.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at com.dtolabs.rundeck.server.plugins.RundeckPluginRegistry.createPluggableService(RundeckPluginRegistry.groovy:114)
        at com.dtolabs.rundeck.core.plugins.PluginRegistry$createPluggableService.call(Unknown Source)
        at rundeck.services.ExecutionService.$tt__executeAsyncBegin(ExecutionService.groovy:998)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
        at rundeck.services.ExecutionService$_executeAsyncBegin_closure20.doCall(ExecutionService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy)
        at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy)
        at rundeck.services.ExecutionService$executeAsyncBegin$43.call(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:354)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:96)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:126)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:95)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```
