### ISSUE TITLE
Slack Notification Plugin not working behing a Proxy

### ISSUE THREAD

**Issue by jsantama** [rundeck/rundeck#4380]
**Describe the bug**
When trying to configure the Slack Notification Plugin, behind a proxy server without authentication, the plugin cannot communicate with the Slack platform so the notification won't arrive.
As a test, another Rundeck instance was created from a different network, without a Proxy and used the same configuration for the Webhook and the notifications arrived normally.

**My Rundeck detail**

* Rundeck version: 2.3.4
* install type: RPM
* OS Name/version: Linux CentOS 6.9
* Proxy: Squid

**To Reproduce**
1. Set a Squid proxy on the same machine of Rundeck. Configure it to handle the traffic to the Internet
2. Select Slack Notification on any job, and configure it using the webhook provided by Slack 
3. Configure the parameters for the proxy on /etc/sysconfig/rundeckd: export RDECK_JVM="$RDECK_JVM -Dhttp.proxyHost=proxy-va -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=localhost
4. Restart Rundeck service
5. This is the error that appears on service.log when Rundeck is trying to send the notification:
`ERROR ExecutionUtilService: Execution failed: 38221 in project Install_Anything: [Workflow result: , step failures: {7=Interrupted: Cancellation while running step [7]}, flow control: Continue, status: failed]
ERROR NotificationService: Error sending notification: Notification{eventTrigger='onfailure', type='SlackNotification', content='{"webhook_token":"T08T0TEJZ/BDY9KGZ38/pLz9xbjvZnCPsfDOSj06FAVg","webhook_base_url":"https://hooks.slack.com/services"}'}: class com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data to Slack URL: [Connection refused (Connection refused)].
com.bitplaces.rundeck.plugins.slack.SlackNotificationPluginException: Error putting data to Slack URL: [Connection refused (Connection refused)].
at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.putRequestStream(SlackNotificationPlugin.java:203)
at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.invokeSlackAPIMethod(SlackNotificationPlugin.java:163)
at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.postNotification(SlackNotificationPlugin.java:109)
at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:525)
at rundeck.services.NotificationService$_triggerJobNotification_closure9.doCall(NotificationService.groovy:387)
at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:175)
at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:117)
at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:114)
at rundeck.services.ExecutionService$_saveExecutionState_closure64.doCall(ExecutionService.groovy:2610)
at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2511)
at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:548)
at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:487)
at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:558)
at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:166)
at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:93)
at com.codahale.metrics.Timer.time(Timer.java:99)
at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:92)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at com.bitplaces.rundeck.plugins.slack.SlackNotificationPlugin.putRequestStream(SlackNotificationPlugin.java:198)`

**Expected behavior**
A notification sent to Slack, on the desired channel

**Comment by jessemarple** [comment]
This issue might be resolved by upgrading to the latest version of Rundeck. Rundeck 2.3.4 is a very old version. If the issue persists please post the issue in the particular plugin repo.
