### ISSUE TITLE
Can't delete certain jobs

### ISSUE THREAD

**Issue by pbenas** [rundeck/rundeck#4650]
**Describe the bug**
Noticed this while cleaning up some obsolete projects. Some projects can't be deleted with `update or delete on table "scheduled_execution" violates foreign key constraint ID on table "scheduled_execution_stats"`

**My Rundeck detail**

* Rundeck version: 2.11.8-1 
* install type: war, tomcat 7
* OS Name/version: CentOS 7.5
* DB Type/version: postgres

**To Reproduce**
Attempt to delete all jobs or whole project.

```
ERROR: update or delete on table "scheduled_execution" violates foreign key constraint "fkpwc0snw00ehserhlpgftbu8aw" on table "scheduled_execution_stats" Detail: Key (id)=(1215229) is still referenced from table "scheduled_execution_stats".
```
**Expected behavior**
Whole project is deleted with all references to it. 

**Additional context**
```
org.postgresql.util.PSQLException: ERROR: update or delete on table "scheduled_execution" violates foreign key constraint "fkpwc0snw00ehserhlpgftbu8aw" on table "scheduled_execution_stats"
  Detail: Key (id)=(1215229) is still referenced from table "scheduled_execution_stats".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at rundeck.services.ScheduledExecutionService$_deleteScheduledExecution_closure24.doCall(ScheduledExecutionService.groovy:921)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
	at rundeck.services.ScheduledExecutionService.deleteScheduledExecution(ScheduledExecutionService.groovy:888)
	at rundeck.services.ScheduledExecutionService.deleteScheduledExecutionById(ScheduledExecutionService.groovy:989)
	at rundeck.controllers.ScheduledExecutionController$_deleteBulk_closure46$_closure173.doCall(ScheduledExecutionController.groovy:1568)
	at rundeck.controllers.ScheduledExecutionController$_deleteBulk_closure46.doCall(ScheduledExecutionController.groovy:1566)
	at org.grails.plugins.web.rest.api.ControllersRestApi.withForm(ControllersRestApi.groovy:53)
	at rundeck.controllers.ScheduledExecutionController.deleteBulk(ScheduledExecutionController.groovy:1556)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:113)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ProTip** [comment]
Hi @pbenas ,

The scheduled execution stats table is a new edition in Rundeck `3.0.x` that doesn't appear back-ported to `2.11.x`. Are you certain you are on `2.11.8-1`, and if so is it possible you have a database that was partially upgraded by a `3.0.x` Rundeck instance?

Thanks!

**Comment by pbenas** [comment]
Hi @ProTip, 

yes, it seems to be the case. This instance was upgraded to Rundeck 3, but due to UI performance issues was downgraded back to Rundeck 2. Thought the instance was redeployed, but after the inspection of the logs it turned out it was not. 

Thanks for the investigation!

**Comment by jtobard** [comment]
@pbenas do you mind to share those UI performance issues? Or maybe you could make a new issue so we can deal with that.

**Comment by pbenas** [comment]
These were already reported by my fellow. 
https://github.com/rundeck/rundeck/issues/4616
https://github.com/rundeck/rundeck/issues/4617
