### ISSUE TITLE
Unable to delete Rundeck job due to Foreign Key constraint - Rundeck 2.11.7-1

### ISSUE THREAD

**Issue by sblaufuss** [rundeck/rundeck#4676]
**Describe the bug**
I am unable to delete a job due to a foreign key constraint.

**My Rundeck detail**

* Rundeck version: 2.11.7-1
* install type: RPM
* OS Name/version: CentOS 6.10
* DB Type/version: MySQL 5.7.20

**To Reproduce**
1.  Select a Project
2. Select the job from the job list
3. From the Job Actions drop-down arrow, select "Delete Job"
4. Confirm job deletion
5. See Error

NOTE: This same error occurs when deleting the job directly from the /job/show page as well. Our rundeck server has been upgraded twice (that I know of), the first time from version 2.6.6-18 to 2.10.8-1.50, and then again from 1.10.8-1.50 to 2.11.7-1

**Expected behavior**
The job should be deleted with speed and authority.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6 (17G5019)
 - Browser Chrome
 - Version 73.0.3683.86, 64-bit

**Additional context**
Error details and stack trace:

Request: /scheduledExecution/delete/97f81fb9-6aa7-4573-b779-3e521930809d?SYNCHRONIZER_URI=%2Fproject%2FKearney%2Fjob%2Fshow%2F97f81fb9-6aa7-4573-b779-3e521930809d&deleteExecutions=true&SYNCHRONIZER_TOKEN=8718be4c91e639384e19cde6095845675c8fbd018ac8a4cbe1e7502e3f55f60b
Message: Cannot delete or update a parent row: a foreign key constraint fails (`rundeck2`.`rdoption`, CONSTRAINT `FK_jraxrdpul0ne9eediy1xjlsfv` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`)) 
Caused by: Cannot delete or update a parent row: a foreign key constraint fails (`rundeck2`.`rdoption`, CONSTRAINT `FK_jraxrdpul0ne9eediy1xjlsfv` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`)) 
Class: ScheduledExecutionController 
At Line: [1415] 
Code Snippet:
Stack Trace
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`rundeck2`.`rdoption`, CONSTRAINT `FK_jraxrdpul0ne9eediy1xjlsfv` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`))
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at rundeck.services.ScheduledExecutionService$_deleteScheduledExecution_closure24.doCall(ScheduledExecutionService.groovy:921)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
	at rundeck.services.ScheduledExecutionService.deleteScheduledExecution(ScheduledExecutionService.groovy:888)
	at rundeck.services.ScheduledExecutionService.deleteScheduledExecutionById(ScheduledExecutionService.groovy:989)
	at rundeck.controllers.ScheduledExecutionController$_delete_closure41.doCall(ScheduledExecutionController.groovy:1419)
	at org.grails.plugins.web.rest.api.ControllersRestApi.withForm(ControllersRestApi.groovy:53)
	at rundeck.controllers.ScheduledExecutionController.delete(ScheduledExecutionController.groovy:1415)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:529)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)

**Comment by reinerrdeck** [comment]
Hi,

Your issue is very similar to this: https://github.com/rundeck/rundeck/issues/3360

At that time a fix solved the problem (under 2.11.X), that which suggests that it rarely occurs in branch 2.11.X.

So the main advice is to upgrade your instance to last Rundeck version to solve this. Here you have a good starting point:

https://docs.rundeck.com/docs/upgrading/upgrade-to-rundeck-3.x.html

Remember backup all your data and test the upgrade in a safe environment before proceeding at the production environment.

Regards.
