### ISSUE TITLE
Page rendering error for missing plugin

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#4786]
**Describe the bug**
A plugin without a description field causes a page render error.

**My Rundeck detail**

* Rundeck version: 3.1.0-snapshot
* install type: launcher
* OS Name/version: MacOs
* DB Type/version: H2

**To Reproduce**
1. Deploy a plugin that does not have a description property.
2. Click on job view page that uses that step plugin
3. See error

**Expected behavior**
The page rendering should tolerate plugins that do not have a description property.

**Screenshots**

![image](https://user-images.githubusercontent.com/275924/57181764-c3058700-6e4c-11e9-9c25-85722aad4846.png)

The following is written to the service.log
```
Caused by: org.grails.taglib.GrailsTagException: [views/execution/_wfItemView.gsp:77] Error executing tag <stepplugin:display>: Cannot get property 'description' on null object
	at org.grails.gsp.GroovyPage.throwRootCause(GroovyPage.java:473)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:415)
	at gsp_rundeck_execution_wfItemView_gsp.run(gsp_rundeck_execution_wfItemView_gsp.groovy:129)
	at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
	at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
	at org.grails.web.gsp.GroovyPagesTemplateRenderer.makeTemplate(GroovyPagesTemplateRenderer.java:232)
	at org.grails.web.gsp.GroovyPagesTemplateRenderer.render(GroovyPagesTemplateRenderer.java:113)
	at org.grails.plugins.web.taglib.RenderTagLib$_closure7.doCall(RenderTagLib.groovy:367)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
	... 139 common frames omitted
Caused by: java.lang.NullPointerException: Cannot get property 'description' on null object
	at rundeck.services.FrameworkService.getStepPluginDescription(FrameworkService.groovy:744)
	at rundeck.services.FrameworkService.getPluginDescriptionForItem(FrameworkService.groovy:720)
	at rundeck.PluginTagLib$_closure1.doCall(PluginTagLib.groovy:32)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:446)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:364)
	... 147 common frames omitted
```
**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Firefox
 - Version: newest

**Comment by gschueler** [comment]
This occurs if a workflow is defined using a step plugin that is no longer installed
