### ISSUE TITLE
Timed tasks can sometimes not be executed

### ISSUE THREAD

**Issue by 397334469** [rundeck/rundeck#4987]
The same task has 10 tasks scheduled at the same time, and 2 tasks cannot be run.

-------------------

2019-06-22 05:30:00.105 ERROR --- [eduler_Worker-3] rundeck.quartzjobs.ExecutionJob          : Execution 1560 failed to start: Unable to create directories for storage: /var/lib/rundeck/logs/rundeck/open_falcon_info/job/991db7d3-a45b-4dde-9ed0-2bb0eedca751/logs/1560.rdlog

java.lang.IllegalStateException: Unable to create directories for storage: /var/lib/rundeck/logs/rundeck/open_falcon_info/job/991db7d3-a45b-4dde-9ed0-2bb0eedca751/logs/1560.rdlog
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at rundeck.services.LogFileStorageService.getLogFileWriterForExecution(LogFileStorageService.groovy:490)
	at rundeck.services.LogFileStorageService$getLogFileWriterForExecution$10.call(Unknown Source)
	at rundeck.services.LoggingService.openLogWriter(LoggingService.groovy:160)
	at rundeck.services.LoggingService$openLogWriter$1.call(Unknown Source)
	at rundeck.services.ExecutionService.$tt__executeAsyncBegin(ExecutionService.groovy:974)
	at sun.reflect.GeneratedMethodAccessor2243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
	at rundeck.services.ExecutionService$_executeAsyncBegin_closure20.doCall(ExecutionService.groovy)
	at sun.reflect.GeneratedMethodAccessor2414.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy)
	at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy)
	at rundeck.services.ExecutionService$executeAsyncBegin$27.call(Unknown Source)
	at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:354)
	at sun.reflect.GeneratedMethodAccessor2242.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:148)
	at sun.reflect.GeneratedMethodAccessor2240.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:96)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy)
	at sun.reflect.GeneratedMethodAccessor2411.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:95)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by MegaDrive68k** [comment]
Hi @397334469 

Can you explain more the issue?: Rundeck version, Java version, the steps to reproduce the issue, an explanation about the issue.

Thanks!

Regards!

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
