### ISSUE TITLE
added new user with Jetty utility but rundeck service is going down after restarting

### ISSUE THREAD

**Issue by OmPrasadReddy** [rundeck/rundeck#5073]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: 3.0.9
* install type: war
* OS Name/version: Red Hat Enterprise Linux Server release 6.10 (Santiago)
* DB Type/version: mssql

**To Reproduce**
1) stop the runeck with sh rundeckd stop
2) Generate pwd with java -jar rundeck-3.0.9-20181127.war --encryptpwd Jetty
3. add user in realm.properties file
support: MD5:d2984b749105aa8f9a2a10b6fca9567e,user,admin
4.  start with sh rundeckd start

**Expected behavior**
rundeck service should come up

**Screenshots**
I have added new user and encrypted password with Jetty utility but rundeck service is going down after restarting. I saw below exception. Has anyone seen this?

2019-07-19 04:43:04.925  WARN --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh
 attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NullPointerException
2019-07-19 04:43:04.973 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NullPointerException
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at rundeckapp.Application.main(Application.groovy:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.NullPointerException: null
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:201)
        at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory$Jetty93SessionConfigurer.getSessionManager(JettyEmbeddedServletContainerFactory.java:1030)
        at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory$Jetty93SessionConfigurer.configure(JettyEmbeddedServletContainerFactory.java:1015)
at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.configureSession(JettyEmbeddedServletContainerFactory.java:378)
        at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.configureWebAppContext(JettyEmbeddedServletContainerFactory.java:372)
        at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:175)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
        ... 21 common frames omitted

Thanks!!!

**Comment by MegaDrive68k** [comment]
Hi!

which Java JDK version do you have? check this with:

`java -version`

Rundeck needs JDK 8 (1.8) to works properly:

https://docs.rundeck.com/docs/administration/install/system-requirements.html#java

Greetings!

**Comment by OmPrasadReddy** [comment]
Thanks  for your reply. It's using JDK 1.8 and I have seen posted exception when i start the rundeck service. I have removed users (all) in realm.properties and started but still it's going down. How to fix it this issue?
 java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by MegaDrive68k** [comment]
Solved on Google Groups:

https://groups.google.com/forum/#!topic/rundeck-discuss/hn-d7ZXq4Gg

Possible encode error on file. Re-open if happens again.
