### ISSUE TITLE
No matched nodes when executing a job locally

### ISSUE THREAD

**Issue by optplx** [rundeck/rundeck#5336]
**Describe the bug**
When launching a job manually from the console, that should execute locally, I get the below error (debug mode). I don't see more in the logs.
```
[workflow] Begin execution: node-first
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:369)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:222)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:83)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:74)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}
[workflow] Finish execution:  node-first: [Workflow result: , exception: com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}, flow control: Continue, status: failed]
No matched nodes: NodeSet{}
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:369)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:222)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:83)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:74)
``` 

**My Rundeck detail**

* Rundeck version: Rundeck 3.1.0-20190731
* install type: deb
* OS Name/version: Debian 4.9.82-1+deb9u2 x86_64
* DB Type/version: mysql 5.7

**To Reproduce**
1. Create a job in previous version of Rundeck, which executes locally a script hosted on the Rundeck machine
2. upgrade Rundeck to 3.1.0
3. the script doesn't work anymore

**Expected behavior**
The scripts did work with the previous version of Rundeck, but doesn't work anymore after upgrading. We did the upgrade from the very previous version, not an old one.

**Desktop (please complete the following information):**
Is not client dependent

**Additional context**
Note: we push our Rundeck jobs using Terraform. After editing a job manually and re-triggering a Terraform apply, the job works.

In the DB we see that the broken jobs have the following differences versus an updated and working job (table rundeck.scheduled_execution):

| column                   | failing job | updated job |
|--------------------------|-------------|-------------|
| node_threadcount         | 5           | 1           |
| node_selected_by_default | 0           | 1           |
| default_tab              | NULL        | nodes       |
| node_threadcount_dynamic | NULL        | 1           |
| exclude_filter_uncheck   | NULL        | 0           |

I found out that changing node_selected_by_default from 0 to 1 is enough to fix the issue. This is an acceptable workaround for us but it would be good to understand the root cause of it.

Thanks for your help!

**Comment by MegaDrive68k** [comment]
Hi @optplx 

Just to check and get the right scenario: Which Rundeck version did you using before the upgrade? You can describe how did you upgrade Rundeck in your server?

Kind regards!

**Comment by carlgevans** [comment]
We are seeing this on most jobs as well since upgrading to v3.2.1-20200113.

`Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}
No matched nodes: NodeSet{}`

We can bodge it by changing all of the jobs to a specific node filter for the local server rather than 'Execute Locally'.

Is there an easier workaround instead of changing all jobs?

**Comment by optplx** [comment]
@carlgevans fyi here is what I did (edited the DB directly)

`select * from scheduled_execution where nodes_selected_by_default=0 and group_path like '%YOUR_JOB_NAMES%' order by group_path;`

`update scheduled_execution set nodes_selected_by_default=1 where nodes_selected_by_default=0 and group_path like '%YOUR_JOB_NAMES%';`

hope that help

**Comment by mthemis-provenir** [comment]
For anyone looking for this in 2025, this bug still exists. As @carlgevans mentions, duplicating the job and deleting the original one works. Not sure why it's closed.
