### ISSUE TITLE
Unable to use multiple LDAP servers

### ISSUE THREAD

**Issue by jdmulloy** [rundeck/rundeck#541]
I'm attempting to configure Rundeck to use two LDAP/AD servers for redundancy in case one goes down following the documentation here: http://rundeck.org/docs/administration/authentication.html#redundant-connection-options. When I attempt to configure two LDAPS servers logins don't work and I get the following in /var/log/rundeck/service.log.

> 2013-09-12 15:16:49.973::WARN:  java.lang.SecurityException: Configuration >Error:
>        Line 4: expected [option key], found [null]
> 2013-09-12 15:16:49.974::WARN:  AUTH FAILURE: user jmulloy

I've tried using quotes and no quotes in providerUrl and using spaces, comas and semicolons to separate the URLs. Looking at the code in rundeck/rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java it doesn't look like there is any code to handle multiple LDAP servers, unless jaas is supposed to do it.

This is the anonymized contents of my jaas-loginmodule.conf file. It works fine with just one LDAPS server.

> multiauth {
>    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
>        debug="true"
>        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
>        providerUrl=ldaps://ldap01.corp.company.com ldaps://ldap02.corp.company.com
>        bindDn="CN=LdapServiceAccount,OU=Service Accounts,OU=company,OU=Secondary Accounts,DC=corp,DC=company,DC=com"
>        bindPassword="SecretPassword"
>        authenticationMethod="simple"
>        forceBindingLogin="true"
>        userBaseDn="OU=Delegated Admins,DC=corp,DC=company,DC=com"
>        userRdnAttribute="cn"
>        userIdAttribute="sAMAccountName"
>        userPasswordAttribute="unicodePwd"
>        userObjectClass="user"
>        roleBaseDn="ou=groups,dc=corp,dc=company,dc=com"
>        roleNameAttribute="cn"
>        roleMemberAttribute="member"
>        roleObjectClass="group"
>        cacheDurationMillis="300000"
>        reportStatistics="true";
> 
>    org.mortbay.jetty.plus.jaas.spi.PropertyFileLoginModule required
>        debug="true"
>        file="/etc/rundeck/realm.properties";
> };

**Comment by richiereynolds** [comment]
Hi, got a question then, is there any way to support multiple AD servers for login? E.g. users in each region have their own providerUrl but all want to use the same RD server.

**Comment by gschueler** [comment]
@richiereynolds you could try the space-separated URLs, or try multiple login module declarations

**Comment by camAtGitHub** [comment]
Hello! 
With some basic testing I can see that multiple LDAP servers are supported how ever multiple LDAPS servers are not.

Eg
```
providerUrl="ldap://ldap1.foobar.com ldap://ldap2.foobar.com"
```
Works fine and fails over if a server disappears

However:
```
providerUrl="ldaps://ldap1.foobar.com ldaps://ldap2.foobar.com"
```
Fails when someone tries to login with the stacktrace:
```
==> service.log <==
2017-09-01 05:21:16.312:WARN:oejj.JAASLoginService:qtp1989780873-12: 
javax.security.auth.login.LoginException: java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in authority at index 8: ldaps://ldap1.foobar.com ldaps://ldap2.foobar.com|?at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getEnvironment(JettyCachingLdapLoginModule.java:967)|?at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.initialize(JettyCachingLdapLoginModule.java:813)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:498)|?at javax.security.auth.login.LoginContext.invoke(LoginContext.java:736)|?at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)|?at java.security.AccessController.doPrivileged(Native Method)|?at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)|?at javax.security.auth.login.LoginContext.login(LoginContext.java:587)|?at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)|?at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)|?at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)|?at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)|?at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)|?at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)|?at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)|?at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)|?at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)|?at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)|?at org.eclipse.jetty.server.Server.handle(Server.java:446)|?at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)|?at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)|?at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)|?at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)|?at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)|?at java.lang.Thread.run(Thread.java:748)|Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: ldaps://ldap1.foobar.com ldaps://ldap2.foobar.com|?at java.net.URI$Parser.fail(URI.java:2848)|?at java.net.URI$Parser.parseAuthority(URI.java:3186)|?at java.net.URI$Parser.parseHierarchical(URI.java:3097)|?at java.net.URI$Parser.parse(URI.java:3053)|?at java.net.URI.<init>(URI.java:588)|?at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getEnvironment(JettyCachingLdapLoginModule.java:961)|?... 31 more|
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:856)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
	at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:446)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by matthias-colt** [comment]
Related ticket for ldaps constraint #1853
