### ISSUE TITLE
AD integration with Rundeck

### ISSUE THREAD

**Issue by Bhavana-P123** [rundeck/rundeck#5541]
**Describe the bug**
Issue while using active directory authentication.

**My Rundeck detail**

* Rundeck version: [ e.g. 3.0.24]
* install type: [choose: rpm]
* OS Name/version: [e.g. amazon-linux(2)]
* DB Type/version: [choose: mysql (RDS)]

**To Reproduce**
1. Content of jaas-activedirectory.conf:
activedirectory {
com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
debug="true"
contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
providerUrl="x.x.x.x:389"
bindDn="CN=,CN=Users,DC=,DC="
bindPassword=""
authenticationMethod="simple"
forceBindingLogin="true"
userBaseDn="dc=,dc="
userRdnAttribute="sAMAccountName"
userIdAttribute="sAMAccountName"
userPasswordAttribute="unicodePwd"
userObjectClass="user"
roleBaseDn="cn=,dc=,dc="
roleNameAttribute="cn"
roleMemberAttribute="member"
roleObjectClass="group"
cacheDurationMillis="0"
reportStatistics="true";
};

2. Using following in profile:
RDECK_JVM=-Djava.security.auth.login.config=/etc/rundeck/jaas-activedirectory.conf \
                     -Dloginmodule.name=activedirectory \

3. service rundeckd restart

4. Error received:
**_org.springframework.security.authentication.AuthenticationServiceException: java.lang.IllegalStateException: Unable to establish root context: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580]
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.initialize(JettyCachingLdapLoginModule.java:916)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:736)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.springframework.security.authentication.jaas.AbstractJaasAuthenticationProvider.authenticate(AbstractJaasAuthenticationProvider.java:180)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
        at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
        at grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter.attemptAuthentication(GrailsUsernamePasswordAuthenticationFilter.groovy:53)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)_**

**Expected behavior**
Authentication via corresponding Active Directory.

**Comment by MegaDrive68k** [comment]
Hi @Bhavana-P123 

That looks very similar to this issue, please check:

https://github.com/rundeck/rundeck/issues/2707

Regards!
