### ISSUE TITLE
Jobs randomly fail after 2.10.2 => 3.1.3 upgrade (No row with the given identifier exists)

### ISSUE THREAD

**Issue by hazarguney** [rundeck/rundeck#5608]
**Describe the bug**
I have upgraded our environment to 3.1.3 from 2.10.2-1. Migration of jobs has been performed using SCM (push from old version and pull from the new one). When schedule is enabled on project, jobs randomly fail and logs below appear:

`[2019-12-17 10:29:00.665] ERROR ExecutionJob --- [eduler_Worker-2] Failed execution 46 : No row with the given identifier exists: [rundeck.CommandExec#668]; nested exception is org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.CommandExec#668]

org.springframework.orm.hibernate5.HibernateObjectRetrievalFailureException: No row with the given identifier exists: [rundeck.CommandExec#668]; nested exception is org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.CommandExec#668]
        at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:274)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:724)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:303)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.refresh(GrailsHibernateTemplate.java:457)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.refresh(GrailsHibernateTemplate.java:453)
        at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.refresh(AbstractHibernateGormInstanceApi.groovy:246)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.refresh(GormEntity.groovy:90)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$refresh$13.call(Unknown Source)
        at rundeck.Execution.refresh(Execution.groovy)
        at rundeck.Execution.refresh(Execution.groovy)
        at org.grails.datastore.gorm.GormEntity$refresh$0.call(Unknown Source)
        at rundeck.services.ExecutionService.$tt__executeAsyncBegin(ExecutionService.groovy:990)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
        at rundeck.services.ExecutionService$_executeAsyncBegin_closure20.doCall(ExecutionService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy)
        at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy)
        at rundeck.services.ExecutionService$executeAsyncBegin$34.call(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:363)
        at rundeck.quartzjobs.ExecutionJob$executeCommand$13.callCurrent(Unknown Source)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:97)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:126)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:96)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.UnresolvableObjectException: No row with the given identifier exists: [rundeck.CommandExec#668]
        at org.hibernate.UnresolvableObjectException.throwIfNull(UnresolvableObjectException.java:51)
        at org.hibernate.event.internal.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:185)
        at org.hibernate.internal.SessionImpl.fireRefresh(SessionImpl.java:1202)
        at org.hibernate.internal.SessionImpl.refresh(SessionImpl.java:1186)
        at org.hibernate.engine.spi.CascadingActions$3.cascade(CascadingActions.java:141)
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:423)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:348)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:187)
        at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:456)
        at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:388)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:351)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:187)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:136)
        at org.hibernate.event.internal.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:125)
        at org.hibernate.internal.SessionImpl.fireRefresh(SessionImpl.java:1202)
        at org.hibernate.internal.SessionImpl.refresh(SessionImpl.java:1186)
        at org.hibernate.engine.spi.CascadingActions$3.cascade(CascadingActions.java:141)
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:423)
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:348)
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:187)
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:136)
        at org.hibernate.event.internal.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:125)
        at org.hibernate.event.internal.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:48)
        at org.hibernate.internal.SessionImpl.fireRefresh(SessionImpl.java:1193)
        at org.hibernate.internal.SessionImpl.refresh(SessionImpl.java:1166)
        at org.hibernate.internal.SessionImpl.refresh(SessionImpl.java:1161)
        at org.grails.orm.hibernate.GrailsHibernateTemplate$11.doInHibernate(GrailsHibernateTemplate.java:460)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:299)
        ... 68 common frames omitted`

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3] 3.1.3
* install type: [choose: rpm,deb,war,launcher] Docker Image
* OS Name/version: [e.g. ubuntu 16.04] Docker Image
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ] MySQL

Your support will be highly appreciated.

**Comment by hazarguney** [comment]
I have migrated jobs using "rd jobs list" from the old server and "Upload Definition" in the new one. This issue still exists using this method.

**Comment by MegaDrive68k** [comment]
Hi @hazarguney 

Seems similar to this: https://github.com/rundeck/rundeck/issues/1712

It seems that some process/event in your environment does not allow the schema migration to be completed successfully to 3.1.3 (then 3.1.3 is working on 2.10 database schema).

Also, can you test that jobs on fresh 3.1.3 instance configured with a fresh database? Maybe the job definition breaks some compatibility with 3.1.x (in this case, please share the job definition to test it, hide or change any potentially sensitive data).

Regards.

**Comment by hazarguney** [comment]
Actually, I have created a whole new environment instead of upgrading the current one. Projects (not too many) have been created manually and transferred using SCM hence database is fresh. I cannot share any job definition because not a specific job fails, jobs in the project somehow randomly fail.

**Comment by hazarguney** [comment]
It seems that the issue occurs due to master-master MySQL configuration behind ProxySQL. When ProxySQL is bypassed, everything works fine. Thank you.

**Comment by jasonparmar26** [comment]
I had this problem using AWS mysql, i know it sounds strange but recreating a fresh new RDS instance not just the DB solved this issue for me.
