### ISSUE TITLE
500 Internal Server error during login due to Hibernate exception

### ISSUE THREAD

**Issue by agoca80** [rundeck/rundeck#5835]
**Describe the bug**

External integration receives an 500 Server Error while login into Rundeck due to a Hibernate issue.

**My Rundeck detail**

* Rundeck version: Rundeck 3.2.1-20200113
* install type: rpm
* OS Name/version: Amazon Linux v1
* DB Type/version: AWS RDS MySQL 5.5.61 engine version

**To Reproduce**

The issue happens sporadically from an external integration using Rundeck API.

**Expected behavior**

A valid response is provided to the login request as described in https://docs.rundeck.com/docs/api/rundeck-api.html#password-authentication

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Additional context**

Excerpts from the integration logs:

```
2020-02-27 09:30:05.811 [scheduler-pool-1-thread-127] {task=Applications/Folderbfd5955e581d41439fa41b94bebd773e/Folder6ddcb37b22bc4540b6fa8898ca54640e/Releaseec272ffe0f2a4cac8d7dbfcff35e62f1/Phase7178275/Task39729115/Task0c23df1c8a6e468a8
b7ede0825d652f4} WARN  c.x.x.s.jython.JythonScriptService - Exception during execution
javax.script.ScriptException: org.rundeck.api.RundeckApiException$RundeckApiLoginException: org.rundeck.api.RundeckApiException$RundeckApiLoginException: Invalid HTTP response 'HTTP/1.1 500 Server Error' for https://rundeck.ls.clarivate.i
o/j_security_check in <script> at line number 67
...
Caused by: org.rundeck.api.RundeckApiException$RundeckApiLoginException: Invalid HTTP response 'HTTP/1.1 500 Server Error' for https://rundeck.ls.clarivate.io/j_security_check
        at org.rundeck.api.ApiCall.login(ApiCall.java:745)
```

Full Rundeck error stacktrace:

```
[2020-02-27 09:30:05.732] DEBUG GrailsUsernamePasswordAuthenticationFilter --- [qtp546452352-25] Request is to process authentication
[2020-02-27 09:30:05.741]  INFO JettyCachingLdapLoginModule --- [qtp546452352-25] Login attempts: 21251, Hits: 0, Ratio: 0%.
[2020-02-27 09:30:05.741] DEBUG JettyCachingLdapLoginModule --- [qtp546452352-25] Cache Miss for svc-xlrelease-rundeck@clarivate.com.
[2020-02-27 09:30:05.741] DEBUG JettyCachingLdapLoginModule --- [qtp546452352-25] Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: DC=mm-ads,DC=com
[2020-02-27 09:30:05.743] DEBUG JettyCachingLdapLoginModule --- [qtp546452352-25] Found user?: true
[2020-02-27 09:30:05.743]  INFO JettyCachingLdapLoginModule --- [qtp546452352-25] Attempting authentication: CN=svc-xlrelease-rundeck,OU=Service Accounts,OU=Clarivate,DC=mm-ads,DC=com
[2020-02-27 09:30:05.747] DEBUG JettyCachingLdapLoginModule --- [qtp546452352-25] JettyCachingLdapLoginModule: User 'svc-xlrelease-rundeck@clarivate.com' has roles: [rundeck-ls-prod, Deny Interactive Logon for Service Accounts]
[2020-02-27 09:30:05.747] DEBUG JettyCachingLdapLoginModule --- [qtp546452352-25] Adding svc-xlrelease-rundeck@clarivate.com set to expire: 1582795805747300000
[2020-02-27 09:30:05.755] DEBUG GrailsUsernamePasswordAuthenticationFilter --- [546452352-96957] Request is to process authentication
[2020-02-27 09:30:05.760]  INFO JettyCachingLdapLoginModule --- [546452352-96957] Login attempts: 21252, Hits: 0, Ratio: 0%.
[2020-02-27 09:30:05.760] DEBUG JettyCachingLdapLoginModule --- [546452352-96957] Cache Miss for svc-xlrelease-rundeck@clarivate.com.
[2020-02-27 09:30:05.760] DEBUG JettyCachingLdapLoginModule --- [546452352-96957] Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: DC=mm-ads,DC=com
[2020-02-27 09:30:05.762] DEBUG JettyCachingLdapLoginModule --- [546452352-96957] Found user?: true
[2020-02-27 09:30:05.762]  INFO JettyCachingLdapLoginModule --- [546452352-96957] Attempting authentication: CN=svc-xlrelease-rundeck,OU=Service Accounts,OU=Clarivate,DC=mm-ads,DC=com
[2020-02-27 09:30:05.766] DEBUG JettyCachingLdapLoginModule --- [546452352-96957] JettyCachingLdapLoginModule: User 'svc-xlrelease-rundeck@clarivate.com' has roles: [rundeck-ls-prod, Deny Interactive Logon for Service Accounts]
[2020-02-27 09:30:05.766] DEBUG JettyCachingLdapLoginModule --- [546452352-96957] Adding svc-xlrelease-rundeck@clarivate.com set to expire: 1582795805766300000
[2020-02-27 09:30:05.775]  WARN HttpChannel --- [546452352-96957] /j_security_check

org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:283)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:724)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:303)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:243)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:117)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.performSave(AbstractHibernateGormInstanceApi.groovy:251)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:168)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$save$4.call(Unknown Source)
	at rundeck.User.save(User.groovy)
	at rundeck.User.save(User.groovy)
	at org.grails.datastore.gorm.GormEntity$save.call(Unknown Source)
	at rundeck.services.UserService.$tt__registerLogin(UserService.groovy:76)
	at sun.reflect.GeneratedMethodAccessor850.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
	at rundeck.services.UserService$_registerLogin_closure2.doCall(UserService.groovy)
	at sun.reflect.GeneratedMethodAccessor849.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at rundeck.services.UserService.registerLogin(UserService.groovy)
	at rundeck.services.UserService$registerLogin$0.call(Unknown Source)
	at rundeck.services.events.UserActionService.$tt__handleAuthenticationSuccessEvent(UserActionService.groovy:26)
	at sun.reflect.GeneratedMethodAccessor848.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
	at rundeck.services.events.UserActionService$_handleAuthenticationSuccessEvent_closure1.doCall(UserActionService.groovy)
	at sun.reflect.GeneratedMethodAccessor846.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at rundeck.services.events.UserActionService.handleAuthenticationSuccessEvent(UserActionService.groovy)
	at sun.reflect.GeneratedMethodAccessor842.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:258)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.security.authentication.DefaultAuthenticationEventPublisher.publishAuthenticationSuccess(DefaultAuthenticationEventPublisher.java:99)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:220)
	at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
	at grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter.attemptAuthentication(GrailsUsernamePasswordAuthenticationFilter.groovy:53)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3198)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3077)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3457)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:589)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.flushSession(AbstractHibernateGormInstanceApi.groovy:289)
	at sun.reflect.GeneratedMethodAccessor552.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi$_performSave_closure3.doCall(AbstractHibernateGormInstanceApi.groovy:254)
	at sun.reflect.GeneratedMethodAccessor551.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy126.doInHibernate(Unknown Source)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:299)
	... 131 common frames omitted
```

**Comment by MegaDrive68k** [comment]
Hi @agoca80 

Can you provide your API call (maybe running a job?) to do some tests?

Thank you!

**Comment by agoca80** [comment]
Hi @MegaDrive68k 

> Did you upgrade Rundeck recently?

We upgraded from 3.1.2 to 3.2.1 around ~20th of Jan.

> Can you provide your API call (maybe running a job?) to do some tests?

Unfortunately, I can't, unless I set some proxy in the middle to capture the right HTTP request, as this was requested from an external tool. Also, it happens sporadically, so it is not reproducible. The same integration has worked fine under the current version. 

I have detected this stacktrace at least twice. I may try to trigger it, but as it seems a race in the hibernate backend, it will be difficult to reproduce it at will. If you provide any tips, I may give it a try.

Let me know if you need more information and I'll try to deliver :)

**Comment by sjrd218** [comment]
@agoca80 Can you test if this occurs if the api calls happen within a few milliseconds of each other.

**Comment by agoca80** [comment]
Thanks for looking into this guys. This is not something I can test easily, but this looks the same as #5836 , which matches our scenario. Our environment uses different integrations to launch a lot of rundeck tasks more or less at the same time, so, the premise makes sense and the fix looks right.
Thanks!
