### ISSUE TITLE
rundeck-3.2.3 + Oracle DB + Caused by: java.sql.SQLException: Stream has already been closed

### ISSUE THREAD

**Issue by balbir0308** [rundeck/rundeck#5858]
Did a fresh installation of Rundeck: rundeck-3.2.3.20200221-1.noarch
Connecting to Oracle DB and followed all steps laid out in the document.

Rundeck starts fine and all tables are created. 

We were able to import the jobs. But Jobs fail to start with the below exception. We are not sure why we are seeing this issue since we have another rundeck server running on rundeck-2.11.4-1.55.GA.noarch connecting to same oracle DB but different database

```
[2020-03-04 14:32:23.631] ERROR ExceptionPrinterJobListener --- [eduler_Worker-1] Exception occurred in job: null

org.quartz.JobExecutionException: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not load an entity: [rundeck.Execution#143627]; uncategorized SQLException for SQL [select execution0_.id as id1_2_4_, execution0_.version as version2_2_4_, execution0_.scheduled_execution_id as scheduled_executio3_2_4_, execution0_.do_nodedispatch as do_nodedispatch4_2_4_, execution0_.node_exclude_os_arch as node_exclude_os_ar5_2_4_, execution0_.node_keepgoing as node_keepgoing6_2_4_, execution0_.succeeded_node_list as succeeded_node_lis7_2_4_, execution0_.retry_attempt as retry_attempt8_2_4_, execution0_.node_include as node_include9_2_4_, execution0_.retry_prev_id as retry_prev_id10_2_4_, execution0_.success_on_empty_node_filter as success_on_empty_11_2_4_, execution0_.extra_metadata as extra_metadata12_2_4_, execution0_.node_exclude_os_version as node_exclude_os_v13_2_4_, execution0_.timeout as timeout14_2_4_, execution0_.node_exclude_precedence as node_exclude_prec15_2_4_, execution0_.node_exclude_name as node_exclude_name16_2_4_, execution0_.node_include_os_version as node_include_os_v17_2_4_, execution0_.node_exclude_os_name as node_exclude_os_n18_2_4_, execution0_.retry as retry19_2_4_, execution0_.filter as filter20_2_4_, execution0_.orchestrator_id as orchestrator_id21_2_4_, execution0_.node_include_name as node_include_name22_2_4_, execution0_.rduser as rduser23_2_4_, execution0_.retry_original_id as retry_original_id24_2_4_, execution0_.execution_type as execution_type25_2_4_, execution0_.node_include_os_name as node_include_os_n26_2_4_, execution0_.abortedby as abortedby27_2_4_, execution0_.filter_exclude as filter_exclude28_2_4_, execution0_.node_exclude as node_exclude29_2_4_, execution0_.node_rank_order_ascending as node_rank_order_a30_2_4_, execution0_.node_include_os_arch as node_include_os_a31_2_4_, execution0_.loglevel as loglevel32_2_4_, execution0_.node_exclude_os_family as node_exclude_os_f33_2_4_, execution0_.node_include_os_family as node_include_os_f34_2_4_, execution0_.cancelled as cancelled35_2_4_, execution0_.retry_delay as retry_delay36_2_4_, execution0_.workflow_id as workflow_id37_2_4_, execution0_.timed_out as timed_out38_2_4_, execution0_.failed_node_list as failed_node_list39_2_4_, execution0_.arg_string as arg_string40_2_4_, execution0_.user_role_list as user_role_list41_2_4_, execution0_.node_rank_attribute as node_rank_attribu42_2_4_, execution0_.date_completed as date_completed43_2_4_, execution0_.outputfilepath as outputfilepath44_2_4_, execution0_.server_nodeuuid as server_nodeuuid45_2_4_, execution0_.will_retry as will_retry46_2_4_, execution0_.retry_execution_id as retry_execution_i47_2_4_, execution0_.node_exclude_tags as node_exclude_tags48_2_4_, execution0_.exclude_filter_uncheck as exclude_filter_un49_2_4_, execution0_.node_threadcount as node_threadcount50_2_4_, execution0_.node_include_tags as node_include_tags51_2_4_, execution0_.date_started as date_started52_2_4_, execution0_.status as status53_2_4_, execution0_.node_filter_editable as node_filter_edita54_2_4_, execution0_.project as project55_2_4_, logfilesto1_.id as id1_4_0_, logfilesto1_.version as version2_4_0_, logfilesto1_.plugin_name as plugin_name3_4_0_, logfilesto1_.date_created as date_created4_4_0_, logfilesto1_.filetype as filetype5_4_0_, logfilesto1_.last_updated as last_updated6_4_0_, logfilesto1_.completed as completed7_4_0_, logfilesto1_.execution_id as execution_id8_4_0_, workflow2_.id as id1_20_1_, workflow2_.version as version2_20_1_, workflow2_.strategy as strategy3_20_1_, workflow2_.keepgoing as keepgoing4_20_1_, workflow2_.threadcount as threadcount5_20_1_, workflow2_.plugin_config as plugin_config6_20_1_, commands3_.workflow_commands_id as workflow_commands_1_22_6_, workflowst4_.id as workflow_step_id2_22_6_, commands3_.commands_idx as commands_idx3_6_, workflowst4_.id as id1_21_2_, workflowst4_.version as version2_21_2_, workflowst4_.plugin_config_data as plugin_config_data3_21_2_, workflowst4_.keepgoing_on_success as keepgoing_on_succe4_21_2_, workflowst4_.error_handler_id as error_handler_id5_21_2_, workflowst4_.description as description6_21_2_, workflowst4_.file_extension as file_extension8_21_2_, workflowst4_.interpreter_args_quoted as interpreter_args_q9_21_2_, workflowst4_.adhoc_execution as adhoc_execution10_21_2_, workflowst4_.arg_string as arg_string11_21_2_, workflowst4_.adhoc_filepath as adhoc_filepath12_21_2_, workflowst4_.adhoc_remote_string as adhoc_remote_stri13_21_2_, workflowst4_.script_interpreter as script_interprete14_21_2_, workflowst4_.adhoc_local_string as adhoc_local_strin15_21_2_, workflowst4_.fail_on_disable as fail_on_disable16_21_2_, workflowst4_.node_keepgoing as node_keepgoing17_21_2_, workflowst4_.uuid as uuid18_21_2_, workflowst4_.ignore_notifications as ignore_notificati19_21_2_, workflowst4_.node_step as node_step20_21_2_, workflowst4_.node_intersect as node_intersect21_21_2_, workflowst4_.node_filter as node_filter22_21_2_, workflowst4_.node_rank_attribute as node_rank_attribu23_21_2_, workflowst4_.node_threadcount as node_threadcount24_21_2_, workflowst4_.job_project as job_project25_21_2_, workflowst4_.job_name as job_name26_21_2_, workflowst4_.use_name as use_name27_21_2_, workflowst4_.job_group as job_group28_21_2_, workflowst4_.import_options as import_options29_21_2_, workflowst4_.node_rank_order_ascending as node_rank_order_a30_21_2_, workflowst4_.json_data as json_data31_21_2_, workflowst4_.type as type32_21_2_, workflowst4_.class as class7_21_2_, workflowst5_.id as id1_21_3_, workflowst5_.version as version2_21_3_, workflowst5_.plugin_config_data as plugin_config_data3_21_3_, workflowst5_.keepgoing_on_success as keepgoing_on_succe4_21_3_, workflowst5_.error_handler_id as error_handler_id5_21_3_, workflowst5_.description as description6_21_3_, workflowst5_.file_extension as file_extension8_21_3_, workflowst5_.interpreter_args_quoted as interpreter_args_q9_21_3_, workflowst5_.adhoc_execution as adhoc_execution10_21_3_, workflowst5_.arg_string as arg_string11_21_3_, workflowst5_.adhoc_filepath as adhoc_filepath12_21_3_, workflowst5_.adhoc_remote_string as adhoc_remote_stri13_21_3_, workflowst5_.script_interpreter as script_interprete14_21_3_, workflowst5_.adhoc_local_string as adhoc_local_strin15_21_3_, workflowst5_.fail_on_disable as fail_on_disable16_21_3_, workflowst5_.node_keepgoing as node_keepgoing17_21_3_, workflowst5_.uuid as uuid18_21_3_, workflowst5_.ignore_notifications as ignore_notificati19_21_3_, workflowst5_.node_step as node_step20_21_3_, workflowst5_.node_intersect as node_intersect21_21_3_, workflowst5_.node_filter as node_filter22_21_3_, workflowst5_.node_rank_attribute as node_rank_attribu23_21_3_, workflowst5_.node_threadcount as node_threadcount24_21_3_, workflowst5_.job_project as job_project25_21_3_, workflowst5_.job_name as job_name26_21_3_, workflowst5_.use_name as use_name27_21_3_, workflowst5_.job_group as job_group28_21_3_, workflowst5_.import_options as import_options29_21_3_, workflowst5_.node_rank_order_ascending as node_rank_order_a30_21_3_, workflowst5_.json_data as json_data31_21_3_, workflowst5_.type as type32_21_3_, workflowst5_.class as class7_21_3_ from execution execution0_ left outer join log_file_storage_request logfilesto1_ on execution0_.id=logfilesto1_.execution_id left outer join workflow workflow2_ on execution0_.workflow_id=workflow2_.id left outer join workflow_workflow_step commands3_ on workflow2_.id=commands3_.workflow_commands_id left outer join workflow_step workflowst4_ on commands3_.workflow_step_id=workflowst4_.id left outer join workflow_step workflowst5_ on workflowst4_.error_handler_id=workflowst5_.id where execution0_.id=?]; SQL state [99999]; error code [17027]; Stream has already been closed; nested exception is java.sql.SQLException: Stream has already been closed]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:218)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        ... 1 common frames omitted
Caused by: org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not load an entity: [rundeck.Execution#143627]; uncategorized SQLException for SQL [select execution0_.id as id1_2_4_, execution0_.version as version2_2_4_, execution0_.scheduled_execution_id as scheduled_executio3_2_4_, execution0_.do_nodedispatch as do_nodedispatch4_2_4_, execution0_.node_exclude_os_arch as node_exclude_os_ar5_2_4_, execution0_.node_keepgoing as node_keepgoing6_2_4_, execution0_.succeeded_node_list as succeeded_node_lis7_2_4_, execution0_.retry_attempt as retry_attempt8_2_4_, execution0_.node_include as node_include9_2_4_, execution0_.retry_prev_id as retry_prev_id10_2_4_, execution0_.success_on_empty_node_filter as success_on_empty_11_2_4_, execution0_.extra_metadata as extra_metadata12_2_4_, execution0_.node_exclude_os_version as node_exclude_os_v13_2_4_, execution0_.timeout as timeout14_2_4_, execution0_.node_exclude_precedence as node_exclude_prec15_2_4_, execution0_.node_exclude_name as node_exclude_name16_2_4_, execution0_.node_include_os_version as node_include_os_v17_2_4_, execution0_.node_exclude_os_name as node_exclude_os_n18_2_4_, execution0_.retry as retry19_2_4_, execution0_.filter as filter20_2_4_, execution0_.orchestrator_id as orchestrator_id21_2_4_, execution0_.node_include_name as node_include_name22_2_4_, execution0_.rduser as rduser23_2_4_, execution0_.retry_original_id as retry_original_id24_2_4_, execution0_.execution_type as execution_type25_2_4_, execution0_.node_include_os_name as node_include_os_n26_2_4_, execution0_.abortedby as abortedby27_2_4_, execution0_.filter_exclude as filter_exclude28_2_4_, execution0_.node_exclude as node_exclude29_2_4_, execution0_.node_rank_order_ascending as node_rank_order_a30_2_4_, execution0_.node_include_os_arch as node_include_os_a31_2_4_, execution0_.loglevel as loglevel32_2_4_, execution0_.node_exclude_os_family as node_exclude_os_f33_2_4_, execution0_.node_include_os_family as node_include_os_f34_2_4_, execution0_.cancelled as cancelled35_2_4_, execution0_.retry_delay as retry_delay36_2_4_, execution0_.workflow_id as workflow_id37_2_4_, execution0_.timed_out as timed_out38_2_4_, execution0_.failed_node_list as failed_node_list39_2_4_, execution0_.arg_string as arg_string40_2_4_, execution0_.user_role_list as user_role_list41_2_4_, execution0_.node_rank_attribute as node_rank_attribu42_2_4_, execution0_.date_completed as date_completed43_2_4_, execution0_.outputfilepath as outputfilepath44_2_4_, execution0_.server_nodeuuid as server_nodeuuid45_2_4_, execution0_.will_retry as will_retry46_2_4_, execution0_.retry_execution_id as retry_execution_i47_2_4_, execution0_.node_exclude_tags as node_exclude_tags48_2_4_, execution0_.exclude_filter_uncheck as exclude_filter_un49_2_4_, execution0_.node_threadcount as node_threadcount50_2_4_, execution0_.node_include_tags as node_include_tags51_2_4_, execution0_.date_started as date_started52_2_4_, execution0_.status as status53_2_4_, execution0_.node_filter_editable as node_filter_edita54_2_4_, execution0_.project as project55_2_4_, logfilesto1_.id as id1_4_0_, logfilesto1_.version as version2_4_0_, logfilesto1_.plugin_name as plugin_name3_4_0_, logfilesto1_.date_created as date_created4_4_0_, logfilesto1_.filetype as filetype5_4_0_, logfilesto1_.last_updated as last_updated6_4_0_, logfilesto1_.completed as completed7_4_0_, logfilesto1_.execution_id as execution_id8_4_0_, workflow2_.id as id1_20_1_, workflow2_.version as version2_20_1_, workflow2_.strategy as strategy3_20_1_, workflow2_.keepgoing as keepgoing4_20_1_, workflow2_.threadcount as threadcount5_20_1_, workflow2_.plugin_config as plugin_config6_20_1_, commands3_.workflow_commands_id as workflow_commands_1_22_6_, workflowst4_.id as workflow_step_id2_22_6_, commands3_.commands_idx as commands_idx3_6_, workflowst4_.id as id1_21_2_, workflowst4_.version as version2_21_2_, workflowst4_.plugin_config_data as plugin_config_data3_21_2_, workflowst4_.keepgoing_on_success as keepgoing_on_succe4_21_2_, workflowst4_.error_handler_id as error_handler_id5_21_2_, workflowst4_.description as description6_21_2_, workflowst4_.file_extension as file_extension8_21_2_, workflowst4_.interpreter_args_quoted as interpreter_args_q9_21_2_, workflowst4_.adhoc_execution as adhoc_execution10_21_2_, workflowst4_.arg_string as arg_string11_21_2_, workflowst4_.adhoc_filepath as adhoc_filepath12_21_2_, workflowst4_.adhoc_remote_string as adhoc_remote_stri13_21_2_, workflowst4_.script_interpreter as script_interprete14_21_2_, workflowst4_.adhoc_local_string as adhoc_local_strin15_21_2_, workflowst4_.fail_on_disable as fail_on_disable16_21_2_, workflowst4_.node_keepgoing as node_keepgoing17_21_2_, workflowst4_.uuid as uuid18_21_2_, workflowst4_.ignore_notifications as ignore_notificati19_21_2_, workflowst4_.node_step as node_step20_21_2_, workflowst4_.node_intersect as node_intersect21_21_2_, workflowst4_.node_filter as node_filter22_21_2_, workflowst4_.node_rank_attribute as node_rank_attribu23_21_2_, workflowst4_.node_threadcount as node_threadcount24_21_2_, workflowst4_.job_project as job_project25_21_2_, workflowst4_.job_name as job_name26_21_2_, workflowst4_.use_name as use_name27_21_2_, workflowst4_.job_group as job_group28_21_2_, workflowst4_.import_options as import_options29_21_2_, workflowst4_.node_rank_order_ascending as node_rank_order_a30_21_2_, workflowst4_.json_data as json_data31_21_2_, workflowst4_.type as type32_21_2_, workflowst4_.class as class7_21_2_, workflowst5_.id as id1_21_3_, workflowst5_.version as version2_21_3_, workflowst5_.plugin_config_data as plugin_config_data3_21_3_, workflowst5_.keepgoing_on_success as keepgoing_on_succe4_21_3_, workflowst5_.error_handler_id as error_handler_id5_21_3_, workflowst5_.description as description6_21_3_, workflowst5_.file_extension as file_extension8_21_3_, workflowst5_.interpreter_args_quoted as interpreter_args_q9_21_3_, workflowst5_.adhoc_execution as adhoc_execution10_21_3_, workflowst5_.arg_string as arg_string11_21_3_, workflowst5_.adhoc_filepath as adhoc_filepath12_21_3_, workflowst5_.adhoc_remote_string as adhoc_remote_stri13_21_3_, workflowst5_.script_interpreter as script_interprete14_21_3_, workflowst5_.adhoc_local_string as adhoc_local_strin15_21_3_, workflowst5_.fail_on_disable as fail_on_disable16_21_3_, workflowst5_.node_keepgoing as node_keepgoing17_21_3_, workflowst5_.uuid as uuid18_21_3_, workflowst5_.ignore_notifications as ignore_notificati19_21_3_, workflowst5_.node_step as node_step20_21_3_, workflowst5_.node_intersect as node_intersect21_21_3_, workflowst5_.node_filter as node_filter22_21_3_, workflowst5_.node_rank_attribute as node_rank_attribu23_21_3_, workflowst5_.node_threadcount as node_threadcount24_21_3_, workflowst5_.job_project as job_project25_21_3_, workflowst5_.job_name as job_name26_21_3_, workflowst5_.use_name as use_name27_21_3_, workflowst5_.job_group as job_group28_21_3_, workflowst5_.import_options as import_options29_21_3_, workflowst5_.node_rank_order_ascending as node_rank_order_a30_21_3_, workflowst5_.json_data as json_data31_21_3_, workflowst5_.type as type32_21_3_, workflowst5_.class as class7_21_3_ from execution execution0_ left outer join log_file_storage_request logfilesto1_ on execution0_.id=logfilesto1_.execution_id left outer join workflow workflow2_ on execution0_.workflow_id=workflow2_.id left outer join workflow_workflow_step commands3_ on workflow2_.id=commands3_.workflow_commands_id left outer join workflow_step workflowst4_ on commands3_.workflow_step_id=workflowst4_.id left outer join workflow_step workflowst5_ on workflowst4_.error_handler_id=workflowst5_.id where execution0_.id=?]; SQL state [99999]; error code [17027]; Stream has already been closed; nested exception is java.sql.SQLException: Stream has already been closed
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.convertJdbcAccessException(GrailsHibernateTemplate.java:731)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:719)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:303)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.refresh(GrailsHibernateTemplate.java:457)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.refresh(GrailsHibernateTemplate.java:453)
        at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.refresh(AbstractHibernateGormInstanceApi.groovy:246)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.refresh(GormEntity.groovy:90)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$refresh$12.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at rundeck.Execution.refresh(Execution.groovy)
        at rundeck.Execution.refresh(Execution.groovy)
        at org.grails.datastore.gorm.GormEntity$refresh$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at rundeck.quartzjobs.ExecutionJob.$tt__fetchExecution(ExecutionJob.groovy:631)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:947)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:92)
        at rundeck.quartzjobs.ExecutionJob$_fetchExecution_closure7.doCall(ExecutionJob.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at rundeck.quartzjobs.ExecutionJob.fetchExecution(ExecutionJob.groovy)
        at rundeck.quartzjobs.ExecutionJob$fetchExecution$4.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
        at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:261)
        at rundeck.quartzjobs.ExecutionJob$initialize.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:98)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:97)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 common frames omitted
Caused by: java.sql.SQLException: Stream has already been closed
        at oracle.jdbc.driver.LongAccessor.getBytesInternal(LongAccessor.java:131)
        at oracle.jdbc.driver.Accessor.getBytes(Accessor.java:951)
        at oracle.jdbc.driver.LongAccessor.getString(LongAccessor.java:166)
        at oracle.jdbc.driver.GeneratedStatement.getString(GeneratedStatement.java:327)
        at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:882)
        at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:1460)
        at org.hibernate.type.descriptor.sql.VarcharTypeDescriptor$2.doExtract(VarcharTypeDescriptor.java:62)
        at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:235)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:231)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:222)
        at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:296)
        at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2854)
        at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1735)
        at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1661)
        at org.hibernate.loader.Loader.getRow(Loader.java:1550)
        at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:733)
        at org.hibernate.loader.Loader.processResultSet(Loader.java:978)
        at org.hibernate.loader.Loader.doQuery(Loader.java:936)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:312)
        at org.hibernate.loader.Loader.loadEntity(Loader.java:2209)
        at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:60)
        at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:50)
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4083)
        at org.hibernate.event.internal.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:171)
        at org.hibernate.event.internal.DefaultRefreshEventListener.onRefresh(DefaultRefreshEventListener.java:48)
        at org.hibernate.internal.SessionImpl.fireRefresh(SessionImpl.java:1193)
        at org.hibernate.internal.SessionImpl.refresh(SessionImpl.java:1166)
        at org.hibernate.internal.SessionImpl.refresh(SessionImpl.java:1161)
        at org.grails.orm.hibernate.GrailsHibernateTemplate$11.doInHibernate(GrailsHibernateTemplate.java:460)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:299)
        ... 83 common frames omitted

```

**Comment by MegaDrive68k** [comment]
Hi @balbir0308 

Which Oracle version are you using?

Thanks.

**Comment by balbir0308** [comment]
It is 

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by MegaDrive68k** [comment]
Hi @balbir0308 

Can you share how do you configure the database in the `rundeck-config.properties` file? (please change any potentially sensitive information).

This is my setup that works with Oracle 18c. Also, i use the [ojdbc8.jar ](https://www.oracle.com/database/technologies/appdev/jdbc-ucp-183-downloads.html)dialect.

```
# oracle 18c setup
dataSource.url = jdbc:oracle:thin:@localhost:1521:ORCLCDB
dataSource.driverClassName = oracle.jdbc.driver.OracleDriver
dataSource.username = rundeckuser
dataSource.password = rundeckpassword
dataSource.dialect = org.rundeck.hibernate.RundeckOracleDialect
dataSource.properties.validationQuery = SELECT 1 FROM DUAL
```

Thanks!

**Comment by balbir0308** [comment]
Sorry for the late response, we had to actually roll back the Rundeck to 3.0.24-20190719 after rollback with the same Oracle DB and table created with 3.2 Rundeck is working fine.

It's working with ojdbc7.jar connecting to same oracle DB so it could be a driver issue but not encountered with 3.0.24-20190719

We have used exactly the same setting mentioned in your earlier post and followed the steps mentioned in Rundeck Dochttps://docs.rundeck.com/docs/administration/configuration/database/oracle.html
