### ISSUE TITLE
External URL Node Source parsing

### ISSUE THREAD

**Issue by joemillerr** [rundeck/rundeck#5917]
I have a tiny web service that has run on localhost of my Rundeck machine I have used for years to generate a dynamic nodes list, this has worked without issue since I began using it.  I have moved this functionality into an external service and when trying to consume it in Rundeck I am having issues.  
```
ERROR com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource - [ResourceModelSource: 2.source (url), project: asdfsad]
java.lang.NullPointerException
	at com.dtolabs.rundeck.core.resources.format.json.ResourceJsonFormatParser.convertListNodes(ResourceJsonFormatParser.java:141)
	at com.dtolabs.rundeck.core.resources.format.json.ResourceJsonFormatParser.convertNodes(ResourceJsonFormatParser.java:126)
	at com.dtolabs.rundeck.core.resources.format.json.ResourceJsonFormatParser.parseDocument(ResourceJsonFormatParser.java:116)
	at com.dtolabs.rundeck.core.resources.format.json.ResourceJsonFormatParser.parseDocument(ResourceJsonFormatParser.java:106)
	at com.dtolabs.rundeck.core.resources.URLResourceModelSource.getNodes(URLResourceModelSource.java:318)
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
	at com.dtolabs.rundeck.core.resources.DelegateResourceModelSource.getNodes(DelegateResourceModelSource.java:35)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:136)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:356)
	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44)
	at rundeck.services.nodes.CachedProjectNodes.getNodeSet(CachedProjectNodes.groovy:40)
	at com.dtolabs.rundeck.core.common.FrameworkProject.getNodeSet(FrameworkProject.java:297)
	at com.dtolabs.rundeck.core.common.IRundeckProject$getNodeSet$3.call(Unknown Source)
	at rundeck.controllers.FrameworkController.nodeSummaryAjax(FrameworkController.groovy:531)
	at rundeck.controllers.FrameworkController.nodeSummaryAjax(FrameworkController.groovy)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter.doFilterInternal(RundeckSecurityHeadersFilter.groovy:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter.doFilterInternal(GrailsHttpPutFormContentFilter.groovy:54)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
```
Valid JSON is being returned and its identical to the working localhost URL Source.  I have forced application/json and UTF-8 encoding and I've also forced content-type to identity in case compression is an issue.  Neither worked.

The only difference between these two sources at this point are:
- External
- SSL
- Caching (which shouldnt make a difference but does add headers to the response)

I'm at a loss, please help!

**My Rundeck detail**

* Rundeck version: 3.0.23
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: mysql

**Comment by joemillerr** [comment]
I've just tried hosting the service on localhost and I get the same issue.  So now the only difference is caching.  I piped the curl localhost output to jq as well just to be sure and it parses fine.

**Comment by joemillerr** [comment]
More info that hopefully helps:  On a brand new project it will load the cached nodes from another project using the old URL source even though it has never been configured to use that.  It's almost like the node cache in rundeck is broken?  I've tried flipping off all of the caching settings to no avail.

**Comment by ahonor** [comment]
@joemillerr do you mind scrubbing an example of the returned json?

**Comment by joemillerr** [comment]
@ahonor thanks alex! here ya go, nothing is sensitive so this is exactly whats returned:

https://gist.github.com/joemillerr/9452dfb04e533d460566440af9407952

I haven't changed the fields at all in the move to this other service.

**Comment by ahonor** [comment]
@joemillerr that json was useful. I just tried loading the same data into a File model source and got an error with an NPE similar to what you saw.

**Comment by joemillerr** [comment]
weird, do you see whats wrong with it?  I've tried validating it in several different tools and it all comes back clean in those

thanks so much Alex!

**Comment by dutchrapley** [comment]
@joemillerr `nodename` is optional. If you have a `name` attribute on each item in the array, it should work. That'll remove the NullPointer exception and Rundeck will load your nodes.

**Comment by ahonor** [comment]
@dutchrapley That was super helpful. I think we should still treat the NPE as a bug. Maybe we can print a better error message too.

**Comment by joemillerr** [comment]
@dutchrapley so I should rename nodename to name?  I don't currently have a "name" field.  Also, this is exactly how my current JSON object looks on the URL source I've been using for ~5 years

**Comment by dutchrapley** [comment]
@joemillerr You don't have to rename `nodename` to `name`. You can have both, especially if you're using `nodename` in your node filters. I think the issue comes down to parsing in this instance by the formatter that's being invoked. The JSON formatter can parse both an array and a map.

When a map is specified, the key of each item in the map is assigned to the `name` attribute automatically, without having to specify it.

**Comment by joemillerr** [comment]
I added name and I still get this:
```
ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 1.source (url), project: TechOps]
java.lang.NullPointerException
WARN  LoggingResourceModelSourceCache: [ResourceModelSource: 1.source (url), project: TechOps] Returning cached model data
ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 1.source (url), project: TechOps]
java.lang.NullPointerException
```
another weird thing is that it just returns a node list for another project that I don't even have configured for this one

**Comment by dutchrapley** [comment]
@joemillerr Can you post another gist of the newly updated JSON?

**Comment by joemillerr** [comment]
@dutchrapley here ya go, thank you!
https://gist.github.com/joemillerr/b81f8ff316c6c19f82d8acc781b819b5

**Comment by dutchrapley** [comment]
@joemillerr It looks like there may be some bad data in there as well.

`    {
        "name": null,
        "nodename": null,
        "tags": "undefined",
        "osFamily": "undefined",
        "osName": "Undefined ",
        "FQDN": null,
        "hostname": null,
        "IP": null,
        "ChefTags": "undefined",
        "Environment": "devops0",
        "EnvironmentRole": "undefined",
        "Domain": null,
        "Cloud": "undefined",
        "Location": "undefined",
        "node-executor": "jsch-ssh",
        "file-copier": "jsch-scp"
    }`

**Comment by dutchrapley** [comment]
@joemillerr I wanted to mention that I didn't catch the null issues earlier since I was testing a very small subset of the JSON you provided. I also wanted to let you know that I tested the JSON using a file based Resource Model and then choosing the JSON formatter.

**Comment by ahonor** [comment]
I think we should add a test to the JSON resource format plugin to check for cases when data shows null for name and nodename and not throw an NPE.

**Comment by joemillerr** [comment]
@dutchrapley  Ugh I knew it was going to be something dumb like that.  I've sanitized the output but now nothing loads in the nodes list and I'm not seeing anything in the logs other than audit/access when I try to load the nodes page.  Sorry for all the trouble, this has been one thing after another.

**Comment by joemillerr** [comment]
@dutchrapley  @ahonor  I figured it out, apparently it doesn't like empty strings even though thats valid JSON.  As far as I can tell there is nothing emitting to the logs to even indicate a problem much less what it is, it just simply doesn't load anything.  Thank you for all of your help! so glad it appears to be working now 👍

**Comment by ahonor** [comment]
@joemillerr just to clarify do you mean it did not like `""` or no value?

**Comment by joemillerr** [comment]
`""`
