### ISSUE TITLE
LDAP connexion not working

### ISSUE THREAD

**Issue by bdietric5** [rundeck/rundeck#6049]
**Describe the bug**
I want to be able to identify users with a ldap server.

**My Rundeck detail**

Rundeck version: latest
 install type: apt-get install rundeck
 OS Name/version: Debian 10
 DB Type/version: default

**To Reproduce**
 1-Install Rundeck
 2-Create file jaas-ldap.config in /etc/rundeck as follow :

ldap { com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
debug="true"
contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
providerUrl="ldap://ldap.test.fr:389"
bindDn="cn=admin,dc=test,dc=fr"
bindPassword="mdp"
authenticationMethod="simple"
forceBindingLogin="true" 
userBaseDn="dc=test,dc=fr"
userRdnAttribute="sAMAccountName"
userIdAttribute="sAMAccountName"
userPasswordAttribute="unicodePwd"
userObjectClass="user"
roleBaseDn="DC=test,DC=lan"
roleNameAttribute="cn"
roleMemberAttribute="member"
roleObjectClass="group"
cacheDurationMillis="30000"
reportStatistics="true
timeoutRead="10000"
timeoutConnect="20000"
nestedGroups="true"
storePass="true";
};

3- Modify profile file as follow:
RDECK_JVM="-Drundeck.jaaslogin=true \
           -Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf \
           -Dloginmodule.name=ldap \

**Expected behavior**
Be able to connect to rundeck interface with ldap user and password.

**Errors**
[2020-05-13 15:08:39.890] ERROR SpringApplication --- [           main] Application startup failed

org.grails.core.exceptions.GrailsConfigurationException: Error loading spring/resources.groovy file: java.io.IOException: Erreur de configuration :
	Ligne 7 : attendu [option key], trouvé [null]
	at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:184)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at rundeckapp.Application.main(Application.groovy:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.SecurityException: java.io.IOException: Erreur de configuration :
	Ligne 7 : attendu [option key], trouvé [null]
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
	at javax.security.auth.login.Configuration$getConfiguration.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at resources$_run_closure1$_closure60.doCall(resources.groovy:550)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at grails.spring.BeanBuilder.invokeBeanDefiningMethod(BeanBuilder.java:708)
	at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:565)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:414)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at resources$_run_closure1.doCall(resources.groovy:549)
	at resources$_run_closure1.doCall(resources.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
	at org.grails.spring.RuntimeSpringConfigUtilities.reloadSpringResourcesConfig(RuntimeSpringConfigUtilities.java:103)
	at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:181)
	... 24 common frames omitted
Caused by: java.io.IOException: Erreur de configuration :
	Ligne 7 : attendu [option key], trouvé [null]
	at sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:666)
	at sun.security.provider.ConfigFile$Spi.match(ConfigFile.java:579)
	at sun.security.provider.ConfigFile$Spi.parseLoginEntry(ConfigFile.java:477)
	at sun.security.provider.ConfigFile$Spi.readConfig(ConfigFile.java:427)
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:329)
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:271)
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
	... 73 common frames omitted

**Comment by MegaDrive68k** [comment]
Hi @bdietric5 

You need to close the double quotes on  `reportStatistics="true` line.

You can check a good example of LDAP configuration [here](https://docs.rundeck.com/docs/administration/security/authentication.html#login-module-configuration).

Hope it helps!

**Comment by bdietric5** [comment]
Hello i have an other problem, i need want to use the admin account create by default by rundeck (in real.properties), I created a multiauth login module as follow : 

jaas-multiauth.conf : 

multiauth {                                                                                                                                                                                                                                                                    
   org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule sufficient                                                                                                                                                                                                          
      debug="true"                                                                                                                                                                                                                                                              
      file="/path/to/realm.properties";                                                                                                                                                                                                              
                                                                                                                                                                                                                                                              
   com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule required
      debug="true"
      contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl="ldap://ldap.mysite.com:389/"
      bindDn="cn=admin,ou=datacenter,o=auth"
      bindPassword="*********"
      authenticationMethod="simple"
      forceBindingLogin="true"
      userBaseDn="ou=users,ou=users,o=auth"
      userRdnAttribute="uid"
      userIdAttribute="uid"
      userPasswordAttribute="userPassword"
      userObjectClass="inetOrgPerson"
      roleBaseDn="ou=UNIX,ou=DATACENTER,o=AUTH"
      roleNameAttribute="cn"
      roleMemberAttribute="objectClass"
      roleUsernameMemberAttribute="cn"
      roleObjectClass="groupOfNames"
      roleSearchSubtree="true"
      supplementalRoles="user"
      reportStatistics="true"
      timeoutRead="10000"
      timeoutConnect="20000"
      ignoreRoles="true"
      storePass="true";
   org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
      debug="true"
      useFirstPass="true"
      file="/path/to/realm.properties";
     
};

But i can't connect to rundeck interface by using a ldap account or the admin account (user=admin , password = admin). 

I did the following change in profile : 
RDECK_JVM="-Drundeck.jaaslogin=true \
           -Djava.security.auth.login.config=/etc/rundeck/jaas-multiauth.conf \
           -Dloginmodule.name=multiauth \

I don't know if i need to change the realm.properties : 
admin:admin,user,admin,architect,deploy,build

**Comment by MegaDrive68k** [comment]
Hi @bdietric5 

Can you try changing `org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule` by `org.eclipse.jetty.jaas.spi.PropertyFileLoginModule`?

I leave my working example of multiauth config:

```
multiauth {
  com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldap://localhost:389"
    bindDn="cn=admin,dc=example,dc=net"
    bindPassword="admin"
    authenticationMethod="simple"
    forceBindingLogin="false"
    userBaseDn="ou=Users,dc=example,dc=net"
    userRdnAttribute="uid"
    userIdAttribute="uid"
    userPasswordAttribute="userPassword"
    userObjectClass="posixAccount"
    roleBaseDn="cn=Roles,dc=example,dc=net"
    roleNameAttribute="cn"
    roleUsernameMemberAttribute="memberUid"
    roleMemberAttribute="memberUid"
    roleObjectClass="posixGroup"
    cacheDurationMillis="300000"
    supplementalRoles="user"
    reportStatistics="true"
    timeoutRead="10000"
    timeoutConnect="20000"
    nestedGroups="false";

  org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
    debug="true"
    file="/etc/rundeck/realm.properties";
};
```

You can check a good example here:

https://docs.rundeck.com/docs/administration/security/authentication.html#multiple-authentication-modules

Regards!
