### ISSUE TITLE
Warning and errors messages on 3.3.0-PREVIEW2 with Oracle Database (related to Calendars add on)

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6141]
**Describe the bug**

Warning messages when configuring 3.3.0-PREVIEW2 with Oracle Database (related to Calendars add on), tested on Oracle 18c.

```
[2020-06-16T10:11:36,520] WARN  org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl2 - GenerationTarget encountered exception accepting command : Error executing DDL "create table calendar (id number(19,0) not null, version number(19,0) not null, level varchar2(7 char) not null, date_created timestamp not null, all_reference number(1,0) not null, last_updated timestamp not null, date_definition_json clob not null, enable number(1,0) not null, calendar_type varchar2(8 char) not null, json_data clob, date_type varchar2(7 char) not null, recurrent number(1,0) not null, name varchar2(255 char) not null, description clob, project varchar2(255 char), primary key (id))" via JDBC Statement
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table calendar (id number(19,0) not null, version number(19,0) not null, level varchar2(7 char) not null, date_created timestamp not null, all_reference number(1,0) not null, last_updated timestamp not null, date_definition_json clob not null, enable number(1,0) not null, calendar_type varchar2(8 char) not null, json_data clob, date_type varchar2(7 char) not null, recurrent number(1,0) not null, name varchar2(255 char) not null, description clob, project varchar2(255 char), primary key (id))" via JDBC Statement
```

**My Rundeck detail**

* Rundeck version: 3.3.0-PREVIEW2
* install type: WAR
* OS Name/version: Ubuntu 20.04
* DB Type/version: Oracle 18c (tested with Oracle OJDBC7 and OJDBC8 dialects).

**To Reproduce**
1. Configure Rundeck 3.3.0-PREVIEW2 with Oracle following [this](https://docs.rundeck.com/docs/administration/configuration/database/oracle.html#using-oracle-as-a-database-backend).
2. Start Rundeck.
3. Check the warnings on `service.log` output.

**Additional context**

Full-stack warnings:

```
Configuring Spring Security Core ...
... finished configuring Spring Security Core

[2020-06-15T18:24:55,690] WARN  org.hibernate.orm.cache2 - HHH90001006: Missing cache[default-update-timestamps-region] was created on-the-fly. The created cache will use a provider-specific default configuration: make sure you defined one. You can disable this warning by setting 'hibernate.cache.ehcache.missing_cache_strategy' to 'create'.
[2020-06-15T18:24:55,848] WARN  org.hibernate.orm.cache2 - HHH90001006: Missing cache[default-query-results-region] was created on-the-fly. The created cache will use a provider-specific default configuration: make sure you defined one. You can disable this warning by setting 'hibernate.cache.ehcache.missing_cache_strategy' to 'create'.
[2020-06-15T18:24:56,553] WARN  org.hibernate.orm.cache2 - HHH90001006: Missing cache[rundeck.Storage] was created on-the-fly. The created cache will use a provider-specific default configuration: make sure you defined one. You can disable this warning by setting 'hibernate.cache.ehcache.missing_cache_strategy' to 'create'.
[2020-06-15T18:24:56,567] WARN  org.hibernate.orm.cache2 - HHH90001006: Missing cache[rundeck.db.login.LoginRole] was created on-the-fly. The created cache will use a provider-specific default configuration: make sure you defined one. You can disable this warning by setting 'hibernate.cache.ehcache.missing_cache_strategy' to 'create'.
[2020-06-15T18:24:59,363] WARN  org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl2 - GenerationTarget encountered exception accepting command : Error executing DDL "create table calendar (id number(19,0) not null, version number(19,0) not null, level varchar2(7 char) not null, date_created timestamp not null, all_reference number(1,0) not null, last_updated timestamp not null, date_definition_json clob not null, enable number(1,0) not null, calendar_type varchar2(8 char) not null, json_data clob, date_type varchar2(7 char) not null, recurrent number(1,0) not null, name varchar2(255 char) not null, description clob, project varchar2(255 char), primary key (id))" via JDBC Statement
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table calendar (id number(19,0) not null, version number(19,0) not null, level varchar2(7 char) not null, date_created timestamp not null, all_reference number(1,0) not null, last_updated timestamp not null, date_definition_json clob not null, enable number(1,0) not null, calendar_type varchar2(8 char) not null, json_data clob, date_type varchar2(7 char) not null, recurrent number(1,0) not null, name varchar2(255 char) not null, description clob, project varchar2(255 char), primary key (id))" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:559) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:504) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.createTable(AbstractSchemaMigrator.java:277) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:71) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:207) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:114) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:183) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:309) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:287) ~[grails-datastore-gorm-hibernate5-7.0.3.RELEASE.jar!/:?]
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86) ~[grails-datastore-gorm-hibernate5-7.0.3.RELEASE.jar!/:?]
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39) ~[grails-datastore-gorm-hibernate5-7.0.3.RELEASE.jar!/:?]
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23) ~[grails-datastore-gorm-hibernate5-7.0.3.RELEASE.jar!/:?]
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64) ~[grails-datastore-core-7.0.4.RELEASE.jar!/:?]
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52) ~[grails-datastore-core-7.0.4.RELEASE.jar!/:?]
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24) ~[grails-datastore-core-7.0.4.RELEASE.jar!/:?]
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:212) ~[grails-datastore-gorm-hibernate5-7.0.3.RELEASE.jar!/:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_252]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_252]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1340) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1186) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:303) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:676) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:188) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1340) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1186) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:990) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:864) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:574) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:520) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:483) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:227) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1419) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1218) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1320) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1159) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) [spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) [spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:228) [spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:721) [spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534) [spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:96) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:456) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:443) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-4.0.3.jar!/:4.0.3]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) [groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.Application.main(Application.groovy:28) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [rundeckpro-enterprise-3.3.0-preview2-20200610.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [rundeckpro-enterprise-3.3.0-preview2-20200610.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [rundeckpro-enterprise-3.3.0-preview2-20200610.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [rundeckpro-enterprise-3.3.0-preview2-20200610.war:?]
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: : invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:210) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:30) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:931) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1792) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1745) ~[ojdbc7.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:334) ~[ojdbc7.jar:12.1.0.2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-9.0.31.jar!/:?]
	at com.sun.proxy.$Proxy120.execute(Unknown Source) ~[?:?]
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	... 84 more
[2020-06-15T18:25:03,426] WARN  org.springframework.beans.GenericTypeAwarePropertyDescriptor2 - Invalid JavaBean property 'exceptionMappings' being accessed! Ambiguous write methods found next to actually used [public void grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler.setExceptionMappings(java.util.List)]: [public void org.springframework.security.web.authentication.ExceptionMappingAuthenticationFailureHandler.setExceptionMappings(java.util.Map)]
[2020-06-15T18:25:10,291] DEBUG rundeck.interceptors.AuditInterceptor2 - Audit Interceptor Init
[2020-06-15T18:25:10,294] DEBUG rundeck.interceptors.AuditInterceptor2 - Audit Interceptor initialized. ProjectNotify: 1800000 CacheRetention: 1800000
[2020-06-15T18:25:16,196] INFO  rundeckapp.BootStrap2 - Starting RUNDECK ENTERPRISE 3.3.0-preview2-20200610 (2020-06-10) ...
[2020-06-15T18:25:16,196] INFO  rundeckapp.BootStrap2 - using rdeck.base config property: /home/m68k/Rundeck/testing/3.3.0-P2
[2020-06-15T18:25:16,218] INFO  rundeckapp.BootStrap2 - loaded configuration: /home/m68k/Rundeck/testing/3.3.0-P2/etc/framework.properties
[2020-06-15T18:25:16,225] WARN  rundeckapp.BootStrap2 - Cluster mode enabled, this server's UUID: 33d1d276-939e-440c-a7ed-3bb5cdae69c1
[2020-06-15T18:25:17,028] INFO  rundeckapp.BootStrap2 - RSS feeds disabled
[2020-06-15T18:25:17,028] INFO  rundeckapp.BootStrap2 - Using builtin realm authentication
[2020-06-15T18:25:17,028] INFO  rundeckapp.BootStrap2 - Preauthentication is disabled
[2020-06-15T18:25:17,139] INFO  rundeckapp.BootStrap2 - workflowConfigFix973: applying... 
[2020-06-15T18:25:17,155] INFO  rundeckapp.BootStrap2 - workflowConfigFix973: No fix was needed. Storing fix application state.
[2020-06-15T18:25:17,303] INFO  rundeckapp.BootStrap2 - Rundeck is ACTIVE: executions can be run.
[2020-06-15T18:25:17,600] INFO  rundeckapp.BootStrap2 - Rundeck startup finished in 1570ms
[2020-06-15T18:25:17,736] INFO  rundeckapp.Application2 - Started Application in 51.167 seconds (JVM running for 54.758)
Grails application running at http://hyperion:4440 in environment: production
[2020-06-15T18:25:54,411] DEBUG grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter2 - Request is to process authentication
[2020-06-15T18:25:54,826] DEBUG grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter2 - Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@ffc9140f: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: admin,user; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@0: RemoteIpAddress: 127.0.0.1; SessionId: node01jpjoimhtxul5meg6o9h4383e0; Granted Authorities: admin, user
[2020-06-15T18:25:55,061] DEBUG rundeck.interceptors.SetUserInterceptor2 - Empty role list from bean containerRoleSource for admin
[2020-06-15T18:25:55,074] DEBUG rundeck.interceptors.SetUserInterceptor2 - Accepting user role list from bean containerPrincipalRoleSource for admin: [admin, user]
[2020-06-15T18:25:55,074] DEBUG rundeck.interceptors.SetUserInterceptor2 - Role source not enabled, bean preauthenticatedAttributeRoleSource
[2020-06-15T18:25:56,628] DEBUG rundeck.interceptors.ApiAccessInterceptor2 - Disallowing API access, blocked due to request for plugin/pluginFile
[2020-06-15T18:26:01,411] WARN  org.grails.config.NavigableMapConfig2 - A plugin or your application called the flatten() method which can degrade startup performance
```

**Comment by jplassnibatt** [comment]
Debug output, rundeck 3.3.0-preview2, oracle db:12.2.0.1.- for when calendar section is selected (top right icon).

[debug.txt](https://github.com/rundeck/rundeck/files/4787168/debug.txt)

**Comment by MegaDrive68k** [comment]
Confirmed on Oracle 18c.

[error18c.txt](https://github.com/rundeck/rundeck/files/4787187/error18c.txt)

**Comment by MegaDrive68k** [comment]
Moved to: https://github.com/rundeckpro/enterprise-calendars/issues/33
