### ISSUE TITLE
Could not initialize class com.rundeck.plugins.aws.S3Base when use AWS S3 remote model source

### ISSUE THREAD

**Issue by pdanchak** [rundeck/rundeck#6361]
AWS S3 remote model source

```
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:337) [groovy-2.5.6.jar!/:2.5.6]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) [groovy-2.5.6.jar!/:2.5.6]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) [groovy-2.5.6.jar!/:2.5.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) [groovy-2.5.6.jar!/:2.5.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176) [groovy-2.5.6.jar!/:2.5.6]
        at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy:147) [classes!/:?]
        at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
        at groovy.lang.Closure.call(Closure.java:405) [groovy-2.5.6.jar!/:2.5.6]
        at groovy.lang.Closure.call(Closure.java:399) [groovy-2.5.6.jar!/:2.5.6]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_262]
        at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:275) [spring-cor
e-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
**Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.rundeck.plugins.aws.S3Base
        at com.rundeck.plugins.aws.S3ResourceModelSource.createResourceModelSource(S3ResourceModelSource.java:160) ~[?:?]
        at** com.dtolabs.rundeck.core.resources.ResourceModelSourceFactory.createResourceModelSource(ResourceModelSourceFactory.java:55) ~[rundeck
-core-3.3.2-20200727.jar!/:?]
        at com.dtolabs.rundeck.core.resources.ResourceModelSourceService$2.apply(ResourceModelSourceService.java:174) ~[rundeck-core-3.3.2-20200
727.jar!/:?]
        at com.dtolabs.rundeck.core.resources.ResourceModelSourceService$2.apply(ResourceModelSourceService.java:170) ~[rundeck-core-3.3.2-20200
727.jar!/:?]
        at com.dtolabs.rundeck.core.plugins.CloseableProvider.convert(CloseableProvider.java:43) ~[rundeck-core-3.3.2-20200727.jar!/:?]
        at com.dtolabs.rundeck.core.plugins.CloseableProvider$convert.call(Unknown Source) ~[?:?]
        at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy:244) ~[classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
```

**Comment by MegaDrive68k** [comment]
Confirmed,

I saw the same error on 3.3.2-SNAPSHOT too:

```
[2020-08-12T15:56:32,530] ERROR common.ProjectNodeSupport - Failed loading resource model source #3 in project ProjectEXAMPLE, skipping: java.lang.NoClassDefFoundError: Could not initialize class com.rundeck.plugins.aws.S3Base
com.dtolabs.rundeck.core.execution.service.ExecutionServiceException: java.lang.NoClassDefFoundError: Could not initialize class com.rundeck.plugins.aws.S3Base
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.loadResourceModelSource(ProjectNodeSupport.java:500) ~[rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.loadResourceModelSources(ProjectNodeSupport.java:286) [rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getResourceModelSourcesInternal(ProjectNodeSupport.java:227) [rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:137) [rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:359) [rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:58) [rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source) [rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44) [classes!/:?]
	at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source) [classes!/:?]
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:313) [classes!/:?]
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) [groovy-2.5.6.jar!/:2.5.6]
	at com.codahale.metrics.Timer.time(Timer.java:104) [metrics-core-4.0.7.jar!/:4.0.7]
	at sun.reflect.GeneratedMethodAccessor393.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:188) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) [groovy-2.5.6.jar!/:2.5.6]
	at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:60) [metricsweb-3.3.2-SNAPSHOT.jar!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:179) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:103) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService.loadNodes(NodeService.groovy:325) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:94) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy) [classes!/:?]
	at rundeck.services.NodeService$3.methodMissing(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService$3.invokeMethod(NodeService.groovy) [classes!/:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:337) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy:147) [classes!/:?]
	at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) [groovy-2.5.6.jar!/:2.5.6]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:275) [spring-core-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.rundeck.plugins.aws.S3Base
	at com.rundeck.plugins.aws.S3ResourceModelSource.createResourceModelSource(S3ResourceModelSource.java:160) ~[?:?]
	at com.dtolabs.rundeck.core.resources.ResourceModelSourceFactory.createResourceModelSource(ResourceModelSourceFactory.java:55) ~[rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ResourceModelSourceService$2.apply(ResourceModelSourceService.java:174) ~[rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ResourceModelSourceService$2.apply(ResourceModelSourceService.java:170) ~[rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.plugins.CloseableProvider.convert(CloseableProvider.java:43) ~[rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	at com.dtolabs.rundeck.core.plugins.CloseableProvider$convert.call(Unknown Source) ~[?:?]
	at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy:244) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor1115.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122) ~[groovy-2.5.6.jar!/:2.5.6]
	at com.sun.proxy.$Proxy34.apply(Unknown Source) ~[?:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.loadResourceModelSource(ProjectNodeSupport.java:498) ~[rundeck-core-3.3.2-SNAPSHOT.jar!/:?]
	... 83 more
```

Works fine on 3.2.9.

Thanks for your feedback @pdanchak!

**Comment by gschueler** [comment]
fix here https://github.com/rundeck-plugins/aws-s3-model-source/pull/9
