### ISSUE TITLE
Java Class issue after upgrade to 3.3.2

### ISSUE THREAD

**Issue by dcarrion87** [rundeck/rundeck#6405]
**Describe the bug**

Rundeck will not start after upgrade from 3.2.8 to 3.3.2 using rpm

**My Rundeck detail**

* Rundeck version: rundeck-3.3.2
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: N/A

**To Reproduce**

using Repo at https://dl.bintray.com/rundeck/rundeck-rpm/

`yum update rundeck`

Following error encountered on start. Downgrading back to 3.2.8 resolves issue.

```
[2020-08-26T09:36:18,011] WARN  context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script1598434577879374386665.groovy: 3: unable to resolve class ch.qos.logback.classic.Level
 @ line 3, column 1.
   import ch.qos.logback.classic.Level
   ^

script1598434577879374386665.groovy: 2: unable to resolve class ch.qos.logback.classic.LoggerContext
 @ line 2, column 1.
   import ch.qos.logback.classic.LoggerContext
   ^

2 errors

[2020-08-26T09:36:18,081] ERROR boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script1598434577879374386665.groovy: 3: unable to resolve class ch.qos.logback.classic.Level
 @ line 3, column 1.
   import ch.qos.logback.classic.Level
   ^

script1598434577879374386665.groovy: 2: unable to resolve class ch.qos.logback.classic.LoggerContext
 @ line 2, column 1.
   import ch.qos.logback.classic.LoggerContext
   ^

2 errors

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]

```

**Expected behavior**

Rundeck should start

**Comment by sjrd218** [comment]
@dcarrion87 Do you have a rundeck-config.groovy that contains imports for logback classes?

**Comment by dcarrion87** [comment]
I do. It was added for debugging auth related issues

```
import org.slf4j.LoggerFactory
import ch.qos.logback.classic.LoggerContext
import ch.qos.logback.classic.Level

LoggerContext loggerContext = (LoggerContext)LoggerFactory.getILoggerFactory();
loggerContext.getLogger("org.rundeck.security.RundeckPreauthenticationRequestHeaderFilter").setLevel(Level.INFO)

```

**Comment by sjrd218** [comment]
You can remove that now. All logging in the system has been converted to log4j2. You can set all logs using the log4j2.properties file.

When you upgrade, be sure to remove any old plugins from the libext folder that use old log4j or logback classes.
