### ISSUE TITLE
ldaps auth not working with self signded cert

### ISSUE THREAD

**Issue by flynn1973** [rundeck/rundeck#6448]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: 3.3.3.20200910
* install type: rpm
* OS Name/version: RedHat EL 7.8
* DB Type/version: postgresql 10

**To Reproduce**
i gathered the cert from the openldap server with openssl s_client and imported it with keytool

```
 root@lpgaixmgmtlx01:/var/log/rundeck>keytool -list -keystore /etc/rundeck/ssl/truststore -storepass somepass
Keystore type: jks
Keystore provider: SUN

Your keystore contains 1 entry

itsv_ldap, Sep 15, 2020, trustedCertEntry,
Certificate fingerprint (SHA1): 9D:84:X:X:X:X:X
```
error:

```
2020-09-15T14:54:38,151] INFO  rundeckapp.BootStrap - Starting Rundeck 3.3.3-20200910 (2020-09-10) ...
[2020-09-15T14:54:38,152] INFO  rundeckapp.BootStrap - using rdeck.base config property: /var/lib/rundeck
[2020-09-15T14:54:38,165] INFO  rundeckapp.BootStrap - loaded configuration: /etc/rundeck/framework.properties
[2020-09-15T14:54:38,209] INFO  rundeckapp.BootStrap - RSS feeds disabled
[2020-09-15T14:54:38,210] INFO  rundeckapp.BootStrap - Using jaas authentication
[2020-09-15T14:54:38,215] INFO  rundeckapp.BootStrap - Preauthentication is disabled
[2020-09-15T14:54:38,718] INFO  rundeckapp.BootStrap - Rundeck is ACTIVE: executions can be run.
[2020-09-15T14:54:38,991] INFO  rundeckapp.BootStrap - Rundeck startup finished in 1003ms
[2020-09-15T14:54:39,109] INFO  rundeckapp.Application - Started Application in 39.969 seconds (JVM running for 43.27)
Grails application running at http://lpgaixmgmtlx01.my.domain:4440 in environment: production
[2020-09-15T14:55:03,315] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Request is to process authentication
[2020-09-15T14:55:03,426] ERROR jaas.JettyCachingLdapLoginModule - Naming error
javax.naming.CommunicationException: ldap.my.domaint:636
...
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450) ~[?:1.8.0_252]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317) ~[?:1.8.0_252]
        at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_252]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330) ~[?:1.8.0_252]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237) ~[?:1.8.0_252]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113) ~[?:1.8.0_252]
        at com.dtolabs.rundeck.jetty.jaas.HostnameVerifyingTrustManager.checkServerTrusted(HostnameVerifyingTrustManager.java:74) ~[classes!/:?]
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1099) ~[?:1.8.0_252]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670) ~[?:1.8.0_252]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226) ~[?:1.8.0_252]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082) ~[?:1.8.0_252]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400) ~[?:1.8.0_252]
        at com.sun.jndi.ldap.Connection.createSocket(Connection.java:391) ~[?:1.8.0_252]
        at com.sun.jndi.ldap.Connection.<init>(Connection.java:213) ~[?:1.8.0_252]
...
[2020-09-15T14:55:03,446] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Authentication request failed: org.springframework.security.authentication.AuthenticationServiceException: java.lang.IllegalStateException: Unable to establish root context: ldap.my.domain:636
...
[2020-09-15T14:55:03,451] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Updated SecurityContextHolder to contain null Authentication
[2020-09-15T14:55:03,451] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Delegating to authentication failure handler grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler@7315264e
```
everything works without ldaps...

```
[2020-09-15T15:18:29,051] INFO  rundeckapp.BootStrap - Starting Rundeck 3.3.3-20200910 (2020-09-10) ...
[2020-09-15T15:18:29,052] INFO  rundeckapp.BootStrap - using rdeck.base config property: /var/lib/rundeck
[2020-09-15T15:18:29,065] INFO  rundeckapp.BootStrap - loaded configuration: /etc/rundeck/framework.properties
[2020-09-15T15:18:29,114] INFO  rundeckapp.BootStrap - RSS feeds disabled
[2020-09-15T15:18:29,114] INFO  rundeckapp.BootStrap - Using jaas authentication
[2020-09-15T15:18:29,120] INFO  rundeckapp.BootStrap - Preauthentication is disabled
[2020-09-15T15:18:29,686] INFO  rundeckapp.BootStrap - Rundeck is ACTIVE: executions can be run.
[2020-09-15T15:18:29,932] INFO  rundeckapp.BootStrap - Rundeck startup finished in 1032ms
[2020-09-15T15:18:30,051] INFO  rundeckapp.Application - Started Application in 48.827 seconds (JVM running for 52.689)
Grails application running at http://lpgaixmgmtlx01.my.domain:4440 in environment: production
[2020-09-15T15:18:47,601] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Request is to process authentication
[2020-09-15T15:18:47,632] INFO  jaas.JettyCachingLdapLoginModule - Login attempts: 1, Hits: 0, Ratio: 0%.
[2020-09-15T15:18:47,638] DEBUG jaas.JettyCachingLdapLoginModule - Found user?: true
[2020-09-15T15:18:47,638] DEBUG jaas.JettyCachingLdapLoginModule - Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: ou=users,ou=aix,ou=apps,dc=my,dc=domain
[2020-09-15T15:18:47,640] DEBUG jaas.JettyCachingLdapLoginModule - Found user?: true
[2020-09-15T15:18:47,641] DEBUG jaas.JettyCachingLdapLoginModule - user cred is present: true
[2020-09-15T15:18:47,646] DEBUG jaas.JettyCachingLdapLoginModule - JettyCachingLdapLoginModule: User 'pennywise' has roles: [aix_staff]
[2020-09-15T15:18:48,174] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.authentication.jaas.JaasAuthenticationToken@3397d150: Principal: pennywise; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@0: RemoteIpAddress: 1.2.3.4; SessionId: null; Granted Authorities: Jaas Authority [aix_staff,aix_staff]
```

**Expected behavior**
working login via ldaps

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 78.2.0 ESR

**Additional context**
none

**Comment by flynn1973** [comment]
the tip from https://github.com/rundeck/rundeck/issues/6268 solved the issue, i could not find this info in the offical config guide. maybe this should be added.

/etc/sysconfig/rundeckd

`-Djavax.net.ssl.trustStore=/etc/rundeck/ssl/truststore"`
