### ISSUE TITLE
Add an account in /etc/rundeck/realm.properties can't hotReload properly

### ISSUE THREAD

**Issue by pizza0223** [rundeck/rundeck#6468]
Describe the bug

My Rundeck detail

Rundeck version: 3.3.2
install type: yum
OS Name/version: CentOS 7
DB Type/version: postgresql
To Reproduce

vi open /etc/rundeck/realm.properties

add a ldap account like:
xxx: -,user,admin

save it and exit.

Expected behavior
I use account "xxx" and its ldap password can login and see all projects if xxx have privileges about these projects.

Screenshots

Desktop (please complete the following information):

OS: MacOS 10.15.6
Browser: chrome
Version:
Additional context
There are some logs about this.
[2020-09-21T16:35:56,871] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Request is to process authentication
[2020-09-21T16:35:56,873] DEBUG pam.AbstractPamLoginModule - PAM authentication trying (sshd) for: xxx
[2020-09-21T16:35:56,990] DEBUG pam.AbstractPamLoginModule - PAM authentication succeeded for: xxx
AbstractSharedLoginModule: login with sharedLoginState auth, try? false, use? true
ReloadablePropertyFileLoginModule: Checking PropertyUserStore /etc/rundeck/realm.properties for xxx
ReloadablePropertyFileLoginModule: Found: xxx in PropertyUserStore /etc/rundeck/realm.properties
JettyRolePropertyFileLoginModule: userInfo found for xxx? true
AbstractSharedLoginModule: using login result: true
role names: [user, admin]
[2020-09-21T16:35:57,004] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.authentication.jaas.JaasAuthenticationToken@6d3be7c4: Principal: xxx; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@2eb76: RemoteIpAddress: 127.0.0.1; SessionId: node01kuc9spwzucpc1592he6pog4652; Granted Authorities: Jaas Authority [readonly,readonly], Jaas Authority [user,user], Jaas Authority [admin,admin]
[2020-09-21T16:44:05,094] WARN security.PropertyUserStore -
java.nio.file.AccessDeniedException: /etc/rundeck/realm.properties
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_232]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_232]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_232]
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_232]
at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_232]
at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_232]
at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_232]
at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_232]
at org.eclipse.jetty.util.resource.PathResource.getInputStream(PathResource.java:421) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
at org.eclipse.jetty.security.PropertyUserStore.loadUsers(PropertyUserStore.java:248) ~[jetty-security-9.4.26.v20200117.jar!/:9.4.26.v20200117]
at org.eclipse.jetty.security.PropertyUserStore.onPathWatchEvent(PropertyUserStore.java:326) [jetty-security-9.4.26.v20200117.jar!/:9.4.26.v20200117]
at org.eclipse.jetty.util.PathWatcher.notifyEvents(PathWatcher.java:1366) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
at org.eclipse.jetty.util.PathWatcher.run(PathWatcher.java:1170) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

any ideas?

**Comment by MegaDrive68k** [comment]
Hi @pizza0223 

You did configure `jaas-loginmodule.conf` file (usually at `/etc/rundeck` path) to allow hot reload? Take a look at [this](https://docs.rundeck.com/docs/administration/security/authentication.html#hot-reloading-the-realm-properties-file).

Hope it helps!

**Comment by pizza0223** [comment]
Hi @MegaDrive68k 
Yes, I had been setting this configuation file before, my conf file is as follows:

RDpropertyfilelogin {
org.rundeck.jaas.jetty.JettyPamLoginModule requisite
debug="true"
service="sshd"
supplementalRoles="readonly"
storePass="true";

org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
debug="true"
useFirstPass="true"
caseInsensitive="false"
hotReload="true"
file="/etc/rundeck/realm.properties";

};

**Comment by MegaDrive68k** [comment]
You need to use:

`org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule` instead of `org.eclipse.jetty.jaas.spi.PropertyFileLoginModule`.

Can you test it? Check [this](https://docs.rundeck.com/docs/administration/security/authentication.html#hot-reloading-the-realm-properties-file), please.

Regards!

**Comment by MegaDrive68k** [comment]
Hi @pizza0223 

Use [that](https://github.com/rundeck/rundeck/issues/6468#issuecomment-696122005) parameter on [multiauth](https://docs.rundeck.com/docs/administration/security/authentication.html#multiple-authentication-modules) configuration.

**Comment by MegaDrive68k** [comment]
I did a test and works in this way.

`jaas-loginmodule.conf` file content:

```
RDpropertyfilelogin {
org.rundeck.jaas.jetty.JettyPamLoginModule requisite
debug="true"
service="sshd"
supplementalRoles="readonly"
storePass="true";

org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
debug="true"
refreshInterval="10"
hotReload="true"
file="/path/to/your/realm.properties";
};
```

Sorry for the (deleted) comment, I reopened the issue :)

Greetings!

**Comment by pizza0223** [comment]
Hi,

If I use this configuration in my jaas-loginmodule.conf but it takes no effect.
And then, my ldap account (xxx) can't login rundeck.

The following is my service.log.

[2020-09-21T23:30:37,275] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Request is to process authentication
[2020-09-21T23:30:37,302] DEBUG pam.AbstractPamLoginModule - PAM authentication trying (sshd) for: xxx
[2020-09-21T23:30:37,652] DEBUG pam.AbstractPamLoginModule - PAM authentication succeeded for: xxx
ReloadablePropertyFileLoginModule: setupPropertyUserStore: Starting new PropertyUserStore. PropertiesFile: /etc/rundeck/realm.properties refreshInterval: 10
ReloadablePropertyFileLoginModule: Checking PropertyUserStore /etc/rundeck/realm.properties for xxx
ReloadablePropertyFileLoginModule: Found: xxx in PropertyUserStore /etc/rundeck/realm.properties
[2020-09-21T23:30:37,724] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Authentication request failed: org.springframework.security.authentication.AuthenticationServiceException
org.springframework.security.authentication.AuthenticationServiceException: null
    at org.springframework.security.authentication.jaas.DefaultLoginExceptionResolver.resolveException(DefaultLoginExceptionResolver.java:35) ~[spring-security-core-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.authentication.jaas.AbstractJaasAuthenticationProvider.authenticate(AbstractJaasAuthenticationProvider.java:217) ~[spring-security-core-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175) ~[spring-security-core-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter.attemptAuthentication(GrailsUsernamePasswordAuthenticationFilter.groovy:53) ~[spring-security-core-4.0.2.jar!/:?]
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64) ~[spring-security-core-4.0.2.jar!/:?]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58) ~[spring-security-core-4.0.2.jar!/:?]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77) ~[grails-web-mvc-4.0.3.jar!/:4.0.3]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77) ~[grails-web-mvc-4.0.3.jar!/:4.0.3]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67) ~[grails-web-mvc-4.0.3.jar!/:4.0.3]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114) ~[spring-boot-actuator-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
    at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104) ~[spring-boot-actuator-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590) ~[jetty-security-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) ~[jetty-servlet-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.Server.handle(Server.java:500) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) [jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) [jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: javax.security.auth.login.FailedLoginException
    at org.eclipse.jetty.jaas.spi.AbstractLoginModule.login(AbstractLoginModule.java:270) ~[jetty-jaas-9.4.26.v20200117.jar!/:9.4.26.v20200117]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
    at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_232]
    at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_232]
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_232]
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_232]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_232]
    at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_232]
    at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_232]
    at org.springframework.security.authentication.jaas.AbstractJaasAuthenticationProvider.authenticate(AbstractJaasAuthenticationProvider.java:180) ~[spring-security-core-5.1.11.RELEASE.jar!/:5.1.11.RELEASE]
    ... 61 more
[2020-09-21T23:30:37,747] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Updated SecurityContextHolder to contain null Authentication
[2020-09-21T23:30:37,747] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Delegating to authentication failure handler grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler@14501070

**Comment by MegaDrive68k** [comment]
Hi @pizza0223 

To use LDAP + local users (`realm.properties` file) you need to combine both modules following [this](https://docs.rundeck.com/docs/administration/security/authentication.html#multiple-authentication-modules).

Regards.
