### ISSUE TITLE
Error loading class after upgrading to rundeck >= 3.3.0

### ISSUE THREAD

**Issue by wep-p** [rundeck/rundeck#6503]
**Describe the bug**
After upgrading to Rundeck >= 3.3.0, every job produces the same error in the "Prepare Workspace" workflow step: 

`com.dtolabs.rundeck.core.plugins.PluginException: Error loading class: org.rundeck.plugin.encryption.JasyptEncryptionConverterPlugin
	at com.dtolabs.rundeck.core.plugins.JarPluginProviderLoader.loadClass(JarPluginProviderLoader.java:440)
	at com.dtolabs.rundeck.core.plugins.JarPluginProviderLoader.isLoaderFor(JarPluginProviderLoader.java:579)
	at com.dtolabs.rundeck.core.plugins.DirPluginScanner.test(DirPluginScanner.java:189)
	at com.dtolabs.rundeck.core.plugins.DirPluginScanner.scanFor(DirPluginScanner.java:156)
	at com.dtolabs.rundeck.core.plugins.DirPluginScanner.scanForFile(DirPluginScanner.java:109)
	at com.dtolabs.rundeck.core.plugins.FilePluginCache.rescanForItem(FilePluginCache.java:147)
	at com.dtolabs.rundeck.core.plugins.FilePluginCache.getLoaderForIdent(FilePluginCache.java:110)
	at com.dtolabs.rundeck.core.plugins.PluginManagerService.loadProvider(PluginManagerService.java:142)
	at com.dtolabs.rundeck.core.plugins.BasePluggableProviderService.providerOfType(BasePluggableProviderService.java:75)
	at com.dtolabs.rundeck.core.plugins.AdapterService.providerOfType(AdapterService.java:51)
	at com.dtolabs.rundeck.core.plugins.ChainedProviderService.providerOfType(ChainedProviderService.java:49)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepExecutionService.getExecutorForExecutionItem(NodeStepExecutionService.java:239)
	at com.dtolabs.rundeck.core.common.ServiceSupport.getNodeStepExecutorForItem(ServiceSupport.java:146)
	at com.dtolabs.rundeck.core.common.FrameworkBase.getNodeStepExecutorForItem(FrameworkBase.java:173)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:134)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:130)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:61)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:262)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:233)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:111)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:287)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:683)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:76)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:32)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$beginOperation$2(WorkflowEngineOperationsProcessor.java:330)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.rundeck.plugin.encryption.JasyptEncryptionConverterPlugin
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.dtolabs.rundeck.core.plugins.JarPluginProviderLoader.loadClass(JarPluginProviderLoader.java:435)
	... 32 more`

The jobs worked without errors in the previous versions <= 3.2.8. They still work and produce the wanted results, but the users are pretty irritated by the wall of red error messages and often report failed jobs because of these. 

**My Rundeck detail**

Rundeck version: Rundeck 3.3.0/ 3.3.1/3.3.2
install type: war
OS Name/version: SLES12 SP5
DB Type/version: postgres

**To Reproduce**
1. Every run of a job produces this error. 

**Screenshots**

**Desktop:**
 - OS: Win 10
 - Browser  chrome, firefox

**Comment by sjrd218** [comment]
If you have any old versions of the jasypt encryption plugin in your libext directory you will need to remove them.

**Comment by wep-p** [comment]
@sjrd218 thank you! That resolved all errors
