### ISSUE TITLE
Fails to start with "Unable to load class: com.mysql.cj.jdbc.Driver"

### ISSUE THREAD

**Issue by liubinas** [rundeck/rundeck#6537]
**Describe the bug**
After upgrade to 3.3.4 Rundeck server fails to start. Issue is resolved when downgraded to 3.3.3

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.4]
* install type: [rpm]
* OS Name/version: [e.g. Centos 7]
* DB Type/version: [mysql]

**To Reproduce**
1. systemctl start rundeckd

**Expected behavior**
Rundeck starts

**Additional context**
[2020-10-08T09:20:08,296] ERROR pool.ConnectionPool - Unable to create initial connections of pool.
java.sql.SQLException: Unable to load class: com.mysql.cj.jdbc.Driver from ClassLoader:org.springframework.boot.loade
r.LaunchedURLClassLoader@5010be6;ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@5010be6
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:292) ~[tomcat-jdbc-9
.0.31.jar!/:?]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212) ~[tomcat-jdbc-9.0.31.jar!/
:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:744) ~[tomcat-jdbc-9.0.31.
jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:676) ~[tomcat-jdbc-9.0.31.
jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:483) ~[tomcat-jdbc-9.0.31.jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154) ~[tomcat-jdbc-9.0.31.jar!/:?]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118) ~[tomcat-jdbc-9.0.31.jar
!/:?]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107) ~[tomcat-jdbc-9.0.31.jar!
/:?]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131) ~[tomcat-jdbc-9.0.31.j
ar!/:?]

**Comment by MegaDrive68k** [comment]
Hi @liubinas 

That's because on 3.3.4, set the MariaDB driver for MySQL database, the driver is no longer available by default, please take a look at [this](https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.3.4.html#mysql).

Regards!
