### ISSUE TITLE
failed job cause rundeck to shutdown

### ISSUE THREAD

**Issue by halradaideh** [rundeck/rundeck#6539]
**Describe the bug**
when a specific job fail in my project, a shutdown signal is being fire causing rundeck to shutdown.

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: docker-container
* DB Type/version: mysql

**rundeck log**
```
[2020-10-07T11:11:29,333] ERROR services.ExecutionUtilService - Execution failed: 830 in project Rundeck: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [rundeck-server-server-dc855d557-qqmgc: NonZeroResultCode: Result code was 143 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:rundeck-server-server-dc855d557-qqmgc)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:rundeck-server-server-dc855d557-qqmgc)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, Node failures: {rundeck-server-server-dc855d557-qqmgc=[NonZeroResultCode: Result code was 143 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:rundeck-server-server-dc855d557-qqmgc)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:rundeck-server-server-dc855d557-qqmgc)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, status: failed]
[2020-10-07T11:11:30,046] INFO  execution.status admin finish [830:failed] Rundeck admin/- "Projects/Backup  -"[b8c1ac03-dedb-42d0-8d33-e59857cf3581] 
[2020-10-07T11:11:30,798] INFO  rundeckapp.BootStrap - Rundeck Shutdown detected
[2020-10-07T11:11:30,963] ERROR events.EventSubscriberTrigger - Error triggering event [executionComplete] for subscriber [grails.events.subscriber.MethodSubscriber(public java.lang.Object rundeck.services.ExecutionEventsService.executionComplete(rundeck.services.events.ExecutionCompleteEvent))]: Could not open Hibernate Session for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:581) ~[spring-orm-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.grails.orm.hibernate.GrailsHibernateTransactionManager.doBegin(GrailsHibernateTransactionManager.groovy:65) ~[grails-datastore-gorm-hibernate5-7.0.3.RELEASE.jar!/:?]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at rundeck.services.ExecutionEventsService.executionComplete(ExecutionEventsService.groovy) ~[classes!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor2156.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at grails.events.subscriber.MethodSubscriber.call(MethodSubscriber.groovy:51) ~[grails-events-4.0.0.jar!/:?]
	at org.grails.events.EventSubscriberTrigger.proceed(EventSubscriberTrigger.groovy:34) [grails-events-4.0.0.jar!/:?]
	at org.grails.events.bus.ExecutorEventBus$_buildNotificationCallable_closure1$_closure3.doCall(ExecutorEventBus.groovy:36) [grails-events-4.0.0.jar!/:?]
	at org.grails.events.bus.ExecutorEventBus$_buildNotificationCallable_closure1$_closure3.call(ExecutorEventBus.groovy) [grails-events-4.0.0.jar!/:?]
	at groovy.lang.Closure.run(Closure.java:486) [groovy-2.5.6.jar!/:2.5.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:530) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.internal.SessionFactoryImpl.getCache(SessionFactoryImpl.java:828) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.<init>(AbstractSharedSessionContract.java:143) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.internal.AbstractSessionImpl.<init>(AbstractSessionImpl.java:29) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.internal.SessionImpl.<init>(SessionImpl.java:257) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1288) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.hibernate.internal.SessionFactoryImpl.openSession(SessionFactoryImpl.java:481) ~[hibernate-core-5.4.0.Final.jar!/:5.4.0.Final]
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:464) ~[spring-orm-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	... 19 more
```

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome

**Comment by ThaSami** [comment]
+1

**Comment by halradaideh** [comment]
@gschueler  any thoughts ?

**Comment by fdevans** [comment]
Have you tried on the latest version?  Did you install fresh or upgrade from a previous version?  Can you share the job definition that is causing this? (omit sensitive data)

**Comment by halradaideh** [comment]
yes it is happening on rundeck 3.3.4
yes fresh installation ( the database is the same )

 `
<joblist>
<job>
<defaultTab>nodes</defaultTab>
<description/>
<executionEnabled>true</executionEnabled>
<group>Projects</group>
<id>b8c1ac03-dedb-42d0-8d33-e59857cf3581</id>
<loglevel>INFO</loglevel>
<name>Backup</name>
<nodeFilterEditable>false</nodeFilterEditable>
<plugins/>
<schedule>
<month month="*"/>
<time hour="5-16" minute="0" seconds="0"/>
<weekday day="*"/>
<year year="*"/>
</schedule>
<scheduleEnabled>true</scheduleEnabled>
<sequence keepgoing="false" strategy="node-first">
<command>
<script>
SCRIPT HERE
</script>
<scriptargs/>
</command>
</sequence>
<uuid>b8c1ac03-dedb-42d0-8d33-e59857cf3581</uuid>
</job>
</joblist>
`

**Comment by ProTip** [comment]
Hi @halradaideh ,

It looks to me like perhaps the job is failing _because_ Rundeck is getting shutdown. The stack trace is likely caused by a thread trying to use the database after the main thread has shut down hibernate.

Is it possible something is killing the pid 1 in the container? Perhaps the job is trying to cleanup processes when it finishes and is accidentally killing the server? Or maybe the container is getting killed externally for some reason?

**Comment by halradaideh** [comment]
@ProTip 

> Is it possible something is killing the pid 1 in the container?
if the PID 1 was killed in the container , Rundeck will not have time to shutdown, it will be terminated 

> Perhaps the job is trying to cleanup processes when it finishes and is accidentally killing the server?
the job is just backing up Rundeck, nothing fancy 

> Or maybe the container is getting killed externally for some reason?
might be
