### ISSUE TITLE
No signature of method rundeck.services.ExecutionService.lookupMessage()

### ISSUE THREAD

**Issue by elledido** [rundeck/rundeck#6596]
**Describe the bug**
Suddenly none of my scheduled jobs works anymore.
If I try to run anyone of the jobs I have, this error appears.

**NOTES:**
The error becomes to appear the 20th of October, after the last rundeck version update.

![rundeck_error](https://user-images.githubusercontent.com/6837518/97719745-be647200-1ac7-11eb-88d6-af35bd337dc5.PNG)

**My Rundeck detail**

* Rundeck version: 3.3.5
* OS Name/version: Ubuntu 16.04
* DB Type/version: postgres

**Comment by MegaDrive68k** [comment]
Hi @elledido 

What Rundeck version did you have before the 3.3.5 update? Is a DEB based or WAR based installation? Can you share the full `service.log` output to take a look? (usually at `/var/log/rundeck` path, please hide or change any potentially sensitive information).

Regards.

**Comment by elledido** [comment]
Hi @MegaDrive68k ,

The version I had before updating to 3.3.5 was the 3.3.4, a DEB based installation. So I removed the 3.3.5 version packet, reinstalled the 3.3.4 version packet and marked it as "hold" so it will not automatically update.
Now everything is working like before. I'll try to share the `service.log` file you requested tomorrow.
Thanks a lot.

Regards.

**Comment by cova-fe** [comment]
Hi, we are basically in the same situation, the only relevant difference is that we are using ubuntu 18.04.
Service logs shows the following:
[2020-11-18T17:08:00,210] ERROR listeners.ExceptionPrinterJobListener - Exception occurred in job: 
org.quartz.JobExecutionException: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: groovy.lang.MissingMethodException: No signature of method: rundeck.services.ExecutionService.lookupMessage() is applicable for argument types: ([Ljava.lang.String;, [Ljava.lang.Object;, String) values: [[rundeck.Execution.serverNodeUUID.maxSize.error.rundeck.Execution.serverNodeUUID, ...], ...]
Possible solutions: lookupMessage([Ljava.lang.String;, java.util.List, java.lang.String), lookupMessage([Ljava.lang.String;, java.util.List), lookupMessage(java.lang.String, java.util.List, java.lang.String), lookupMessage(java.lang.String, java.util.List)]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:218) [quartz-2.3.2.jar!/:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:?]
Caused by: org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.3.2.jar!/:?]
	... 1 more
Caused by: groovy.lang.MissingMethodException: No signature of method: rundeck.services.ExecutionService.lookupMessage() is applicable for argument types: ([Ljava.lang.String;, [Ljava.lang.Object;, String) values: [[rundeck.Execution.serverNodeUUID.maxSize.error.rundeck.Execution.serverNodeUUID, ...], ...]
Possible solutions: lookupMessage([Ljava.lang.String;, java.util.List, java.lang.String), lookupMessage([Ljava.lang.String;, java.util.List), lookupMessage(java.lang.String, java.util.List, java.lang.String), lookupMessage(java.lang.String, java.util.List)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:76) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.ExecutionService$__tt__int_createExecution_closure145.doCall(ExecutionService.groovy:2456) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor891.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3540) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3525) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3625) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.dgm$87.invoke(Unknown Source) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.ExecutionService.$tt__int_createExecution(ExecutionService.groovy:2456) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor696.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.ExecutionService$_int_createExecution_closure40.doCall(ExecutionService.groovy) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor693.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.6.jar!/:2.5.6]
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at rundeck.services.ExecutionService.int_createExecution(ExecutionService.groovy) ~[classes!/:?]
	at rundeck.services.ExecutionService$int_createExecution$4.callCurrent(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.ExecutionService$int_createExecution$4.callCurrent(Unknown Source) ~[?:?]
	at rundeck.services.ExecutionService.$pub__createExecution(ExecutionService.groovy:2532) ~[classes!/:?]
	at rundeck.services.ExecutionService.$tt__createExecution(ExecutionService.groovy) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor641.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.ExecutionService$_createExecution_closure42.doCall(ExecutionService.groovy) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor637.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.6.jar!/:2.5.6]
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at rundeck.services.ExecutionService.createExecution(ExecutionService.groovy) ~[classes!/:?]
	at rundeck.services.ExecutionService.createExecution(ExecutionService.groovy) ~[classes!/:?]
	at rundeck.quartzjobs.ExecutionJob.initialize(ExecutionJob.groovy:331) ~[classes!/:?]
	at rundeck.quartzjobs.ExecutionJob$initialize$1.callCurrent(Unknown Source) ~[?:?]
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:119) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor630.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:98) ~[classes!/:?]
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy) ~[classes!/:?]
	at sun.reflect.GeneratedMethodAccessor628.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.run(Closure.java:486) ~[groovy-2.5.6.jar!/:2.5.6]
	at com.codahale.metrics.Timer.time(Timer.java:137) ~[metrics-core-4.0.7.jar!/:4.0.7]
	at com.codahale.metrics.Timer$time$1.call(Unknown Source) ~[?:?]
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:97) ~[classes!/:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:?]
	... 1 more

**Comment by cova-fe** [comment]
Maybe this could be interesting as well. I noticed also a warning in service.log that could be related to the previous exception; it complains about a too long serverNodeUUID field (field content replaced by a string of the same length)

[2020-11-18T13:16:01,890] WARN  services.ExecutionService - Field error in object 'rundeck.Execution' on field 'serverNodeUUID': rejected value [12345678901234567890123456789012345678901234]; codes [rundeck.Execution.serverNodeUUID.maxSize.error.rundeck.Execution.serverNodeUUID,rundeck.Execution.serverNodeUUID.maxSize.error.serverNodeUUID,rundeck.Execution.serverNodeUUID.maxSize.error.java.lang.String,rundeck.Execution.serverNodeUUID.maxSize.error,execution.serverNodeUUID.maxSize.error.rundeck.Execution.serverNodeUUID,execution.serverNodeUUID.maxSize.error.serverNodeUUID,execution.serverNodeUUID.maxSize.error.java.lang.String,execution.serverNodeUUID.maxSize.error,rundeck.Execution.serverNodeUUID.maxSize.exceeded.rundeck.Execution.serverNodeUUID,rundeck.Execution.serverNodeUUID.maxSize.exceeded.serverNodeUUID,rundeck.Execution.serverNodeUUID.maxSize.exceeded.java.lang.String,rundeck.Execution.serverNodeUUID.maxSize.exceeded,execution.serverNodeUUID.maxSize.exceeded.rundeck.Execution.serverNodeUUID,execution.serverNodeUUID.maxSize.exceeded.serverNodeUUID,execution.serverNodeUUID.maxSize.exceeded.java.lang.String,execution.serverNodeUUID.maxSize.exceeded,maxSize.exceeded.rundeck.Execution.serverNodeUUID,maxSize.exceeded.serverNodeUUID,maxSize.exceeded.java.lang.String,maxSize.exceeded]; arguments [serverNodeUUID,class rundeck.Execution,12345678901234567890123456789012345678901234,36]; default message [Property [{0}] of class [{1}] with value [{2}] exceeds the maxim size of [{3}]]

**Comment by cova-fe** [comment]
Forgot to mention: this happens with 3.3.5 and 3.3.6 (logs are from deb package Installed: 3.3.6.20201111-1)

**Comment by cova-fe** [comment]
I tried to force the UUID in this way:
echo "rundeck.server.uuid="$(uuidgen) >> /etc/rundeck/framework.properties
And this seems to have fixed the issue, even though I need to do more test.

**Comment by Micsi** [comment]
I see this too from time to time for several months, well over a year now... I am on Debian 9 installed with puppet module using apt.

The rundeck.server.uuid is changed automatically from time to time to a value that does not work. The value relates to our virtualisation beeing Vmware. Sorry, I do not have an example at hand, but is a series of Hex values, separated by Strings and something with VMWare as well...
