### ISSUE TITLE
Startup failure of Rundeck v3.3.5 when using symbolic link to installation path

### ISSUE THREAD

**Issue by AchimW** [rundeck/rundeck#6605]
**Describe the bug**
We have installed Rundeck on the system in the directory `/data/rundeck/` and created a symbolic link with the name `rundeck` from `/var/lib/` to this directory. Until Rundeck 3.3.4 this is no problem, but with the update to Rundeck 3.3.5 with this type of installation Rundeck does not start.

Our current solution is that we set the base path of Rundeck directly to our installation directory `/data/rundeck/`. In fact it worked with previous versions of Rundeck, this seems to be a bug.

**My Rundeck detail**

* Rundeck version: 3.3.5
* install type: deb
* OS Name/version: Ubuntu 18.04.5 LTS
* DB Type/version: MariaDB / 10.4.15-MariaDB-1:10.4.15+maria~bionic-log

**To Reproduce**
1. Install Rundeck (e.g. Version 3.3.4) in a different location than /var/lib/rundeck
2. Create Symlink /var/lib/rundeck to installation path
3. Update Rundeck with `apt upgrade` to Version 3.3.5
4. Start/Restart Rundeck with `sudo service rundeckd start` or `sudo service rundeckd restart`
5. Rundeck startup fails with error `PreBootstrap process rundeckapp.init.prebootstrap.InitializeRundeckPreboostrap failed
java.nio.file.FileAlreadyExistsException: /var/lib/rundeck`

**Expected behavior**
It is expected that Rundeck follows the symbolic link to the current installation path. Instead the symbolic link is treated as a normal file.

**Screenshots**
Attached service log: [service.log](https://github.com/rundeck/rundeck/files/5487068/service.log)

**Comment by MegaDrive68k** [comment]
Confirmed following these steps:

1. Install Rundeck DEB 3.3.4.
2. Create a "custom directory" like `/rundeck`.
3. Move the content of `/var/lib/rundeck` on `/rundeck`.
4. Create a `/rundeck` symlink to `/var/lib/rundeck` doing `ln -s /rundeck /var/lib/rundeck`.
5. Start Rundeck service doing: `systemctl start rundeckd`. Rundeck starts normally, `service.log` content:

```
[2020-11-04T19:17:32,088] INFO  rundeckapp.BootStrap - Rundeck is ACTIVE: executions can be run.
[2020-11-04T19:17:32,261] WARN  rundeckapp.BootStrap - [Development Mode] Usage of H2 database is recommended only for development and testing
[2020-11-04T19:17:32,530] INFO  rundeckapp.BootStrap - workflowConfigFix973: applying... 
[2020-11-04T19:17:32,546] INFO  rundeckapp.BootStrap - workflowConfigFix973: No fix was needed. Storing fix application state.
[2020-11-04T19:17:32,857] INFO  rundeckapp.BootStrap - Rundeck startup finished in 1179ms
[2020-11-04T19:17:33,073] INFO  rundeckapp.Application - Started Application in 30.321 seconds (JVM running for 33.146)
Grails application running at http://localhost:4440 in environment: production
```

6. Stop the Rundeck service  doing: `systemctl stop rundeckd`.
7. Now upgrade to Rundeck 3.3.5 (or just put the 3.3.5 WAR on the `/rundeck/bootstrap/` path and delete the 3.3.4 WAR).
8. Start the Rundeck service and check the `service.log`, Rundeck fails with the following error:

```
PreBootstrap process rundeckapp.init.prebootstrap.InitializeRundeckPreboostrap failed
java.nio.file.FileAlreadyExistsException: /var/lib/rundeck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at rundeckapp.init.RundeckInitializer.initServerUuidWithFrameworkProps(RundeckInitializer.groovy:138)
	at rundeckapp.init.RundeckInitializer.initialize(RundeckInitializer.groovy:100)
	at rundeckapp.init.RundeckInitializer$initialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at rundeckapp.init.prebootstrap.InitializeRundeckPreboostrap.run(InitializeRundeckPreboostrap.groovy:30)
	at org.rundeck.app.bootstrap.PreBootstrap$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at rundeckapp.Application$_runPreboostrap_closure4.doCall(Application.groovy:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
	at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at rundeckapp.Application.runPreboostrap(Application.groovy:70)
	at rundeckapp.Application.main(Application.groovy:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
[2020-11-04T19:19:51,571] INFO  rundeckapp.Application - The following profiles are active: production
[2020-11-04T19:19:52,815] WARN  context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is java.lang.NullPointerException: Cannot get property 'realm.properties.location' on null object
[2020-11-04T19:19:52,831] ERROR boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is java.lang.NullPointerException: Cannot get property 'realm.properties.location' on null object
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1318) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:96) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:456) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:443) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-4.0.3.jar!/:4.0.3]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) [groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.Application.main(Application.groovy:32) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [rundeck-3.3.5-20201019.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [rundeck-3.3.5-20201019.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [rundeck-3.3.5-20201019.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [rundeck-3.3.5-20201019.war:?]
Caused by: java.lang.NullPointerException: Cannot get property 'realm.properties.location' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyObject$getProperty.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.Application.setEnvironment(Application.groovy:53) ~[classes!/:?]
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:105) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:96) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	... 37 more
```

Thanks for your feedback @AchimW!

**Comment by ramspoluri** [comment]
Ran into the same issue after upgrading to v3.3.5.

As workaround removed the symbolic link and did **bind mount** and the application started fine.
```
mount -B /opt/rundeck /var/lib/rundeck
```

**Comment by lokly** [comment]
Same issue with version 3.3.6

**Comment by xavier8854** [comment]
Thanks @ramspoluri , you saved my life ! Worls like a charm
Xavier

**Comment by reingit** [comment]
Same issue with rundeck_3.3.8.20210111-1_all.deb

**Comment by Daryes** [comment]
aside @ramspoluri solution, if I'm not mistaken, you can fix the null error without the bind by inserting this line in /etc/default/rundeckd :
`JAAS_CONF="/real/path/to/jaas-loginmodule.conf`
