### ISSUE TITLE
Rundeck cannot reach online plugin list via HTTP proxy with authentication

### ISSUE THREAD

**Issue by n3y** [rundeck/rundeck#6669]
**Bug description**
Hello.

In an environment where internet access is only possible via HTTP proxy with authentication,
I can't get Rundeck to reach & read the online plugin list.

Results of clicking "Plugins - Find Plugins" in GUI interface are :
- page does not show any plugis (0 plugins in repo)
- an error is produced in console output / logs

These are (shortened) examples of usual errors produced
(the slight difference is there just because I tried a different way or arguments to pass proxy configuration) :

```
[2020-12-10T21:49:44,420] ERROR manifest.RundeckOfficialManifestService - listArtifacts error
java.io.IOException: Failed to authenticate with proxy
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:418) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:236) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:177) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.7.jar!/:?]
        at okhttp3.Call$execute.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.6.jar!/:2.5.6]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.6.jar!/:2.5.6]
        at com.rundeck.repository.client.manifest.RundeckOfficialManifestService.listArtifacts(RundeckOfficialManifestService.groovy:97) ~[repository-client-0.12.0.jar!/:?]
. . .
```

```
[2020-12-08T22:26:36,029] ERROR manifest.RundeckOfficialManifestService - listArtifacts error
java.net.ConnectException: Failed to connect to api.rundeck.com/99.84.8.66:443
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.7.jar!/:?]
at okhttp3.Call$execute.call(Unknown Source) ~[?:?]
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.6.jar!/:2.5.6]
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.6.jar!/:2.5.6]
at com.rundeck.repository.client.manifest.RundeckOfficialManifestService.listArtifacts(RundeckOfficialManifestService.groovy:97) ~[repository-client-0.12.0.jar!/:?]
at com.rundeck.repository.manifest.ManifestService$listArtifacts$0.call(Unknown Source) ~[?:?]
. . .
```

I've tried several ways and their combinations to export/pass variables
containing proxy settings, but none fixed the issue so far :

```
# environment variables
ftp_proxy=...
FTP_PROXY=...
http_proxy=...
HTTP_PROXY=...
https_proxy=...
HTTPS_PROXY=...
export http_proxy https_proxy ftp_proxy no_proxy HTTP_PROXY HTTPS_PROXY FTP_PROXY NO_PROXY

# java options
-Dhttp.proxyHost=... -Dhttp.proxyPort=... -Dhttp.proxyUser=... -Dhttp.proxyPassword=... \
-Dhttps.proxyHost=... -Dhttps.proxyPort=... -Dhttps.proxyUser=... -Dhttps.proxyPassword=... \
-Dhttp.nonProxyHosts=... \

-Djava.net.useSystemProxies=true \

-Djdk.http.auth.tunneling.disabledSchemes="" \

-DproxySet=true \

-DproxyHost=... -DproxyPort=... -DproxyUsername=... -DproxyPassword=... \
```

For common OS utilities like "wget" or "curl", access to
"https://api.rundeck.com/repo/v1/oss/list" using the same HTTP proxy works OK :

```
$ https_proxy=http://pxuser:pxpass@pxnode:8012 wget -dv https://api.rundeck.com/repo/v1/oss/list
. . .
--2020-12-10 23:21:46--  https://api.rundeck.com/repo/v1/oss/list
Resolving pxnode (pxnode)... 158.169.131.13
Caching pxnode => 158.169.131.13
Connecting to pxnode (pxnode)|158.169.131.13|:8012... connected.
Created socket 3.
Releasing 0x0000000001a95fc0 (new refcount 1).
---request begin---
CONNECT api.rundeck.com:443 HTTP/1.1
User-Agent: Wget/1.14 (linux-gnu)
Proxy-Authorization: Basic abcdefghijklmnopqrstuvwxyz=
Host: api.rundeck.com:443
---request end---
proxy responded with: [HTTP/1.1 200 Connection established
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x0000000001aa4130
certificate:
  subject: /CN=api.rundeck.com
  issuer:  /C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
X509 certificate successfully verified and matches host api.rundeck.com
---request begin---
GET /repo/v1/oss/list HTTP/1.1
User-Agent: Wget/1.14 (linux-gnu)
Accept: */*
Host: api.rundeck.com
Connection: Close
Proxy-Connection: Keep-Alive
---request end---
Proxy request sent, awaiting response...
---response begin---
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 19671
Connection: close
Date: Thu, 10 Dec 2020 22:21:46 GMT
x-amzn-RequestId: 3f85386f-e3ab-4fca-a43a-7a0ff7c7dfc7
Access-Control-Allow-Origin: *
x-amz-apigw-id: XW3bOFb4PHcFwJg=
X-Amzn-Trace-Id: Root=1-5fd29f7a-2fb405ca71a074e802a82571;Sampled=0
X-Cache: Miss from cloudfront
Via: 1.1 001d2c0e1017c442fd79b22841d53218.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LHR62-C2
X-Amz-Cf-Id: qbs8pAFG2HdQnXLcCsdKI1lYRXXUQMG0n7ltQqTvNmisccvdzudOGg==
---response end---
200 OK
Length: 19671 (19K) [application/json]
Saving to: ‘list’
100%[================================>] 19,671      --.-K/s   in 0s
Closed 3/SSL 0x0000000001aa4130
2020-12-10 23:21:47 (199 MB/s) - ‘list’ saved [19671/19671]
```

**My Rundeck detail**
- Rundeck version: 3.3.6
- install type: war
- OS Name/version: RHEL 7.8
- DB Type/version: H2
- This is fresh installation of Rundeck 3.3.6. I used Rundeck 3.2.9 before, and it had the same issue/behavior.
- Common user account (not root) is used.
- Symlinks used in our case (I'm mentioning this because I saw some bug report related to using symlinks):
Rundeck war file symlink : rundeck.war -> rundeck-3.3.6-20201111.war
Java home dir symlink : jdk11 -> jdk-11.0.9/

**To Reproduce**
1. Have Rundeck on server which can only reach the Internet via HTTP proxy requiring authentication
2. Click on 'Plugins - Find Plugins'

**Expected behavior**
Rundeck is expected to get the list of plugins via HTTP proxy with authentication,
using proxy configuration passed to it in some way
(I didn't find in the documentation which way is the preferred/recommended one).

**Comment by Vebryn** [comment]
+1
