### ISSUE TITLE
ref a job with empty node

### ISSUE THREAD

**Issue by Shinku-Chen** [rundeck/rundeck#6729]
ref a job with empty node:

```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[]}
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.validateNodeSet(BaseWorkflowExecutor.java:880)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:92)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:220)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:95)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:79)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[]}
Execution failed: 378789 in project ADX: [Workflow result: , step failures: {7=JobFailed: Job [15eb41fb-eb77-4fea-83ff-1fcd348f5ee8] failed}, Node failures: {tapadtest-dev=[]}, status: failed]
```

**Comment by Shinku-Chen** [comment]
Rundeck 3.3.8-20210111

**Comment by Shinku-Chen** [comment]
ref a job  and this job  ref a job with empty node:
