### ISSUE TITLE
ERROR boot.SpringApplication - Application run failed

### ISSUE THREAD

**Issue by tianyujia20200101** [rundeck/rundeck#6805]
Hi Team,

I just installed Rundeck on my Ubuntu.
The service status is active and running, however there's no any process listening on port 4443(which i set to be the rundeck port) hence it is not responding to any ingress request, and cant access via GUI 

please help check below output messages and suggest, this has been puzzled me weeks. really urgent

 

 

root@sinvlii10751:/apps/rundeck# java -Drundeck.ssl.config=/apps/rundeck/server/config/ssl.properties -jar rundeck-3.3.6-20201111.war

[2021-02-22T12:36:13,336] INFO  rundeckapp.Application - The following profiles are active: production

 

Configuring Spring Security Core ...

... finished configuring Spring Security Core

 

[2021-02-22T12:36:43,521] INFO  rundeckapp.BootStrap - Starting Rundeck 3.3.6-20201111 (2020-11-12) ...

[2021-02-22T12:36:43,525] INFO  rundeckapp.BootStrap - using rdeck.base config property: /apps/rundeck

[2021-02-22T12:36:43,553] INFO  rundeckapp.BootStrap - loaded configuration: /apps/rundeck/etc/framework.properties

[2021-02-22T12:36:43,640] INFO  rundeckapp.BootStrap - RSS feeds disabled

[2021-02-22T12:36:43,640] INFO  rundeckapp.BootStrap - Using builtin realm authentication

[2021-02-22T12:36:43,641] INFO  rundeckapp.BootStrap - Preauthentication is disabled

[2021-02-22T12:36:43,742] INFO  rundeckapp.BootStrap - Rundeck is ACTIVE: executions can be run.

[2021-02-22T12:36:43,996] WARN  rundeckapp.BootStrap - [Development Mode] Usage of H2 database is recommended only for development and testing

[2021-02-22T12:36:44,449] INFO  rundeckapp.BootStrap - Rundeck startup finished in 1127ms

[2021-02-22T12:36:45,015] INFO  rundeckapp.BootStrap - Rundeck Shutdown detected

[2021-02-22T12:36:45,203] ERROR boot.SpringApplication - Application run failed

org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server

        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:166) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:297) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]

        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at grails.boot.GrailsApp.run(GrailsApp.groovy:96) [grails-core-4.0.3.jar!/:4.0.3]

        at grails.boot.GrailsApp.run(GrailsApp.groovy:456) [grails-core-4.0.3.jar!/:4.0.3]

        at grails.boot.GrailsApp.run(GrailsApp.groovy:443) [grails-core-4.0.3.jar!/:4.0.3]

        at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-4.0.3.jar!/:?]

        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) [groovy-2.5.6.jar!/:2.5.6]

        at rundeckapp.Application.main(Application.groovy:32) [classes!/:?]

        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [rundeck-3.3.6-20201111.war:?]

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [rundeck-3.3.6-20201111.war:?]

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [rundeck-3.3.6-20201111.war:?]

        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [rundeck-3.3.6-20201111.war:?]

Caused by: java.lang.IllegalStateException: no valid keystore

        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:50) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1188) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:323) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:92) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:320) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231) ~[jetty-server-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.springframework.boot.web.embedded.jetty.SslServerCustomizer$SslValidatingServerConnector.doStart(SslServerCustomizer.java:248) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72) ~[jetty-util-9.4.26.v20200117.jar!/:9.4.26.v20200117]

        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:147) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]

        ... 23 more

Error heating the plugin cache

java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@15bc339 has been closed already

        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1090)

        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)

        at org.springframework.beans.factory.BeanFactory$getBean$0.call(Unknown Source)

        at com.dtolabs.rundeck.server.plugins.RundeckPluginRegistry.findBean(RundeckPluginRegistry.groovy:469)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)

        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)

        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)

        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)

        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)

        at com.dtolabs.rundeck.server.plugins.RundeckPluginRegistry$_listPluginDescriptors_closure5.doCall(RundeckPluginRegistry.groovy:500)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)

        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)

        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)

        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)

        at groovy.lang.Closure.call(Closure.java:405)

        at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5927)

        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2373)

        at org.codehaus.groovy.runtime.dgm$187.invoke(Unknown Source)

        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)

        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)

        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)

        at com.dtolabs.rundeck.server.plugins.RundeckPluginRegistry.listPluginDescriptors(RundeckPluginRegistry.groovy:497)

        at rundeck.services.PluginService.listPlugins(PluginService.groovy:578)

        at rundeck.services.PluginService$listPlugins.call(Unknown Source)

        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)

        at rundeck.services.PluginApiService.listPluginsDetailed(PluginApiService.groovy:75)

        at rundeck.services.PluginApiService$listPluginsDetailed.call(Unknown Source)

        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)

        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)

        at rundeckapp.init.PluginCachePreloader.boostrap(PluginCachePreloader.groovy:32)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)

        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:266)

        at grails.events.subscriber.MethodSubscriber.call(MethodSubscriber.groovy:47)

        at org.grails.events.EventSubscriberTrigger.proceed(EventSubscriberTrigger.groovy:34)

        at org.grails.events.bus.ExecutorEventBus$_buildNotificationCallable_closure1$_closure3.doCall(ExecutorEventBus.groovy:36)

        at org.grails.events.bus.ExecutorEventBus$_buildNotificationCallable_closure1$_closure3.call(ExecutorEventBus.groovy)

        at groovy.lang.Closure.run(Closure.java:486)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

        at java.base/java.lang.Thread.run(Thread.java:834)

 

 

 

root@sinvlii10751:/apps/rundeck# java -version

java version "11.0.10" 2021-01-19 LTS

Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)

Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

root@sinvlii10751:/apps/rundeck# apt show jetty9

Package: jetty9

Version: 9.2.14-1

Priority: optional

Section: universe/java

Origin: Ubuntu

Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>

Original-Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>

Bugs: https://bugs.launchpad.net/ubuntu/+filebug

Installed-Size: 531 kB

Depends: adduser, apache2-utils, default-jre-headless | java7-runtime-headless, libjetty9-java (>= 9.2.14-1), libjetty9-extra-java (>= 9.2.14-1)

Recommends: authbind

Homepage: http://www.eclipse.org/jetty/

Download-Size: 88.7 kB

APT-Sources: https://cleversafe-direct-apac.xmp.net.intra/iv2_platform_unix_debian_repo_dev xenial/main amd64 Packages

Description: Java servlet engine and webserver

 

root@sinvlii10751:/apps/rundeck#

**Comment by MegaDrive68k** [comment]
Hi @tianyujia20200101 

It seems that your key storage isn't valid, could you follow [these steps](https://stackoverflow.com/a/60930884/10426011) to configure Rundeck SSL correctly?

Hope it helps!
