### ISSUE TITLE
Error encountered during Project Import after upgrade to 2.0

### ISSUE THREAD

**Issue by larryfast** [rundeck/rundeck#705]
Non-life threatening. This is a low priority for me, I'm just reporting it for general awareness. I could send you the export.jar but it's not clear where to attach it.

Saved a project using 1.4.2.  Upgraded system to 2.0 (full reinstall).
Import Project using 2.0 ... waited over 2 minutes, then Error below was reported.
However, on first glance all my Jobs seem to arrive intact.

```
An Error Occurred
No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (java.lang.Boolean) values: [true] Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean()
Details:
Request: /project/ublum/importArchive?import.jobUUIDBehavior=preserve&import=%5BjobUUIDBehavior%3Apreserve%2C+executionImportBehavior%3Aimport%5D&import.executionImportBehavior=import&_action_importArchive=Import&zipFile=org.springframework.web.multipart.commons.CommonsMultipartFile%407f02dfd9
Message: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (java.lang.Boolean) values: [true] Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() 
Caused by: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (java.lang.Boolean) values: [true] Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() 
Class: ProjectController 
At Line: [93] 
Code Snippet:
Stack Trace
groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (java.lang.Boolean) values: [true]
Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean()
    at rundeck.codecs.JobsXMLCodec$_convertXmlWorkflowToMap_closure1.doCall(JobsXMLCodec.groovy:301)
    at rundeck.codecs.JobsXMLCodec.convertXmlWorkflowToMap(JobsXMLCodec.groovy:335)
    at rundeck.services.ProjectService$_loadExecutions_closure6.doCall(ProjectService.groovy:190)
    at rundeck.services.ProjectService.loadExecutions(ProjectService.groovy:187)
    at rundeck.services.ProjectService$_importExecutionsToProject_closure15.doCall(ProjectService.groovy:465)
    at rundeck.services.ProjectService.importExecutionsToProject(ProjectService.groovy:464)
    at rundeck.services.ProjectService.importToProject(ProjectService.groovy:403)
    at rundeck.controllers.ProjectController$_closure2.doCall(ProjectController.groovy:93)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
--- truncated ---
```

**Comment by ahonor** [comment]
Reopen if this is still a concern
