### ISSUE TITLE
Fails to launch on fresh install of fresh Ubuntu (in ec2)- Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

### ISSUE THREAD

**Issue by peace-blaster** [rundeck/rundeck#7063]
After following the guide [here](https://docs.rundeck.com/docs/administration/install/linux-deb.html#installing-rundeck), the service fails to start, and I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.<init>(ClassMetaClassGetPropertySite.java:35)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createClassMetaClassGetPropertySite(AbstractCallSite.java:379)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:327)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.acceptGetProperty(AbstractCallSite.java:314)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
        at rundeckapp.Application.<clinit>(Application.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)```

Is happening with most current version at the time of this posting- `3.3.11.20210507-1`

**Comment by MegaDrive68k** [comment]
Hi @peace-blaster 

Which java version are you using in your Ubuntu instance? Could you post the full stack trace?

Regards.

**Comment by Davidh-claranet** [comment]
Hello
I have the same issue
I installed openjdk-8-jdk-headless openjdk-8-jre-headless packages
ubuntu 20.04
Thanks
David

**Comment by realvinay** [comment]
The installation guide [suggests](https://docs.rundeck.com/docs/administration/install/linux-deb.html#installing-rundeck) to use Java 11, try installing **openjdk-11-jre-headless**
```sudo apt-get install openjdk-11-jre-headless```

**Comment by ruairinewman** [comment]
Same issue. Tried to install using every openjdk version from 8 to 17, with no difference.
