### ISSUE TITLE
Job stay in "running" and doesn't end

### ISSUE THREAD

**Issue by thewasta** [rundeck/rundeck#7088]
**Describe the bug**
Before my Rundeck version was 3.0 and I decided to upgrade it to latest version (3.3.11).

My steps to upgrade:
`wget --content-disposition https://packagecloud.io/pagerduty/rundeck/packages/any/any/rundeck_3.3.11.20210507-1_all.deb/download.deb`

`dpkg -i rundeck*.deb`

and it asked me to replace the new version with the actual version configuration, I press N, so it keep my configuration.

Some jobs works great. But some doesn't. 

The action on every job is a command 
`cd /var/www/html && php artisan my:command`

logs:

```
org.grails.web.json.JSONException: Missing value. at character 0 of 
	at org.grails.web.json.JSONTokener.syntaxError(JSONTokener.java:481) ~[grails-web-common-4.0.3.jar!/:4.0.3]
	at org.grails.web.json.JSONTokener.nextValue(JSONTokener.java:358) ~[grails-web-common-4.0.3.jar!/:4.0.3]
```
```
[2021-05-25T09:37:42,369] ERROR StackTrace - Full Stack Trace:
org.grails.web.converters.exceptions.ConverterException: Error parsing JSON
	at grails.converters.JSON.parse(JSON.java:260) ~[converters-4.0.0.jar!/:?]
	at rundeck.services.WorkflowService.deserializeState(WorkflowService.groovy:325) ~[classes!/:?]
	at rundeck.services.WorkflowService.requestStateSummary(WorkflowService.groovy:398) ~[classes!/:?]
	at rundeck.controllers.ExecutionController.ajaxExecState(ExecutionController.groovy:387) ~[classes!/:?]
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223) ~[grails-core-4.0.3.jar!/:4.0.3]

```

**My Rundeck detail**

* Rundeck version: 3.3.11
* install type: deb
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**Expected behavior**

**Screenshots**
![Captura de pantalla de 2021-05-26 08-44-21](https://user-images.githubusercontent.com/24923980/119614468-9d19f900-bdfe-11eb-9746-ee2a0ef0e8e6.png)

**Desktop (please complete the following information):**

**Additional context**
The average time to complete job is about 5min (the max time, most is 1min).
```
$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

**Comment by thewasta** [comment]
Reason was: Storage was 100%.

**Comment by thewasta** [comment]
Reason was: Storage was 100%.
