### ISSUE TITLE
Check for valid pattern in the key-value plugin

### ISSUE THREAD

**Issue by gaddman** [rundeck/rundeck#7099]
**Is your feature request related to a problem? Please describe.**
The **Key Value Data** Log Filter Plugin requires a Pattern for matching key/value data. If no capture group is included in the regular expression the job fails when run with a java error (version 3.3.12):

```
Exception in thread "Thread-5438" java.lang.IndexOutOfBoundsException: No group 1
	at java.util.regex.Matcher.group(Matcher.java:538)
	at java_util_regex_MatchResult$group.call(Unknown Source)
	at com.dtolabs.rundeck.server.plugins.logging.SimpleDataFilterPlugin.handleEvent(SimpleDataFilterPlugin.groovy:143)
	at com.dtolabs.rundeck.core.logging.PluginFilteredStreamingLogWriter.addEvent(PluginFilteredStreamingLogWriter.java:221)
	at com.dtolabs.rundeck.core.logging.OverridableStreamingLogWriter.addEvent(OverridableStreamingLogWriter.java:62)
	at sun.reflect.GeneratedMethodAccessor10222.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1050)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1092)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
	at com.sun.proxy.$Proxy205.accept(Unknown Source)
	at com.dtolabs.rundeck.core.utils.ThreadBoundLogOutputStream.flushEventBuffer(ThreadBoundLogOutputStream.java:149)
	at com.dtolabs.rundeck.core.utils.ThreadBoundLogOutputStream.write(ThreadBoundLogOutputStream.java:109)
	at com.dtolabs.rundeck.core.utils.ThreadBoundOutputStream.write(ThreadBoundOutputStream.java:123)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at java.io.PrintStream.write(PrintStream.java:480)
	at com.dtolabs.utils.Streams.copyStreamCount(Streams.java:67)
	at com.dtolabs.utils.Streams.copyStream(Streams.java:48)
	at com.dtolabs.utils.Streams$StreamCopyThread.run(Streams.java:115)
0
Exception while executing step [1]: [java.lang.IndexOutOfBoundsException: No group 1]
```

For new users, particularly those unfamiliar with regular expressions, it's not clear from this error why the job has failed.

**Describe the solution you'd like**
A check before saving the log filter could verify if the right number of capture groups has been provided, ie one if the _Name Data_ is provided, two otherwise.

**Additional context**
Example pattern which will cause an error:
![image](https://user-images.githubusercontent.com/1311209/120565431-236ab680-c461-11eb-8d6d-2e702a41ca10.png)

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
