### ISSUE TITLE
Scheduled job fails when LDAP user that last edited job is disabled

### ISSUE THREAD

**Issue by ghost** [rundeck/rundeck#7102]
We utilize LDAP/Active Directory authentication and noticed that when a user that last edited the scheduled job is disabled, the scheduled job will fail

**My Rundeck detail**

* Rundeck version: [3.3.10]
* install type: [choose: rpm]
* OS Name/version: [CentOS 7 (Core)]
* DB Type/version: [postgres]

**Additional context**
The log output indicates that nodes could not be matched:
`com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={tags=postgres, dominant=false, }}
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.validateNodeSet(BaseWorkflowExecutor.java:880)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.executeWorkflowImpl(EngineWorkflowExecutor.java:214)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:220)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:95)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:77)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={tags=postgres, dominant=false, }}
No matched nodes: NodeSet{includes={tags=postgres, dominant=false, }}`

When the disabled user is re-enabled, the scheduled jobs run again

**Comment by MegaDrive68k** [comment]
Hi @tfreycb 

I'm trying to reproduce your issue unsuccessfully. Could you provide the steps to reproduce it?

Regards.

**Comment by tfreycb** [comment]
Hi @MegaDrive68k ,

here's what I observed:

- we have a variety of scheduled jobs that run once daily (typically around midnight)
- last Thursday we terminated a user account (disabled in Active Directory)
- Thursday night and Friday night jobs were still running normally but starting Saturday night all jobs that were last edited by the user that was terminated failed. All other jobs that were not last edited by that user ran normally
- When I manually re-ran the jobs they ran normally and after editing the job and saving them, they're now running normally (and show as being run by my user)

**Comment by tfreycb** [comment]
Wanted to bump this again as it is still an issue in version 3.4.6.

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
