### ISSUE TITLE
Support JDK14

### ISSUE THREAD

**Issue by enexusde** [rundeck/rundeck#7110]
**Is your feature request related to a problem? Please describe.**
Rundeck can not be run using jdk14 (I do not mean 1.4 but the latest 14).

**Describe the solution you'd like**
Be able to let rundeck use jdk14

**Describe alternatives you've considered**
Currently I need to install a earlier JDK

**Additional context**
JDK14 will be come soon.

Exception from `/var/log/rundeck/service.log` is
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.<init>(ClassMetaClassGetPropertySite.java:35)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createClassMetaClassGetPropertySite(AbstractCallSite.java:379)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:327)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.acceptGetProperty(AbstractCallSite.java:314)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
        at rundeckapp.Application.<clinit>(Application.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
```

**Comment by MegaDrive68k** [comment]
Hi @enexusde 

Rundeck supports the LTS JDK releases (8 and 11), take a look at the Java requirements [here](https://docs.rundeck.com/docs/administration/install/system-requirements.html#java).

Regards.

**Comment by enexusde** [comment]
Why closed?
