### ISSUE TITLE
Rundeck 3.4.0 - Scheduled Job stuck at waiting for execution

### ISSUE THREAD

**Issue by jhonore** [rundeck/rundeck#7127]
# What happened:

Sheduled Job failed to start and display a waiting message

<img width="1695" alt="image" src="https://user-images.githubusercontent.com/18578614/122578676-1aaddf00-d022-11eb-8ec3-0153c75bbf14.png">

# What you expected to happen:

Sheduled Job executed on time and return an exit code (0,1...)

# How to reproduce it :

Create a Job that executed a remote command via SSH.
SSH command are performed by *openssh / executor plugin* (using sshpass for authentication)

```yaml
- defaultTab: output
  description: ''
  executionEnabled: true
  id: a6c9dad7-724e-4eeb-a12b-f547bef6460b
  loglevel: DEBUG
  name: Test Bug
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: MY_REMOTE_HOST
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: null
  schedule:
    month: '*'
    time:
      hour: '*'
      minute: 0/5
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash
        python3.5 /tmp/main.py
    keepgoing: false
    strategy: node-first
  timeout: 60
  uuid: a6c9dad7-724e-4eeb-a12b-f547bef6460b
```

> NOTE: The 60 second timeout never occur

main.py

```python
import requests

api_url = "https://api.ipify.org?format=json"
response = requests.get(api_url)
response.raise_for_status()
json = response.json()

print("JSON: ")
print(json)
```

# Anything else we need to know?:

The job create 4 sessions to execute the script is that normal ? 
```
Jun 17 16:34:53 MY_REMOTE sshd[6534]: Accepted password for RUNDECK_USER from MY_RUNDECK_IP port 55494 ssh2
Jun 17 16:34:53 MY_REMOTE sshd[6534]: pam_unix(sshd:session): session opened for user rundeck by (uid=0)
Jun 17 16:34:53 MY_REMOTE sshd[6547]: Accepted password for RUNDECK_USER from MY_RUNDECK_IP port 55496 ssh2
Jun 17 16:34:53 MY_REMOTE sshd[6547]: pam_unix(sshd:session): session opened for user rundeck by (uid=0)
Jun 17 16:34:53 MY_REMOTE sshd[6562]: Accepted password for RUNDECK_USER from MY_RUNDECK_IP port 55498 ssh2
Jun 17 16:34:53 MY_REMOTE sshd[6562]: pam_unix(sshd:session): session opened for user rundeck by (uid=0)
Jun 17 16:34:56 MY_REMOTE sshd[6617]: Accepted password for RUNDECK_USER from MY_RUNDECK_IP port 55500 ssh2
Jun 17 16:34:56 MY_REMOTE sshd[6617]: pam_unix(sshd:session): session opened for user rundeck by (uid=0)
```

I tried to export  thread dump  with ```kill -3 <PID>``` but nothing happened.

# Environment:

* Rundeck version: 3.4.0-20210614
* install type: DEB
* DB Type/version: ```PostgreSQL 11.8 (Debian 11.8-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit``
* OS: Debian 10.9
* Kernel: ```Linux XXXXXX 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux```
* OpenSSH version: ```OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019```
* sshpass version: 1.06

* Remote node OS: Debian 9.9
* Remote node kernel: ```Linux XXXXXX 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux```
* OpenSSH version: ```OpenSSH_7.4p1 Debian-10+deb9u6, OpenSSL 1.0.2u  20 Dec 2019```

**Comment by MegaDrive68k** [comment]
Hi @jhonore 

Could you share the` service.log` output at the moment of those scheduled executions? (`tail -f /var/log/rundeck/service.log`).

Thanks!

**Comment by jhonore** [comment]
Hi @MegaDrive68k 

Find below the output I got

```
[2021-06-18T11:45:00,099] ERROR core.ErrorLogger - Job (fwi_dev:Test Bug:.1260:Test Bug threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.3.2.jar!/:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:?]
Caused by: java.lang.NullPointerException
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:551) ~[classes!/:?]
	at rundeck.quartzjobs.ExecutionJob$saveState$1.callCurrent(Unknown Source) ~[?:?]
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:168) ~[classes!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor3297.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:99) ~[classes!/:?]
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy) ~[classes!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor3296.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.run(Closure.java:486) ~[groovy-2.5.6.jar!/:2.5.6]
	at com.codahale.metrics.Timer.time(Timer.java:137) ~[metrics-core-4.0.7.jar!/:4.0.7]
	at com.codahale.metrics.Timer$time$0.call(Unknown Source) ~[?:?]
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:98) ~[classes!/:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:?]
	... 1 more
[2021-06-18T11:45:00,107] ERROR listeners.ExceptionPrinterJobListener - Exception occurred in job:
org.quartz.JobExecutionException: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:218) [quartz-2.3.2.jar!/:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:?]
Caused by: org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.3.2.jar!/:?]
	... 1 more
Caused by: java.lang.NullPointerException
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:551) ~[classes!/:?]
	at rundeck.quartzjobs.ExecutionJob$saveState$1.callCurrent(Unknown Source) ~[?:?]
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:168) ~[classes!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor3297.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:99) ~[classes!/:?]
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy) ~[classes!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor3296.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.run(Closure.java:486) ~[groovy-2.5.6.jar!/:2.5.6]
	at com.codahale.metrics.Timer.time(Timer.java:137) ~[metrics-core-4.0.7.jar!/:4.0.7]
	at com.codahale.metrics.Timer$time$0.call(Unknown Source) ~[?:?]
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:98) ~[classes!/:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:?]
	... 1 more
```

> NOTE:  When a make the python script  failed voluntarily, this issue never occur.
> it occur only when the python script is triggered correctly.

**Comment by MegaDrive68k** [comment]
Hi @jhonore 

I'm trying to reproduce the bug [unsuccessfully](https://imgur.com/tAJK4qM) on Rundeck 3.4.0: I'm using the OpenSSH node executor, and this scheduled job:

```yaml
- defaultTab: output
  description: ''
  executionEnabled: true
  id: a6c9dad7-724e-4eeb-a12b-f547bef6460b
  loglevel: INFO
  name: Test Bug
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: RemoteNode'
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: null
  schedule:
    month: '*'
    time:
      hour: '*'
      minute: '*'
      seconds: 0/15
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash
        python main.py
    keepgoing: false
    strategy: node-first
  timeout: '60'
  uuid: a6c9dad7-724e-4eeb-a12b-f547bef6460b
```

Against this remote node (password based ssh server):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project>
<node name="RemoteNode"
       description="node00"
       tags="vagrant"
       hostname="192.168.33.20"
       osArch="Linux"
       osFamily="x86_64"
       osName="Linux"
       osVersion="10.12.6"
       username="vagrant"
       ssh-authentication="password"
       node-executor="ssh-exec"
       file-copier="ssh-copier"
       ssh-password-storage-path ="keys/passwd"
       ssh-options="-o ConnectTimeout=5000"/>
</project>
```

Perhaps I'm. missing something?

Thanks!

**Comment by jhonore** [comment]
Hi @MegaDrive68k ,

May I share the configurations files ? 

Which one should I show you ?

**Comment by jhonore** [comment]
+1

**Comment by jhonore** [comment]
+1

**Comment by MegaDrive68k** [comment]
Hey @jhonore 

Your current instance is an upgrade? If so, which was the previous Rundeck version?

Also, recently I reproduced this issue, maybe related: https://github.com/rundeck/rundeck/issues/7139

Regards.

**Comment by jhonore** [comment]
Hi @MegaDrive68k ,

Nop, I've made a fresh install of the version 3.4.0-20210614.

I've the same finality as #7139, but the inbound event is not the same. May they have a relation ?

Tell me if I can help

Regards.

**Comment by gschueler** [comment]
This seems to be caused by failing to properly handle an error when starting the job.  is there any other error output in your service log prior to the one you pasted? @jhonore
