### ISSUE TITLE
SQL error - rundeck with oracle

### ISSUE THREAD

**Issue by satyanarayanads** [rundeck/rundeck#713]
Hi,

  I am doing rundeck 1.6 war deployment in tomcat with oracle as backend. I am facing below error when i login and click on jobs. Please do the needful.

Request: /rundeck/jobs
Message: ORA-00932: inconsistent datatypes: expected - got CLOB
Caused by: ORA-00932: inconsistent datatypes: expected - got CLOB
Class: MenuController
At Line: [142]
Code Snippet:
Stack Trace

java.sql.SQLException: ORA-00932: inconsistent datatypes: expected - got CLOB

```
at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:813)
at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1051)
at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:854)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1156)
at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3460)
at grails.orm.HibernateCriteriaBuilder.invokeMethod(HibernateCriteriaBuilder.java:1163)
at rundeck.services.ScheduledExecutionService.listWorkflows(ScheduledExecutionService.groovy:107)
at rundeck.services.ScheduledExecutionService$listWorkflows.call(Unknown Source)
at rundeck.controllers.MenuController.listWorkflows(MenuController.groovy:236)
at rundeck.controllers.MenuController$_closure11.doCall(MenuController.groovy:195)
at rundeck.controllers.MenuController$_closure11.call(MenuController.groovy)
at rundeck.controllers.MenuController.invokeMethod(MenuController.groovy)
at rundeck.controllers.MenuController$_closure9.doCall(MenuController.groovy:142)
at rundeck.controllers.MenuController$_closure9.call(MenuController.groovy)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAsPrivileged(Subject.java:517)
at java.security.AccessController.doPrivileged(Native Method)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:662)
```

**Comment by ahonor** [comment]
Reopen if this is still an issue
