### ISSUE TITLE
Rundeck fails to initialise the database with java.sql.SQLNonTransientConnectionException on AWS Aurora Mysql DB

### ISSUE THREAD

**Issue by jonathancouchman** [rundeck/rundeck#7272]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**

I have a new Rundeck installation. When I start the server for the first time after following the MySQL DB configuration as described [here](https://docs.rundeck.com/docs/administration/configuration/database/mysql.html) the server appears to hang for a long time (~ 10 minutes) and then multiple exceptions are thrown with the cause  java.sql.SQLException: Too many connections.

If I monitor the database during the server startup I can see that up to 1000 db connections are initiated by the Rundeck server before the exception is thrown

datasource configuration

```
dataSource.url=jdbc:mysql://rundeck-db/rundeck?autoReconnect=true&useSSL=false
dataSource.username=rundeck
dataSource.password=DATABASE_PASSWORD
dataSource.properties.maxActive=100
dataSource.driverClassName=org.mariadb.jdbc.Driver
```
**My Rundeck detail**

* Rundeck version: 3.3.14
* install type: deb
* OS Name/version: debian9 AWS EC2
* DB Type/version: AWS RDS Aurora-MySQL 5.7.mysql_aurora.2.10.0

**To Reproduce**
1. Download Rundeck rundeck_3.3.14.20210827-1_all deb
2. install on EC2 instance
3. Configure a AWS RDS Provisioned Database with engine version 5.7.mysql_aurora.2.10.0
4. Start Rundeck Server
5. Wait 10 minutes, see lots of Exceptions with cause as below

```
Caused by: java.sql.SQLException: Too many connections
	at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:92) ~[mariadb-java-client-2.7.0.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:518) ~[mariadb-java-client-2.7.0.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1380) ~[mariadb-java-client-2.7.0.jar!/:?]
	... 110 more
[2021-09-21T18:08:45,169] WARN  internal.JdbcEnvironmentInitiator - HHH000339: Could not obtain connection metadata: java.sql.SQLNonTransientConnectionException: Could not connect to HostAddress{host='rundeck-mysql', port=3306, type='master'}. Too many connections
```

**Expected behavior**
Server to successfully initialise the database and start correctly

**Screenshots**
db connections during server startup
<img width="896" alt="Screenshot 2021-09-21 at 21 38 34" src="https://user-images.githubusercontent.com/44161978/134245187-664ff530-7009-4b84-85b7-6208f0bad687.png">

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Chrome
 - Version 93

**Additional context**
This seems to be an issue with the provisioned database. I tried both MySQL 5.6 and 5.7 but saw the same issue. However, if I use a serverless Aurora database instance with the same MySQL configuration (5.6) then the database is initialised correctly, the tables are created and the server starts. I cannot determine any difference in the database configurations that would cause the problem. Trying to understand why Rundeck would try to create so many DB connections is the key. I do not understand since the datasource sets maxActive to 100

**Comment by jonathancouchman** [comment]
I have tested Rundeck against the following AWS RDS configurations and it works fine

1. Serverless Aurora MySQL 5.6.10a
2. Instance MySQL Community 8.0.23

It fails to start against the following

1. Regional cluster Aurora MySQL 5.7.mysql_aurora.2.07.2
2. Regional cluster Aurora MySQL 5.6.mysql_aurora.1.23.2

Has anyone else seen issues when running against AWS RDS Databases? Especially Aurora Clusters?

**Comment by jonathancouchman** [comment]
Has anyone any experience of Rundeck creating many database connection during the initial start up, and failing to close the connections, hence exhausting the connection pool of the database?

**Comment by yahonggu** [comment]
Have we found out the root cause of this issue? I'm planning to use Regional cluster 8.0.mysql_aurora.3.01.0 and wonder if the same issue would surface.
