### ISSUE TITLE
Job ends successfully but is displayed as "Failed"

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#742]
Hello,
We have a clustered Rundeck environment. It consists in 2 Tomcat servers, hosting 2 separate Rundeck .war installations. Both rundeck installations are pointing to a MySQL database.
So the configuration is replicated between Rundeck installations and jobs executions, configuration, activity are shared and synchronized.
Log stores are synchronized with a simple filesystem sharing between the Tomcat servers.

All is running fine; but we have one problem:

When the first Rundeck installation launch a job, it works and if the job ends normally (exit 0), both Rundeck installations are displaying the job as Successful.

When we do the same by launching a job from the second Rundeck installation (even the same job); even if the job ends fine (exit 0), the job is dispayed as "Failed".

I think we forgot to synchronize something to share the job exit status between the Rundeck installations. But what and where is it ?

Thanks for your help.

In the debug output, we have that kind of java trace:

```
Exception in thread "Connect thread lcf1 session" java.io.InterruptedIOException
18:11:41            at java.io.FileOutputStream.writeBytes(Native Method)
18:11:41            at java.io.FileOutputStream.write(FileOutputStream.java:260)
18:11:41            at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:202)
18:11:41            at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:272)
18:11:41            at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:276)
18:11:41            at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:122)
18:11:41            at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:212)
18:11:41            at org.codehaus.groovy.runtime.FlushingStreamWriter.write(FlushingStreamWriter.java:45)
18:11:41            at java.io.Writer.write(Writer.java:140)
18:11:41            at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:475)
18:11:41            at org.codehaus.groovy.runtime.IOGroovyMethods.leftShift(IOGroovyMethods.java:93)
18:11:41            at org.codehaus.groovy.runtime.IOGroovyMethods.leftShift(IOGroovyMethods.java:182)
18:11:41            at org.codehaus.groovy.runtime.dgm$675.invoke(Unknown Source)
18:11:41            at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
18:11:41            at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
18:11:41            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
18:11:41            at com.dtolabs.rundeck.app.internal.logging.FSStreamingLogWriter.addEvent(FSStreamingLogWriter.groovy:67)
18:11:41            at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:21)
18:11:41            at rundeck.services.logging.EventStreamingLogWriter.super$2$addEvent(EventStreamingLogWriter.groovy)
18:11:41            at sun.reflect.GeneratedMethodAccessor6034.invoke(Unknown Source)
18:11:41            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
18:11:41            at java.lang.reflect.Method.invoke(Method.java:597)
18:11:41            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
18:11:41            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
18:11:41            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
18:11:41            at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
18:11:41            at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
18:11:41            at rundeck.services.logging.EventStreamingLogWriter.addEvent(EventStreamingLogWriter.groovy:52)
18:11:41            at sun.reflect.GeneratedMethodAccessor6033.invoke(Unknown Source)
18:11:41            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
18:11:41            at java.lang.reflect.Method.invoke(Method.java:597)
18:11:41            at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
18:11:41            at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
18:11:41            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
18:11:41            at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
18:11:41            at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
18:11:41            at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
18:11:41            at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
18:11:41            at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:164)
18:11:41            at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:172)
18:11:41            at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:179)
18:11:41            at rundeck.services.logging.MultiLogWriter.addEvent(MultiLogWriter.groovy:29)
18:11:41            at com.dtolabs.rundeck.core.logging.StreamingLogWriter$addEvent.call(Unknown Source)
18:11:41            at rundeck.services.logging.LoglevelThresholdLogWriter.addEvent(LoglevelThresholdLogWriter.groovy:22)
18:11:41            at com.dtolabs.rundeck.core.logging.FilterStreamingLogWriter.addEvent(FilterStreamingLogWriter.java:21)
18:11:41            at com.dtolabs.rundeck.core.logging.ContextLogWriter.verbose(ContextLogWriter.java:51)
18:11:41            at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.log(ContextualExecutionListener.java:96)
18:11:41            at com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListenerImpl.log(WorkflowExecutionListenerImpl.java:42)
18:11:41            at com.dtolabs.rundeck.core.execution.workflow.ContextualExecutionListener.log(ContextualExecutionListener.java:60)
18:11:41            at com.dtolabs.rundeck.core.execution.ExecutionListener$log.call(Unknown Source)
18:11:41            at com.dtolabs.rundeck.app.internal.workflow.MultiWorkflowExecutionListener.log(MultiWorkflowExecutionListener.groovy:108)
18:11:41            at com.dtolabs.rundeck.core.tasks.net.ThreadBoundJschLogger.log(ThreadBoundJschLogger.java:118)
18:11:41            at com.jcraft.jsch.Session.run(Session.java:1674)
18:11:41            at java.lang.Thread.run(Thread.java:662)
```

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.
