### ISSUE TITLE
Rundeck upgrade from 3.2 to 3.3 is having service startup issue

### ISSUE THREAD

**Issue by satish-yandamuri** [rundeck/rundeck#7454]
**Describe the bug**
I am trying to upgrade the Rundeck from 3.2 to 3.3, after upgrade service starts failed, I can see below logs in service.log

 INFO  rundeckapp.Application - The following profiles are active: production
[2021-12-28T15:12:06,330] WARN  context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script16406845261201527801926.groovy: 3: unable to resolve class ch.qos.logback.classic.Level
 @ line 3, column 1.
   import ch.qos.logback.classic.Level
   ^

script16406845261201527801926.groovy: 2: unable to resolve class ch.qos.logback.classic.LoggerContext
 @ line 2, column 1.
   import ch.qos.logback.classic.LoggerContext
   ^

2 errors

[2021-12-28T15:12:06,404] ERROR boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script16406845261201527801926.groovy: 3: unable to resolve class ch.qos.logback.classic.Level
 @ line 3, column 1.
   import ch.qos.logback.classic.Level
   ^

script16406845261201527801926.groovy: 2: unable to resolve class ch.qos.logback.classic.LoggerContext
 @ line 2, column 1.
   import ch.qos.logback.classic.LoggerContext
   ^

2 errors

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1320) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1159) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:96) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:456) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:443) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-4.0.3.jar!/:4.0.3]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) [groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.Application.main(Application.groovy:28) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [rundeck-3.3.0-20200701.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [rundeck-3.3.0-20200701.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [rundeck-3.3.0-20200701.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [rundeck-3.3.0-20200701.war:?]
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script16406845261201527801926.groovy: 3: unable to resolve class ch.qos.logback.classic.Level
 @ line 3, column 1.
   import ch.qos.logback.classic.Level
   ^

script16406845261201527801926.groovy: 2: unable to resolve class ch.qos.logback.classic.LoggerContext
 @ line 2, column 1.
   import ch.qos.logback.classic.LoggerContext
   ^

2 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:980) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:647) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:596) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:309) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:251) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:261) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.GroovyClassLoader$parseClass.call(Unknown Source) ~[?:?]
	at groovy.util.ConfigSlurper.parse(ConfigSlurper.groovy:170) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.util.ConfigSlurper$parse$2.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.Application.loadGroovyRundeckConfigIfExists(Application.groovy:108) ~[classes!/:?]
	at rundeckapp.Application$loadGroovyRundeckConfigIfExists.callCurrent(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.Application.setEnvironment(Application.groovy:57) ~[classes!/:?]
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:105) ~[spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:96) ~[spring-context-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1763) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	... 37 more

**My Rundeck detail**

* Rundeck version: [ 3.3.0]
* install type: [choose: rpm]
* OS Name/version: [RHEL 7.8]
* DB Type/version: [choose: default db provided by Rundeck]

**To Reproduce**
Upgrade the Rundeck from 3.2.9 to 3.3.0, then start the service and then we can see service failed to start
**Expected behavior**
Service should be run and able to access the Rundeck Web UI
**Screenshots**

**Additional context**
cat rundeck-config.groovy
import org.slf4j.LoggerFactory
import ch.qos.logback.classic.LoggerContext
import ch.qos.logback.classic.Level

LoggerContext loggerContext = (LoggerContext)LoggerFactory.getILoggerFactory();
loggerContext.getLogger("rundeckapp.BootStrap").setLevel(Level.DEBUG)

cat rundeck-config.properties
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=http://hostname:4440
dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true

# Encryption for key storage
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys

rundeck.storage.converter.1.type=jasypt-encryption
rundeck.storage.converter.1.path=keys
rundeck.storage.converter.1.config.encryptorType=custom
rundeck.storage.converter.1.config.password=a5394b75d1123f50
rundeck.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.storage.converter.1.config.provider=BC

# Encryption for project config storage
rundeck.projectsStorageType=db

rundeck.config.storage.converter.1.type=jasypt-encryption
rundeck.config.storage.converter.1.path=projects
rundeck.config.storage.converter.1.config.password=a5394b75d1123f50
rundeck.config.storage.converter.1.config.encryptorType=custom
rundeck.config.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.config.storage.converter.1.config.provider=BC

rundeck.feature.repository.enabled=true

rundeck.gui.title=xxx
#rundeck.gui.logo=xxx
#rundeck.gui.logo-width=64px
#rundeck.gui.logo-height=64px
#rundeck.gui.titleLink=xxx
rundeck.gui.login.welcomeHtml=xxx
#setting the thread count
quartz.props.threadPool.threadCount = 50

cat framework.properties
# framework.properties -
#

# ----------------------------------------------------------------
# Rundeck server connection information
# ----------------------------------------------------------------

framework.server.name = hostname
framework.server.hostname = hostname
framework.server.port = 4440
framework.server.url = http://hostname:4440
# Username/password used by CLI tools.
framework.server.username = admin
framework.server.password = admin1234

# ----------------------------------------------------------------
# Installation locations
# ----------------------------------------------------------------

rdeck.base=/var/lib/rundeck

framework.projects.dir=/var/lib/rundeck/projects
framework.etc.dir=/etc/rundeck
framework.var.dir=/var/lib/rundeck/var
framework.tmp.dir=/var/lib/rundeck/var/tmp
framework.logs.dir=/var/lib/rundeck/logs
framework.libext.dir=/var/lib/rundeck/libext

# ----------------------------------------------------------------
# SSH defaults for node executor and file copier
# ----------------------------------------------------------------

framework.ssh.keypath = /var/lib/rundeck/.ssh/id_rsa
framework.ssh.user = rundeck

# ssh connection timeout after a specified number of milliseconds.
# "0" value means wait forever.
framework.ssh.timeout = 0

# ----------------------------------------------------------------
# Auto generated server UUID: xxxxx
# ----------------------------------------------------------------
rundeck.server.uuid = xxxx
rundeck.tokens.file=/etc/rundeck/api_token

**Comment by satish-yandamuri** [comment]
It is fixed by removing the rundeck-config.grrovy file, seems this file is not required from Rundeck 3.3.x.
