### ISSUE TITLE
When SQL server has an outage while a specific Rundeck jobs is running, that job must be killed manually before scheduled execution can resume

### ISSUE THREAD

**Issue by JongleurNin** [rundeck/rundeck#7463]
**Describe the bug**

When SQL server is patched (e.g. for Windows updates), in-progress jobs in Rundeck will get "stuck" when JDBC connection transaction cannot be rolled back. Users have to manually kill the job to allow subsequent scheduled executions of that job to resume.

**My Rundeck detail**

* Rundeck version: 3.4.8-20211214
* Install type: docker
* OS Name/version: [e.g. ubuntu 20.04]
* DB Type/version: mssql (SQL Server 2017 version 14.0.3411.3, with CU 26 installed)

**To Reproduce**

1. In a project, create a job that takes say 30 seconds to complete. I'll refer to this later as the "child job."
2. In that same project, create another job that runs the first job several times with different options as a "job reference" using the "workflow step" option. I'll refer to this later as the "parent job."
3. Enable execution and scheduling for the parent job, and enable the option to schedule to run repeatedly.
4. Set up scheduling for the parent job to run every 3 minutes (crontab: `0 0/3 * 1/1 * ? *`)
5. While the parent job is midway through execution, restart Microsoft SQL server
6. Verify that an error such as `Failed dispatching to node 5cbe81bce1b7: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection` appears in the job log.
7. Wait until the next scheduled execution, and verify that it gets queued without running.
8. Kill the long-running stuck job (the one where `Unable to rollback against JDBC Connection` appeared in the job log) and verify that subsequent scheduled executions run without issue.

**Expected behavior**

Rundeck should have a feature (configuration, or automatic behavior) to allow a job that failed due to a lost JBDC connection to mssql to be killed automatically, in order to prevent subsequent scheduled executions to succeed without manual intervention. In 

**Screenshots**

Parent job timeout settings

![image](https://user-images.githubusercontent.com/7306738/148109961-7dfe9354-fa46-4007-a8c0-2c2e37c5a200.png)

Scheduled execution settings for parent job

![image](https://user-images.githubusercontent.com/7306738/148110106-0692964b-f66a-4def-a58d-6d1e26e1ec88.png)

Sample of parent job, showing how child job gets called multiple times

![image](https://user-images.githubusercontent.com/7306738/148110140-494ebf41-eb35-44db-a060-e9354ccf0c5a.png)

**Desktop**

This section of the issue-reporting template is not super relevant, since it's a server-side issue, but here goes.
 - OS: Windows
 - Browser: Edge
 - Version: 96.0.1054.62

**Additional context**

Our Java properties from `entry.sh` (part of our Docker code for Rundeck) are as follows.

```
exec java \
    -XX:+UnlockExperimentalVMOptions \
    -XX:MaxRAMFraction="${JVM_MAX_RAM_FRACTION}" \
    -XX:+UseCGroupMemoryLimitForHeap \
    -Dloginmodule.conf.name=jaas-loginmodule.conf \
    -Dloginmodule.name=rundeck \
    -Drundeck.jaaslogin=true \
    -Drundeck.jetty.connector.forwarded="${RUNDECK_SERVER_FORWARDED:-false}" \
    -Dlog4j2.formatMsgNoLookups=true \
    "${@}" \
    -Dserver.web.context=/rundeck \
    -jar rundeck.war
```

Some things I've tried to work around this:

- Setting a "5m" timeout under the Other tab for the main job and the job configured as a "job reference" as a workflow step.
- Making the following configuration changes to the project where the stuck jobs are located.
    - Enabled Force PTY
    - Changed Connection Timeout from 0 (no timeout) to 3,600,000 milliseconds (1 hour)
    - Changed Command Timeout from 0 (no timeout) to 3,600,000 milliseconds (1 hour)
- Setting rundeck.enable.ref.stats=false in /home/rundeck/etc/framework.properties (after reading about related bugs)

A full stack trace from the last time this happened to my team is listed below.

```
Failed dispatching to node 5cbe81bce1b7: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
Exception while executing step [18]: [org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection]
[wf:74d3c4e3-0c93-4679-8cd5-3172df1a0eef] Exception while executing step [18]: 	[java.lang.RuntimeException: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection]
org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doRollback(HibernateTransactionManager.java:658)
	at org.grails.orm.hibernate.GrailsHibernateTransactionManager.doRollback(GrailsHibernateTransactionManager.groovy:82)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:836)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:810)
	at org.springframework.transaction.support.TransactionTemplate.rollbackOnException(TransactionTemplate.java:168)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:144)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at rundeck.services.ProjectManagerService.loadProjectConfig(ProjectManagerService.groovy)
	at com.dtolabs.rundeck.core.execution.workflow.WorkflowStrategyService.getStrategyForWorkflow(WorkflowStrategyService.java:120)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.setupWorkflowStrategy(EngineWorkflowExecutor.java:495)
	at com.dtolabs.rundeck.core.execution.workflow.EngineWorkflowExecutor.executeWorkflowImpl(EngineWorkflowExecutor.java:211)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:220)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:140)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:220)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:95)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:77)
Caused by: org.hibernate.TransactionException: Unable to rollback against JDBC Connection
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:127)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactionCoordinatorImpl.java:304)
	at org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doRollback(HibernateTransactionManager.java:655)
	... 16 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot invoke a rollback operation when the AutoCommit mode is set to "true".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2936)
	at jdk.internal.reflect.GeneratedMethodAccessor320.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:152)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:40)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy115.rollback(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor320.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:385)
	at com.sun.proxy.$Proxy123.rollback(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor320.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:241)
	at com.sun.proxy.$Proxy123.rollback(Unknown Source)
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:121)
	... 19 more
Exception: class org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
```

**Comment by JongleurNin** [comment]
Note: We considered allowing multiple execution to work around this a bit, but would strongly prefer not to do so, since our application (what the jobs run) could end up in a strange state if two instances of one of these jobs were to be running simultaneously.

**Comment by gschueler** [comment]
Thanks for the detailed information

**Comment by JongleurNin** [comment]
Hi @gschueler,

I know this is probably a minor issue in the grand scheme of things, but was wondering if, looking back on all the various improvements that have been made, you think there might be a chance that this has been fixed indirectly through some other refactoring or bug-fixing effort.

Thanks for keeping this on your radar.

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
