### ISSUE TITLE
docker image - 3.4.9 - javax.security.auth.login.LoginException: No LoginModules configured for ldap

### ISSUE THREAD

**Issue by ifelsefi** [rundeck/rundeck#7527]
Hi

I cannot get active directory auth working.  Using your [basic test](https://docs.rundeck.com/docs/administration/security/authentication.html#multiple-authentication-modules) it fails:

```
rundeck@rundeck-7d69c5c5cd-7xq44:~$ java -Drundeck.jaaslogin=true -Dloginmodule.conf.name=jaas-activedirectory.conf -Dloginmodule.name=ldap -jar rundeck.war --testauth
Checking file: /home/rundeck/server/config/jaas-activedirectory.conf
Checking login module: ldap
PreBootstrap process rundeckapp.init.prebootstrap.InitializeRundeckPreboostrap failed
javax.security.auth.login.LoginException: No LoginModules configured for ldap
        at java.base/javax.security.auth.login.LoginContext.init(LoginContext.java:261)
        at java.base/javax.security.auth.login.LoginContext.<init>(LoginContext.java:412)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
```

My jaas-activedirectory.conf:

```
activedirectory {
  com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule required
  debug="true"
  contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
  providerUrl="ldap://ad-server:389"
  bindDn="cn=binduser,ou=Users,dc=example,dc=com"
  bindPassword="bindpw"
  authenticationMethod="simple"
  forceBindingLogin="true"
  userBaseDn="dc=example,dc=com"
  userRdnAttribute="sAMAccountName"
  userIdAttribute="sAMAccountName"
  userPasswordAttribute="unicodePwd"
  userObjectClass="user"
  roleBaseDn="CN=cn,DC=example,DC=dom"
  roleNameAttribute="cn"
  roleMemberAttribute="member"
  roleObjectClass="group"
  cacheDurationMillis="300000"
  reportStatistics="true"
  ignoreRoles="true"
  storePass="true"
  clearPass="true"
  useFirstPass="false"
  tryFirstPass="false";
};
```

Can you please help?   I am running 3.4.9 of your image from Docker hub.

**Comment by ifelsefi** [comment]
User error.

**Comment by kujiy** [comment]
> Jaas Authorization Testing
> https://docs.rundeck.com/docs/administration/security/authentication.html#jaas-authorization-testing

Is this manual correct? 

```
$ java -Drundeck.jaaslogin=true -Dloginmodule.conf.name=jaas-ldap.conf -Dloginmodule.name=ldap -jar rundeck-3.4.6-20211110.war --testauth
```

It specifies ` -Dloginmodule.name=ldap` and the error says it does not exist.

**Comment by kujiy** [comment]
I understood.

If your `jaas-ldap.conf` has `login{ ... }`, you can use `-Dloginmodule.name=ldap`.

My `jass-ldap.conf` has `multiauth{ ... }` so I had to use `-Dloginmodule.name=multiauth`.
