### ISSUE TITLE
Can't kill job stuck in RUNNING state and ignoring the timeout

### ISSUE THREAD

**Issue by S0LERA** [rundeck/rundeck#7541]
**Describe the bug**
I can't kill a stuck running job in Rundeck.
This job has a timeout that rundeck "ignore" and doesn't kill it. And manually with the kill button nothing happens. 
One step of the job fails, and the "on Error" step executes correctly, but, after that, the job stayes in running state forever and it's impossible to kill. I also tried to kill it with rundeck-cli but a java timeout exception occurs (`java.net.SocketTimeoutException: timeout`)

The only solution is to restart the rundeck container.

**My Rundeck detail**

* Rundeck version: [3.4.11]
* install type: [docker]
* OS Name/version: [ubuntu 20.04]
* DB Type/version: [postgres]

**To Reproduce**
(In explorer)
1. Go to Job execution
2. Click on kill

(In rundeck-cli)
`rd executions kill -e <JOB_ID>`

**Expected behavior**
The job terminate when exceed the timeout or when manually kill it in explorer or with rundeck-cli

**Screenshots**
[![firefox-VWet-FD4o-LT.png](https://i.postimg.cc/vTJhcbW8/firefox-VWet-FD4o-LT.png)](https://postimg.cc/1VKwdxCb)
[![firefox-ua-P1x17hl-B.png](https://i.postimg.cc/FR1wSFJ0/firefox-ua-P1x17hl-B.png)](https://postimg.cc/zbZdZr7f)

**Desktop (please complete the following information):**
 - OS: [Windows/Linux]
 - Browser [firefox]
 - Version [97.0]

**Additional context**
Full rundeck-cli exception on kill:
```
java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:276)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:243)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:166)
        at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:606)
        at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:103)
        at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:74)
        at org.rundeck.client.tool.commands.Executions.kill(Executions.java:69)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:1030)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:428)
        at org.rundeck.client.tool.Main.main(Main.java:74)
```

Execution cleaned log in rundeck restart: `ERROR services.ExecutionService - Stale Execution cleaned up: [4328195] in <PROJECT>`

**Comment by MegaDrive68k** [comment]
Hi @S0LERA 

Could you run that job in debug mode to get more clues of that specific step?

Regards.

**Comment by S0LERA** [comment]
> Hi @S0LERA
> 
> Could you run that job in debug mode to get more clues of that specific step?
> 
> Regards.


Hi @MegaDrive68k 

I set the option in this job to run in debug mode. But neither it hangs in all executions of this job, nor it hangs always in this specific job, so I would have to activate this option in all the jobs of every project. I will try to activate the option in all possible to reproduce the error.

**Comment by gabrielrih** [comment]
Was that issue solved?

I'm facing the same error using the version 4.17.1

**Comment by S0LERA** [comment]
Any updates on this?

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
