### ISSUE TITLE
Upgrading to rundeck 3.4.0 project database migration fails (grails.validation.ValidationException)

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck#7562]
**Describe the bug**

When migrating from filesystem based projects to db-based projects, the migration fails if the project description contains a single quote character `'`.

We have been using filesystem based configuration for years because we have systems that wrap and bootstrap and autogenerate projects using project.properties as this is much easier to create than running a series of (extremely slow) `rd projects` commands. Sadly in 3.4.0 this is no longer supported and we are forced to move to db project configuration, requiring re-engineering of that solution, but also that the migration succeeds.

Our expectation is that any project configuration valid in `project..properties` is also valid in the DB configuration. This appears not to be the case.

**My Rundeck detail**

* Rundeck version: 3.4.10

```
$ rpm -qa | grep rundeck
rundeck-3.4.10.20220118-1.noarch
```

* install type: rpm
* OS Name/version: RHEL 7
* DB Type/version:: mariadb

**To Reproduce**

1. in rundeck 3.3.4 with storage type set to "filesystem" create a project with a `project.properties` file with description `Ben's cool project`
2. Leave this configuraiton in place
3. Upgrade to rundeck 3.4.10, setting `dataSource.dbCreate = none` and `grails.plugin.databasemigration.updateOnStart = true` (per the instructions) and set storage type to "db"
4. Start rundeckd

**Expected behavior**

Rundeckd starts up and migrates the configuration to database, then renames the project.properties.

** Actual behaviour **

Rundeckd fails to start. Here's the service log:

```

[2022-03-02T10:32:53,156] WARN  beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'exceptionMappings' being accessed! Ambiguous write methods found next to actually used [public void grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler.setExceptionMappings(java.util.List)]: [public void org.springframework.security.web.authentication.ExceptionMappingAuthenticationFailureHandler.setExceptionMappings(java.util.Map)]
[2022-03-02T10:33:51,497] INFO  rundeckapp.BootStrap - Starting Rundeck 3.4.10-20220118 (2022-01-18) ...
[2022-03-02T10:33:51,499] INFO  rundeckapp.BootStrap - using rdeck.base config property: /var/lib/rundeck
[2022-03-02T10:33:51,548] INFO  rundeckapp.BootStrap - loaded configuration: /etc/rundeck/framework.properties
[2022-03-02T10:33:51,550] WARN  framework.RundeckFilesystemProjectImporter - importing existing filesystem projects
[2022-03-02T10:33:52,498] WARN  framework.RundeckFilesystemProjectImporter - Discovered filesystem project XIT, importing...
[2022-03-02T10:33:54,691] ERROR boot.SpringApplication - Application run failed
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'rundeck.Project' on field 'description': rejected value [Main testing pointing at benj's mainline code]; codes [rundeck.Project.description.matches.error.rundeck.Project.description,rundeck.Project.description.matches.error.description,rundeck.Project.description.matches.error.java.lang.String,rundeck.Project.description.matches.error,project.description.matches.error.rundeck.Project.description,project.description.matches.error.description,project.description.matches.error.java.lang.String,project.description.matches.error,rundeck.Project.description.matches.invalid.rundeck.Project.description,rundeck.Project.description.matches.invalid.description,rundeck.Project.description.matches.invalid.java.lang.String,rundeck.Project.description.matches.invalid,project.description.matches.invalid.rundeck.Project.description,project.description.matches.invalid.description,project.description.matches.invalid.java.lang.String,project.description.matches.invalid,matches.invalid.rundeck.Project.description,matches.invalid.description,matches.invalid.java.lang.String,matches.invalid]; arguments [description,class rundeck.Project,Main testing pointing at benj's mainline code,^[a-zA-Z0-9\p{L}\p{M}\s\.,\(\)_-]+$]; default message [Property [{0}] of class [{1}] with value [{2}] does not match the required pattern [{3}]]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_302]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_302]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1732) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1556) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeConstructorOf(InvokerHelper.java:1042) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.newInstance(DefaultGroovyMethods.java:17159) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:134) ~[grails-datastore-gorm-hibernate5-7.0.3.RELEASE.jar!/:?]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:153) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$save$2.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.Project.save(Project.groovy) ~[classes!/:?]
	at rundeck.Project.save(Project.groovy) ~[classes!/:?]
	at org.grails.datastore.gorm.GormEntity$save.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.ProjectManagerService.$tt__projectManagerService_createFrameworkProject(ProjectManagerService.groovy:560) ~[classes!/:?]
	at rundeck.services.ProjectManagerService$_createFrameworkProject_closure28.doCall(ProjectManagerService.groovy) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.6.jar!/:2.5.6]
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
	at rundeck.services.ProjectManagerService.createFrameworkProject(ProjectManagerService.groovy) ~[classes!/:?]
	at com.dtolabs.rundeck.app.internal.framework.RundeckFilesystemProjectImporter$_importProjectsFromProjectManager_closure1.doCall(RundeckFilesystemProjectImporter.groovy:84) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2310) ~[groovy-2.5.6.jar!/:2.5.6]
	at com.dtolabs.rundeck.app.internal.framework.RundeckFilesystemProjectImporter.importProjectsFromProjectManager(RundeckFilesystemProjectImporter.groovy:73) ~[classes!/:?]
	at com.dtolabs.rundeck.app.internal.framework.RundeckFilesystemProjectImporter.bootstrap(RundeckFilesystemProjectImporter.groovy:65) ~[classes!/:?]
	at com.dtolabs.rundeck.app.internal.framework.RundeckFilesystemProjectImporter$bootstrap.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.BootStrap$_closure1.doCall(BootStrap.groovy:254) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1099) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) ~[groovy-2.5.6.jar!/:2.5.6]
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:594) ~[grails-bootstrap-4.0.3.jar!/:4.0.3]
	at grails.util.Environment.executeForEnvironment(Environment.java:587) ~[grails-bootstrap-4.0.3.jar!/:4.0.3]
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:563) ~[grails-bootstrap-4.0.3.jar!/:4.0.3]
	at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:74) ~[grails-web-4.0.3.jar!/:4.0.3]
	at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:83) ~[grails-web-4.0.3.jar!/:4.0.3]
	at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:56) ~[grails-plugin-controllers-4.0.3.jar!/:4.0.3]
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:269) ~[grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy) ~[grails-core-4.0.3.jar!/:4.0.3]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.13.RELEASE.jar!/:2.1.13.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:96) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:456) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:443) [grails-core-4.0.3.jar!/:4.0.3]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-4.0.3.jar!/:4.0.3]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) [groovy-2.5.6.jar!/:2.5.6]
	at rundeckapp.Application.main(Application.groovy:32) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [rundeck-3.4.10-20220118.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [rundeck-3.4.10-20220118.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [rundeck-3.4.10-20220118.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [rundeck-3.4.10-20220118.war:?]
[2022-03-02T10:33:54,993] INFO  rundeckapp.BootStrap - Rundeck Shutdown detected
```

Here's the project.properties in question:

```
project.name=<snip>
project.description=Main testing pointing at benj's mainline code
project.organization=<snip>
project.disable.executions=false

project.jobs.gui.groupExpandLevel=1
project.gui.readme.display=projectHome
project.gui.motd.display=projectList

project.ssh-authentication=privateKey
project.ssh-key-storage-path=keys/${job.username}.key
project.ssh-key-passphrase-storage-path=keys/${job.username}.passphrase
project.ssh-command-timeout=0
project.local-ssh-agent=true


project.local-ttl-ssh-agent=600
    

service.FileCopier.default.provider=jsch-scp
service.NodeExecutor.default.provider=jsch-ssh

<snip private details>
# vim: ft=tcl

```

After removing the single quote character, the project import starts. It then prints thousands of warnings about files that are in the project directory that are nothing to do with rundeck... but i guess that's expected.

**Comment by puremourning** [comment]
I'm also having difficulty getting `rd projects configure update` to work with the exact same file (having removed the single quote character). RD just returns this:

```
[rundeck@ukwok-pc720-vpc tcl]$ rd projects configure update -p XIT --file /var/lib/rundeck/run/generated-cfg/DEVBENJPC720_LO_XIT_RUNDECK_DEV/ukwok-pc720-vpc/xit_project.properties.XIT.auto.cfg -F properties
# WARNING: RD_INSECURE_SSL=true, no hostname or certificate trust verification will be performed
# Updating 40 configuration properties...
# Updated value: {key=project.description, value=Main testing pointing at benj mainline code}
# Updated value: {key=service.NodeExecutor.default.provider, value=jsch-ssh}
Error: Invalid API Request: value was not specified
[code: api.error.invalid.request; APIv40]
Request failed: 400 Bad Request
[rundeck@ukwok-pc720-vpc tcl]$
```

there is nothing in the service log.

**Comment by puremourning** [comment]
I think the error is because some of the entries in the file have empty values?

```
project.plugin.Notification.teams-notification.webhookUrl=
```
