### ISSUE TITLE
Execution x failed to start: Unable to create directories for storage

### ISSUE THREAD

**Issue by pts-aut** [rundeck/rundeck#7664]
In a few executions in rundeck, the following error occurs -at the same time, two more executions are started without any problems.

ERROR quartzjobs.ExecutionJob - Execution 367579 failed to start: Unable to create directories for storage: /home/rundeck/var/logs/rundeck/Workflows/job/0167159c-4709-4cb0-8b25-7ef7cfabd6ac/logs/367579.rdlog
 java.lang.IllegalStateException: Unable to create directories for storage: /home/rundeck/var/logs/rundeck/Workflows/job/0167159c-4709-4cb0-8b25-7ef7cfabd6ac/logs/367579.rdlog
         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
         at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
         at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249) ~[groovy-2.5.6.jar!/:2.5.6]
         at rundeck.services.LogFileStorageService.$tt__getLogFileWriterForExecution(LogFileStorageService.groovy:533) ~[classes!/:?]
         at jdk.internal.reflect.GeneratedMethodAccessor1863.invoke(Unknown Source) ~[?:?]
         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97) ~[groovy-2.5.6.jar!/:2.5.6]
         at rundeck.services.LogFileStorageService$_getLogFileWriterForExecution_closure30.doCall(LogFileStorageService.groovy) ~[classes!/:?]
         at jdk.internal.reflect.GeneratedMethodAccessor5052.invoke(Unknown Source) ~[?:?]
         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.6.jar!/:2.5.6]
         at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
         at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
         at rundeck.services.LogFileStorageService.getLogFileWriterForExecution(LogFileStorageService.groovy) ~[classes!/:?]
         at rundeck.services.LogFileStorageService$getLogFileWriterForExecution.call(Unknown Source) ~[?:?]
         at rundeck.services.LoggingService.openLogWriter(LoggingService.groovy:159) ~[classes!/:?]
         at rundeck.services.LoggingService$openLogWriter.call(Unknown Source) ~[?:?]
         at rundeck.services.ExecutionService.$tt__executeAsyncBegin(ExecutionService.groovy:1055) ~[classes!/:?]
         at jdk.internal.reflect.GeneratedMethodAccessor1853.invoke(Unknown Source) ~[?:?]
         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97) ~[groovy-2.5.6.jar!/:2.5.6]
         at rundeck.services.ExecutionService$_executeAsyncBegin_closure22.doCall(ExecutionService.groovy) ~[classes!/:?]
         at jdk.internal.reflect.GeneratedMethodAccessor5051.invoke(Unknown Source) ~[?:?]
         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.6.jar!/:2.5.6]
         at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
         at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91) ~[grails-datastore-gorm-7.0.4.RELEASE.jar!/:?]
         at rundeck.services.ExecutionService.executeAsyncBegin(ExecutionService.groovy) ~[classes!/:?]
         at rundeck.quartzjobs.ExecutionJob.executeCommand(ExecutionJob.groovy:360) [classes!/:?]
         at rundeck.quartzjobs.ExecutionJob$executeCommand$0.callCurrent(Unknown Source) [classes!/:?]
         at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:152) [classes!/:?]
         at jdk.internal.reflect.GeneratedMethodAccessor4570.invoke(Unknown Source) ~[?:?]
         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) [groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) [groovy-2.5.6.jar!/:2.5.6]
         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168) [groovy-2.5.6.jar!/:2.5.6]
         at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:99) [classes!/:?]
         at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy) [classes!/:?]
         at jdk.internal.reflect.GeneratedMethodAccessor4569.invoke(Unknown Source) ~[?:?]
         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

Retry of the Execution is starting without problems.

**My Rundeck detail**
* Rundeck version: 3.4.10
* install type: docker
* DB Type/version: postgres

**Comment by sideshowcecil** [comment]
We are still facing this issue sometimes in version 5.1.2.

**Comment by Cdk29** [comment]
Any updates regarding this issue ? Encountered the same today.

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
