### ISSUE TITLE
[Issue] Merging framework.properties works incorrectly

### ISSUE THREAD

**Issue by FireHelmet** [rundeck/rundeck#7853]
_Note: Bug Reports not following this template may be closed without feedback._

**Describe the bug**
Rundeck can't start if I use Remco for extending configuration of framework.properties

**My Rundeck detail**

* Rundeck version: 4.4.0
* install type: docker
* OS Name/version: ubuntu 20.04 (image from rundeck/rundeck:4.4.0)
* DB Type/version: mysql

**To Reproduce**
1. Add a framework-extra.properties by following instruction at https://docs.rundeck.com/docs/administration/configuration/docker/extending-configuration.html
2. Insert a key:value, like : framework.plugin.UserGroupSource.AzureGroupSource.enabled=true
3. Create your image and use it in a container

**Expected behavior**
The key:value correctly inserted (new line) in framework.properties and not stuck to the key:value "rundeck.server.uuid"

**Screenshots**
![image](https://user-images.githubusercontent.com/17533298/184554201-9780154e-dd81-4633-ab46-320cb171c08d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 91

**Additional context**
I got an error message when Rundeck tries to launch:

`[2022-08-14T22:27:15,504] ERROR boot.SpringApplication - Application run failed
java.lang.RuntimeException: Cluster mode: rundeck.clusterMode.enabled is set to 'true', but 'rundeck.server.uuid' not found in framework.properties
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) ~[groovy-3.0.9.jar!/:3.0.9]`

**Comment by FireHelmet** [comment]
Hey!

I was able to find a workaround by adding a carriage return in framework-extra.properties, as a new line so.
But I don’t understand the root cause of this issue.
