### ISSUE TITLE
Upgraded to Rundeck 4.5.0, SCM plugin cannot communicate with GitLab server

### ISSUE THREAD

**Issue by isuftin** [rundeck/rundeck#7857]
**Describe the bug**
Rundeck GitSCM plugin no longer working after upgrading to Rundeck 4.5.0. Upon attempting to save GitSCM configuration for any project in Rundeck I get:

```
Failed fetch from the repository: git@my.gitlab.server:automation/backup/rundeck.git: remote hung up unexpectedly; org/bouncycastle/operator/OperatorCreationException; org.bouncycastle.operator.OperatorCreationException
```

From rundeck.log:

```
[2022-08-16T23:23:37,551] INFO  random.JCERandom [qtp547829031-26] - Creating new SecureRandom.
[2022-08-16T23:23:37,554] INFO  transport.TransportImpl [qtp547829031-26] - Client identity string: SSH-2.0-SSHJ_0.33.0
[2022-08-16T23:23:37,563] INFO  transport.TransportImpl [qtp547829031-26] - Server identity string: SSH-2.0-OpenSSH_7.4
[2022-08-16T23:23:37,615] ERROR services.ScmService [qtp547829031-26] - Unable to initialize SCM for project Datachecks for integration export
com.dtolabs.rundeck.plugins.scm.ScmPluginException: Failed fetch from the repository: git@my.gitlab.server:automation/backup/rundeck.git: remote hung up unexpectedly; org/bouncycastle/operator/OperatorCreationException; org.bouncycastle.operator.OperatorCreationException
        at jdk.internal.reflect.GeneratedConstructorAccessor451.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.rundeck.plugin.scm.git.BaseGitPlugin.cloneOrCreate(BaseGitPlugin.groovy:582) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor1341.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212) ~[groovy-3.0.9.jar!/:3.0.9]
        at org.rundeck.plugin.scm.git.GitExportPlugin.setup(GitExportPlugin.groovy:123) ~[?:?]
        at org.rundeck.plugin.scm.git.GitExportPlugin$setup$0.callCurrent(Unknown Source) ~[?:?]
        at org.rundeck.plugin.scm.git.GitExportPlugin.initialize(GitExportPlugin.groovy:69) ~[?:?]
        at org.rundeck.plugin.scm.git.GitExportPlugin$initialize.call(Unknown Source) ~[?:?]
        at org.rundeck.plugin.scm.git.GitExportPluginFactory.createPlugin(GitExportPluginFactory.groovy:78) ~[?:?]
        at com.dtolabs.rundeck.plugins.scm.ScmExportPluginFactory$createPlugin$0.call(Unknown Source) ~[?:?]
        at rundeck.services.ScmService.loadExportPluginWithConfig(ScmService.groovy:816) ~[classes!/:?]
        at rundeck.services.ScmService$loadExportPluginWithConfig$20.callCurrent(Unknown Source) ~[?:?]
        at rundeck.services.ScmService.loadPluginWithConfig(ScmService.groovy:798) ~[classes!/:?]
        at rundeck.services.ScmService.loadPluginWithConfig(ScmService.groovy) ~[classes!/:?]
        at rundeck.services.ScmService$loadPluginWithConfig$19.callCurrent(Unknown Source) ~[?:?]
        at rundeck.services.ScmService.initPlugin(ScmService.groovy:457) ~[classes!/:?]
        at rundeck.services.ScmService.initPlugin(ScmService.groovy) ~[classes!/:?]
        at rundeck.services.ScmService$initPlugin$18.callCurrent(Unknown Source) ~[?:?]
        at rundeck.services.ScmService.initProject(ScmService.groovy:153) ~[classes!/:?]
        at rundeck.services.ScmService$initProject$2.callCurrent(Unknown Source) ~[?:?]
        at rundeck.services.ScmService.projectHasConfiguredExportPlugin(ScmService.groovy:218) ~[classes!/:?]
        at rundeck.services.ScmService$projectHasConfiguredExportPlugin$6.callCurrent(Unknown Source) ~[?:?]
        at rundeck.services.ScmService.projectHasConfiguredPlugin(ScmService.groovy:213) ~[classes!/:?]
        at rundeck.services.ScmService$projectHasConfiguredPlugin$5.call(Unknown Source) ~[?:?]
        at rundeck.controllers.ScmController.index(ScmController.groovy:193) ~[classes!/:?]
        at rundeck.controllers.ScmController.index(ScmController.groovy) ~[classes!/:?]
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223) ~[grails-core-5.1.9.jar!/:5.1.9]
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188) ~[grails-core-5.1.9.jar!/:5.1.9]
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90) ~[grails-web-url-mappings-5.1.9.jar!/:5.1.9]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.rundeck.plugin.scm.git.BaseGitPlugin.fetchFromRemote(BaseGitPlugin.groovy:253) ~[?:?]
        at org.rundeck.plugin.scm.git.BaseGitPlugin$fetchFromRemote.callCurrent(Unknown Source) ~[?:?]
        at org.rundeck.plugin.scm.git.BaseGitPlugin.cloneOrCreate(BaseGitPlugin.groovy:578) ~[?:?]
        ... 140 more
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/operator/OperatorCreationException
        at net.schmizz.sshj.userauth.keyprovider.OpenSSHKeyFile$Factory.create(OpenSSHKeyFile.java:39) ~[?:?]
        at net.schmizz.sshj.userauth.keyprovider.OpenSSHKeyFile$Factory.create(OpenSSHKeyFile.java:34) ~[?:?]
        at net.schmizz.sshj.common.Factory$Named$Util.create(Factory.java:54) ~[?:?]
        at org.rundeck.plugin.scm.git.ssh.SshjSession.createConnection(SshjSession.groovy:84) ~[?:?]
        at org.rundeck.plugin.scm.git.ssh.SshjSession.<init>(SshjSession.groovy:35) ~[?:?]
        at org.rundeck.plugin.scm.git.ssh.SshjSessionFactory.getSession(SshjSessionFactory.groovy:33) ~[?:?]
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140) ~[?:?]
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280) ~[?:?]
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170) ~[?:?]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:138) ~[?:?]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:124) ~[?:?]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1293) ~[?:?]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244) ~[?:?]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:1) ~[?:?]
        at java_util_concurrent_Callable$call$0.call(Unknown Source) ~[?:?]        at org.rundeck.plugin.scm.git.BaseGitPlugin.fetchFromRemote(BaseGitPlugin.groovy:253) ~[?:?]
        at org.rundeck.plugin.scm.git.BaseGitPlugin$fetchFromRemote.callCurrent(Unknown Source) ~[?:?]
        at org.rundeck.plugin.scm.git.BaseGitPlugin.cloneOrCreate(BaseGitPlugin.groovy:578) ~[?:?]
        ... 140 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.operator.OperatorCreationException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[rundeck-4.5.0-20220811.war:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:58) ~[rundeck-core-4.5.0-20220811.jar!/:?]
        at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:44) ~[rundeck-core-4.5.0-20220811.jar!/:?]
        at net.schmizz.sshj.userauth.keyprovider.OpenSSHKeyFile$Factory.create(OpenSSHKeyFile.java:39) ~[?:?]
        at net.schmizz.sshj.userauth.keyprovider.OpenSSHKeyFile$Factory.create(OpenSSHKeyFile.java:34) ~[?:?]
        at net.schmizz.sshj.common.Factory$Named$Util.create(Factory.java:54) ~[?:?]
        at org.rundeck.plugin.scm.git.ssh.SshjSession.createConnection(SshjSession.groovy:84) ~[?:?]
        at org.rundeck.plugin.scm.git.ssh.SshjSession.<init>(SshjSession.groovy:35) ~[?:?]
        at org.rundeck.plugin.scm.git.ssh.SshjSessionFactory.getSession(SshjSessionFactory.groovy:33) ~[?:?]
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140) ~[?:?]
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280) ~[?:?]
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170) ~[?:?]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:138) ~[?:?]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:124) ~[?:?]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1293) ~[?:?]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244) ~[?:?]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:1) ~[?:?]
        at java_util_concurrent_Callable$call$0.call(Unknown Source) ~[?:?]
        at org.rundeck.plugin.scm.git.BaseGitPlugin.fetchFromRemote(BaseGitPlugin.groovy:253) ~[?:?]
        at org.rundeck.plugin.scm.git.BaseGitPlugin$fetchFromRemote.callCurrent(Unknown Source) ~[?:?]
        at org.rundeck.plugin.scm.git.BaseGitPlugin.cloneOrCreate(BaseGitPlugin.groovy:578) ~[?:?]
        ... 140 more
```

ProjectSCM Config:

```
Export Jobs to a Git Repository
Committer Name: rundeck
Committer Email: rundeck@my-email.address.com
Export UUID Behavior: preserve
Synchronize Automatically: true
Create Branch if it doesn't exist: Yes
Base branch on: master
File Path Template: ${job.id}.${config.format}
Base Directory: /var/lib/rundeck/projects/Datachecks/ScmExport
Git URL: git@my.gitlab.server:automation/backup/rundeck.git
Branch: Datachecks
SSH: Strict Host Key Checking: no
SSH Key Storage Path: keys/global/scm/rundeck-scm-backup
Format: xml
Fetch Automatically: true
```

**My Rundeck detail**

* Rundeck version: 4.5.0
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: Postgresql

**To Reproduce**
1. Go to Setup SCM Plugin: Git Export
2. Enter SCM for your own GitLab server
3. Hit save

**Expected behavior**
Project SCM is set up with no errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 104.0.5112.79

**Additional context**
This is a live Rundeck server that was in-place upgraded from 4.4.0

**Comment by isuftin** [comment]
Also seeing in rundeck.log:

```
[2022-08-16T23:25:37,364] ERROR transport.TransportImpl [sshj-Reader-my.gitlab.server/<private IP>:22] - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF        at net.schmizz.sshj.transport.Reader.run(Reader.java:58) [sshj-0.33.0.jar:?]
[2022-08-16T23:25:37,364] INFO  transport.TransportImpl [sshj-Reader-my.gitlab.server/<private IP>:22] - Disconnected - UNKNOWN[2022-08-16T23:25:37,563] ERROR transport.TransportImpl [sshj-Reader-my.gitlab.server/<private IP>:22] - Dying because - Broken transport; encountered EOF
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF        at net.schmizz.sshj.transport.Reader.run(Reader.java:58) [sshj-0.33.0.jar:?]
[2022-08-16T23:25:37,563] INFO  transport.TransportImpl [sshj-Reader-my.gitlab.server/<private IP>:22] - Disconnected - UNKNOWN
```

**Comment by isuftin** [comment]
According to this: https://docs.rundeck.com/docs/manual/projects/scm/git.html#git-plugin

It seems like Rundeck can't use SSH keys for working with GitLab. I wonder if this is the same issue we're seeing with GitLab.

**Comment by isuftin** [comment]
I've updated the remote SSH key to be RSA for the time being. I've changed the remote to be ssh://git@my.gitlab.server/automation/backup/rundeck.git

This seems to fix the issue but the overall issue in Rundeck does persist. This is a breaking change. Has this been documented in the release notes as such?

**Comment by fdevans** [comment]
In 4.5 we changed the default library for SCM to use SSHJ which supports the newer key types.  I'm pushing an update to the docs, but maybe that helps you troubleshoot?

https://github.com/rundeck/rundeck/pull/7763

**Comment by ipaqmaster** [comment]
Any progress on this? I already had to ditch an RSA key for an ECDSA key because of this long unresolved issue https://github.com/rundeck/rundeck/issues/7274 despite the key exchange working just fine when I `ssh` to the remote using rundeck's identity and no sshd_config changes.

And now you're telling me I have to generate another RSA key anyway because ECDSA isn't supported for SCM? Come on.

**Comment by ipaqmaster** [comment]
Getting the same `remote hung up unexpectedly` experience against a new gitolite setup.

The git server shows: `sshd[14648]: fatal: Timeout before authentication for rundeck.ip.goes.here port 43093` multiple times as rundeck attempts to connect 5/5 times before giving up.

Issue #8338 seems to be related.

**Comment by laryssasre** [comment]
Rundeck only allows ed25519 rsa keys, I was facing the same problem and managed to configure scm import/export generating a new key of this type and importing it into github.

Rundeck version 4.14.2.
