### ISSUE TITLE
Installation failing with rundeck 4.5.0 on tomcat/linux

### ISSUE THREAD

**Issue by ronnie-hoffmann** [rundeck/rundeck#7896]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
On a fresh installation with Rundeck 4.5.0 we'll getting the following error messages and tomcat is not starting:
```
Caused by: liquibase.exception.DatabaseException: ERROR: column "jc_exec_id" does not exist
  Position: 44 [Failed SQL: (0) update base_report set execution_id = cast(JC_EXEC_ID as bigint)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:397) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:660) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:240) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:240) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.Scope.child(Scope.java:244) ~[liquibase-core-4.6.2.jar:?]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66) ~[liquibase-core-4.6.2.jar:?]
        ... 130 more
```

**My Rundeck detail**

* Rundeck version: 4.5.0
* install type: war
* OS Name/version: rhel 8.6
* DB Type/version: postgres

**rundeck-config.properties db-config**
```
dataSource.dbCreate=update
dataSource.url=jdbc:postgresql://<DB-URL>:5432/rundeck
dataSource.driverClassName=org.postgresql.Driver
dataSource.username=<DB-USER>
dataSource.password=<DB-PASSWORD>
```

Updating from rundeck 4.4.0 is working.

**Comment by fidalcastro** [comment]
I am also facing exact same issue in fresh installation of rundeck version 4.5.0.

**Rundeck Details:**

- Rundeck version: 4.5.0
- Install Type: war
- Os Name/Version: Ubuntu 22.04
- DB Type/Version: mysql-server 8.0.30-0ubuntu0.22.04.1

**rundeck-config.groovy db-config**

```
dataSource {
  dbCreate = "update"
  url = "jdbc:mysql://localhost:3306/rundeck"
  driverClassName = "org.mariadb.jdbc.Driver"
  username = "<DB-USER>"
  password = "<DB-PASSWORD>"
  dialect = ""
}
```

**Comment by MegaDrive68k** [comment]
Hi @ronnie-hoffmann 

I tested a fresh 4.5.0 and it works with the following config on the `rundeck-config.properties` file:

```
dataSource.dbCreate = none
dataSource.driverClassName = org.postgresql.Driver
dataSource.url = jdbc:postgresql://postgresql_host/rundeck_db_name
dataSource.username = user
dataSource.password = passwd
```

I followed [this](https://docs.rundeck.com/docs/administration/configuration/database/postgres.html#using-postgres-as-a-database-backend) to create PostgreSQL.

Regards.

**Comment by ronnie-hoffmann** [comment]
Hi @MegaDrive68k ,

that solve my problem.

Thanks
