### ISSUE TITLE
Azure Database for PostgreSQL – Flexible Server Pool Problem

### ISSUE THREAD

**Issue by larsrei** [rundeck/rundeck#7902]
**Describe the bug**
When we use Rundeck with a PostgreSQL in Azure on a Flexible Server, than we become a Connection Pool error

epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web [2022-09-12T08:08:28,037] ERROR pool.ConnectionPool - Unable to create initial connections of pool.
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web org.postgresql.util.PSQLException: The connection attempt failed.
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331) ~[postgresql-42.3.3.jar!/:42.3.3]

**My Rundeck detail**

* Rundeck version: 4.6.0
* install type: docker
* DB Type/version: postgres

**To Reproduce**
1. Create new container in Docker and start it
2. Config is postgres in azure
3. after running Spring Security Core

configuration for Container
         - name: RUNDECK_PROJECTSSTORAGETYPE
            value: "db"
          - name: RUNDECK_DATABASE_DRIVER
            value: "org.postgresql.Driver"
          - name: RUNDECK_DATABASE_USERNAME
            value: "${RUNDECKUSER}"
          - name: RUNDECK_DATABASE_PASSWORD
            value: "${RUNDECKUSERPW}"
          - name: RUNDECK_DATABASE_URL
            value: "jdbc:postgresql://${DATABASE}/rundeck?autoReconnect=true&useSSL=true&allowPublicKeyRetrieval=true"

**Expected behavior**
Server will not come up and will not working

**Desktop (please complete the following information):**
 - OS: MAC OS or Windows 10
 - Browser Chrome, Firefox
 - Version Firefox 104.0.2

**Additional context**
Is pgBouncer needed ?
https://docs.microsoft.com/de-de/azure/postgresql/flexible-server/concepts-pgbouncer

Longer output from error:

epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 2022-09-12T08:07:42.093Z [INFO]  target config out of sync: config=/home/rundeck/server/config/jaas-loginmodule.conf prefix=remco[17] resource=jaas-loginmodule.conf.toml
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 2022-09-12T08:07:42.093Z [INFO]  target config has been updated: config=/home/rundeck/server/config/jaas-loginmodule.conf prefix=remco[17] resource=jaas-loginmodule.conf.toml
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web [2022-09-12T08:07:52,482] INFO  rundeckapp.Application - The following 1 profile is active: "production"
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web Configuring Spring Security Core ...
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web ... finished configuring Spring Security Core
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web [2022-09-12T08:08:28,037] ERROR pool.ConnectionPool - Unable to create initial connections of pool.
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web org.postgresql.util.PSQLException: The connection attempt failed.
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331) ~[postgresql-42.3.3.jar!/:42.3.3]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.3.jar!/:42.3.3]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.3.jar!/:42.3.3]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.postgresql.Driver.makeConnection(Driver.java:400) ~[postgresql-42.3.3.jar!/:42.3.3]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.postgresql.Driver.connect(Driver.java:259) ~[postgresql-42.3.3.jar!/:42.3.3]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:319) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:744) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:676) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:483) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107) ~[tomcat-jdbc-9.0.44.jar!/:?]
epn-rundeck-web-6fd7cc88f6-9jstt epn-rundeck-web 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131) ~[tomcat-jdbc-9.0.44.jar!/:?]
.....

**Comment by larsrei** [comment]
Version 4.6.1 clear the problem. Now it works
