### ISSUE TITLE
Versions AFTER 4.4.0.20220714-1 fail to bootstrap new Postgres database

### ISSUE THREAD

**Issue by erhhung** [rundeck/rundeck#7937]
Rundeck server **versions after 4.4.0.20220714-1** (currently **4.6.1.20220914-1, 4.6.0.20220906-1, and 4.5.0.20220811-1**) fail to start when **bootstrapping a NEW/EMPTY PostgreSQL database** (using these settings in "`rundeck-config.properties`":

```properties
dataSource.dbCreate = update
dataSource.url = jdbc:postgresql://i-0f723f860dc916648.us-west-2.compute.internal:5432/rundeck?sslmode=require
dataSource.username = rundeck_user
dataSource.password = rundeck_pass
dataSource.driverClassName = org.postgresql.Driver
```

On versions 4.6.0.20220906-1 or later:

```log
Configuring Spring Security Core ...
... finished configuring Spring Security Core

[2022-09-29T21:21:28,512] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:21:28,513] WARN  spi.SqlExceptionHelper - constraint "uk_pl6hleyex3ofoaklduhbyretw" of relation "auth_token" does not exist, skipping
[2022-09-29T21:21:28,554] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:21:28,555] WARN  spi.SqlExceptionHelper - constraint "uk_trqsa9so0qcv6okcd6fan88yf" of relation "log_file_storage_request" does not exist, skipping
[2022-09-29T21:21:28,565] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:21:28,566] WARN  spi.SqlExceptionHelper - constraint "uk_3k75vvu7mevyvvb5may5lj8k7" of relation "project" does not exist, skipping
[2022-09-29T21:21:28,572] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:21:28,573] WARN  spi.SqlExceptionHelper - constraint "uk_9dh5owjlbb2x223gopaq6t0jm" of relation "report_filter" does not exist, skipping
[2022-09-29T21:21:28,580] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:21:28,580] WARN  spi.SqlExceptionHelper - constraint "uk_4t4ehlssm8lvaxieybr42ow5x" of relation "scheduled_execution" does not exist, skipping
[2022-09-29T21:21:28,587] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:21:28,587] WARN  spi.SqlExceptionHelper - constraint "uk_ow5u86267bvtsol1k9xsox40i" of relation "storage" does not exist, skipping
Running Changeset: core/HibernateIndex.groovy::3.4.0-1::rundeckuser (generated)
Running Changeset: core/AuthToken.groovy::3.4.0-2::rundeckuser (generated)
Running Changeset: core/BaseReport.groovy::3.4.0-3::rundeckuser (generated)
Running Changeset: core/Execution.groovy::3.4.0-4::rundeckuser (generated)
Running Changeset: core/JobFileRecord.groovy::3.4.0-6::rundeckuser (generated)
Running Changeset: core/JobFileRecord.groovy::3.4.0-7::rundeckuser (generated)
Running Changeset: core/LogFileStorageRequest.groovy::3.4.0-8::rundeckuser (generated)
Running Changeset: core/NodeFilter.groovy::3.4.0-9::rundeckuser (generated)
Running Changeset: core/Notification.groovy::3.4.0-10::rundeckuser (generated)
Running Changeset: core/Orchestrator.groovy::3.4.0-11::rundeckuser (generated)
Running Changeset: core/PluginMeta.groovy::3.4.0-12::rundeckuser (generated)
Running Changeset: core/Project.groovy::3.4.0-13::rundeckuser (generated)
Running Changeset: core/ReferencedExecution.groovy::3.4.0-17::rundeckuser (generated)
Running Changeset: core/RDUSER.groovy::3.4.0-16::rundeckuser (generated)
Running Changeset: core/ReportFilter.groovy::3.4.0-18::rundeckuser (generated)
Running Changeset: core/ScheduledExecution.groovy::3.4.0-19::rundeckuser (generated)
Running Changeset: core/ScheduledExecution.groovy::3.4.0-20::rundeckuser (generated)
Running Changeset: core/ScheduledExecution.groovy::3.4.0-21::rundeckuser (generated)
Running Changeset: core/Storage.groovy::3.4.0-23::rundeckuser (generated)
Running Changeset: core/StoredEvent.groovy::3.4.0-24::rundeckuser (generated)
Running Changeset: core/Workflow.groovy::3.4.0-26::rundeckuser (generated)
Running Changeset: core/Workflow.groovy::3.4.0-27::rundeckuser (generated)
Running Changeset: core/Workflow.groovy::3.4.0-28::rundeckuser (generated)
Running Changeset: core/RDOPTION.groovy::3.4.0-14::rundeckuser (generated)
Running Changeset: core/RDOPTION.groovy::3.4.0-15::rundeckuser (generated)
Running Changeset: core/Webhook.groovy::3.4.0-25::rundeckuser (generated)
Running Changeset: core/Webhook.groovy::3.4.11-webhook-auth_config_json::Stephen Joyner
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-29::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-30::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-31::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-32::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-33::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-34::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-35::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-36::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-37::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-38::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-39::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-40::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-41::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-42::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-43::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-44::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-45::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-46::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-47::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-48::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-49::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-50::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-51::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-52::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-53::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-54::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-55::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-56::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-57::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-58::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-59::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-60::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-61::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-62::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-63::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-64::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-65::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-66::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-67::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-68::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-69::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-70::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-71::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-72::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-73::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-74::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-75::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-76::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-77::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-scm-fixes::rundeckuser (generated)
Running Changeset: core/ConstraintsIndexesKeys.groovy::3.4.0-scm-fixes2::rundeckuser (generated)
Running Changeset: core/WorkflowStep.groovy::1619468434682::rundeckuser (generated)
Running Changeset: core/Tag-3.4.0.groovy::tag-3.4.0::rundeckuser (generated)
Running Changeset: core/Tag-3.4.4.groovy::tag-3.4.4::rundeckuser (generated)
Running Changeset: core/Tag-3.4.7.groovy::tag-3.4.7::rundeckuser (generated)
Running Changeset: core/Tag-4.0.0.groovy::tag-4.0.0::rundeckuser (generated)
Running Changeset: core/ExecReportJcExecIdToExecutionId.groovy::1653344096108-5::gschueler (generated)
Running Changeset: core/ExecReportJcExecIdToExecutionId.groovy::1653344096108-52::gschueler (generated)
[2022-09-29T21:22:05,759] ERROR boot.SpringApplication - Application run failed
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set core/ExecReportJcExecIdToExecutionId.groovy::1653344096108-52::gschueler (generated):
     Reason: liquibase.exception.DatabaseException: ERROR: column "jc_exec_id" does not exist
  Position: 44 [Failed SQL: (0) update base_report set execution_id = cast(JC_EXEC_ID as bigint)]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.runInScope(Liquibase.java:2405) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314) ~[liquibase-core-4.8.0.jar!/:?]
	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.performUpdate(GrailsLiquibase.groovy:81) ~[database-migration-4.1.0-plain.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.8.0.jar!/:?]
	at org.springframework.beans.factory.InitializingBean$afterPropertiesSet.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.grails.plugins.databasemigration.DatabaseMigrationGrailsPlugin$_doWithApplicationContext_closure2$_closure5.doCall(DatabaseMigrationGrailsPlugin.groovy:85) ~[database-migration-4.1.0-plain.jar!/:?]
```

On version 4.5.0.20220811-1:

```log
Configuring Spring Security Core ...
... finished configuring Spring Security Core

[2022-09-29T21:27:52,533] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:27:52,534] WARN  spi.SqlExceptionHelper - constraint "uk_pl6hleyex3ofoaklduhbyretw" of relation "auth_token" does not exist, skipping
[2022-09-29T21:27:52,575] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:27:52,578] WARN  spi.SqlExceptionHelper - constraint "uk_trqsa9so0qcv6okcd6fan88yf" of relation "log_file_storage_request" does not exist, skipping
[2022-09-29T21:27:52,585] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:27:52,586] WARN  spi.SqlExceptionHelper - constraint "uk_3k75vvu7mevyvvb5may5lj8k7" of relation "project" does not exist, skipping
[2022-09-29T21:27:52,592] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:27:52,592] WARN  spi.SqlExceptionHelper - constraint "uk_9dh5owjlbb2x223gopaq6t0jm" of relation "report_filter" does not exist, skipping
[2022-09-29T21:27:52,600] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:27:52,600] WARN  spi.SqlExceptionHelper - constraint "uk_4t4ehlssm8lvaxieybr42ow5x" of relation "scheduled_execution" does not exist, skipping
[2022-09-29T21:27:52,607] WARN  spi.SqlExceptionHelper - SQL Warning Code: 0, SQLState: 00000
[2022-09-29T21:27:52,607] WARN  spi.SqlExceptionHelper - constraint "uk_ow5u86267bvtsol1k9xsox40i" of relation "storage" does not exist, skipping
[2022-09-29T21:28:28,038] ERROR boot.SpringApplication - Application run failed
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set core/ExecReportJcExecIdToExecutionId.groovy::1653344096108-52::gschueler (generated):
     Reason: liquibase.exception.DatabaseException: ERROR: column "jc_exec_id" does not exist
  Position: 44 [Failed SQL: (0) update base_report set execution_id = cast(JC_EXEC_ID as bigint)]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.child(Scope.java:240) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Liquibase.runInScope(Liquibase.java:2404) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.6.2.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314) ~[liquibase-core-4.6.2.jar!/:?]
	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.performUpdate(GrailsLiquibase.groovy:81) ~[database-migration-4.1.0-plain.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.6.2.jar!/:?]
```

**My Rundeck detail**

* Rundeck version: 4.6.1.20220914-1
* install type: rpm
* OS Name/version: Amazon Linux 2
* DB Type/version: PostgreSQL

**To Reproduce**

1. Version 4.6.1.20220914-1 fails to start with a new Postgres database.
2. Downgrade to version 4.6.0.20220906-1: `sudo yum downgrade rundeck`
3. Wipe Rundeck database (drop all objects):
```sql
DROP TABLE auth_token,base_report,databasechangelog,databasechangeloglock,execution,job_file_record,log_file_storage_request,node_filter,notification,orchestrator,plugin_meta,project,rdoption,rdoption_values,rduser,referenced_execution,report_filter,scheduled_execution,scheduled_execution_filter,scheduled_execution_stats,storage,stored_event,webhook,workflow,workflow_step,workflow_workflow_step CASCADE;
DROP SEQUENCE hibernate_sequence;
```
4. Start server and watch it fail with exceptions in "`service.log`".
5. Repeat steps 2 to 4 with versions 4.5.0.20220811-1 and then 4.4.0.20220714-1.
6. **Version 4.4.0.20220714-1 starts up fine**.
7. Now upgrade to version 4.6.1.20220914-1 and **reuse already bootstrapped database**.
8. Server finally starts up fine.

**Expected behavior**

Rundeck server should bootstrap an empty (Postgres) database upon startup.

**Comment by MegaDrive68k** [comment]
Hi, 

Tested with the following config (on 4.6.0) against an empty PostgreSQL 10 backend:

```
dataSource.url = jdbc:postgresql://postgres/rundeck?autoReconnect=true&useSSL=false
dataSource.username = rundeck
dataSource.password = rundeck
dataSource.driverClassName = org.postgresql.Driver
```

In your case test without the `dataSource.dbCreate = update` parameter.

Hope it helps.

**Comment by erhhung** [comment]
@MegaDrive68k Thanks for the tip! I've tried the latest 4.6.1 with an empty Postgres 14, and omitting `dataSource.dbCreate` does indeed work, so I wonder if this is a non-issue.

I think Rundeck should at least log a message saying that `dataSource.dbCreate` has been set but shouldn't be and why, and that it will simply ignore it.

**Comment by roronoall** [comment]
@MegaDrive68k I have the same problem, I have indeed changed the modifications indicated, but the error still appears

**Comment by roronoall** [comment]
here is my config 


# change hostname here
grails.serverURL=http://ip_host:4440
#dataSource.dbCreate = update
#dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=MONTH,HOUR,MINUTE,YEAR,SECONDS
dataSource.driverClassName = org.postgresql.Driver
dataSource.url = jdbc:postgresql://ip_host:5432/rundeckdb
dataSource.username = rundeck
dataSource.password = password
#grails.plugin.databasemigration.updateOnStart=true

**Comment by russellliss** [comment]
I got it to work by dropping all my tables and sequences, as well as commented out the dataSource.dbCreate line.  Without dropping the tables, even commenting it out didn't make any difference.

**Comment by roronoall** [comment]
@russellliss thank you very much, you solved my case

**Comment by Prabodh-07** [comment]
> I got it to work by dropping all my tables and sequences, as well as commented out the dataSource.dbCreate line. Without dropping the tables, even commenting it out didn't make any difference.

But droppping tables will loose all the data , database contains all projects and job which was created. isn't there any other solution ?
