### ISSUE TITLE
Error sending notification - Rundeck 4.7.0

### ISSUE THREAD

**Issue by davidarellanoald** [rundeck/rundeck#8045]
**Describe the bug**
When I configure sending a mail notification in Rundeck 4.7.0 when job stars, the job is stucked and never starts.

**My Rundeck detail**
* Rundeck version: 4.7.0
* install type: War
* OS Name/version: Redhat 8
* DB Type/version: Microsoft SQL Server

**To Reproduce**
1. Configure sending a mail notification in Rundeck 4.7.0 when job stars
2. Start the job manually
3. The job is stucked and never starts.

**Expected behavior**
I expect to receive a mail with the notification when starting job

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version 108.0.1462.46 

**Additional context**
If I set a timeout: 
```
rundeck.feature.notificationsOwnThread.enabled=true
rundeck.notification.threadTimeOut=3000
grails.mail.host=localhost
grails.mail.port=25
```

I receive this exception in logs and job finishes normally
```
[2022-11-24T09:53:24,569] ERROR services.NotificationService - Error sending notification
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:1.8.0_322]
        at org.grails.async.factory.future.FutureTaskPromise.get(FutureTaskPromise.groovy:58) ~[grails-async-4.0.0.jar!/:?]
        at java_util_concurrent_Future$get$0.call(Unknown Source) ~[?:?]
        at rundeck.services.NotificationService.$tt__asyncTriggerJobNotification(NotificationService.groovy:190) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_322]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_322]
```

I have also confirmed mail is working ok by sending a mail directly from a Job.
```
mail -s "Hi" [X...@yyy.com](https://groups.google.com/) <<< 'Mensaje'
```

Related to discussion https://groups.google.com/g/rundeck-discuss/c/WVmNXb3jVWs

**Comment by MegaDrive68k** [comment]
Reproduced, it happens on 4.8.0 too.

Thanks @davidarellanoald!

**Comment by fdevans** [comment]
This issue was already picked up and is being tracked in our internal backlog. Since we can't confirm its current resolution status from here, we're closing the GitHub copy as part of a broader tracker cleanup.

If you're still experiencing this on a currently supported version (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html)), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps, rather than reopening this one — that ensures it's tracked against your current environment.

Thanks,
The Rundeck Team
