### ISSUE TITLE
Failed to compile CreateJob.groovy  with Grails run-app

### ISSUE THREAD

**Issue by leandroidvlab** [rundeck/rundeck#8093]
When I try to run the rundeck with command `grails run-app` I get `Failed to compile CreateJob.groovy`

**System Info**
OS: Fedora 37
Java 8 OpenJDK
Grails 5.1.9
Gradle 7.4.2
Node 16.13.0

**Screenshots**
![image](https://user-images.githubusercontent.com/99025208/212930000-9f0cd6d4-d837-460b-aaeb-c6f199229d2c.png)

**Full StackTrace**
```
| Error Failed to compile CreateJob.groovy: io.micronaut.core.io.service.SoftServiceLoader.firstAvailable()Ljava/util/Optional;
java.lang.NoSuchMethodError: io.micronaut.core.io.service.SoftServiceLoader.firstAvailable()Ljava/util/Optional;
        at io.micronaut.ast.groovy.annotation.GroovyAnnotationMetadataBuilder.<init>(GroovyAnnotationMetadataBuilder.java:102)
        at io.micronaut.ast.groovy.utils.AstAnnotationUtils$_getAnnotationMetadata_closure1.doCall(AstAnnotationUtils.groovy:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:110)
        at com.sun.proxy.$Proxy19.apply(Unknown Source)
        at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
        at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
        at io.micronaut.ast.groovy.utils.AstAnnotationUtils.getAnnotationMetadata(AstAnnotationUtils.groovy:54)
        at io.micronaut.ast.groovy.visitor.LoadedVisitor.matches(LoadedVisitor.groovy:125)
        at io.micronaut.ast.groovy.TypeElementVisitorTransform$_visit_closure1.doCall(TypeElementVisitorTransform.groovy:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
        at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:49)
        at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:52)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4914)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4786)
        at io.micronaut.ast.groovy.TypeElementVisitorTransform.visit(TypeElementVisitorTransform.groovy:85)
        at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:337)
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:288)
        at org.grails.cli.profile.commands.factory.GroovyScriptCommandFactory.readCommandFile(GroovyScriptCommandFactory.groovy:50)
        at org.grails.cli.profile.commands.factory.GroovyScriptCommandFactory.readCommandFile(GroovyScriptCommandFactory.groovy)
        at org.grails.cli.profile.commands.factory.ResourceResolvingCommandFactory.findCommands(ResourceResolvingCommandFactory.groovy:44)
        at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy:86)
        at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy)
        at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:432)
        at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:130)
        at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:462)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Failed to compile CreateJob.groovy: io.micronaut.core.io.service.SoftServiceLoader.firstAvailable()Ljava/util/Optional;
| Error Command [run-app] error: null
java.lang.NullPointerException
        at org.grails.cli.profile.commands.factory.GroovyScriptCommandFactory.createCommand(GroovyScriptCommandFactory.groovy:85)
        at org.grails.cli.profile.commands.factory.GroovyScriptCommandFactory.createCommand(GroovyScriptCommandFactory.groovy)
        at org.grails.cli.profile.commands.factory.ResourceResolvingCommandFactory.findCommands(ResourceResolvingCommandFactory.groovy:46)
        at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy:86)
        at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy)
        at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:432)
        at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:130)
        at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:462)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
        at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Command [run-app] error: null```

**Comment by leandroidvlab** [comment]
I tested the `./run.sh` inside rundeckapp and the version 4.8.0 and below is not affected with this bug, just the latest version 4.9.0
