### ISSUE TITLE
column "jc_exec_id" does not exist RUNDECK ROCKY 8

### ISSUE THREAD

**Issue by roronoall** [rundeck/rundeck#8129]
Hi I am trying to install unrdeck under rocky 8 but I get this error message when I check the log

My Rundeck detail

 
   Rundeck version: rundeck-4.9.0.
   install type: VM azure
   OS Name/version: ROCKY 8
   DB Type/version: postgres

      [[2023-02-03T14:57:34,343] INFO  rundeckapp.Application - The following 1 profile is active: "production"

      Configuring Spring Security Core ...
      finished configuring Spring Security Core

      Running Changeset: core/ExecReportJcExecIdToExecutionId.groovy::1653344096108-52::gschueler (generated)
      [2023-02-03T14:58:44,239] ERROR boot.SpringApplication - Application run failed

      liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set  core / ExecReportJcExecIdToExecutionId.groovy::1653344096108-52::gschueler (generated):

      Reason: liquibase.exception.DatabaseException: ERROR: column "jc_exec_id" does not exist
     Position: 44 [Failed SQL: (0) update base_report set execution_id = cast(JC_EXEC_ID as bigint)]
      at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126) ~[liquibase-core-4.8.0.jar!/:?]
      at liquibase.Liquibase.lambda$null$0(Liquibase.java:265) ~[liquibase-core-4.8.0.jar!/:?]
      at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
      at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
      at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
      at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
     4.1.0-plain.jar!/:?]
      org.grails.plugins.databasemigration.DatabaseMigrationGrailsPlugin$_doWithApplicationContext_closure2$_closure5.doCall(DatabaseMigrationGrailsPlugin.groovy:85) ~[database-migration-4.1.0-plain.jar!/:?]]

here is my config

     #change hostname here
     grails.serverURL=http://ip_host:4440
     #dataSource.dbCreate = update
     #dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb; DB_CLOSE_ON_EXIT = FALSENON_KEYWORDS = MONTH, HOUR,MINUTE,YEAR,SECONDS
     dataSource.driverClassName = org.postgresql.Driver
     dataSource.url = jdbc:postgresql://ip_host:5432/rundeckdb
     dataSource.username = rundeck
     dataSource.password = password
    #grails.plugin.databasemigration.updateOnStart=true.>

**Comment by grin31** [comment]
Hi.
`rundeck/now 4.9.0.20230111-1`
After first run, got the same issue:

```
Caused by: liquibase.exception.DatabaseException: ERROR: column "jc_exec_id" does not exist
  Position: 44 [Failed SQL: (0) update base_report set execution_id = cast(JC_EXEC_ID as bigint)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:397) ~[liquibase-core-4.8.0.jar!/:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83) ~[liquibase-core-4.8.0.jar!/:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151) ~[liquibase-core-4.8.0.jar!/:?]
        ....
        ....
```

**Comment by roronoall** [comment]
@grin31 
I followed to "russellliss" what said in the link below, I deleted the tables with DROP SCHEMA public CASCADE;
and I recreated a new database and restarted rundeck, everything was OK
https://github.com/rundeck/rundeck/issues/7937
