### ISSUE TITLE
java.lang.NullPointerException when running Executing inline script

### ISSUE THREAD

**Issue by humerarehman** [rundeck/rundeck#8142]
**Issue type:** Bug report

**Describe the bug**
When i try to execute script (inline) I get the **java.lang.NullPointerException**. 

Full Stack trace (Debug log) of the job run is below:

`[workflow] Begin step: 3,NodeDispatch
3: Workflow step executing: ScriptFileItem{script=[23 chars]}
preparing for sequential execution on 1 nodes
Executing command on node: rundeck1, NodeEntryImpl{tags=[], attributes={nodename=rundeck1, hostname=rundeck.prod.us-east-1.int.hubdoc.com, osVersion=5.4.0-1089-aws, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux}, project='null'}
[workflow] beginExecuteNodeStep(rundeck1): NodeDispatch: ScriptFileItem{script=[23 chars]}
[workflow] finishExecuteNodeStep(rundeck1): NodeDispatch: Unknown: null
Failed dispatching to node rundeck1: java.lang.NullPointerException
Failed dispatching to node rundeck1: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: java.lang.NullPointerException
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:221)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:130)
	at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:61)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:263)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:234)
	at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:111)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:285)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:681)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:76)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:32)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$beginOperation$1(WorkflowEngineOperationsProcessor.java:323)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at com.dtolabs.rundeck.core.execution.script.ScriptfileUtils.createTempFile(ScriptfileUtils.java:301)
	at com.dtolabs.rundeck.core.execution.impl.common.DefaultFileCopierUtil.writeScriptTempFile(DefaultFileCopierUtil.java:134)
	at com.dtolabs.rundeck.core.execution.impl.common.DefaultFileCopierUtil.writeScriptTempFile(DefaultFileCopierUtil.java:83)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.writeScriptToTempFile(DefaultScriptFileNodeStepUtils.java:184)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:110)
	at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:81)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:207)
	... 18 more
3: Workflow step finished, result: NodeDispatchFailure: Failed dispatching to node rundeck1: java.lang.NullPointerException
[workflow] Finish step: 3,NodeDispatch`

**I get the same error when I try and run **adhoc** command using rd-cli as well.**

`rundeck@rundeck1:~$ rd adhoc -s /tmp/rundeck-get-running-executions.sh  -p TestProject -v -T 10
# Immediate execution scheduled (138)
failedNodes:
  description: #!/bin/bash (5 more lines)
  project: TestProject
  successfulNodes:
  argstring:
  serverUUID: 8b3d419f-7670-48b6-a9f2-731aa9449642
  dateStarted: 2023-02-09T22:38:57Z
  dateEnded:
  id: 138
  href: http://localhost:4441/api/42/execution/138
  permalink: http://localhost:4441/project/TestProject/execution/show/138
  adhoc: true
  user: admin
  status: running`

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.10]
* install type: [choose: rpm,deb,war,docker] : Installed using Ansible Galaxy role https://galaxy.ansible.com/robertdebock/rundeck

* OS Name/version: Ubuntu 18.04.6 LTS
* DB Type/version: mariadb

RUNDECK
APIVERSION : 42
BASE : /opt/rundeck
BUILD : 4.9.0-20230111
BUILDGIT : v4.9.0-0-gdf38b6a
NODE : rundeck1
SERVERUUID : 8brundeck1
VERSION : 4.9.0-20230111

JVM
IMPLEMENTATIONVERSION : 11.0.17+8-post-Ubuntu-1ubuntu218.04
NAME : OpenJDK 64-Bit Server VM
VENDOR : Ubuntu
VERSION : 11.0.17

OS
ARCH : amd64
NAME : Linux
VERSION : 5.4.0-1089-aws

**To Reproduce**
1. Create new project.
2. Create a new job in that project, click on Workflow tab.
3. Add a step, select **Script - Execute an inline script**.
4. Add these 2 lines in the script box:
`#!/bin/bash
whoami`
5. Ensure Nodes tab is set to `Execute locally`.
6. On the `Other` tab, select Log level Debug. 
7. Hit save, hit save and run the job.
8. You will get an error **Unknown:java.lang.NullPointerException**

**Expected behavior**
It should successfully execute. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs Ventura 13.1
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 109.0.5414.119 

**Additional context**
If the step type is set to **Command** or **Script file or URL**, both succeed/run fine. The issue only seems to occur with **in-line Script** step type.

**Comment by humerarehman** [comment]
Closing issue as this seems related to [this](https://galaxy.ansible.com/robertdebock/rundeck) playbook, not the new version of Rundeck.

**Comment by jhanssenfavaro** [comment]
What exactly was wrong with this @humerarehman ? I am having same issue right now.
