### ISSUE TITLE
LDAP: error code 12 - Unknown control 1.2.840.113556.1.4.319"

### ISSUE THREAD

**Issue by riverfell** [rundeck/rundeck#8273]
**Describe the bug**
got an error when login with ldap: 

`[LDAP: error code 12 - Unknown control 1.2.840.113556.1.4.319]`

**My Rundeck detail**

* Rundeck version: 4.11
* install type: rpm
* OS Name/version: centos 8
* DB Type/version: mysql

**Here is log**
`[2023-04-20T17:42:54,406] DEBUG jaas.JettyCachingLdapLoginModule - Cache Miss for xxx.
[2023-04-20T17:42:54,406] DEBUG jaas.JettyCachingLdapLoginModule - Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: ou=people,dc=xxx,dc=com
[2023-04-20T17:42:54,475] DEBUG jaas.JettyCachingLdapLoginModule - Found user?: true
[2023-04-20T17:42:54,476] INFO  jaas.JettyCachingLdapLoginModule - Attempting authentication: uid=xxx,ou=people,dc=xxx,dc=com
javax.naming.OperationNotSupportedException: [LDAP: error code 12 - Unknown control 1.2.840.113556.1.4.319]; remaining name 'ou=group,dc=xxx,dc=com'
        at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3321)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3207)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2998)
        at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1874)
        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1797)
        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1814)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:418)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:396)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:378)
        at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:286)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getPaginatedRoles(JettyCachingLdapLoginModule.java:552)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getUserRolesByDn(JettyCachingLdapLoginModule.java:474)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.bindingLogin(JettyCachingLdapLoginModule.java:932)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.authenticate(JettyCachingLdapLoginModule.java:822)
        at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.login(JettyCachingLdapLoginModule.java:747)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
`

Seems my ldap server doesn't support page result. How could i get rundeck work with my ldap server?

**Comment by FloBEAUG** [comment]
Same here.
I have looked into the jaas-ldap.conf documentation to see if there is some parameters to disable the PagedResultsControl in the LDAP request but I found nothing.

**Comment by FloBEAUG** [comment]
Hello again,

I have to install a new instance and the problem is still not solved under 4.14.1 
Any updates please ?

**Comment by riverfell** [comment]
> Hello again,
> 
> I have to install a new instance and the problem is still not solved under 4.14.1 Any updates please ?

My way to solve: use jenkins

**Comment by rajanshtha** [comment]
I have encountered the similar issue ( javax.naming.OperationNotSupportedException: [LDAP: error code 12 - Unavailable Critical Extension] ) while attempting to upgrade Rundeck docker to the latest version 4.16.0.

Not able to upgrade beyond version 4.10.2 and waiting for this issue to be resolved.

**Comment by palto42** [comment]
I faced the same issue and found that the binddn for group search is empty.

In my config I had `RUNDECK_JAAS_LDAP_BINDDN` was not defined and `RUNDECK_JAAS_LDAP_FORCEBINDINGLOGIN=true` which is supposed to use the user credentials for the bind of the group search (which worked on older Rundeck releases).
With latest release this doesn't seem to work anymore.

My workaround is to configure  `RUNDECK_JAAS_LDAP_BINDDN`  and the related `RUNDECK_JAAS_LDAP_BINDPASSWORD=****`.

**Comment by palto42** [comment]
For me actually adding `rolePagination=“false”` in `server/config/jaas-loginmodule.conf` solved the issue.

The problem with docker based setups is that the current remco template `/home/rundeck/server/config/jaas-loginmodule.conf` doesn't contain this setting. My solution is to map a modified file via the docker volume map.

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
