### ISSUE TITLE
Variation on job execution times - Rundeck 4.3.2

### ISSUE THREAD

**Issue by kevinpemonon** [rundeck/rundeck#8304]
Hello,

We use rundeck 4.3.2, postgresql and the OS is Windows.

We notice on all our jobs a great variation of execution time that goes from a few seconds to 10 minutes depending on the moment.

In the rundeck log files, we find this recurring error : 

######################################################################################################
[2022-11-09T12:22:20,271] ERROR session.Session [Packet Reader for xxx] - Caught exception while closing TreeConnect with id: 1
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Relais brisé (pipe) (Write failed)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:71) ~[smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.connection.Connection.send(Connection.java:240) ~[smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.session.Session.send(Session.java:208) ~[smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:61) ~[smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.share.Share.close(Share.java:90) ~[smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.session.Session.logoff(Session.java:157) [smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.session.Session.close(Session.java:190) [smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.connection.Connection.close(Connection.java:128) [smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.connection.Connection.close(Connection.java:113) [smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:404) [smbj-0.3.0.jar:?]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:53) [smbj-0.3.0.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.net.SocketException: Relais brisé (pipe) (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[?:?]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[?:?]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:69) ~[smbj-0.3.0.jar:?]
	... 11 more
######################################################################################################

For example for the execution of a simple job, which only displays "coucou", the job can also last up to 10 min and we have these logs for the execution of the job: 

######################################################################################################
[workflow] beginExecuteNodeStep(xxx): NodeDispatch: ScriptFileItem{script=[19 chars]}
[xxx] 
[xxx] ConnectionOptions[
	connectionTimeoutMillis --> 28800000
	winrmEnableHttps --> false
	 --> fr_fr
	winrmKerberosDebug --> false
	address --> xxx
	winrmKerberosUseHttpSpn --> false
	os --> WINDOWS
	winrmKerberosAddPortToSpn --> false
	file-copy-destination-dir --> c:\
	connectionType --> WINRM_INTERNAL
	password --> ********
	winrmKerberosTicketCache --> false
	port --> 5985
	winrmTimeout --> PT28800.000S
	username --> xxx
]
[xxx] Destination file acquired xxx
[xxx] Copying file to xxx
[xxx] File copied at: xxx
[xxx] Closing connection
[xxx] powershell Powershell.exe -executionpolicy bypass -File xxx
[xxx] ConnectionOptions[
	connectionTimeoutMillis --> 28800000
	winrmEnableHttps --> false
	 --> fr_fr
	winrmKerberosDebug --> false
	address --> xxx
	winrmKerberosUseHttpSpn --> false
	os --> WINDOWS
	winrmKerberosAddPortToSpn --> false
	connectionType --> WINRM_INTERNAL
	password --> ********
	winrm-cmd --> PowerShell
	winrmKerberosTicketCache --> false
	port --> 5985
	winrmTimeout --> PT28800.000S
	username --> xxx
]
coucou
######################################################################################################

Could you help us understand why job execution times vary so much and how to solve this problem?

Among the transmitted logs, the "xxx" annotations are meant to hide sensitive data, I hope that these remain sufficiently understandable.

We remain at your disposal to provide you with any additional information.

Thank you in advance for your time and for your help 

With kind regards,

**Comment by kevinpemonon** [comment]
Hello everyone,

Does anyone have a lead to explore regarding the above problem?

For information after verification here is the architecture used: 

Rundeck 4.3.2 and Postgres 11.18 installed on Debian 10
Powershell scripts are on Windows servers.

I remain at your disposal for any information necessary to solve our problem.

Best regards,
