### ISSUE TITLE
Rundeck service.log error pool.ConnectionPool - Failed to re-connect connection expired because of maxAge

### ISSUE THREAD

**Issue by dspiersaustin** [rundeck/rundeck#8324]
**Describe the bug**
Recurring issue in Rundeck system.log "ERROR pool.ConnectionPool - Failed to re-connect connection [org.apache.tomcat.jdbc.pool.ConnectionPool@...] that expired because of maxAge"

* Rundeck version: 4.2.1
* install type: rpm
* OS Name/version: RHEL 7.9
* DB Type/version:  mssql - Azure Managed Instance

DB driver = mssql-jdbc-6.4.0.jre8.jar
Java =jdk1.8.0_361

**To Reproduce**
1. Install Rundeck 4.2.1 connected to mssql - Azure Managed Instance
2. Confirm installation with test job that can be executed with Rundeck configuration.
3. Search for reported issue in system.log after 24 hours.
4. See error:
"ERROR pool.ConnectionPool - Failed to re-connect connection [org.apache.tomcat.jdbc.pool.ConnectionPool@...] that expired because of maxAge"

**Expected behavior**
Do not expect to see this connection error in logs.

**Additional context**
Full error below with masked data in < >

[2023-05-12T<HH:MM:SS>,<###>] ERROR pool.ConnectionPool - Failed to re-connect connection [org.apache.tomcat.jdbc.pool.ConnectionPool@...] that expired because of maxAge
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host sql-<abc123>.database.windows.net, port 1433 has failed. Error: "The timeout expired before connecting to the routing destination.". ClientConnectionId:<abc123>
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2670) ~[mssql-jdbc-6.4.0.jre8.jar!/:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2658) ~[mssql-jdbc-6.4.0.jre8.jar!/:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1976) ~[mssql-jdbc-6.4.0.jre8.jar!/:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762) ~[mssql-jdbc-6.4.0.jre8.jar!/:?]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077) ~[mssql-jdbc-6.4.0.jre8.jar!/:?]
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623) ~[mssql-jdbc-6.4.0.jre8.jar!/:?]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:319) ~[tomcat-jdbc-9.0.44.jar!/:?]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212) ~[tomcat-jdbc-9.0.44.jar!/:?]
        at org.apache.tomcat.jdbc.pool.PooledConnection.reconnect(PooledConnection.java:372) ~[tomcat-jdbc-9.0.44.jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.reconnectIfExpired(ConnectionPool.java:932) [tomcat-jdbc-9.0.44.jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.testAllIdle(ConnectionPool.java:1138) [tomcat-jdbc-9.0.44.jar!/:?]
        at org.apache.tomcat.jdbc.pool.ConnectionPool$PoolCleaner.run(ConnectionPool.java:1529) [tomcat-jdbc-9.0.44.jar!/:?]
        at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_361]
        at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_361]

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
