### ISSUE TITLE
URL node sources >3MB fail to process.

### ISSUE THREAD

**Issue by dbrowneihg** [rundeck/rundeck#8353]
**Describe the bug**
URL node sources >3MB fail to process.
This looks to be caused by the default 3MB code point limit introduced in SnakeYaml 1.32 ( https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes )

URL node source fails with error: 'The incoming YAML document exceeds the limit: 3145728 code points'  

service.log

```
[2023-05-29T14:19:42,752] ERROR resources.ExceptionCatchingResourceModelSource - [ResourceModelSource: 1.source (url), project: Patch_Framework-Linux]
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Error requesting URL Resource Model Source: http://localhost:3000/: Content could not be parsed: com.dtolabs.rundeck.core.common.NodeFileParserException: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.

Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
        at com.dtolabs.rundeck.core.resources.URLResourceModelSource.getNodes(URLResourceModelSource.java:318) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:58) [rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.DelegateResourceModelSource.getNodes(DelegateResourceModelSource.java:35) [rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:139) [rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:359) [rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:58) [rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source) [rundeck-core-4.13.0-20230515.jar!/:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) [groovy-3.0.9.jar!/:3.0.9]
        at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44) [classes!/:?]
        at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source) [classes!/:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) [groovy-3.0.9.jar!/:3.0.9]
        at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:320) [classes!/:?]
        at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.Closure.call(Closure.java:412) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.Closure.call(Closure.java:406) [groovy-3.0.9.jar!/:3.0.9]
        at com.codahale.metrics.Timer.time(Timer.java:118) [metrics-core-4.2.15.jar!/:4.2.15]
        at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:61) [grails-metricsweb-4.13.0-20230515-plain.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:182) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:112) [groovy-3.0.9.jar!/:3.0.9]
        at rundeck.services.NodeService$_loadNodes_closure6.doCall(NodeService.groovy:327) [classes!/:?]
        at rundeck.services.NodeService$_loadNodes_closure6.doCall(NodeService.groovy) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.9.jar!/:3.0.9]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.Closure.call(Closure.java:412) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.Closure.call(Closure.java:406) [groovy-3.0.9.jar!/:3.0.9]
        at groovy.lang.Closure.run(Closure.java:493) [groovy-3.0.9.jar!/:3.0.9]
        at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:286) [spring-core-5.3.27.jar!/:5.3.27]
        at java.lang.Thread.run(Thread.java:823) [?:1.8.0_292]
Caused by: com.dtolabs.rundeck.core.resources.format.ResourceFormatParserException: com.dtolabs.rundeck.core.common.NodeFileParserException: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
        at com.dtolabs.rundeck.core.resources.format.ResourceYamlFormatParser.parseDocument(ResourceYamlFormatParser.java:80) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.URLResourceModelSource.getNodes(URLResourceModelSource.java:314) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        ... 54 more
Caused by: com.dtolabs.rundeck.core.common.NodeFileParserException: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
        at com.dtolabs.rundeck.core.common.NodesYamlParser.parse(NodesYamlParser.java:130) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.format.ResourceYamlFormatParser.parseDocument(ResourceYamlFormatParser.java:78) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.URLResourceModelSource.getNodes(URLResourceModelSource.java:314) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        ... 54 more
Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:342) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryKey.produce(ParserImpl.java:611) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:239) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:208) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:270) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:210) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:134) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:168) ~[snakeyaml-1.33.jar!/:?]
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:499) ~[snakeyaml-1.33.jar!/:?]
        at com.dtolabs.rundeck.core.common.NodesYamlParser.parse(NodesYamlParser.java:81) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.format.ResourceYamlFormatParser.parseDocument(ResourceYamlFormatParser.java:78) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        at com.dtolabs.rundeck.core.resources.URLResourceModelSource.getNodes(URLResourceModelSource.java:314) ~[rundeck-core-4.13.0-20230515.jar!/:?]
        ... 54 more
```

**My Rundeck detail**

* Rundeck version: Rundeck 4.13.0
* install type: rpm
* OS Name/version: CentOS release 6.10 (Final)
* DB Type/version: mysql

**To Reproduce**
1. Go to Project Settings -> Edit node
2. Click on 'Add a new Node Source'
3. Select 'URL Source'
4. Input URL that returns YAML document > 3MB
5. Error is displayed:
The Node Source had an error:
Error requesting URL Resource Model Source: http://localhost:3000/ Content could not be parsed: com.dtolabs.rundeck.core.common.NodeFileParserException: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.

**Expected behavior**
Other projects are working around this by adding a configurable option. Ideally Rundeck would implement something similar.
Examples:
https://github.com/jruby/jruby/issues/7543
https://github.com/OpenAPITools/openapi-generator/issues/14096

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 113

**Additional context**
setCodePointLimit in snakeyaml documentation: https://javadoc.io/static/org.yaml/snakeyaml/1.32/org/yaml/snakeyaml/LoaderOptions.html#setCodePointLimit-int-

**Comment by dbrowneihg** [comment]
This is continuing to occur on the latest version of Rundeck (v5.4.0-20240618).
Any chance there will be a way to override the limit?

[2024-07-28T23:30:26,677] ERROR resources.ExceptionCatchingResourceModelSource - [ResourceModelSource: 2.source (url), project: GIO-Run]
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Error requesting URL Resource Model Source: http://localhost:3000/ Content could not be parsed: com.dtolabs.rundeck.core.common.NodeFileParserException: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
