### ISSUE TITLE
ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by nija1996** [rundeck/rundeck#8410]
**Describe the bug**
After update rundeck from 4.13.0 to 4.14.1 it doesn't start. The problem is that rundeck is trying to create a new index and oracle doesn't support identifier longer than 30 characters.

[2023-06-26T16:38:23,868] ERROR boot.SpringApplication - Application run failed
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set core/ScheduledExecution.groovy::4.14.0-add-index-workflow-id::rundeckuser (generated):
     Reason: liquibase.exception.DatabaseException: ORA-00972: identifier is too long
 [Failed SQL: (972) CREATE INDEX RUNDECK_TST.scheduled_execution_workflow_id_idx ON RUNDECK_TST.scheduled_execution(workflow_id)]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.runInScope(Liquibase.java:2405) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314) ~[liquibase-core-4.8.0.jar!/:?]
	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.performUpdate(GrailsLiquibase.groovy:81) ~[database-migration-4.1.0-plain.jar!/:?]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.8.0.jar!/:?]
	at org.springframework.beans.factory.InitializingBean$afterPropertiesSet.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.grails.plugins.databasemigration.DatabaseMigrationGrailsPlugin$_doWithApplicationContext_closure2$_closure5.doCall(DatabaseMigrationGrailsPlugin.groovy:85) ~[database-migration-4.1.0-plain.jar!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.Closure.call(Closure.java:428) ~[groovy-3.0.9.jar!/:3.0.9]
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94) ~[grails-datastore-gorm-7.3.3.jar!/:?]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.27.jar!/:5.3.27]
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91) ~[grails-datastore-gorm-7.3.3.jar!/:?]
	at grails.gorm.transactions.GrailsTransactionTemplate$execute.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.grails.plugins.databasemigration.DatabaseMigrationTransactionManager.withTransaction(DatabaseMigrationTransactionManager.groovy:123) ~[database-migration-4.1.0-plain.jar!/:?]
	at org.grails.plugins.databasemigration.DatabaseMigrationTransactionManager$withTransaction$0.callCurrent(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.grails.plugins.databasemigration.DatabaseMigrationTransactionManager.withTransaction(DatabaseMigrationTransactionManager.groovy:47) ~[database-migration-4.1.0-plain.jar!/:?]
	at org.grails.plugins.databasemigration.DatabaseMigrationTransactionManager$withTransaction.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.grails.plugins.databasemigration.DatabaseMigrationGrailsPlugin$_doWithApplicationContext_closure2.doCall(DatabaseMigrationGrailsPlugin.groovy:74) ~[database-migration-4.1.0-plain.jar!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.Closure.call(Closure.java:428) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2396) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.dgm$204.invoke(Unknown Source) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.9.jar!/:3.0.9]
	at org.grails.plugins.databasemigration.DatabaseMigrationGrailsPlugin.doWithApplicationContext(DatabaseMigrationGrailsPlugin.groovy:58) ~[database-migration-4.1.0-plain.jar!/:?]
	at org.grails.plugins.DefaultGrailsPlugin.doWithApplicationContext(DefaultGrailsPlugin.java:507) ~[grails-core-5.3.2.jar!/:5.3.2]
	at org.grails.plugins.AbstractGrailsPluginManager.doPostProcessing(AbstractGrailsPluginManager.java:223) ~[grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:259) ~[grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy) ~[grails-core-5.3.2.jar!/:5.3.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.12.jar!/:2.7.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) [spring-boot-2.7.12.jar!/:2.7.12]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) [spring-boot-2.7.12.jar!/:2.7.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.7.12.jar!/:2.7.12]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99) [grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:485) [grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:472) [grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-5.3.2.jar!/:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) [groovy-3.0.9.jar!/:3.0.9]
	at rundeckapp.Application.execRunApp(Application.groovy:92) [classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222) [groovy-3.0.9.jar!/:3.0.9]
	at rundeckapp.Application.main(Application.groovy:81) [classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [rundeck.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [rundeck.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [rundeck.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [rundeck.war:?]
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set core/ScheduledExecution.groovy::4.14.0-add-index-workflow-id::rundeckuser (generated):
     Reason: liquibase.exception.DatabaseException: ORA-00972: identifier is too long
 [Failed SQL: (972) CREATE INDEX RUNDECK_TST.scheduled_execution_workflow_id_idx ON RUNDECK_TST.scheduled_execution(workflow_id)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:696) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:247) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65) ~[liquibase-core-4.8.0.jar!/:?]
	... 113 more
Caused by: liquibase.exception.DatabaseException: ORA-00972: identifier is too long
 [Failed SQL: (972) CREATE INDEX RUNDECK_TST.scheduled_execution_workflow_id_idx ON RUNDECK_TST.scheduled_execution(workflow_id)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:397) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:661) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:247) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65) ~[liquibase-core-4.8.0.jar!/:?]
	... 113 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:210) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:30) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:931) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1792) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1745) ~[ojdbc6.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:334) ~[ojdbc6.jar:12.1.0.2.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-9.0.44.jar!/:?]
	at com.sun.proxy.$Proxy431.execute(Unknown Source) ~[?:?]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:661) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.Scope.child(Scope.java:247) ~[liquibase-core-4.8.0.jar!/:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65) ~[liquibase-core-4.8.0.jar!/:?]
	... 113 more
[2023-06-26T16:38:23,892] INFO  rundeckapp.BootStrap - Rundeck Shutdown detected

**My Rundeck detail**

* Rundeck version: 4.14.1
* install type: docker
* OS Name/version:  ubuntu 20.04
* DB Type/version: oracle 11.2.0.4.0

**To Reproduce**

**Expected behavior**
Rundeck can be started.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 114.0.5735.110

**Additional context**

**Comment by fdevans** [comment]
This issue was already picked up and is being tracked in our internal backlog. Since we can't confirm its current resolution status from here, we're closing the GitHub copy as part of a broader tracker cleanup.

If you're still experiencing this on a currently supported version (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html)), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps, rather than reopening this one — that ensures it's tracked against your current environment.

Thanks,
The Rundeck Team
