### ISSUE TITLE
Clean install on Ubuntu 20.04 with apt-get fails to start (4.15.0.20230725-1)

### ISSUE THREAD

**Issue by HairyMike** [rundeck/rundeck#8470]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
Rundeck fails to start from clean install.  Looks like the latest apt package installs java version 1.17.  I suspect this is the cause of the failure.

From install log:
```
Unpacking rundeck (4.15.0.20230725-1) ...
Setting up libgraphite2-3:amd64 (1.3.13-11build1) ...
Setting up liblcms2-2:amd64 (2.9-4) ...
Setting up java-common (0.72) ...
Setting up libavahi-common-data:amd64 (0.7-4ubuntu7.2) ...
Setting up fonts-dejavu-core (2.37-1) ...
Setting up libpcsclite1:amd64 (1.8.26-3) ...
Setting up libjpeg-turbo8:amd64 (2.0.3-0ubuntu1.20.04.3) ...
Setting up libharfbuzz0b:amd64 (2.6.4-1ubuntu4.2) ...
Setting up libjpeg8:amd64 (8c-2ubuntu8) ...
Setting up fontconfig-config (2.13.1-2ubuntu3) ...
Setting up libavahi-common3:amd64 (0.7-4ubuntu7.2) ...
Setting up libfontconfig1:amd64 (2.13.1-2ubuntu3) ...
Setting up libavahi-client3:amd64 (0.7-4ubuntu7.2) ...
Setting up libcups2:amd64 (2.3.1-9ubuntu1.4) ...
Setting up openjdk-17-jre-headless:amd64 (17.0.8+7-1~20.04.2) ...
```

**My Rundeck detail**

* Rundeck version: [ e.g. 4.15.0.20230725-1]
* java version: 1.11
* install type: [choose: deb]
* OS Name/version: [ubuntu 20.04]
* DB Type/version: [choose: h2 ]

**To Reproduce**
Follow install instructions (click on community tab): 
https://docs.rundeck.com/docs/administration/install/linux-deb.html#installing-rundeck

See
```
sudo apt-get install openjdk-11-jre-headless
curl https://raw.githubusercontent.com/rundeck/packaging/main/scripts/deb-setup.sh 2> /dev/null | sudo bash -s rundeck
sudo apt-get install rundeck
sudo systemctl start rundeckd
```

**Expected behavior**
Running `tail -f /var/log/rundeck/service.log` we should see the following:
```
Grails application running at http://localhost:4440 in environment: production
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
Going to the previous version succeeds (from a clean VM):
```
sudo apt-get install rundeck=4.14.2.20230713-1
```

Upgrading to latest version from here seems to also work:
```
sudo apt-get upgrade rundeck
```

**Comment by HairyMike** [comment]
Hi @MegaDrive68k,

Thanks for your reply and for testing this out.  Just retracing my steps here:

For context, I'm creating a VM in azure with terraform, using the following image:
```
storage_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-confidential-vm-focal"
    sku       = "20_04-lts-cvm"
    version   = "latest"
  }
```
1. `sudo apt-get update`
2. `sudo apt-get install openjdk-11-jre-headless`
```
java --version
openjdk 11.0.20 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-post-Ubuntu-1ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Ubuntu-1ubuntu120.04, mixed mode, sharing)
```
3. `curl https://raw.githubusercontent.com/rundeck/packaging/main/scripts/deb-setup.sh 2> /dev/null | sudo bash -s rundeck`
```
Running apt-get update...
Detected operating system as Ubuntu/focal.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... Running apt-get update...
done.
Installing apt-transport-https... done.
Importing gpg key... done.
Running apt-get update...
done.

The repository is setup! You can now install packages.
```
4. `sudo apt-get install rundeck`
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  rundeck
0 upgraded, 1 newly installed, 0 to remove and 39 not upgraded.
Need to get 271 MB of archives.
After this operation, 287 MB of additional disk space will be used.
Get:1 https://packages.rundeck.com/pagerduty/rundeck/any any/main amd64 rundeck all 4.15.0.20230725-1 [271 MB]
Fetched 271 MB in 4s (64.4 MB/s)
Selecting previously unselected package rundeck.
(Reading database ... 58444 files and directories currently installed.)
Preparing to unpack .../rundeck_4.15.0.20230725-1_all.deb ...
Unpacking rundeck (4.15.0.20230725-1) ...
Setting up rundeck (4.15.0.20230725-1) ...
Adding group rundeck....done
Adding system user rundeck....done
Processing triggers for systemd (245.4-4ubuntu3.22) ...
```
5. `sudo systemctl start rundeckd`
6. `cat /var/log/rundeck/service.log`
```
[2023-08-10T14:25:09,564] INFO  rundeckapp.Application - The following 1 profile is active: "production"
[2023-08-10T14:25:37,711] WARN  context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.fac
tory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration: Initialization of bean
failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsInterceptorMappedInterceptor': Cannot create inner bean '(inner bean)#3e476882' of
 type [org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter] while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyExcept
ion: Error creating bean with name '(inner bean)#3e476882': Unsatisfied dependency expressed through method 'setInterceptors' parameter 0; nested exception is org.springframework.beans.factory.BeanCreatio
nException: Error creating bean with name 'controllerBaseInterceptor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with
name 'uiPluginService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'frameworkService': Initialization of bean
 failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionService': Initialization of bean failed; nested exception is org.springframewo
rk.beans.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Err
or creating bean with name 'mailService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailMessageBuilderFacto
ry': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailMessageContentRenderer': Initialization of bean failed;
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'groovyPagesTemplateEngine': Cannot resolve reference to bean 'gspTagLibraryLookup' while setting
 bean property 'tagLibraryLookup'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gspTagLibraryLookup': Invocation of init method failed; neste
d exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rundeck.RepositoryTagLib': Initialization of bean failed; nested exception is org.springframework.bea
ns.factory.BeanCreationException: Error creating bean with name 'repoClient': Cannot resolve reference to bean 'repositoryManager' while setting bean property 'repositoryManager'; nested exception is org.
springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryManager': Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateExce
ption; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'repositoryDefinitionListDatasourceUrl' threw exception; nested exception is java.lang.ExceptionInInitializerError
[2023-08-10T14:25:37,835] ERROR boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfigura
tion: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsInterceptorMappedInterceptor': Cannot create inner be
an '(inner bean)#3e476882' of type [org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter] while setting constructor argument; nested exception is org.springframework.beans.factor
y.UnsatisfiedDependencyException: Error creating bean with name '(inner bean)#3e476882': Unsatisfied dependency expressed through method 'setInterceptors' parameter 0; nested exception is org.springframew
ork.beans.factory.BeanCreationException: Error creating bean with name 'controllerBaseInterceptor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationExcepti
on: Error creating bean with name 'uiPluginService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'frameworkSer
vice': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionService': Initialization of bean failed; nested e
xception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.facto
ry.BeanCreationException: Error creating bean with name 'mailService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with
name 'mailMessageBuilderFactory': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailMessageContentRenderer': In
itialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'groovyPagesTemplateEngine': Cannot resolve reference to bean 'gspTa
gLibraryLookup' while setting bean property 'tagLibraryLookup'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gspTagLibraryLookup': Invocation
 of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rundeck.RepositoryTagLib': Initialization of bean failed; nested excepti
on is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repoClient': Cannot resolve reference to bean 'repositoryManager' while setting bean property 'repositoryManag
er'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryManager': Error setting property values; nested exception is org.springframework.
beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'repositoryDefinitionListDatasourceUrl' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~[spring-beans-5.3.27.jar!/:5.3.27]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.27.jar!/:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.27.jar!/:5.3.27]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.27.jar!/:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.27.jar!/:5.3.27]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.27.jar!/:5.3.27]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.27.jar!/:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.27.jar!/:5.3.27]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.12.jar!/:2.7.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) [spring-boot-2.7.12.jar!/:2.7.12]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) [spring-boot-2.7.12.jar!/:2.7.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.7.12.jar!/:2.7.12]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99) [grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:485) [grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:472) [grails-core-5.3.2.jar!/:5.3.2]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-5.3.2.jar!/:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) [groovy-3.0.9.jar!/:3.0.9]
	at rundeckapp.Application.execRunApp(Application.groovy:92) [classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.9.jar!/:3.0.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217) [groovy-3.0.9.jar!/:3.0.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222) [groovy-3.0.9.jar!/:3.0.9]
	at rundeckapp.Application.main(Application.groovy:81) [classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [rundeck-4.15.0-20230725.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [rundeck-4.15.0-20230725.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [rundeck-4.15.0-20230725.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [rundeck-4.15.0-20230725.war:?]
```

This could be related to the sources.list file.  This is what mine says (after apt-get update):
```
## Note, this file is written by cloud-init on first boot of an instance
## modifications made here will not survive a re-bundle.
## if you wish to make changes you can:
## a.) add 'apt_preserve_sources_list: true' to /etc/cloud/cloud.cfg
##     or do the same in user-data
## b.) add sources in /etc/apt/sources.list.d
## c.) make changes to template file /etc/cloud/templates/sources.list.tmpl

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://azure.archive.ubuntu.com/ubuntu/ focal main restricted
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://azure.archive.ubuntu.com/ubuntu/ focal-updates main restricted
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://azure.archive.ubuntu.com/ubuntu/ focal universe
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal universe
deb http://azure.archive.ubuntu.com/ubuntu/ focal-updates universe
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://azure.archive.ubuntu.com/ubuntu/ focal multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal multiverse
deb http://azure.archive.ubuntu.com/ubuntu/ focal-updates multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://azure.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu focal partner
# deb-src http://archive.canonical.com/ubuntu focal partner

deb http://azure.archive.ubuntu.com/ubuntu/ focal-security main restricted
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-security main restricted
deb http://azure.archive.ubuntu.com/ubuntu/ focal-security universe
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-security universe
deb http://azure.archive.ubuntu.com/ubuntu/ focal-security multiverse
# deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-security multiverse
```

Thanks again for your time

**Comment by MegaDrive68k** [comment]
Hi @HairyMike 

Is that image a fresh Ubuntu image? I tried with Azure repo without problems, but checking the error it seems that your're facing [this](https://github.com/rundeck/rundeck/issues/6452) (root cause [here](https://github.com/rundeck/rundeck/issues/6452#issuecomment-693842391)). Could you double check the ubuntu image integrity?

Greetings!

**Comment by HairyMike** [comment]
Wow @MegaDrive68k, you are 100% right on the cause of the issue.

I had this file provisioner in my terraform:
```
provisioner "file" {
   content = file("${path.module}/configs/${var.rundeck_profile_file}")
   destination = "/tmp/rundeck/profile"
}
```

The provisioner runs as a different user to rundecks service account.  Taking this out solves the issue.  Not sure how going to the previous version got it working, but was late in the day (I was probably half asleep).

Thank you @MegaDrive68k, kudos to you sir
