### ISSUE TITLE
Updating from 4.16.0 to 4.17.0 fails with Exception (error executing alter table)

### ISSUE THREAD

**Issue by rlueckl** [rundeck/rundeck#8582]
**Describe the bug**
After upgrading the Debian package from 4.16.0 to 4.17.0 the application won't start. There's an exception during startup (see below).

**My Rundeck detail**

* Rundeck version: 4.17.0.20230925-1 (upgrading from 4.16.0.20230825-1)
* install type: deb
* OS Name/version: Debian 11 Bullseye
* DB Type/version: postgres

**To Reproduce**
1. Install Rundeck 4.16.0 and configure to use Postgres as DB.
2. Create a job and run it a few times, so that the `executions` table in Postgres has at least a few entries.
3. Upgrade to 4.17.0
4. During startup Rundeck tries to modify the DB, but fails with an error.

**Expected behavior**
The application can modify the DB and starts up normal.

**Additional context**
During startup the following exception is thrown:
```
[2023-09-29T07:46:49,225] WARN  internal.ExceptionHandlerLoggedImpl - GenerationTarget encountered exception accepting command : Error executing DDL "alter table if exists execution add column uuid varchar(255) not null" via JDBC Statement
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table if exists execution add column uuid varchar(255) not null" via JDBC Statement
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:581) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:602) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.migrateTable(AbstractSchemaMigrator.java:314) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:78) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:220) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
[... snip ...]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [rundeck-4.17.0-20230925.war:?]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [rundeck-4.17.0-20230925.war:?]
Caused by: org.postgresql.util.PSQLException: ERROR: column "uuid" of relation "execution" contains null values
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.8.jar!/:42.3.8]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[postgresql-42.3.8.jar!/:42.3.8]
[... snip ...]
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        ... 137 more
Running Changeset: core/Execution.groovy::4.x-add-uuid-and-job-uuid::rundeckdev
Running Changeset: core/Execution.groovy::4.x-add-uuid-and-job-uuid-indexes::rundeckdev
[2023-09-29T07:47:07,503] ERROR boot.SpringApplication - Application run failed
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset core/Execution.groovy::4.x-add-uuid-and-job-uuid-indexes::rundeckdev:
     Reason: liquibase.exception.DatabaseException: ERROR: column "uuid" does not exist [Failed SQL: (0) CREATE INDEX execution_uuid_idx ON rundeck.execution(uuid)]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:127) ~[liquibase-core-4.19.0.jar!/:?]
        at liquibase.Liquibase.lambda$null$0(Liquibase.java:291) ~[liquibase-core-4.19.0.jar!/:?]
[... snip ...]
```

It looks like the application is trying to add a new column `uuid` to the table `executions`. The column is defined as "not null" which means that adding this column to a table which already has some entries will always fail unless there's a default value specified.

**Comment by MegaDrive68k** [comment]
Hi @rlueckl 

Could you post your `rundeck-config.properties` to take a look? (please hide/edit any sensitive info) I tried to reproduce the issue but the instance was upgraded properly. Is that 4.16 instance an upgraded from an older version?

**Comment by rlueckl** [comment]
Hi @MegaDrive68k ,

yes, this is a very old Rundeck installation. It has been upgraded since 2.x with `apt`. That's also the reason for us using `rundeck-config.groovy`.

```
# cat rundeck-config.groovy 
loglevel.default = "INFO"
rdeck.base = "/var/lib/rundeck"
rss.enabled = "false"
rundeck.log4j.config.file = "/etc/rundeck/log4j.properties"

rundeck.security.useHMacRequestTokens = true
rundeck.security.apiCookieAccess.enabled = true

dataSource {
  dbCreate = "update"
  url = "jdbc:postgresql://******:5432/rundeck?sslmode=require"
  driverClassName = "org.postgresql.Driver"
  username = "******"
  password = "******"
  dialect = ""
}


grails {
  mail {
    host = "localhost"
    port = 25
    props = []
  }
}
grails.mail.default.from = "rundeck@******"
grails.serverURL = "https://******"
rundeck.clusterMode.enabled = "false"

rundeck.projectsStorageType = "db"
quartz.props.threadPool.threadCount = "60"

rundeck.storage.provider."1".type = "db"
rundeck.storage.provider."1".path = "/"

rundeck.security.authorization.preauthenticated.enabled = "false"
rundeck.security.authorization.preauthenticated.attributeName = "REMOTE_USER_GROUPS"
rundeck.security.authorization.preauthenticated.delimiter = ":"
rundeck.security.authorization.preauthenticated.userNameHeader = "X-Forwarded-Uuid"
rundeck.security.authorization.preauthenticated.userRolesHeader = "X-Forwarded-Roles"
rundeck.security.authorization.preauthenticated.redirectLogout = "false"
rundeck.security.authorization.preauthenticated.redirectUrl = "/oauth2/sign_in"

dataSource.properties.autoReconnect = "true"
dataSource.properties.autoReconnectForPools = "true"
rundeck.api.tokens.duration.max = "1y"
rundeck.gui.login.welcome = "******"
rundeck.security.syncLdapUser = "true"
rundeck.storage.converter."1".config.algorithm = "******"
rundeck.storage.converter."1".config.encryptorType = "custom"
rundeck.storage.converter."1".config.password = "******"
rundeck.storage.converter."1".config.provider = "BC"
rundeck.storage.converter."1".path = "keys"
rundeck.storage.converter."1".type = "jasypt-encryption"
```

Here's also how the `execution` table currently looks like:
```
            Column            |            Type             | Collation | Nullable | Default 
------------------------------+-----------------------------+-----------+----------+---------
 id                           | bigint                      |           | not null | 
 version                      | bigint                      |           | not null | 
 scheduled_execution_id       | bigint                      |           |          | 
 do_nodedispatch              | boolean                     |           |          | 
 node_exclude_os_arch         | text                        |           |          | 
 node_keepgoing               | boolean                     |           |          | 
 succeeded_node_list          | text                        |           |          | 
 retry_attempt                | integer                     |           |          | 
 node_include                 | text                        |           |          | 
 success_on_empty_node_filter | boolean                     |           |          | 
 retry_prev_id                | bigint                      |           |          | 
 extra_metadata               | text                        |           |          | 
 node_exclude_os_version      | text                        |           |          | 
 timeout                      | text                        |           |          | 
 node_exclude_precedence      | boolean                     |           |          | 
 node_exclude_name            | text                        |           |          | 
 node_include_os_version      | text                        |           |          | 
 node_exclude_os_name         | text                        |           |          | 
 retry                        | text                        |           |          | 
 filter                       | text                        |           |          | 
 orchestrator_id              | bigint                      |           |          | 
 node_include_name            | text                        |           |          | 
 rduser                       | character varying(255)      |           | not null | 
 retry_original_id            | bigint                      |           |          | 
 execution_type               | character varying(30)       |           |          | 
 node_include_os_name         | text                        |           |          | 
 abortedby                    | character varying(255)      |           |          | 
 filter_exclude               | text                        |           |          | 
 node_exclude                 | text                        |           |          | 
 node_rank_order_ascending    | boolean                     |           |          | 
 node_include_os_arch         | text                        |           |          | 
 loglevel                     | character varying(255)      |           |          | 
 node_exclude_os_family       | text                        |           |          | 
 node_include_os_family       | text                        |           |          | 
 cancelled                    | boolean                     |           | not null | 
 retry_delay                  | text                        |           |          | 
 workflow_id                  | bigint                      |           |          | 
 timed_out                    | boolean                     |           |          | 
 failed_node_list             | text                        |           |          | 
 arg_string                   | text                        |           |          | 
 user_role_list               | text                        |           |          | 
 node_rank_attribute          | character varying(255)      |           |          | 
 date_completed               | timestamp without time zone |           |          | 
 outputfilepath               | text                        |           |          | 
 server_nodeuuid              | character varying(36)       |           |          | 
 will_retry                   | boolean                     |           |          | 
 retry_execution_id           | bigint                      |           |          | 
 node_exclude_tags            | text                        |           |          | 
 exclude_filter_uncheck       | boolean                     |           |          | 
 node_threadcount             | integer                     |           |          | 
 node_include_tags            | text                        |           |          | 
 date_started                 | timestamp without time zone |           |          | 
 status                       | character varying(255)      |           |          | 
 node_filter_editable         | boolean                     |           |          | 
 project                      | character varying(255)      |           | not null | 
```

**Comment by molinarif02** [comment]
hi rlueckl,
had the same issue and dropping table public.execution (drop table public.execution cascade;) solved it!

**Comment by rlueckl** [comment]
Thanks, but I'd prefer not to loose years of deployment history if possible.

**Comment by NickSmyr** [comment]
I have the same issue when upgrading from 3.2.6-20200427  to 4.17

**Comment by rlueckl** [comment]
@MegaDrive68k Since apparently I'm not the only one with this problem, could you please take another look?

My very limited Postgres knowledge says that your `ALTER TABLE` statement should contain a default value in case the `execution` table already contains entries. Something like:
```
alter table if exists execution add column uuid varchar(255) default 00000000-0000-0000-0000-000000000000 not null
```
instead of:
```
alter table if exists execution add column uuid varchar(255) not null
```

Of course the application has to be able to cope with it, if multiple rows give you the same uuid or has to rewrite/generate the uuid for each row after altering the table and adding a default value.

**Comment by rlueckl** [comment]
@MegaDrive68k @gschueler Any news/updates on this issue?

4.17.3 was released yesterday, but still no fix for this as far as I can see.

**Comment by MegaDrive68k** [comment]
Confirmed. 

Steps to reproduce:

1. Launch PostgreSQL 13 (I have tested using the following docker container):

```docker-compose
version: '3'
services:
  postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=rundeck
        - POSTGRES_USER=rundeck
        - POSTGRES_PASSWORD=rundeck
```

2. Launch a fresh Rundeck 4.16.0 WAR, then stop the instance, and put the following  `.groovy` file on the same `rundeck-config.properties` directory:

```groovy
loglevel.default = "INFO"
rdeck.base = "/home/reideianto/Deployments/Rundeck/4.16.0"
rss.enabled = "false"

rundeck.security.useHMacRequestTokens = true
rundeck.security.apiCookieAccess.enabled = true

dataSource {
  dbCreate = "update"
  url = "jdbc:postgresql://localhost/rundeck"
  driverClassName = "org.postgresql.Driver"
  username = "rundeck"
  password = "rundeck"
  dialect = "org.hibernate.dialect.PostgreSQLDialect"
}

rundeck.clusterMode.enabled = "false"

rundeck.projectsStorageType = "db"
quartz.props.threadPool.threadCount = "60"

rundeck.security.authorization.preauthenticated.enabled = "false"
rundeck.security.authorization.preauthenticated.attributeName = "REMOTE_USER_GROUPS"
rundeck.security.authorization.preauthenticated.delimiter = ":"
rundeck.security.authorization.preauthenticated.userNameHeader = "X-Forwarded-Uuid"
rundeck.security.authorization.preauthenticated.userRolesHeader = "X-Forwarded-Roles"
rundeck.security.authorization.preauthenticated.redirectLogout = "false"
rundeck.security.authorization.preauthenticated.redirectUrl = "/oauth2/sign_in"
```

3. Launch Rundeck 4.16.0, create a project, a couple of jobs, etc.
4. Stop Rundeck 4.16.0 and upgrade launch Rundeck 4.17 (launch Rundeck 4.17 WAR).
5. See the error. Full error stack [here](https://github.com/rundeck/rundeck/files/13393849/error_output.txt).

![Screenshot_2023-11-17_12-47-17](https://github.com/rundeck/rundeck/assets/51376003/19519e64-8309-4070-a8e4-7620ba6bde2d)

**Comment by carlosrfranco** [comment]
@rlueckl If you have the database in the state before the upgrade attempt, you can try changing dbCreate config to `none` instead of `update`.  If the database is in the state after you ran the 4.17 rundeck version, you can try also run this two sql statements and then run 4.17 again:  
```
delete from databasechangelog where id = '4.x-add-uuid-and-job-uuid';
alter table execution drop column job_uuid;
```

**Comment by jgarces-pd** [comment]
@carlosrfranco can you confirm that is `job_uuid` and not `uuid`?
It seems that `uuid` was introduced on 4.17 compared to `job_uuid` which existed previously

**Comment by carlosrfranco** [comment]
> > ```sql
> > delete from databasechangelog where id = '4.x-add-uuid-and-job-uuid';
> > alter table execution drop column job_uuid;
> > ```
> 
> @carlosrfranco can you confirm that is `job_uuid` and not `uuid`? It seems that `uuid` was introduced on 4.17 compared to `job_uuid` which existed previously

Both are created at the same time. To run this changeset migration again in order to create the uuid, it needs to delete job_uuid to satisfy some pre-conditions validations

**Comment by jgarces-pd** [comment]
@carlosrfranco by deleting the `job_uuid` can cause jobs to lose their UUID?
I'm thinking in cases like jobs with job referenced by UUID.

**Comment by rlueckl** [comment]
> @rlueckl If you have the database in the state before the upgrade attempt, you can try changing dbCreate config to `none` instead of `update`. If the database is in the state after you ran the 4.17 rundeck version, you can try also run this two sql statements and then run 4.17 again:
> 
> ```
> delete from databasechangelog where id = '4.x-add-uuid-and-job-uuid';
> alter table execution drop column job_uuid;
> ```
> 
> Also, the dbCreate config should not be set or should have the value `none` for any rundeck version after 3.4.0

It's been a long time, but I haven't really got around to testing this out until now. Changing `dbCreate` to `none` and deleting/altering the DB as you suggested let me update from 4.16.0 to 4.17.4.

At first it looked fine, running jobs works, reading log outputs from previous executions also works, but when deleting a job I get an exception:
```
[2024-02-13T08:00:48,983] WARN  spi.SqlExceptionHelper - SQL Error: 0, SQLState: 23503
[2024-02-13T08:00:48,983] ERROR spi.SqlExceptionHelper - ERROR: update or delete on table "scheduled_execution" violates foreign key constraint "fkdtqy2uar1ln372ne8u2jj27nw" on table "execution"
  Detail: Key (id)=(32153) is still referenced from table "execution".
[2024-02-13T08:00:49,021] ERROR StackTrace - Full Stack Trace:
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [fkdtqy2uar1ln372ne8u2jj27nw]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:212) ~[spring-orm-5.3.27.jar!/:5.3.27]
...
 ```
(the full stack trace is multiple pages long)

The job I was trying to delete was scheduled to run every day, but we don't need it anymore. Disabling the schedule in the job then trying to delete it again didn't help either. I'm getting the same error message.

Trying to delete any other job also throws this error. It doesn't seem to matter if the job has/had a schedule or not.

Full Stack Trace: [rundeck_delete_job_exception.log](https://github.com/rundeck/rundeck/files/14257357/rundeck_delete_job_exception.log)

Error I'm seeing in the browser: ![rundeck_server_error](https://github.com/rundeck/rundeck/assets/10848041/b23419e1-0dbd-4e2a-81ef-0d741778dd71)

**Comment by rlueckl** [comment]
Small update: it's possible to delete old (pre-4.17) jobs, when also selecting to delete all executions of the job. The exception only appears when I'm trying to delete an old job, but I don't want to delete the executions (so I could look them up later under "Activity").

**Comment by rlueckl** [comment]
Updating to 5.1.2 I'm now able to delete pre-4.71 jobs without deleting their history/activity log. So I guess everything works now.
