### ISSUE TITLE
"Error: Rendered items limit reached" while viewing execution log with a long output

### ISSUE THREAD

**Issue by lenaing** [rundeck/rundeck#8692]
**Describe the bug**
With a log execution with numerous elements, the rendering by Vue.js stops with the following errors:

``` 
Error: Rendered items limit reached
    itemsLimitError chunk-vendors.js:164732
    updateVisibleItems chunk-vendors.js:164732
    handleResize chunk-vendors.js:164732
    jt vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2
    Ut vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2
    an vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2
    emitSize chunk-vendors.js:164732
    compareAndNotify chunk-vendors.js:164732
[vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:14930](https://rundeck.example.com/rundeck/assets/vendor/vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js)
It seems the scroller element isn't scrolling, so it tries to render all the items at once. Scroller: 
<div class="vue-recycle-scroller rea…er execution-log__chunk" data-v-1b7898a8="">
[chunk-vendors.js:164732](webpack://rundeckCore/js/chunk-vendors.js)
Make sure the scroller has a fixed height (or width) and 'overflow-y' (or 'overflow-x') set to 'auto' so it can scroll correctly and only render the items visible in the scroll viewport.
```

**My Rundeck detail**

* Rundeck version: 4.17.1
* install type: war
* OS Name/version: CentOS 7
* DB Type/version: Postgres

**To Reproduce**
I don't know how to reproduce, it happens on some of our jobs with numerous log outputs (> 6000 lines)

**Expected behavior**
Viewing the correct execution logs with no rendering cuts.

**Screenshots**
![image](https://github.com/rundeck/rundeck/assets/1098971/11567999-4f66-455e-b6ab-1a1622234d6a)
![image](https://github.com/rundeck/rundeck/assets/1098971/bef5b3f4-8ef2-49b2-8329-b821f5e3516e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 119.0.1

**Additional context**
N/A

**Comment by thedoc31** [comment]
I also see this on 4.17.3 for output from a Script step, but only on the Nodes view. If I go to Log Output tab I can see all log lines (after a ton of scrolling). In some cases the Nodes view log display doesn't even start at the top - it just renders some chunk of logs and a bunch of blank space, then gives up. It does not always even start at the top of the log as one would expect. It is also preceded by a "Cannot read properties of undefined" error and is not browser-specific.

This issue does not occur on 4.8.0. This is a major blocker for adoption of newer versions. 

```
TypeError: Cannot read properties of undefined (reading 'map')
    at Proxy.entryOutputs (chunk-common.js:1:1)
    at me.run (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:5802)
    at get value [as value] (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:14378)
    at Object.get [as entryOutputs] (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:33569)
    at Object.get (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:31489)
    at Proxy.R (chunk-common.js:1:1)
    at gn (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:17558)
    at me.fn (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:49222)
    at me.run (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:5802)
    at U.e.update (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:49913)
```

```
vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2 Error: Rendered items limit reached
    at Proxy.itemsLimitError (chunk-vendors.js:164732:1)
    at Proxy.updateVisibleItems (chunk-vendors.js:164732:1)
    at Proxy.handleResize (chunk-vendors.js:164732:1)
    at jt (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:14459)
    at Ut (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:14537)
    at an (vue.global.prod-dc35d3e1a7d3ba06231f8aef2f387a92.js:2:16440)
    at Proxy.emitSize (chunk-vendors.js:164732:1)
    at Proxy.compareAndNotify (chunk-vendors.js:164732:1)
    at Proxy.addResizeHandlers (chunk-vendors.js:164732:1)
```

Desktop: MacOS Sonoma 14.1.2
Browser: Chrome (latest) and Firefox (latest)

**Comment by thedoc31** [comment]
Also confirmed today the issue remains in 5.0.0.

**Comment by idl0r** [comment]
Any news on this by chance?

**Comment by ellisgeek** [comment]
We are also experiencing this issue on 5.0.4.

**Comment by thedoc31** [comment]
Confirmed the issue still exists in `rundeck-5.10.0-20250312`. I spent a bunch of time today with Cursor AI helping me analyze the Rundeck LogNodeChunk code and trying various fixes in the hope there could be a quick fix, but unfortunately it looks to be much more involved than just fixing the console errors. 

To be honest, I'm not surprised the bug has lasted this long, because there are zero unit tests that validate any use of the vue-virtual-scroller component, which might have been able to catch this.

To fix the `Error: Rendered items limit reached` console error, the `page-mode` directive needs to be added directly after the `key-field="lineNumber"` entry in [1].

Then, to fix the `TypeError: Cannot read properties of undefined (reading 'map')`, the `entries` stanza appears to need a default initialization like `default: () => []` after line 98 [2] because I guess the code gets into a race condition where it's checking for properties that don't exist yet.

Once these two issues are resolved, you can see that all of the responses from the execution are present, but only 16 or 17 lines actually display. The data is all there in the http response. It's literally just a matter of getting all the lines to size themselves and display properly. Unfortunately, that's far beyond my skills and any LLM's explanations of what to do next. IMO, it's something only a real javascript/vue engineer can fix. 

For what it's worth, there also appear to be a number of bugs in `vue-virtual-scroller v2.0.0-beta.8` that could be related and have since been resolved with subsequent merged PRs. Problem there is no new release is available to consume. There's no way to tell if that would improve anything.

Ultimately, I'm confused how anyone can use Rundeck versions > `4.16.0` with this bug. Any Rundeck peeps listening out there?

[1]
https://github.com/rundeck/rundeck/blob/main/rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/LogNodeChunk.vue#L12

[2]
https://github.com/rundeck/rundeck/blob/main/rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/LogNodeChunk.vue#L96-L99

**Comment by dingouerinitx** [comment]
Great analysis of the issue @thedoc31, thank you very much and big **upvote** for this to prioritise the resolution for this annoying issue. Either rundeck frontend devs should update and/or find and help in resolving `vue-virtual-scroller` issues or use (if in any case possible) an alternative library 😬 🫣. But I wonder if its just us having so much log output that this glitch exists, that there is not more rumor about it... 🧐

**Comment by steinbrueckri** [comment]
> But I wonder if its just us having so much log output that this glitch exists, that there is not more rumor about it... 🧐

We have the same issue 🤷‍♂️
There are workarounds but still it is a bit annoying.

**Comment by thedoc31** [comment]
> > But I wonder if its just us having so much log output that this glitch exists, that there is not more rumor about it... 🧐
> 
> We have the same issue 🤷‍♂️ There are workarounds but still it is a bit annoying.

Curious what workaround you're using. 

I agree with @dingouerinitx; I have no idea why people aren't making more noise about this. Unfortunately, it seems that Rundeck engineering either doesn't think this is a big enough deal to fix or it's just gotten buried so deep they can't find that it's still an active issue. I'm half tempted to open a new issue just to reference this one and bubble it back up.

Maybe in a few more months there'll be an LLM smart enough to fix vue issues.

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
