### ISSUE TITLE
"Authentication is required" error when access rundeck web console

### ISSUE THREAD

**Issue by chp320** [rundeck/rundeck#8785]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
I installed a rundeck on my EC2 (t2.micro) using yum. 
I edited several below files to setting my EIP.
* vi /etc/rundeck/framework.properties
```
framework.server.name = [server IP]
framework.server.hostname = [server IP]
framework.server.port = 4440
framework.server.url = http://[server IP]:4440
```
* vi /etc/rundeck/rundeck-config.properties
```
grails.serverURL=http://[server IP]:4440
```

Started service below command.
```
sudo systemctl start rundeckd
```

I checked a log to verify the service.
```
tail -f /var/log/rundeck/service.log
```

On my notebook, try to connect web console but I got an error message : Authentication is required.
```
http://[server IP]:4440
```

**My Rundeck detail**

* Rundeck version: 5.0.0.20231216
* install type: rpm
* OS Name/version: Amazon Linux release 2023 (Amazon Linux)
* DB Type/version: nope

**To Reproduce**
1. check the port(4440) is correct on EC2 > security > inbound rule.
2. check the /var/log/rundeck/rundeck.log file.
it says:
```
[2024-01-05T01:41:28,741] ERROR boot.SpringApplication [main] - Application run failed
liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by ip-xxx-xxx-xxx-xxx.ap-northeast-2.compute.internal (xxx.xxx.xxx.xxx) since 1/4/24, 1:08 AM
        at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:275) ~[liquibase-core-4.19.0.jar!/:?]
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:239) ~[liquibase-core-4.19.0.jar!/:?]
        at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.19.0.jar!/:?]
...
```
* xxx.xxx.xxx.xxx is a "Private IPv4 address". So, I check 'oubound rule'. it setted for all range like 0.0.0.0/0.

**Expected behavior**
![image](https://github.com/rundeck/rundeck/assets/47440517/0c6ee30a-32f2-4054-98e5-8dbbf6c4b212)

**Screenshots**
<img width="835" alt="image" src="https://github.com/rundeck/rundeck/assets/47440517/610bca60-4b7b-441c-8ccd-8829a48df699">

**Desktop (please complete the following information):**
 - OS: macOS 14.1.2
 - Browser: chrome, safari
 - Version: chrome 120.0.6099.129, safari 17.1.2

**Comment by whitehatmiddleman** [comment]
I ran into the same issue and this was due to a failed locked on the database. I had to do the following, but this was based on a docker compose filed.

This is due to a failed locked on the database
 ```
docker compose exec rundeck-db /bin/bash
psql -U <user> -W <db>
enter password

SELECT * FROM PUBLIC.DATABASECHANGELOGLOCK;
DELETE FROM DATABASECHANGELOGLOCK;

docker compose down
docker compose up -d
```

**Comment by jinnabaalu** [comment]
Following steps worked for me

Steps followed :
- `systemctl stop rundeckd`

```sql
UPDATE PUBLIC.DATABASECHANGELOGLOCK
SET locked = false,
    lockgranted = NULL,
    lockedby = NULL
WHERE id = 1;
```
- `systemctl start rundeckd`

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
