### ISSUE TITLE
Unable to authenticate user: admin when running jobs from Command line

### ISSUE THREAD

**Issue by ghost** [rundeck/rundeck#882]
Hi,
I am currently unable to run a job from command line if the admin password has been changed from default.

kindly check.
## Logs

$ ./run -v -j "Users" -p "Ops"
com.dtolabs.rundeck.core.CoreException: Error making server request to http://localhost:4444/rundeck: Unable to authenticate user: admin
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:200)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:142)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:98)
        at com.dtolabs.client.services.RundeckAPICentralDispatcher.reallistStoredJobs(RundeckAPICentralDispatcher.java:1241)
        at com.dtolabs.client.services.RundeckAPICentralDispatcher.queueDispatcherJob(RundeckAPICentralDispatcher.java:1338)
        at com.dtolabs.rundeck.core.cli.run.RunTool.jobrunAction(RunTool.java:436)
        at com.dtolabs.rundeck.core.cli.run.RunTool.go(RunTool.java:392)
        at com.dtolabs.rundeck.core.cli.BaseTool.run(BaseTool.java:108)
        at com.dtolabs.rundeck.core.cli.run.RunTool.main(RunTool.java:124)
Caused by: com.dtolabs.client.utils.AuthorizationFailureException: Unable to authenticate user: admin
        at com.dtolabs.client.utils.BaseHttpClientChannel.doAuthentication(BaseHttpClientChannel.java:129)
        at com.dtolabs.client.utils.HttpClientChannel.makeRequest(HttpClientChannel.java:325)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:196)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:142)
        at com.dtolabs.client.services.ServerService.makeRundeckRequest(ServerService.java:98)
        at com.dtolabs.client.services.RundeckAPICentralDispatcher.reallistStoredJobs(RundeckAPICentralDispatcher.java:1241)
        at com.dtolabs.client.services.RundeckAPICentralDispatcher.queueDispatcherJob(RundeckAPICentralDispatcher.java:1338)
        at com.dtolabs.rundeck.core.cli.run.RunTool.jobrunAction(RunTool.java:436)
        at com.dtolabs.rundeck.core.cli.run.RunTool.go(RunTool.java:392)
        at com.dtolabs.rundeck.core.cli.BaseTool.run(BaseTool.java:109)
        at com.dtolabs.rundeck.core.cli.run.RunTool.main(RunTool.java:125)
Error: Error making server request to http://localhost:4444/rundeck: Unable to authenticate user: admin

Contents of the realm.properties file.
# 
# This file defines users passwords and roles for a HashUserRealm
# 
# The format is
# <username>: <password>[,<rolename> ...]
# 
# Passwords may be clear text, obfuscated or checksummed.  The class
# org.mortbay.util.Password should be used to generate obfuscated
# passwords or password checksums
# 
# This sets the temporary user accounts for the Rundeck app
# 

admin:admin12,user,admin

**Comment by timbers123** [comment]
Which password should it match?  I've inherited a rundeck 2.6 application and getting the error "Unable to authenticate user: admin" I can see the password in framework.properties, but what password is the admin account supposed to match to?  I'm trying to run a rundeck job as the rundeck user on the rundeck host - so hopefully there s a way of bypassing the http call and hence this password issue.
Many thanks
