### ISSUE TITLE
Handshake status 400 Bad Request when using kubernetes/pod/script execute

### ISSUE THREAD

**Issue by genseb13011** [rundeck/rundeck#9158]
Issue type: Error

Hi,

I'm facing an issue when using the kubernetes/pod/script execute plugin.

I try to run below script on a pod (container: httpd:alpine3.19) using the kubernetes/pod/script execute plugin

```
#!/bin/sh
echo "Hello @option.Name@"
```

**Error message **
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/stream/ws_client.py", line 523, in websocket_call
    client = WSClient(configuration, url, headers, capture_all)
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/stream/ws_client.py", line 65, in __init__
    self.sock = create_websocket(configuration, url, headers)
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/stream/ws_client.py", line 489, in create_websocket
    websocket.connect(url, **connect_opt)
  File "/usr/local/lib/python3.10/dist-packages/websocket/_core.py", line 261, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/usr/local/lib/python3.10/dist-packages/websocket/_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python3.10/dist-packages/websocket/_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException(
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request -+-+- {'audit-id': '00dc84ac-3e42-415a-b678-8667f413239d', 'cache-control': 'no-cache, private', 'content-type': 'application/json', 'date': 'Mon, 03 Jun 2024 11:29:01 GMT', 'content-length': '168'} -+-+- b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container  httpd:alpine3.19 is not valid for pod test","reason":"BadRequest","code":400}\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/rundeck/libext/cache/kubernetes-2.0.13/pods-run-script.py", line 164, in <module>
    main()
  File "/home/rundeck/libext/cache/kubernetes-2.0.13/pods-run-script.py", line 94, in main
    common.copy_file(name=name,
  File "/home/rundeck/libext/cache/kubernetes-2.0.13/common.py", line 455, in copy_file
    resp = stream(api.connect_get_namespaced_pod_exec, name, namespace,
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/stream/stream.py", line 35, in _websocket_request
    return api_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec
    return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.10/dist-packages/kubernetes/stream/ws_client.py", line 529, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: Handshake status 400 Bad Request -+-+- {'audit-id': '00dc84ac-3e42-415a-b678-8667f413239d', 'cache-control': 'no-cache, private', 'content-type': 'application/json', 'date': 'Mon, 03 Jun 2024 11:29:01 GMT', 'content-length': '168'} -+-+- b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container  httpd:alpine3.19 is not valid for pod test","reason":"BadRequest","code":400}\n'
Failed: NonZeroResultCode: Script result code was: 1
```

**My Rundeck detail**

* Rundeck version: 5.3.0
* install type: (rpm,deb,war,launcher?): container image rundeck/rundeck:5.3.0
* OS Name/version: kubernetes (node debian 12)
* DB: jdbc:h2:file:/home/rundeck/server/data/grailsdb

** Other informations **
* works well with the kubernetes/pod/command execute plugin
* the serviceaccount role have full access to kube RBAC

Thanks for your help

**Comment by genseb13011** [comment]
Error was on my side.
I have dumbly set the image name as container name in the interface....
