### ISSUE TITLE
Failed: Unknown: Exhausted available authentication methods

### ISSUE THREAD

**Issue by WhiskyCoca34** [rundeck/rundeck#9368]
**Describe the bug**
Whether after the update to version 5.5 or with a fresh installation of 5.6 on Ubuntu 22, my tasks no longer execute.
I encounter the error message mentioned in the title. See the screenshots below for more details.
I am using 'Ansible Resource Model Source' to configure my nodes, as well as the connection user and SSH key. Nothing is working anymore.

**My Rundeck detail**

* Rundeck version: 5.6
* install type: deb
* OS Name/version: 22.04
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

```
[2024-09-17T11:41:10,402] ERROR node.NodeStepPluginAdapter [pool-59-thread-1] - Error executing node step.
com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: Exhausted available authentication methods
        at jdk.internal.reflect.GeneratedConstructorAccessor608.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:295) ~[groovy-3.0.19.jar!/:3.0.19]
        at org.rundeck.plugin.scriptnodestep.Util.handleFailureResult(Util.groovy:13) ~[?:?]
        at org.rundeck.plugin.scriptnodestep.Util$handleFailureResult.call(Unknown Source) ~[?:?]
        at org.rundeck.plugin.scriptnodestep.CommandNodeStepPlugin.executeNodeStep(CommandNodeStepPlugin.groovy:54) ~[?:?]
        at com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepPluginAdapter.executeNodeStep(NodeStepPluginAdapter.java:180) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:207) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:130) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:61) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodesWith(ExecutionServiceImpl.java:263) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.dispatchToNodes(ExecutionServiceImpl.java:234) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.workflow.steps.NodeDispatchStepExecutor.executeWorkflowStep(NodeDispatchStepExecutor.java:66) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:111) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:285) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:681) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:76) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:32) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$beginOperation$1(WorkflowEngineOperationsProcessor.java:323) ~[rundeck-core-5.6.0-20240912.jar!/:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-32.0.1-jre.jar!/:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75) ~[guava-32.0.1-jre.jar!/:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-32.0.1-jre.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2024-09-17T11:41:10,425] ERROR api.workflowstatus [pool-59-thread-1] - Step 1 failed: exec-command
[2024-09-17T11:41:10,680] WARN  workflow.EngineWorkflowExecutor [Thread-111] - [wf:2257f6ed-060a-495e-8391-20b064ff4226] Step [2] did not run. start conditions: [(after.step.1 == 'true')], skip conditions: [(step.2.completed == 'true')]
[2024-09-17T11:41:10,681] WARN  workflow.EngineWorkflowExecutor [Thread-111] - [wf:2257f6ed-060a-495e-8391-20b064ff4226] Step [3] did not run. start conditions: [(after.step.2 == 'true')], skip conditions: [(step.3.completed == 'true')]
[2024-09-17T11:41:10,694] ERROR services.ExecutionUtilService [quartzScheduler_Worker-5] - Execution failed: 134 in project MISE_A_JOURS_SERVEURS_VCENTER: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [server01: Unknown: Exhausted available authentication methods + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:server01)=BaseDataContext{{exec={exitCode=-1}}}, ContextView(node:server01)=BaseDataContext{{exec={exitCode=-1}}}}, base=null)} ]}, Node failures: {server01=[Unknown: Exhausted available authentication methods + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:server01)=BaseDataContext{{exec={exitCode=-1}}}, ContextView(node:server01)=BaseDataContext{{exec={exitCode=-1}}}}, base=null)} ]}, status: failed]
```

**Screenshots**
![image](https://github.com/user-attachments/assets/244d6402-0669-4f77-8863-77fe66a624a2)

![image](https://github.com/user-attachments/assets/eeaf5840-3463-48a8-adad-b77f6d73e651)

Node :
![image](https://github.com/user-attachments/assets/d4ffd25f-89fd-47b6-a6e3-2d05463c6c7b)

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our issue tracker, we're closing issues older than 12 months, in line with Rundeck's support policy of one year from a release's date (see the [release calendar](https://docs.rundeck.com/docs/history/release-calendar.html) for currently supported versions). This isn't a judgment that the report is invalid — many of these are likely still real — but we can't verify against a version this old.

If you're still seeing this on a currently supported release (6.1.x or 5.20.x+), please open a new issue using our [bug report template](https://github.com/rundeck/rundeck/issues/new?template=bug_report.yml) with your version and reproduction steps. Please don't reopen this issue — a fresh issue keeps things tracked against a supported version and gets it in front of us properly. We're actively working on improving how issues get submitted and triaged going forward.

Thanks for your patience,
The Rundeck Team
