### ISSUE TITLE
java.lang.NullPointerException thrown when starting a job

### ISSUE THREAD

**Issue by jippi** [rundeck/rundeck#964]
With version 2.2.3-1 (debian)

```
java.lang.NullPointerException
07:05:29            at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.convertFailures(BaseWorkflowStrategy.java:452)
07:05:29            at com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:89)
07:05:29            at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:120)
07:05:29            at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
07:05:29            null
```

**Comment by pramodsetlur** [comment]
Probably one of the parameters you are passing through rundeck.xml is empty?
