### ISSUE TITLE
Rundeck Job server reports job as running and refuses to kill despite dead Unix process

### ISSUE THREAD

**Issue by gslonim** [rundeck/rundeck#974]
Symptoms:
Rundeck UI reports job as running. Attempting to kill the job via the interface results in "Failed to kill job: Server Error"
The actual Unix process is not running at all.

Details:
$RUNDECK_BASE/var/log/service.log reports:

```
2014-10-16 12:29:56,034 ERROR GrailsExceptionResolver - JdbcSQLException occurred when processing request: [POST] /execution/cancelExecution.json 
Concurrent update in table "EXECUTION": another transaction has updated or deleted the same row [90131-164]. Stacktrace follows: 
org.h2.jdbc.JdbcSQLException: Concurrent update in table "EXECUTION": another transaction has updated or deleted the same row [90131-164] 
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) 
        at org.h2.message.DbException.get(DbException.java:169) 
        at org.h2.message.DbException.get(DbException.java:146) 
        at org.h2.table.RegularTable.removeRow(RegularTable.java:346) 
        at org.h2.table.Table.updateRows(Table.java:430) 
        at org.h2.command.dml.Update.update(Update.java:128) 
        at org.h2.command.CommandContainer.update(CommandContainer.java:73) 
        at org.h2.command.Command.executeUpdate(Command.java:226) 
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:143) 
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:129) 
        at rundeck.services.ExecutionService$_abortExecution_closure20.doCall(ExecutionService.groovy:951) 
        at rundeck.services.ExecutionService.abortExecution(ExecutionService.groovy:947) 
        at rundeck.controllers.ExecutionController$_closure8.doCall(ExecutionController.groovy:229) 
.... (unrelated jetty stack traces)
```

Please advise.

**Comment by ahonor** [comment]
Reopen if this is still an issue for 2.10.x
